### ISSUE TITLE
Supporting custom eviction policy

### ISSUE THREAD

**Issue by hshankar** [ben-manes/caffeine#100]
We have a use case where we want to set the createTime on which eviction should be based, rather than always using the time the entry was created. Extending it further, I think it would be nice to have support for custom eviction policies instead of always using LRU. 

Do you see major issues with supporting it? I am willing to spend some time implementing it if there is support for this requirement and no major design issues.

**Comment by ben-manes** [comment]
The eviction policy is [TinyLFU](https://github.com/ben-manes/caffeine/wiki/Efficiency). We don't want to provide a custom size-based policy because that's error prone and very unlikely able to make a significantly wiser decision than these types of heuristics.

If the creation time is from the perspective of the cache, then you are describing a FIFO policy. Otherwise the cache would have to evaluate the entry to get a priority, resulting in an O(lg n) insertion time. Currently we use only O(1) algorithms.

Does`expireAfterWrite` handle your use-case? This tells the cache to evict entries beyond a certain age, e.g. due to the data being stale.

If you need variable per-entry expiration then this is where things get trickier for inclusion. There are good common solutions for your code, but not for the library. I have an idea for a nice approach (hash wheel timers), but haven't experimented much yet.

**Comment by hshankar** [comment]
So, my use case is to be able to set custom weights on each entry such that the entries with lower weights are removed first. LRU is a special case where the custom weight is the time of creation of the entry. 

The problem with expireAfterWrite is that it assumes a time (= current time). I want to set a different time on which to base eviction.

**Comment by ben-manes** [comment]
FIFO is time of creation, LRU is time of last access. Those are of course logical clocks, not wall clock time. The `expireAfterWrite` and `expireAfterAccess` are the wall-clock versions.

I'm still confused if your actually want your weights to be based on wall-clock time or if your weights are logical. The former would be expiration, where a per-entry might be used for HTTP GET caching. But that is about data freshness, which doesn't seem like what you are trying to describe.

In either case per-entry weights often leads to either O(lg n) priority queues or random sampling find a good enough candidate. Can you describe your use-case?

**Comment by hshankar** [comment]
I am not sure I understand your confusion. Here is a use case:

The records I store in the cache have  a "createdDate" of their own. This is not the creation date of the entry in the cache, but createdDate of the record itself. I want to evict the records with oldest createdDate instead of the oldest entry in the cache. The records can arrive out of order. So if we say record Cx has created time x, I have a use case where we get C10, C20, C30 and then suddenly get a flood of C11, C12 etc. In this case, I want C10, C11, C12 to be evicted before C30.

**Comment by ben-manes** [comment]
I see, so you want a size-based policy that uses the createdDate to prioritize. Here time is an implementation detail, and has nothing to do with expiration.

Do you really think this policy would provide a higher hit rate than using frequency and recency? The current approach is near optimal across many workloads. I think you should validate that your design ideas, if you haven't already.

This would be O(lg n) on insert or require random sampling on eviction to find the victim. There are libraries that provide those, but neither work wonderfully. I don't think making the strategy is useful for most users, I'm doubtful its beneficial for you, and the current one does extremely well.

If you'd like to capture an access trace we can easily simulate your policy against others. Then we'll have data to backup our opinions.

**Comment by hshankar** [comment]
I need more deterministic behavior than regular caching. In my use case, I have enough RAM to not worry about evictions at all. As long as I can guarantee that all entries with creationDate > some time (say currentTime - T) are in the cache. So it is like FIFO but with custom time instead of insertion time to determine order. And the weight is static. I am actually not aware of caffeine or guava cache internals on how they manage evictions so I was not sure how easy/hard it would be to support it.

**Comment by ben-manes** [comment]
You can read the [HighScalability article](http://highscalability.com/blog/2016/1/25/design-of-a-modern-cache.html) which provides an overview. The latter half is similar to Guava, too.

Caching is very much about non-deterministic behavior and using probabilities to predict what is most likely best to retain given the limited space. Your case might just be too far out of the norm for what most expect from a cache. The more deterministic behavior you require, the less your scenario fits a traditional cache.

I don't think you'll find exactly what you want with an off the shelf library. You'd probably be best served with a custom implementation.

**Comment by ben-manes** [comment]
Closing, as I don't plan on making the policy pluggable.
