### ISSUE TITLE
Simple feature: update value of key?

### ISSUE THREAD

**Issue by korri123** [ben-manes/caffeine#102]
Would this be feasible? E.g. this 
```java
LoadingCache<Integer, ArrayList> loadingCache = ...;

loadingCache.update(12, (ArrayList list) -> {
    list.add(new Object());
});
```
The list at key 12 would now have this object. Now instead of fetching again from the DB it would be updated realtime.

**Comment by ben-manes** [comment]
`Cache#asMap()` provides access to perform `compute`, `computeIfAbsent`, `computeIfPresent`, and `merge`. That opts out of automatically calling an attached `CacheLoader` or `CacheWriter`, which can be called manually inside of your atomic block.

```java
cache.asMap().computeIfPresent(12, (key, list) ->
  ImmutableList.copyOf(Iterables.concat(list, ImmutableList.of(5)))
);
```

Note that we have to be careful of concurrent reads accessing the value. Your options are either to make a new value (like above) or synchronize on the value prior to reading (e.g. `Collections#synchronizedList`). An update doesn't preclude you from having to consider thread safety from the reader's perspective.

**Comment by korri123** [comment]
Thanks, I hadn't thought of the concurrency implications.

**Comment by ben-manes** [comment]
Closing as I think using `asMap` is a nice solution. Feel free to reopen if you find difficulties where a specialized method would be beneficial.
