### ISSUE TITLE
Handling checked exceptions

### ISSUE THREAD

**Issue by jnehlmeier** [ben-manes/caffeine#1039]
Have you ever considered supporting checked exceptions in `mappingFunction` by providing a set of extra `getChecked()` methods?

Something like
```java
try {
  // V getChecked(K key, ThrowingFunction<? super K, ? extends @PolyNull V> mappingFunction) throws Exception
  var value = cache.getChecked(key, key -> load(key));
} catch (IOException e) {
  ...
} catch (Exception e) {
  ...
}
```
looks way better than
```java
try {
  var value = cache.get(key, key -> {
    try {
      return load(key);
    } catch (Exception e) {
      throw new CacheLoadingRuntimeException(e);
    }
  });
} catch (CacheLoadingRuntimeException e) {
  var cause = e.getCause();
  if (cause instanceof IOException) {
    ...
  } else if (...) {
    ...
  }
}
```

**Comment by ben-manes** [comment]
That’s a generic problem, so I use [Unchecked.function](https://github.com/jOOQ/jOOL#orgjooqlambdaunchecked) when needed. The CacheLoader allows throwing checked exceptions. Do either of those help?

**Comment by jnehlmeier** [comment]
> That’s a generic problem, so I use [Unchecked.function](https://github.com/jOOQ/jOOL#orgjooqlambdaunchecked) when needed. 

I am not sure what exactly you mean with "generic problem". If you meant it is a general problem of JDK functional interfaces then yes that is true. But as a library you can always define your own functional interfaces that allow throwing checked exceptions to make the usage of the library API more pleasant. 

However if you meant it is Java generics problem then I can not follow. You could very well have a `get` overload taking a different functional interface. However that would mean that the caller has to cast the lambda into the correct functional interface. So this would be annoying on the caller side and would also be a breaking change since existing method calls would be ambiguous without the cast. That is why my example above uses a different method name together with a `ThrowingFunction` functional interface (see code comment above).


> The CacheLoader allows throwing checked exceptions. 

Yes, but mostly the value computation requires more data than just the key. So I mostly use the `get()` functions to compute the value instead of `CacheLoader`.


> Do either of those help?

Not exactly. While `Unchecked.function` or any other wrapper makes it a little more readable inside the lambda you still have to unwrap the exception in the catch block and do an instanceof chain. 

So I would still favor first class support of checked exceptions in the Cache API. Especially because `CacheLoader` allows for checked exceptions it feels like an API discrepancy without a good reason in all the `get()` methods.

**Comment by ben-manes** [comment]
Thanks for the thoughtful response.

As a workaround that I'm sure you've thought of, a utility function could provide this as `getChecked(cache, func)`.

As a matter of style, I don't particularly like throwing raw `Exception` as it leads to poor error handling. If we tried to narrow by wrapping a raw Exception with a `ExecutionException` then that would defeat the purpose of your api. Ideally it might be part of the function's generic type, but that has its own troubles (K, V, T1, T2, ...). 

In Java 21, the code would be a [little friendlier](https://openjdk.org/jeps/441) to write against the existing api,

```java
try {
  return cache.get(key, Unchecked.function(this::load);
} catch (RuntimeException error) {
  switch (error.getCause()) {
    case null -> throw error;
    case IOException e -> ...
    case Exception e -> throw e;
}
```

A big question, though, is are these conditions from which the caller can reasonably be expected to recover (EJ 70)? I would argue that within the mapping function these are, but outside it becomes less clear. Typically the cache serves as a data load, so either the value is present or absent (returning `null`) which mirrors `Map.computeIfAbsent`.

If you are using it for recoverable conditions outside of the cache load then I would argue that this will be frustrating api limitation across a broad set of classes (both JDK and library). You'll find that other languages (Kotlin, Scala, C#) don't support checked exceptions and this doesn't cause them problems, so using that for your own error handling tends to be alright. Then if you use only runtime exceptions you can write that in your preferred style.
