### ISSUE TITLE
support for recording traces

### ISSUE THREAD

**Issue by phraktle** [ben-manes/caffeine#105]
We're evaluating Caffeine as a replacement for Guava caches. So far it looks generally good (thanks for all your effort!), but we do see a case where hit rates seem to be lower than previously. Does Caffeine have an easy way to record access traces to later run in the simulator, to compare eviction policies?

**Comment by ben-manes** [comment]
Unfortunately that was removed as an unused feature. But you can easy trace using a standard logger, appending to dedicated file, and reducing the format (e.g. just the message). The simulator works using `long` keys and no values, so a log of key hashes should work. You generally only need to log around a `get`. We can then either reuse a trace reader or add a new one.

The only scenario (that I know of) where it might underperform is recency-skewed distributions with a small cache. In that case the cache is too tiny to leverage frequency, the policy's frequency bias works against it, and the "admission window" isn't large enough to correct for that. In my experiments an [adaptive window](https://github.com/ben-manes/caffeine/blob/master/simulator/src/main/java/com/github/benmanes/caffeine/cache/simulator/policy/sketch/AdaptiveWindowTinyLfuPolicy.java) resolve this, but without a user report I hadn't gotten around integrating the optimization.

**Comment by phraktle** [comment]
Thanks for the fast response! It was easy enough to record a trace (just dumping hashes on gets in a file) and simulating it. I'm closing this ticket and will open another one with the trace to see if it can be optimized.
