### ISSUE TITLE
In TinyLFU, why do we need to increment all counters instead of just the smallest one?

### ISSUE THREAD

**Issue by zztaki** [ben-manes/caffeine#1068]
In my understanding, the smallest counter can more realistically reflect the frequency of request object, so why do we need to increment all counters instead of just the smallest one? This `Add` method  may inflect high-frequency items.

I'm very interested in caching, thanks for creating this awesome repo!

**Comment by ben-manes** [comment]
The simulator has this option and at the time, I don’t recall it helping improve the hit rates meaningfully. You are welcome to revisit this. See this [comment](https://github.com/ben-manes/caffeine/discussions/1016) for more details on what I guessed was why it wasn’t as helpful as one might expect.

https://github.com/ben-manes/caffeine/blob/b2dc82ddc8d8ba3c6566e7c1bdef9742f12f52a6/simulator/src/main/resources/reference.conf#L196-L197

**Comment by zztaki** [comment]
> The simulator has this option and at the time, I don’t recall it helping improve the hit rates meaningfully. You are welcome to revisit this. See this [comment](https://github.com/ben-manes/caffeine/discussions/1016) for more details on what I guessed was why it wasn’t as helpful as one might expect.
> 
> https://github.com/ben-manes/caffeine/blob/b2dc82ddc8d8ba3c6566e7c1bdef9742f12f52a6/simulator/src/main/resources/reference.conf#L196-L197

Thank you so much for your quick reply, I will revisit this. 

have a nice day！
