### ISSUE TITLE
Caffeine cache does not work scene query

### ISSUE THREAD

**Issue by sxyc026** [ben-manes/caffeine#1102]
Caffeine Version:2.9.3
```java
    @Override
    public Map<String, String> getNameMapAccess(String id) {
        return getStringStringMap(id);
    }

    @Cacheable(key = "#id", value = CaffeineNameTimeConstant.ExpiredAfterWrite.CACHE_5_SECOND)
    public Map<String, String> getStringStringMap(String id) {
        Map<String, String> map = new HashMap<>();
        int andIncrement = ATOMIC_INTEGER.getAndIncrement();
        map.put(id, andIncrement + ":ok");
        System.out.println(andIncrement + "!!!!!!!");
        return map;
    }
```
When I call the getNameMapAccess method, it doesn't work.
But the following scenarios can take effect：
```java

    @Cacheable(key = "#id", value = CaffeineNameTimeConstant.ExpiredAfterWrite.CACHE_5_SECOND)
    @Override
    public Map<String, String> getNameMapAccess(String id) {
        Map<String, String> map = new HashMap<>();
        int andIncrement = ATOMIC_INTEGER.getAndIncrement();
        map.put(id, andIncrement + ":ok");
        System.out.println(andIncrement + "!!!!!!!");
        return map;
    }
```
What should I do to make the first scene work?

**Comment by ben-manes** [comment]
Are you using Spring? I believe their version of AOP does not work for methods calls within the same class, as they use proxy objects to intercept external calls. A quick search recommended this [documentation](https://docs.spring.io/spring-framework/reference/core/aop/proxying.html#aop-understanding-aop-proxies) explaining that, but I haven't read it. Does that help?

**Comment by sxyc026** [comment]
My initial guess is this, I am preparing to write a demo for testing, thank you very much.
