### ISSUE TITLE
why not support jdk17

### ISSUE THREAD

**Issue by konakonata** [ben-manes/caffeine#1103]
when can support? pls contact me, tks.

**Comment by ben-manes** [comment]
It’s supported. What else are you looking for?

**Comment by ben-manes** [comment]
> A newbee in Java programming

Oh, I see. Java has excellent compatibility to our support for Java 11 onwards means it works perfectly fine in Java 17. We run a sanity check on our minimum Java version (11), the latest release Java version (20), and the pre-release Java version (21). This means you can run on Java 17 or later without worrying.
