### ISSUE TITLE
Obtain memory size statistics for each key

### ISSUE THREAD

**Issue by hudongdong129** [ben-manes/caffeine#1125]
There is no way to get the corresponding memory size for each caffeine instance？

**Comment by ben-manes** [comment]
If you use a weighted cache then you can [query](https://www.javadoc.io/doc/com.github.ben-manes.caffeine/caffeine/latest/com.github.benmanes.caffeine/com/github/benmanes/caffeine/cache/Policy.Eviction.html) for the total weight:
```java
cache.policy().eviction().orElseThrow().weightedSize()
```

We do not attempt to track the native object size, this is complicated enough that the Java team has a [JEP proposal](https://openjdk.org/jeps/8249196) for that. They list estimates that can be used in a custom `Weigher`.

**Comment by hudongdong129** [comment]
ok thanks
