### ISSUE TITLE
How can we restrict 'Null' values to add into cache?

### ISSUE THREAD

**Issue by ankit8051** [ben-manes/caffeine#118]
Hi Team,

How can we restrict 'Null' values to add into cache? 
Because I have one use case that if the value is null then we have to grab the data, not from the cache.

Thanks in advance.

**Comment by ben-manes** [comment]
The cache does not allow storing null values. If you perform a computation and return null then this indicates the data doesn't exist and the caller receives null. So for example `cache.get(key, function)` or `CacheLoader#load` behave similar to `ConcurrentHashMap#computeIfAbsent`. An explicit `put(key, null)` is not allowed and will throw an exception.

Does that resolve your scenario?

**Comment by ankit8051** [comment]
Thanks, Ben,

Thanks for your quick reply.

You are right. Cache is not allowing the null values. 

Actually, I was storing [java.util.Optional](https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html) so that's why I was not getting an exception.

**Comment by ben-manes** [comment]
`Optional` is a good technique for negative caching.

Can you clarify if you have an open question? I'm unsure how to proceed.

**Comment by ankit8051** [comment]
My question is resolved now.

Closing this question.
