### ISSUE TITLE
Cache with read-through cache loader throws NPE

### ISSUE THREAD

**Issue by chrisstockton** [ben-manes/caffeine#119]
Whenever a ```CacheLoader.load()``` returns a null, the ```JCacheLoaderAdapter.load()``` doesn't check that the value is not null before wrapping it in an ```Expirable``` which doesn't allow nulls.

Adding ```return value == null ? null : new Expirable<>(value, expireTimeMS());``` on line 81 seems to fix the failing test.

https://github.com/ben-manes/caffeine/compare/master...chrisstockton:read-through-load-null?expand=1

```CacheLoader.loadAll()``` also has the same problem and is similarly fixable, but hopefully it's not as common to return a null instead of any empty map.

**Comment by ben-manes** [comment]
ahh, sorry about that. I relied on the TCK with a additional tests based on code coverage and discovered bugs. Unfortunately the TCK turns out to be pretty poor and admittedly I put most of my effort towards Caffeine's core test suite. The adapter is a lot larger than I'd like due to significant differences in designs.

Since there might be other mistakes, can you use a SNAPSHOT? I figure you'll be banging on it a bit over the next few days and we can avoid version noise. If that's okay, then I'd bump the release when you gave the thumbs up.

**Comment by chrisstockton** [comment]
Sure, sounds good.  It might take a little longer than a few days, "real-work" is getting in the way lately.  But I'll be playing with it when I have spare time.

**Comment by ben-manes** [comment]
Thanks! Just let me know when you're moving off either due to lack of time or no more issues found. I think we can delay because JCache has had low adoption, isn't the primary API, and the module has a tiny download rate (253 in July according to Central).

**Comment by ben-manes** [comment]
It seems that `loadAll` does not define what happens on a `null` return value. Neither the JavaDoc nor the specification mention it, and none of the other implementations have special handling so they too would NPE. So I'm going to be null averse in my reading and assume it is not allowed.

**Comment by ben-manes** [comment]
Snapshot should be good now that the CI behaves correctly again.

**Comment by chrisstockton** [comment]
I had to take a break for a while there, but I picked this back up a few weeks ago.  I've been using the cache loader with read-through from the snapshot in production for about a week now and haven't found any more issues.

**Comment by ben-manes** [comment]
Thanks! Let me sort out #127 and then I'll get you a proper version.

**Comment by chrisstockton** [comment]
Does it look like 2.3.4 will be out soon.  It's looking like #127 is fixed?

**Comment by ben-manes** [comment]
I'd like to wait until JCTools is released with the fix, in case additional tests are going to be added. But if not then done soon then I'll go ahead regardless and apply the changes, which are non-invasive. Its critical enough that I won't delay it beyond this week and will have a release out over the weekend regardless of JCTools' status.

**Comment by ben-manes** [comment]
Released 2.3.4 with this fix. Thanks for being patient.
