### ISSUE TITLE
Mild optimization suggestion to size() preventing a concurrent chase

### ISSUE THREAD

**Issue by nitsanw** [ben-manes/caffeine#12]
Instead of chasing a moving target as producers add to the queue we can justify (IMO) representing a snapshot of the size at the time the request is made:

    public int size() {
        LinkedQueueNode<E> curr = lvConsumerNode();
        final LinkedQueueNode<E> currProducerNode = lvProducerNode();
        int size = 0;
        // must chase the nodes all the way to the producer node, but there's no need to chase a moving target.
        while (curr != currProducerNode && size < Integer.MAX_VALUE) {
            LinkedQueueNode<E> next;
            while((next = curr.lvNext()) == null);
            curr = next;
            size++;
        }
        return size;
    }

**Comment by ben-manes** [comment]
Isn't that how it is implemented? The head and tail are read once. Traversal uses a relaxed read, falling back to a volatile read spin wait until the next field is visible. The current version is,

```java
  public int size() {
    Node<E> cursor = head;
    Node<E> t = tail;
    int size = 0;
    while ((cursor != t) && (size != Integer.MAX_VALUE)) {
      Node<E> next = cursor.getNextRelaxed();
      if (next == null) {
        while ((next = cursor.next) == null) {}
      }
      size++;
      cursor = next;
    }
    return size;
  }
```

**Comment by nitsanw** [comment]
My bad, coffee underflow error.

**Comment by ben-manes** [comment]
Thanks, though! Grab a redbull =)

**Comment by nitsanw** [comment]
Yuck :P never liked that one...
I'm traditional, I'll put the kettle on.

**Comment by ben-manes** [comment]
fyi,
I rewrote my `EliminationStack` to include combining properties. The resulting `ConcurrentLinkedStack` performs quite well in my benchmarks. You may find it interesting to glance over.
