### ISSUE TITLE
Taking Snapshots of the Cache to Disk

### ISSUE THREAD

**Issue by kutchar** [ben-manes/caffeine#123]
What would be the best way to snapshot the cache state to disk (all the elements and their expirations) on some interval to be able to recover the cache when the process restarts?

**Comment by ben-manes** [comment]
Take a look at the [Policy](https://github.com/ben-manes/caffeine/wiki/Policy) api. It provides snapshot iteration order and the ability to query the internal metadata.

**Comment by kutchar** [comment]
I'm assuming you're referring to the following, right?

[Policy.Expiration.oldest](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/main/java/com/github/benmanes/caffeine/cache/Policy.java#L244)
[Policy.Expiration.youngest](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/main/java/com/github/benmanes/caffeine/cache/Policy.java#L261)
[Policy.Expiration.getExpiresAfter](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/main/java/com/github/benmanes/caffeine/cache/Policy.java#L217)

So considering the `oldest` and `youngest` are not constant time, wouldn't it be better to use the `asMap` since I just need a snapshot of the cache and not necessarily in any order?

Also, I'm assuming in either case I have to iterate through the iterator and call `Expiration.getExpiresAfter` on each item to get the expiration, correct?

**Comment by ben-manes** [comment]
If you don't care about order then, as you said, using `asMap` and `ageOf` would be best.

**Comment by kutchar** [comment]
Thanks :)

**Comment by ben-manes** [comment]
If you run into any snags be sure to let me know.
