### ISSUE TITLE
Performance: Caffeine vs ConcurrentHashMap

### ISSUE THREAD

**Issue by Zuplyx** [ben-manes/caffeine#1240]
Hello,

I created a simple JMH benchmark comparing Caffeine to the JDKs `ConcurrentHashMap` in a scenario where both are filled with 100k entries and then randomized access with 1M existing keys is performed.

According to the results Caffeine performs worse than the `ConcurrentHashMap`:

```
Benchmark                          Mode  Cnt   Score   Error  Units
CacheBenchmark.caffeineBenchmark  thrpt   25  27,002 ± 1,237  ops/s
CacheBenchmark.chmBenchmark       thrpt   25  31,441 ± 1,762  ops/s
```

Is this the expected result or did I make a mistake somewhere?

I've attached the maven project I created for the benchmark, as well as a full log of the benchmark execution:
[CacheBenchmarks.zip](https://github.com/ben-manes/caffeine/files/12818456/CacheBenchmarks.zip)
[benchmark.txt](https://github.com/ben-manes/caffeine/files/12819285/benchmark.txt)

**Comment by ben-manes** [comment]
Caffeine is built on top of ConcurrentHashMap so it is expected to be slower in most cases. The challenge was minimizing the impact of each feature while maximizing its capability.

The one case where it may be faster is computeIfAbsent on a present key. Originally CHM always locked, but in response to our benchmarks it changed to a partial prescreen. Caffeine always prescreens which can still be beneficial.
