### ISSUE TITLE
explanation on hitcount

### ISSUE THREAD

**Issue by shikhahere** [ben-manes/caffeine#1270]
I am using the CacheMetriccollector from io.prometheus.client.cache.caffeine.CacheMetricsCollector. And I am building a cache using

    val cache = Caffeine.newBuilder().maximumSize(maxSize).recordStats().build[key, value]()
    cacheMetricsCollector.addCache("<<cachename>>", cache)
   
when i am doing cache.getIfPresent(<key>)

I see the hit count is much higher then what i expect, because i also add a log when a value was found in cache.
So Ideally these counts with stats and log should match but they dont (why would that be?)

Any pointers what i could look for?

In addition I do see that the misscount and estimatedSize match correctly.

**Comment by ben-manes** [comment]
You could use a custom StatsCounter to log a stacktrace when called, and then look through a sample to see any unexpected calls.

**Comment by shikhahere** [comment]
Does that mean i have to implement pretty much what a ConcurrentStatsCounter is with a stack trace built in method?

**Comment by ben-manes** [comment]
yep. you could use delegation to decorate to a ConcurrentStatsCounter and add your logging.

**Comment by shikhahere** [comment]
Ah okay something like GuardedStatsCounter is doing, but ofcourse just a forced trace.
