### ISSUE TITLE
How to Implement Batch Loading and Ensure Deduplication of Remote Loads in Caffeine

### ISSUE THREAD

**Issue by TheBestWangHao** [ben-manes/caffeine#1292]
When I attempt to retrieve values for a batch of keys, I aim to achieve the following:

For existing keys: I want to be able to concurrently retrieve values for these keys, without being affected by operations from other threads that might be loading values for keys that do not exist. In other words, if a key already exists in the local cache, I expect to get its value immediately without waiting for other threads to load values for non-existing keys.

For non-existing keys: I prefer only one thread to trigger the remote loading operation. I want to ensure that only one thread goes to fetch values for keys that do not exist. Other threads should wait until this loading operation is completed before they can proceed. This approach prevents redundant loading, thereby enhancing efficiency.

how can i do

**Comment by ben-manes** [comment]
The caches support bulk loading using `getAll`, either passing in a mapping function or delegating to a cache loader. If the latter then you would override `loadAll` or use the `bulk` static factory method. The blocking behavior during the load is described in the [FAQ: Bulk Loads](https://github.com/ben-manes/caffeine/wiki/Faq#bulk-loads) and offers the behavior you are seeking.

For a similar but different use-case, you may also be interested in the [coalescing bulkloader](https://github.com/ben-manes/caffeine/tree/master/examples/coalescing-bulkloader-reactor) example to batch independent requests into a single load.
