### ISSUE TITLE
Deadlock when BoundedLocalCache.scheduleDrainBuffers throws an exception

### ISSUE THREAD

**Issue by tepitebson** [ben-manes/caffeine#130]
Used version: 2.3.2
In an error situation, we noticed a deadlock during call to cache's get method. We have no clear stacks to show the actual deadlock, but according to the log, an OutOfMemoryError was catched by BoundedLocalCache.scheduleDrainBuffers().

It seems that if no executor is defined for the cache it uses ForkJoinPool and with ForkJoinPool, cache's evictionLock is a NonReentrantLock which by its documentation will deadlock if called recursively.

If scheduleDrainBuffers throws an exception, performCleanup is called inside the catch-block while still holding the evictionLock. And since the performCleanup calls evictionLock.lock() on its first line, it seems that a deadlock is unavoidable in this scenario?

**Comment by ben-manes** [comment]
Thanks for the investigative work! You're absolutely correct that I forgot about this scenario. I must have only considered reentrancy if the executor threw a `RejectedExecutionException` which FJP does not (`BoundedLocalCacheTest#evict_rejected`). The fix seems straightforward so I'll have a release over the weekend.

In the mean time, as I am sure you know, you can use a non-FJP executor or even `ForkJoinPool.commonPool()::execute` to force a reentrant lock.

**Comment by ben-manes** [comment]
I plan on releasing this tomorrow and will update you when its published. Thanks again for reporting and debugging the issue.

**Comment by ben-manes** [comment]
Released 2.3.5
