### ISSUE TITLE
Neo4j uses Caffeine

### ISSUE THREAD

**Issue by Mats-SX** [ben-manes/caffeine#132]
Hello Caffeine

In the `README` a few software systems that use, or are about to use, Caffeine are mentioned. I would just like to point out that [Neo4j](https://github.com/neo4j/neo4j) is now also using Caffeine, in more than one use case internal to the database. I can provide details if necessary, but my main goal with this issue is to suggest to add Neo4j to the `on the radar` list in the `README` (Neo4j `3.1` is coming close to release, which would be the first release to include Caffeine).

All the best
Mats

**Comment by ben-manes** [comment]
Sure, we can do that. But my concern is that it might appear as an exaggeration. My understanding is that the library is used in non-critical scenarios, so the benefits might be negligible. The highly impactful use-case in neo4j is the page cache, which is a well-designed custom implementation. We wouldn't know if the techniques used by Caffeine would be useful without access traces to estimate the hit rate differences.

I don't want to detract from @chrisvest and the rest of the team's work by overstating the usage, so let me know if it would be appropriate.

**Comment by Mats-SX** [comment]
I see what you mean. I'd say that one of the use cases, the Cypher planner cache, _is_ critical, but it's typically a fairly small cache that gets accessed only once per request. For highly concurrent workloads, the cache's performance (especially if full) would probably matter, but I haven't seen any numbers on that.

**Comment by ben-manes** [comment]
You're right, the query planner should be quite important. I don't want to de-emphasize your hard work either and I'm quite happy to list Neo4j at your recommendation. Thanks for the recommendation.
