### ISSUE TITLE
priority based eviction?

### ISSUE THREAD

**Issue by asafbennatan** [ben-manes/caffeine#133]
Hi , i was wondering if i could use caffeine to cache objects each with a numbered priority (int 1-5).
when eviction is necessary caffeine will remove the object with the lowest priority number , if several exist use LRU policy,
Thanks.

**Comment by ben-manes** [comment]
Short answer:
Caffeine does not provide a pluggable eviction policy. This won't change, so your desired behavior will not be supportable.

Long answer:
Instead Caffeine implements a policy that is near optimal across a wide range of workloads. It takes into account recency and frequency, including the historic frequencies of entries no longer retained in the cache. This is performed in O(1) time, so the cache's size doesn't significantly impact the policy's performance. The goal is to maximize hit rates without users having to provide extra hints or bypass the cache to avoid thrashing. Most likely the current policy will out perform your custom one for the same workload.
