### ISSUE TITLE
JCache - Cache.asMap usage

### ISSUE THREAD

**Issue by pizzi80** [ben-manes/caffeine#1335]
Hi,

I'm trying to use Caffeine via the JCache API to stay as standard as possible

I'm trying to define some atomic cache operations that are missing in JCache (no comments on how poor this API is)

I'm struggling to use the `Cache.asMap` `Map` because it returns a 
`Map<K,Expirable<V>>` ... instead of a `Map<K,V>`

how I should use this map to not alter or eventually reset the current key expiration?

for example, how to use `Cache.asMap().merge( ... )` ?

```
public static int addIntValueInCache( String cacheName , String key , int amount ) {
      Cache<String,Integer> cache = getCache(cacheName);  // return the JCache from the CacheManager
      com.github.benmanes.caffeine.cache.Cache<K,Expirable<V>> caffeineCache = cache.unwrap(com.github.benmanes.caffeine.cache.Cache.class);
      ConcurrentMap<String,Expirable<Integer>> cacheAsMap = caffeineCache.asMap();
      return cacheAsMap.merge( key , ....... ?? );
}

```

usually on a `Map<K,V>` it's easy as `merge( key , amount , Integer::sum)`;

thanks!

**Comment by ben-manes** [comment]
You shouldn’t need to unwrap, can you use the `Cache.invoke` api? That is a computation by a different name. The implementation doesn’t try to hide itself and just assumes that the std api is used, so it might expose too much details.

**Comment by pizzi80** [comment]
thanks for your fast reply, I'll explore your suggestion!

In the meantime I've make it work calling with reflection `CacheProxy.getWriteExpireTimeMS`
which is exactly what I need to define a `Map.merge` function over an` Expirable<Integer>`
but is a _protected_ method:

```

private static final BiFunction<Expirable<Integer>, Expirable<Integer>, Expirable<Integer>> EXPIRABLE_INTEGER_MERGE_FUNCTION
			= (oldValue, newValue) -> new Expirable<>(oldValue.get() + newValue.get(), oldValue.getExpireTimeMS() );

```

and inside the main method 

```

long defaultExpiresMS = getCacheDefaultExpiration( cache )


return cacheAsMap.merge( key , new Expirable<>(amount,defaultExpiresMS) , EXPIRABLE_INTEGER_MERGE_FUNCTION).get();


```

this is obviously a worst solution because reflection is slow 
and is not a standard way of using JCache

so I'll go with invoke ... :smiley: 

thanks!!

**Comment by ben-manes** [comment]
haha, that’s horrifying 😄

If you run into any problems let me know. The invoke api is quirky but I think you’ll be happy enough with it
