### ISSUE TITLE
GC time becomes increasingly to 60s

### ISSUE THREAD

**Issue by timlincool** [ben-manes/caffeine#138]
I have daily reloaded cache at 5:00 AM. It looks fine at the beginning, but after few days. 
GC time becomes increasingly to 60s, and without full GC.

And I try on my own PC. Reload cache 30 times continuously. GC time only 0.46s.
Its seems the problem should wait for few days.

These are GCViewer pic.

server 
![gcprolbem](https://cloud.githubusercontent.com/assets/5269547/21209770/432d351c-c2b1-11e6-997f-b38006c1ef7f.png)

own PC test
![gc2](https://cloud.githubusercontent.com/assets/5269547/21210011/dfa5b422-c2b2-11e6-8b50-f11119b5709d.png)

This is my code. Did I have something wrong?

```
public class NaiveBayesianCache {

    public Cache<String, HashMap<String, Double>>    getItnameCpPro=Caffeine.newBuilder()
                                   .expireAfterWrite(25, TimeUnit.HOURS)
				   .maximumSize(1_000_000)
				   .build();

    public void doProcessDailyInitialNew(){
           HashMap<String, HashMap<String, Double>> getNaiveBayesQueryLog=getQueryLog();
           getItnameCpPro.putAll(getNaiveBayesQueryLog);
     }

}
```

VM version: java version "1.8.0_101"
VM options: " -server -Xms9g -Xmx9g -Xmn1024m -XX:PermSize=128m -XX:MaxPermSize=256m -XX:NewRatio=3 -XX:SurvivorRatio=4 -XX:+UseParNewGC -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=8 -XX:+UseConcMarkSweepGC -XX:+CMSScavengeBeforeRemark -XX:PretenureSizeThreshold=64m -XX:CMSFullGCsBeforeCompaction=1 -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70 -XX:CMSTriggerPermRatio=80 -XX:CMSMaxAbortablePrecleanTime=6000 -XX:+CMSParallelRemarkEnabled -XX:+ParallelRefProcEnabled -XX:+UseLargePages -XX:+AggressiveOpts  -XX:+DisableExplicitGC -verbose:gc -XX:+PrintGCApplicationStoppedTime -XX:+PrintGCDetails -XX:+PrintGCDateStamps -Xloggc:/dev/shm/gc.log -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=2  -XX:GCLogFileSize=70M"

caffeine 2.3.5

**Comment by ben-manes** [comment]
You probably want to take a heap dump to see what is taking up the most memory.

Note that your cache value is an unbounded map. That means the cache might be correctly limiting it to the number of entries, but some of the maps grew at an uncontrolled rate. In that case you might prefer to use `maximumWeight` and a `weigher` based on the size of the map.

**Comment by timlincool** [comment]
In this case, my hashmap could have 1~300 element. 

```
public Cache<String, HashMap<String, Double>> getItnameCpPro=Caffeine.newBuilder()
                                                                .expireAfterWrite(25, TimeUnit.HOURS)
								.maximumWeight(1_000_000)
								.weigher((String string, HashMap hashMap) -> hashMap.size())
								.build();
```
 Is that correct? Thanks for the help.

**Comment by ben-manes** [comment]
yes, lets see if that helps.

**Comment by ben-manes** [comment]
oh, and you should probably enable `recordStats` and monitor them. That way you can track the health of the cache. In addition if you want to track the size, too, then you can look at `cache.estimatedSize()` for the entry count, and `cache.policy().eviction().weightedSize()` for the overall weight. Should be pretty easy to wire it up to a reporting system, e.g. see Dropwizard Metrics in the example folder.

**Comment by ben-manes** [comment]
@timlincool is your problem resolved?

**Comment by ben-manes** [comment]
Closing, as no follow-up sounds like its fixed.
