### ISSUE TITLE
Top-K entries

### ISSUE THREAD

**Issue by davidhoyt** [ben-manes/caffeine#140]
Is it possible to introduce a way to retrieve the top-K most recently or frequently used entries in the cache? By way of example, OHC has `OHCache.hotKeyIterator()`.

**Comment by ben-manes** [comment]
Yes, see the [Cache.policy()](http://static.javadoc.io/com.github.ben-manes.caffeine/caffeine/2.3.5/com/github/benmanes/caffeine/cache/Policy.html). The `Policy.Eviction#hottest(n)` is what you're looking for.

**Comment by davidhoyt** [comment]
Thanks!

**Comment by davidhoyt** [comment]
@ben-manes is it safe to always hold a reference to the returned `Policy`?

**Comment by ben-manes** [comment]
Yes. If you know that a policy must be set, e.g. eviction, you can store the unwrapped optional to a field for cleaner code.
