### ISSUE TITLE
Add a `notificationExecutor`?

### ISSUE THREAD

**Issue by He-Pin** [ben-manes/caffeine#1432]
The current `executor` is used for both async cache loading, refreshing and removeLisenser notification.

When migrate from guava cache, I find it was:
```
removalListener(RemovalListeners.asynchronous((RemovalListener<String, String>) notification -> {
			....
		}, asyncSendTestMsgThreadPool))
```
where the executor is only used for notification remove listener

I think we can add a dedicated `nofication/listenerNotification/listenerExecutor`?

**Comment by ben-manes** [comment]
I think parameterizing them differently adds a lot of noise that isn't useful most of the time. Eventually when virtual threads mature we'll default to that.

wdyt of simply forwarding it over to your own executor as part of the removal listener? That's all that Guava is doing except on the caller's thread.

**Comment by He-Pin** [comment]
![image](https://github.com/ben-manes/caffeine/assets/501740/d32ba39a-2bc7-4aa4-ab15-4c14c53e862a)

@ben-manes I'm migrating because of the current guava pin the carried thread, and I have to say, a directly smooth brain change would make life easier for daily crud boy. how about :
```java
removeListener(xxx, executor)
```

**Comment by ben-manes** [comment]
right, I'm just not sure if it will be relevant once Java migrates onto virtual threads. regardless, it won't help you until a new release if we made that change.

Why not,
```java
removalListener((K key, V value, RemovalCause cause) -> {
  asyncSendTestMsgThreadPool.execute(() -> ...);
})

**Comment by He-Pin** [comment]
Yes, that's what I just did, but Istill think there are so many people would like to see a more smooth brain support. thank you for quick response.

**Comment by ben-manes** [comment]
great. I'll close this for now but I'll keep an open mind if it is brought up again in the future.
