### ISSUE TITLE
ExpireAfterCreate test failing based on EndDate from cached object

### ISSUE THREAD

**Issue by dwalker64** [ben-manes/caffeine#1450]
I'm caching an object (JCache unfortunately).  In the configuration I'm using one of the fields, LocalDate endDate, from the object to calculate when it should expire.

```java
public long expireAfterCreate(String key, CacheObject cacheObject, long currentTime) {
     LocalDate expirationDate = cacheObject.getEndDate().plusDays(5);
     Duration duration = Duration.between(LocalDateTime.now(), LocalDateTime(expirationDate, LocalTime.MIDNIGHT));
     return duration;
}
```

I'm using FakeTicker in my test.

The particular test that's failing is:

    ticker.advance(5, TimeUnit.DAYS);
    assertNull(cache.get(key));

I've tried advancing 1 second beyond that point as well. But the object is still in the cache.  I've also executed Thread.sleep(10* 1000); thinking that a background thread has not done its thing.  But the object is still in the cache.

Not sure what I'm doing incorrectly here.   Any guidance is much appreciated.

**Comment by ben-manes** [comment]
hmm.. can you write a self contained unit test or java project that I can step through? It shouldn't be returning an expired entry even if not yet discarded internally and instead fake a cache miss.

**Comment by ben-manes** [comment]
Here's some [unit tests](https://github.com/ben-manes/caffeine/blob/master/jcache/src/test/java/com/github/benmanes/caffeine/jcache/expiry/JCacheCreationExpiryTest.java) if somehow helpful...

**Comment by dwalker64** [comment]
Here's an example.  It's now failing on the 2 assertion:

[ExpirationTest.java.txt](https://github.com/ben-manes/caffeine/files/13956691/ExpirationTest.java.txt)

**Comment by dwalker64** [comment]
Here's that build.gradle file:


/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.6.3/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    id 'application'
    id "io.franzbecker.gradle-lombok" version "5.0.0"
}

java.sourceCompatibility = JavaVersion.VERSION_1_8
java.targetCompatibility = JavaVersion.VERSION_1_8

lombok {
    version = "1.18.+"
    sha256 = ""  // skip verifyLombok task
}


repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    compileOnly 'org.projectlombok:lombok:1.18.28'
    annotationProcessor 'org.projectlombok:lombok'

    // This dependency is used by the application.
    implementation 'com.google.guava:guava:31.1-jre'
    implementation 'com.google.inject:guice:5.0.1'
    implementation 'org.jsr107.ri:cache-annotations-ri:1.1.1'
    implementation 'com.github.ben-manes.caffeine:caffeine:2.9.1'
    implementation 'com.github.ben-manes.caffeine:jcache:2.9.1'


    // Use JUnit Jupiter for testing.
    testImplementation 'org.junit.jupiter:junit-jupiter:5.9.1'
    testImplementation 'org.junit.vintage:junit-vintage-engine:5.9.1'
    testImplementation 'com.google.guava:guava-testlib:31.1-jre'

}

application {
    // Define the main class for the application.
    mainClass = 'jcacheexpirationexample.App'
}

tasks.named('test') {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

**Comment by ben-manes** [comment]
Running your test and it fails for the opposite reason of the entry not being found. That is because you are setting the new duration to immediately expire after a read or update. If I change that to return `currentDuration` then your test passes.

```java
@Override
public long expireAfterUpdate(@NonNull String key, @NonNull CachedObject value,
    long currentTime, @NonNegative long currentDuration) {
  return 0;
}

@Override
public long expireAfterRead(@NonNull String key, @NonNull CachedObject value,
    long currentTime, @NonNegative long currentDuration) {
  return 0;
}
```

**Comment by dwalker64** [comment]
I changed those two methods to return `currentDuration` and it passes as you say.

In my production code, I am returning `currentDuration` and it's still failing.  I'm left wondering what's different between my two tests.

**Comment by ben-manes** [comment]
if you'd like to jump on a teams or zoom I might be able to help debug you through it.

**Comment by dwalker64** [comment]
Wow!!!  So generous!
How can I send you a zoom link privately?

**Comment by ben-manes** [comment]
ben.manes @ gmail

**Comment by dwalker64** [comment]
Thank you for all your awesome help!  You Rock!!!
