### ISSUE TITLE
Caffeine Cache not working in Spring Boot 3

### ISSUE THREAD

**Issue by ssolanki38** [ben-manes/caffeine#1453]
I have a Spring Boot application in which I have the following implementation of Caffeine to help me cache some tokens:

CacheConfig.java
```
@Configuration
@EnableCaching
@Profile("!test")
public class CacheConfig {
  private static final Logger logger = LoggerFactory.getLogger(CacheConfig.class);

  @Bean
  public Caffeine<Object, Object> caffeineConfig() {
    return Caffeine.newBuilder()
        .maximumSize(15)
        .expireAfterWrite(60, TimeUnit.SECONDS)
        .initialCapacity(10);
  }

  @Bean
  public CacheManager cacheManager(Caffeine caffeine) {
    logger.info("Initializing Caffeine Cache");
    CaffeineCacheManager caffeineCacheManager = new CaffeineCacheManager("TokenCache");
    caffeineCacheManager.setCaffeine(caffeine);
    return caffeineCacheManager;
  }
```

MainApplication.java:
```
@SpringBootApplication
@EnableCaching
public class InstanceServiceApplication {

  public static void main(String[] args) {
    SpringApplication.run(InstanceServiceApplication.class, args).start();
  }
}
```

And I am using the @Cacheable annotation to try to cache the token:
```
@Service
public class CloningInstanceService {
  @Cacheable(value = "TokenCache", key="#user") // Specify the cache and key name
  public String getSwiftStackTokenCache(String user) {
    String swiftStackPwd = vaultUtil.getSecret(ApplicationContext.SWIFT_STACK_PWD);
    String url = SWIFT_STACK_URI + "auth/v1.0";
    HttpResponse<String> response =
        Unirest.get(url).header("x-auth-user", user).header("x-auth-key", swiftStackPwd).asString();
    Headers responseHeaders = response.getHeaders();
    String authToken = responseHeaders.getFirst("X-Auth-Token");
    logger.info("authTokenCache: {}", authToken);
    return authToken;
  }
}
```

I have tried adding the following to the application.yaml file: 
```
spring:
  cache:
    type: caffeine
```

I've also tried using key="user" and key="{#user}" in the @Cacheable annotation but that didn't help. I'm logging the cache after calling the token and nothing is in it. Another way I can tell the cache isn't working is that i'm getting a new token in subsequent call, whereas I should be getting the same token. Have consulted multiple websites and tried looking for help online but I haven't been able to resolve this. Are there any ideas? Thanks in advance.

**Comment by ben-manes** [comment]
Unfortunately I can't help you because I have not used Spring since its 1.x release, back in its xml days. I'd recommend finding a sample project, like their pet clinic, and trying to reproduce it.

**Comment by ben-manes** [comment]
fwiw, you don’t show the calling code. If you are calling that method internally in the class then it will not go through the AOP proxy. So a direct call will not invoke the cache, but calling it on an injected instance should.

**Comment by ssolanki38** [comment]
Ah. that was the problem, the code is working as expected now. for some reason the tutorials I was using didn't specify this so I was calling the @Cacheable function from the same class. 

Thanks so much!

**Comment by ben-manes** [comment]
oh wonderful. I only know it from old Spring days and when asked previously where I had referenced this [documentation](https://docs.spring.io/spring-framework/reference/core/aop/proxying.html) that might be helpful.
