### ISSUE TITLE
Does `compute` renew the `expireAfterWrite` expiry?

### ISSUE THREAD

**Issue by SHxKM** [ben-manes/caffeine#1470]
Hi,

If I'm doing something like (pseudo):

```java
cache.asMap().compute(key, (k, val) -> {
  if (val == null) {
      val = fetchRemotely();
  }

  return val;
});
```

And I have `.expireAfterWrite(CACHE_DURATION)`, will an entry with `k=n` that is constantly requested from the cache be renewed at the same rate? In other words: does `compute()` renew/reset the expiry duration if the key is found?

**Comment by ben-manes** [comment]
Yes, a compute is always a write operation, even if it did not change the value. Similarly to `put(key, value)` that over writes with the same instance is also a considered a write. They should both renew/reset the entry's expireAfterWrite duration.

**Comment by SHxKM** [comment]
Thanks @ben-manes. So if I want static expiry (expire after 12 hours no matter what), I should prefer `get(key, mappingFunction)` I guess.

**Comment by ben-manes** [comment]
Correct, that delegates to `computeIfAbsent` which is a read if present, else a write to populate the cache (similar to `putIfAbsent`).

**Comment by ben-manes** [comment]
You could also use variable expiration and use `expireAfterCreate` to set an initial duration, and then not change it on a read or update. The `Expiry` interface gives you flexibility to calculate the new duration or do nothing.
