### ISSUE TITLE
caffeine 2.9.2 deadlock

### ISSUE THREAD

**Issue by Tzq1234** [ben-manes/caffeine#1489]
I used caffeine as a local caching tool in a production environment, but it caused a deadlock. Here are a few stack traces from some of the locked threads, I am not sure if this is enough to debug the matter.
<img width="1138" alt="stack" src="https://github.com/ben-manes/caffeine/assets/40854587/eb2cdf1b-3d47-4c4e-958b-a610d914ee6d">
I am not sure is `cache.refresh` caused this deadlock:

    public T get(String key) {
        if (!isInitial.get()) {
            return null;
        }

        if (StringUtils.isBlank(key)) {
            return null;
        }

        return cache.get(key, this::asyncLoad);
    }

    private T asyncLoad(String k) {
        cache.refresh(k);
        return null;
    }

**Comment by ben-manes** [comment]
ConcurrentHashMap does not support nested computations. The `CacheLoader` is called within a computation and generally warn against updating any mappings directly. What are you attempting to do?

**Comment by ben-manes** [comment]
You might find the FAQ section [Recursive Computations](https://github.com/ben-manes/caffeine/wiki/Faq#recursive-computations) helpful. Note that the livelock in Java 8 was resolved so that it should throw an exception in later JDK releases.

**Comment by Tzq1234** [comment]
I wrapped get method, want to this method return null directly if not present, and async load new data.

FYI, the init method like this: 

      private void initCache() {
         cache = Caffeine.newBuilder()
                .refreshAfterWrite(5, TimeUnit.MINUTES) 
                .build(new CacheLoader<String, T>() {
                    @Override
                    public T load(@NonNull String key) {
                        return loadData(key, localCacheConfigDRM.getLocalCacheSource());
                    }

                    @Override
                    public T reload(@NonNull String key, @NonNull T oldValue) {
                        return loadData(key, localCacheConfigDRM.getLocalCacheSource());
                    }
                });
      }

**Comment by ben-manes** [comment]
Why not use getIfPresent or an AsyncLoadingCache?

**Comment by Tzq1234** [comment]
ok thanks, I will take a look, this help a lot
