### ISSUE TITLE
RemovalListener not always called in unit test.

### ISSUE THREAD

**Issue by Galabar001** [ben-manes/caffeine#1503]
I have the unit test below.  I see:

% mvn -Dtest=CaffeineTest test
...
[ERROR]   CaffeineTest.testCache:32 expected: <1> but was: <0>
[ERROR]   CaffeineTest.testCache:32 expected: <1> but was: <0>
[ERROR]   CaffeineTest.testCache:32 expected: <1> but was: <0>
[INFO] 
[ERROR] Tests run: 100, Failures: 32, Errors: 0, Skipped: 0

I'm not sure if this unit test is valid.  If not, please let me know.

```
import java.util.ArrayList;
import java.util.List;

import com.github.benmanes.caffeine.cache.Cache;
import com.github.benmanes.caffeine.cache.Caffeine;
import com.github.benmanes.caffeine.cache.RemovalListener;

import org.junit.jupiter.api.RepeatedTest;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class CaffeineTest {

    @RepeatedTest(100)
    void testCache() {
	List<String> removed = new ArrayList<>();
	
	Cache<String, String> cache = Caffeine.newBuilder()
	    .maximumSize(2)
	    .removalListener((key, value, cause) -> { removed.add((String) key); })
	    .build();

	cache.put("one", "one");
	cache.put("two", "two");
	cache.put("three", "three");

	cache.cleanUp();
	assertEquals(2, cache.asMap().size());

	// Seeing that removed often has size 0.
	assertEquals(1, removed.size());
    }
}
```

**Comment by ben-manes** [comment]
Since the listener is notified asynchronously by submitting the evicted item to an executor, you are allowing the test to race ahead. The `cleanUp()` triggers an eviction, but the notification task is separate. You can use [Awaitility](https://github.com/awaitility/awaitility) for concurrent tests, something like `await().until(removed, hasSize(2))`.

**Comment by ben-manes** [comment]
Generally for non-async tests I use the `Runnable::run` trick, e.g. for the test suite here. Then it gets done immediately on the caller thread so there is less test code. If it is allowed to be async and I need to assert behavior, then `cleanUp()` is a good choice. However, often I'll just let that be handled by Awaitility as it polls until the desired state or a timeout. Below is an example of your test using that.

```java
import static org.awaitility.Awaitility.await;
import static org.hamcrest.Matchers.aMapWithSize;
import static org.hamcrest.Matchers.hasSize;
import static org.hamcrest.Matchers.is;

import java.util.concurrent.ConcurrentLinkedQueue;

import org.junit.jupiter.api.RepeatedTest;

import com.github.benmanes.caffeine.cache.Cache;
import com.github.benmanes.caffeine.cache.Caffeine;
import com.github.benmanes.caffeine.cache.RemovalCause;

public class CaffeineTest {

  @RepeatedTest(100)
  void testCache() {
    var removed = new ConcurrentLinkedQueue<String>();
    Cache<String, String> cache = Caffeine.newBuilder()
        .removalListener((String key, String value, RemovalCause cause) -> {
          removed.add((String) key);
        })
        .maximumSize(2)
        .build();

    cache.put("one", "one");
    cache.put("two", "two");
    cache.put("three", "three");

    await().until(cache::asMap, is(aMapWithSize(2)));
    await().until(() -> removed, hasSize(1));
  }
}
```
