### ISSUE TITLE
Mark cache entries as non-evictable

### ISSUE THREAD

**Issue by vatbub** [ben-manes/caffeine#1522]
I am trying to write a video recorder that can skip back and forth in the recorded video stream as it is recording. This essentially means that I am reading from a video file as I am encoding the video, which is at best not a good idea and at worst not possible at all. To try to solve this, I am splitting the video stream into multiple smaller video files and have Caffeine as an in-memory caching layer. The way I imagine this to work is as follows:

1. A video frame is received from the camera. It is written to the cache and encoded to the video file. Since the video file is not yet available for reading, the cache must not evict the recorded frames, as there is no way yet to read them back from the video file.
2. After every say 30 frames, the video file is closed and a new video file is started for recording. This means that the previous video file is now available for reading. Consequently, the cache may now evict the frames from the previous video file.

As far as I am aware, Caffeine does not have such a mechanic, yet that allows certain cache entries to be marked as non-evictable, in which case, implementing that would be a nice addition.

Cheers :)

**Comment by ben-manes** [comment]
This is called pinning, see the [faq entry](https://github.com/ben-manes/caffeine/wiki/Faq#pinning-entries) for how to do this. Does that help?
