### ISSUE TITLE
Documentation on jcache application.conf settings

### ISSUE THREAD

**Issue by wsargent** [ben-manes/caffeine#154]
I have a working example of Play WS using HTTP caching with Caffeine JCache as the backend JSR 107 implementation.  

I'd like to point people to a documentation page detailing how they can control the size and expiration of HTTP responses in the cache -- currently I have this:

https://github.com/wsargent/play-ws-using-http-cache-example/blob/master/conf/application.conf

```

caffeine.jcache {
  play-ws-cache {
    listeners = ["caffeine.jcache.listeners.test-listener"]

    monitoring {
      statistics = true
      management = true
    }

    policy {
      # Corresponds to jcache expiration.  HTTP Cache is designed to stick around even if stale, so
      # there is no point in dumping anything manually.
      lazy-expiration {
        creation = eternal
        update = eternal
        access = eternal
      }

      eager-expiration {
        # Expire entries after the specified duration has passed since the entry was created, or the most recent replacement of the value.
        # This could be desirable if cached data grows stale after a certain amount of time.
        after-write = 24h

        # Expire entries after the specified duration has passed since the entry was last accessed by a read or a write.
        after-access = 24h
      }

      maximum {
        # Number of entries allowed in cache.  Note that this does not account for overall size of the HTTP response,
        # so you should use a weigher if you are concerned about memory.
        size = 10000
      }
    }
  }

  listeners {
    test-listener {
      class = "controllers.TestCacheEntryListener"
      filter = "controllers.TestCacheEntryEventFilter"
      synchronous = false
      old-value-required = false
    }
  }

}
```

Is there any documentation / comments I can add for this?  It looks like the only application.conf in caffeine itself is https://github.com/ben-manes/caffeine/blob/master/jcache/src/test/resources/application.conf but that doesn't detail what the various flags do.  

Also, it would help to know the ideal settings for this -- if a custom weigher should be used, or if it's possible to expire based on count and time through the listeners and filters.  What's the worst case scenario on caching -- if someone sets a maximum size of one hundred billion, will the JVM run out of memory, or will it attempt to clear?

**Comment by ben-manes** [comment]
Oh, I think you're looking at the wrong configuration file. The [reference.conf](https://github.com/ben-manes/caffeine/blob/master/jcache/src/main/resources/reference.conf) provides more detail. It is still sparse compared to the wiki, but mostly because the settings are either JCache or correspond directly to a Caffeine feature.

I am working on unit tests for variable expiration, which I hope to get baked soon. Then I'd integrate that with JCache to make `lazy-expiration` eager (deprecate that block with a more appropriate name). This is based on a [TimerWheel](https://github.com/ben-manes/caffeine/blob/expiry/caffeine/src/main/java/com/github/benmanes/caffeine/cache/TimerWheel.java) to be amortized O(1). That might work nicely if caching remote HTTP resources based on their expires header. Unfortunately JCache's expiry doesn't accept the key/value, but perhaps we can support either theirs or ours (if there is interest).

JCache is incompatible with weak/soft references, so all entries are strong. There isn't any attempt to clear the cache by monitoring free memory, as that is error prone. So a worst case setting is either a memory leak or lack of data consistency by not refreshing.

**Comment by wsargent** [comment]
Okay, so the advantage of the jcache layer here is that it's implementation independent and I can configure it from application.conf... the disadvantage is that it's hard to manage the overall size of the cache without some extra call back logic, and expiration can't be done per entry.  Does that sound about right?

**Comment by ben-manes** [comment]
What do you mean by "hard to manage the overall size of the cache without some extra call back logic"?

JCache has a weird variable expiration that lets entries differ, but doesn't allow for inspecting them to decide on without threadlocal hacks. The spec authors rely on a size constraint to remove dead entries, but don't offer size as a JCache feature. There are a lot of odd decisions in JCache, but if your usage is simple then you can be vendor neutral.

**Comment by wsargent** [comment]
> What do you mean by "hard to manage the overall size of the cache without some extra call back logic"?

Using a weigher for example:

https://github.com/ben-manes/caffeine/blob/master/jcache/src/test/java/com/github/benmanes/caffeine/jcache/configuration/TestWeigher.java

**Comment by ben-manes** [comment]
Oh, then yes.

**Comment by ben-manes** [comment]
Can I close? Or do you have suggestions for where you think documentation is lacking, etc. that might be helpful?

**Comment by wsargent** [comment]
If you keep it open, I'll have some suggestions on Monday.

**Comment by ben-manes** [comment]
Eager per entry expiration is now supported as of 2.5.0.

JCache's per-entry remains lazy. It was too complicated to be backwards compatible, map to eager, and work around API differences causing the TCK to fail. The cost is that lazy acts the same as the spec author's implementations, which means it was intentionally a dangerous method when used without a size constraint. In v3.0, the "eager" and "lazy" expirations will be replaced with a single type that map's to JCache's. 

Eager expiration can be used by setting `eager-expiration.variable` to an `Expiry` class. Alternatively the native API can be configured using `Caffeine.expireAfter(Expiry)`.

The implementation is optimized for durations up to 7 days and degrades away from O(1) if that overflows.

Note too that this provider supports DI, e.g. see [JCacheGuiceTest](https://github.com/ben-manes/caffeine/blob/master/jcache/src/test/java/com/github/benmanes/caffeine/jcache/JCacheGuiceTest.java).

**Comment by wsargent** [comment]
Thanks.  I haven't forgotten about this -- there's been a number of fires to put out each day today and we're looking at RC1 this week...
