### ISSUE TITLE
JCache interface ExpireAfterAccess is not honored if statistics is not enabled

### ISSUE THREAD

**Issue by IsenGrim613** [ben-manes/caffeine#158]
in method
`com.github.benmanes.caffeine.jcache.CacheProxy::setAccessExpirationTime(Expirable<?> expirable, long currentTimeMS)`

Line 1077: `currentTimeMS = ticker.read();` is wrong.
`ticker.read();` returns the current time in nano seconds resulting in the `getExpiryForAccess` feature not being honored.

The correct line should read
`currentTimeMS = nanosToMillis(ticker.read());`

The current workaround is to enable statistics, which pre-populates `currentTimeMS` from a correct value.

**Comment by ben-manes** [comment]
Thanks for investigating, identifying the bug fix, and the workaround. Sorry if this caused any problems. I'll add a test case and have patch release out over the weekend.

**Comment by ben-manes** [comment]
Released `2.5.1`
