### ISSUE TITLE
How to run the benchmarks?

### ISSUE THREAD

**Issue by cruftex** [ben-manes/caffeine#16]
Can you please add information to the benchmarks wiki page how to run the benchmarks?

I dit try:
./gradlew jmh

And get:

...
FAILURE: Build failed with an exception.

* Where:
Script '/home/jeans/ideaWork/caffeine/caffeine/gradle/jmh.gradle' line: 32

* What went wrong:
Execution failed for task ':caffeine:jmh'.
> jmh: includePattern expected

**Comment by ben-manes** [comment]
This is documented under [How to Contribute](https://github.com/ben-manes/caffeine/wiki/Contribute). The `jmh.gradle` file includes a link to the plugin where the configuration options are explained.

You'd want to run,
```bash
./gradlew jmh -PincludePattern=GetPutBenchmark
```
