### ISSUE TITLE
Version 3.1.8 is not compatible with jdk21

### ISSUE THREAD

**Issue by liu9187** [ben-manes/caffeine#1619]
I found that jdk21 is missing the java.util.concurrent.TimeUnit class, so the expiration time cannot be set.

**Comment by ben-manes** [comment]
It sounds like a local environment issue as that class still [exists](https://docs.oracle.com/en%2Fjava%2Fjavase%2F21%2Fdocs%2Fapi%2F%2F/java.base/java/util/concurrent/TimeUnit.html). The release was [cross-compiled](https://github.com/ben-manes/caffeine/actions/runs/5805460394) with jdk21 as part of the github action. The current master is compiled and benchmarked against 11, 22, 23 (EA), and Graal 21.

**Comment by liu9187** [comment]
Okay, I understand.  I have tried it and version 17 can also be used

**Comment by liu9187** [comment]
Okay, I understand.  I have tried it and version 17 can also be used
