### ISSUE TITLE
Caffeine.newBuilder is typed to Caffeine<Object, Object>

### ISSUE THREAD

**Issue by arnaudroger** [ben-manes/caffeine#166]
is there a reason for that? 
why not 
<K, V>  Caffeine<K, V> newBuilder() ?

**Comment by arnaudroger** [comment]
nevermind, realised it's not relevant to return type of build().

**Comment by ben-manes** [comment]
yeah, the intermediate inferences would still be needed to make its way through the chain or users would always have to explicitly set the types. This is @kevinb9n's trick when he designed Guava's builder.
