### ISSUE TITLE
Get the least recent used key-value

### ISSUE THREAD

**Issue by Aitozi** [ben-manes/caffeine#1727]
Can we retrieve the least recently used key-value pair from the cache that is about to expire?

I want to use Caffeine as a memory map for values stored on disk. When the capacity is reached, I need to identify the next key-value pair set to expire and determine which value will free up space for storing new data on disk.

**Comment by ben-manes** [comment]
Yes, see [cache.policy()](https://www.javadoc.io/doc/com.github.ben-manes.caffeine/caffeine/latest/com.github.benmanes.caffeine/com/github/benmanes/caffeine/cache/Policy.html). The expiration policy can return what it thinks are the oldest (next to expire).
