### ISSUE TITLE
Feature request: add compute/computeIfPresent to LoadingCache

### ISSUE THREAD

**Issue by oobles** [ben-manes/caffeine#173]
When using a LoadingCache with expiry, it is sometimes useful to update the state of a value in the cache.  Doing something like:

   ObjectX  x  = cache.get( key );
   x.setUpdateValue( newValue );

However, this has the possibility of a race condition if another thread causes key to expire and get evicted from the cache.  It would be possible to update the value atomically using a compute function:

   cache.computeIfPresent(key, (k,v) -> { v.setUpdateValue( newValue ); return v; } );

Combined with a loadingCache, the loaded item would be loaded and updated all atomically.  Also, adding compute/computeIfPresent/computeIfAbsent would be useful for other purposes.

**Comment by ben-manes** [comment]
Yes, this is available in the asMap() view, which is an escape hatch to do more low level operations that wouldn't typically be done by an opinionated interface.

**Comment by oobles** [comment]
Thanks for the fast response.  I had just found the asMap() and was implementing and about to come back and close this. :)  If I return null from computeIfPresent and the value is discarded will the removal listener get called?

**Comment by ben-manes** [comment]
Yes, with the cause explicit. The only writer won't be called, since you already have an explicit atomic block so it would be redundant / confusing.

**Comment by oobles** [comment]
Thanks! Just what I was hoping.
