### ISSUE TITLE
The new created entry is easy to be evicted when maxWeight is set.

### ISSUE THREAD

**Issue by Aitozi** [ben-manes/caffeine#1757]
Caffeine use window-tinyLFU to decide the item to evict. If the maxWeight is set, The window cache size use 1% max weight. If a new entry exceed the 1% max weight, it could very likely be evicted. Because, it has no time to gather the `candidateFreq` bigger than 5 ? 

<img width="685" alt="image" src="https://github.com/user-attachments/assets/5d991cca-9f94-428d-ae89-859869020c30">

For example, If I have a cache with 20GB max weight. And a new created file 500MB > 200MB(window size). And if all other cache are touched. This new created file will be expired directly.

<img width="834" alt="image" src="https://github.com/user-attachments/assets/8e9e2c93-8b96-4a34-af85-2ec81aa68bba">

Partially reported [here](https://github.com/apache/paimon/pull/1644#discussion_r1273399483) and [here](https://github.com/apache/paimon/issues/3855)

Can a higher window cache size solve this? I think the new added item (bigger than the window size) need time to observe before quickly evicted.

**Comment by ben-manes** [comment]
The optimal size of the window cache isn't known upfront so the cache will monitor and adjust it to maximize the hit rate. 

https://github.com/ben-manes/caffeine/blob/98895ffbb5e06b345d69fa969fc116c625b70217/caffeine/src/main/java/com/github/benmanes/caffeine/cache/BoundedLocalCache.java#L153-L162

This is easy to see in a stress test for a non-weighted workload,

![image](https://github.com/user-attachments/assets/2f816fff-1f46-46a3-b356-e03d014670d8)

The default starting configuration is 1% because that works well in many critical workloads so it seemed like a reasonable best guess. Since we can't predict if that is beneficial or harmful, we have to rely on a grace period until things warm up enough to settle at a more optimal state (similar in spirit to the JIT). If you capture a trace or monitor for a longer duration then you should observe good performance, but the startup might be a little below par out of simple bad luck.

**Comment by ben-manes** [comment]
You might try upgrading to see if the refinement in https://github.com/ben-manes/caffeine/commit/25b7d17b1a246a63e4991d4902a2ecf24e86d234 helps. You are on an older version, try our latest release.

**Comment by Aitozi** [comment]
Very thanks for your detailed and helpful comments. I hadn't noticed the hill climbing mechanism before.

> You might try upgrading to see if the refinement in https://github.com/ben-manes/caffeine/commit/25b7d17b1a246a63e4991d4902a2ecf24e86d234 helps. You are on an older version, try our latest release.

Will upgrade and test it.

I see this picture before, but not quite understand the meaning, what's the `% window` line mean ? 
![](https://private-user-images.githubusercontent.com/378614/355674631-2f816fff-1f46-46a3-b356-e03d014670d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMDc1OTMsIm5iZiI6MTcyMzAwNzI5MywicGF0aCI6Ii8zNzg2MTQvMzU1Njc0NjMxLTJmODE2ZmZmLTFmNDYtNDZhMy1iMzU2LWUwM2QwMTQ2NzBkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QwNTA4MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00N2QwMDYzNjU0OTE1NjZkOTlmMDViNzFkYWNkMmNlMDRlN2M5OTEwM2VkODZkYjRmNGMzNjJjMzUzNDYxOTRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.J39F-A5teHZwObrHn7c_kxEOF7_K8nZarN7qbRK0W1w),

**Comment by ben-manes** [comment]
> I see this picture before, but not quite understand the meaning, what's the % window line mean ?

`% window` means how large the window is in terms of total capacity. The picture shows the cache adapt from its 1% configuration (frequency-biased) to window size of 60% when optimizing for an LRU-biased trace. It then shrinks that to 0% when an MRU-biased trace runs, and so on. The cache is split into two regions, window and main, and the percentage is how much of the maximum total capacity they manage.

**Comment by Aitozi** [comment]
Thanks, get it.

**Comment by Aitozi** [comment]
After upgrading to 3.1.2, the newly added entry is not evicted immediately (in the unit test). Is this mainly due to this line [change](https://github.com/ben-manes/caffeine/commit/25b7d17b1a246a63e4991d4902a2ecf24e86d234#diff-6681a4453a3e3fe82880b8f0c5b943b65b66829fe35b1cd09e57bd8a9b799f0aL723) ?

**Comment by ben-manes** [comment]
That seems likely but I certainly wouldn’t remember the details by now. There is a lot of complexity to juggle that’s too subtle to recall. Perhaps I was polling from the wrong end by mistake and realized that then. Glad it’s looking better!
