### ISSUE TITLE
Make checker-qual dependency optional?

### ISSUE THREAD

**Issue by chrylis** [ben-manes/caffeine#1765]
Caffeine has a `compile` dependency on `org.checkerframework:checker-qual`, which pulls `checker-qual` into the visible class/modulepath of any project that uses Caffeine. This seems unnecessary, since `checker-qual` provides only annotations, and I _think_ it could be made `optional`.

**Comment by ben-manes** [comment]
It is too messy of a situation that the simplest is to advise those who want to exclude it to do that in their builds. There are some exhausting threads on Guava about it and my rule-of-thumb was just to mimic them and not get into that debate. I think sometime soon they will switch to jspecify when it has tooling support.

A few of the random pains that I've encountered (maybe more by others)
1. Some JVM languages have had bugs where they could not load classes with missing annotations. These are fixed and resurface, even though the JVMLS says it is optional.
2. The Java Module System requires that these are declared in its metadata, but I am unsure how it treats it when those modules are not present, and might have changed between releases. I'm unsure if a JPMS modular app may require this to be a present dependency.
3. A lot of confusion between when to use optional or provided scope by the Maven community, so I think it adds another wrinkle of what developers seem to want.

As a library author it seems safest to include and not have surprising downstream breakages. The dependency is very small and should be optional, so excluding it is okay but a consumer-side decision, who can then be responsible if that causes some compatibility problems.
