### ISSUE TITLE
Pinning of values in the cache

### ISSUE THREAD

**Issue by JohannesLichtenberger** [ben-manes/caffeine#1776]
Hi Ben,

I'm currently changing the pages of my DBS project to use MemorySegments. So, I have to decide when to close the arenas, which allocate the space... I will pin the pages as long as they are in use, but

```java
  public PageCache(final int maxWeight) {
    final RemovalListener<PageReference, Page> removalListener = (PageReference key, Page page, RemovalCause cause) -> {
      assert key != null;
      key.setPage(null);
      assert page != null;

      if (page instanceof KeyValueLeafPage keyValueLeafPage) {
        assert keyValueLeafPage.getPinCount() == 0 : "Page must not be pinned: " + keyValueLeafPage.getPinCount();
      }
      page.close();
    };

    cache = Caffeine.newBuilder().maximumWeight(maxWeight).weigher((PageReference _, Page value) -> {
      if (value instanceof KeyValueLeafPage keyValueLeafPage) {
        return keyValueLeafPage.getPinCount() > 0 ? 0 : keyValueLeafPage.getUsedSlotsSize();
      } else {
        return 1000;
      }
    }).scheduler(scheduler).removalListener(removalListener).build();
  }
```

The assertion in the removal listener doesn't hold, but I think Caffeine doesn't evict the entries immediately!?

Pinning itself is implemented as

```java
  @Override
  public void pin(int trxId, PageReference key, KeyValueLeafPage page, boolean updateRecordPageCache) {
    LOGGER.trace("Pin page {} from trxId {}", page.getPageKey(), trxId);
    AtomicBoolean pinned = new AtomicBoolean(false);
    if (updateRecordPageCache) {
      assert recordPageCache.get(key) != null;
      recordPageCache.asMap().merge(key, page, (_, _) -> {
        pinned.set(true);
        page.incrementPinCount();
        return page;
      });
    } else {
      assert pageCache.get(key) != null;
      pageCache.asMap().merge(key, page, (_, _) -> {
        pinned.set(true);
        page.incrementPinCount();
        return page;
      });
    }
    pageKeyToOffsetCache.put(page.getPageKey(), key.getKey());
    addPageKey(trxId, page.getPageKey());
    if (!pinned.get()) {
      LOGGER.trace("Page {} not found in cache, put it in cache", page.getPageKey());
      assert pinned.get();
    }
  }
```

**Comment by ben-manes** [comment]
There are a points that might cause confusion so I'll bullet them out. I'm not sure if you had a question so maybe these will help.

1. The `Caffeine.removalListener` is run asynchronously after the item was removed, outside of the entry's lock.
2. The `Caffeine.evictionListener` is called atomically within the entry's lock during automatic removal (size, expiration, collected).
3. The listeners will swallow and log any exception thrown.
4. To run validation logic on an explicit removal and cancel that operation, e.g. throw if pinned, then that validation check should be made manually within the removal computation. 
5. If the removed item can be reinserted then inspections under the entry's lock for state changes is ideal to avoid racy reads for transition logic. So if the item could be removed but reacquired, then closing under a computation is better else the lock-free call could collide with an repinning.
6. Eviction is not performed immediately but is prioritized. If it was instant that would require all writes to throttle on a shared lock so that every insert has a corresponding eviction, ensuring the cache never exceeds its threshold. This becomes a scalability bottleneck, rarely is needed, and can be emulated client-side (lock + `cleanUp()`). Instead the write is performed, the policy update added to a write buffer, and draining that buffer is scheduled on the executor. This way more writes can occur and the buffer absorb them with similar latency for eviction, with a buffer max size to avoid runaway growth for back pressure if inserts outpace the eviction throughput.
7. The `scheduler` is only applicable for expiration for more prompt eviction if the cache is idle so some background thread needs to know to tigger a `cleanUp()`.

**Comment by JohannesLichtenberger** [comment]
Thanks for the explanation. The question should be how it's possible that a pinned page is evicted (though as explained later I think it's my misunderstanding of the listener and it's most probably a race between the listener call and a reinsertion and pinning).

So, I think I should use the eviction listener instead.  Am I right that the page should never be evicted if the pin count is > 0? I'm assigning a weight of 0.

Currently, I think what may happen is, that the page is fetched again and stored in the cache (also pinned) before the call to the removal listener.

**Comment by ben-manes** [comment]
yep, sounds like a race on reinsertion. The weight of zero should avoid the size eviction as it will skip over that entry, and uses its own computation to do the removal so if it flips after selection but before locking it, it will cancel that attempt and find another victim.

**Comment by JohannesLichtenberger** [comment]
So, next problem:

```java
Already closed
java.lang.IllegalStateException: Already closed
	at java.base/jdk.internal.foreign.MemorySessionImpl.alreadyClosed(MemorySessionImpl.java:310)
	at java.base/jdk.internal.misc.ScopedMemoryAccess$ScopedAccessError.newRuntimeException(ScopedMemoryAccess.java:113)
	at java.base/jdk.internal.misc.ScopedMemoryAccess.getIntUnaligned(ScopedMemoryAccess.java:1883)
	at java.base/java.lang.invoke.VarHandleSegmentAsInts.get(VarHandleSegmentAsInts.java:108)
	at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.get(AbstractMemorySegmentImpl.java:772)
	at io.sirix.page.KeyValueLeafPage.getAvailableSpace(KeyValueLeafPage.java:463)
	at io.sirix.page.KeyValueLeafPage.getUsedByteSize(KeyValueLeafPage.java:524)
	at io.sirix.page.KeyValueLeafPage.getUsedSlotsSize(KeyValueLeafPage.java:517)
	at io.sirix.cache.PageCache.lambda$new$1(PageCache.java:34)
	at com.github.benmanes.caffeine.cache.BoundedWeigher.weigh(Weigher.java:93)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$remap$16(BoundedLocalCache.java:2860)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1957)
```

The arena is closed in `page.close()`:

```java
  @Override
  public void close() {
    if (!isClosed) {
      assert pinCount.get() == 0;
      isClosed = true;
      arena.close();
    }
  }
```

Not sure why this is happening now / what can be the cause :-/

**Comment by ben-manes** [comment]
It sounds like you must have closed it outside of a `ConcurrentHashMap.compute`?

**Comment by ben-manes** [comment]
> a race between the listener call and a reinsertion and pinning
if you are able to reinserting it, you would need to check if closed under that compute and cancel, right? The insert might have a stale page it is trying to add and pin.

**Comment by JohannesLichtenberger** [comment]
Outside the EvictionListener, probably. Do you know if I can print the stack trace on each close call? Maybe I should switch to another method, as it's not easy to find the close-calls ;-)

**Comment by JohannesLichtenberger** [comment]
I've used a `clear` method instead, but only call in the listener:

```java
    final RemovalListener<PageReference, Page> removalListener = (PageReference key, Page page, RemovalCause cause) -> {
      assert key != null;
      key.setPage(null);
      assert page != null;

      if (page instanceof KeyValueLeafPage keyValueLeafPage) {
        assert keyValueLeafPage.getPinCount() == 0 : "Page must not be pinned: " + keyValueLeafPage.getPinCount();
      }
      page.clear();
    };
```

Really strange... but I think for today I'll leave it at that

**Comment by ben-manes** [comment]
> Do you know if I can print the stack trace on each close call?

You can create and log an exception, which is good enough for debugging. For real usage, you can use the `StackWalker` api to get the caller very cheaply (`StackWalker.getInstance(RETAIN_CLASS_REFERENCE).getCallerClass()`).

> I think for today I'll leave it at that

welp, glad you have a good enough solution for now.

**Comment by JohannesLichtenberger** [comment]
> > a race between the listener call and a reinsertion and pinning
> 
> if you are able to reinserting it, you would need to check if closed under that compute and cancel, right? The insert might have a stale page it is trying to add and pin.

It shouldn't be in the cache when I close/clear in the evictionListener. When it's not in an in-memory reference and not in the cache it's reread from disk, so not sure what's going on.

**Comment by JohannesLichtenberger** [comment]
```java
      page = (KeyValuePage<DataRecord>) resourceBufferManager.getPageCache()
                                                             .get(pageReferenceWithKey,
                                                                  _ -> pageReader.read(pageReferenceWithKey,
                                                                                       resourceSession.getResourceConfig()));
      assert !page.isClosed();
```

```
  @Override
  public Page get(PageReference key, Function<? super PageReference, ? extends @PolyNull Page> mappingFunction) {
    return cache.get(key, mappingFunction);
  }
```

That's strange, that the assertion fails, as I'm reading here from the cache:

```
java.lang.AssertionError
	at io.sirix.access.trx.page.NodePageReadOnlyTrx.getPageFragments(NodePageReadOnlyTrx.java:640)
	at io.sirix.access.trx.page.NodePageReadOnlyTrx.loadDataPageFromDurableStorageAndCombinePageFragments(NodePageReadOnlyTrx.java:557)
```

**Comment by ben-manes** [comment]
There is the race of the entry being read before the computation completes and updates the hash table mapping. Similarly it could get the value, the thread is context switched, and it was closed by the time it asserted. I'd think you'd be acquiring it via a compute to pin it or else have a retry loop if you want to allow for optimistic reads that might fail.

**Comment by JohannesLichtenberger** [comment]
@ben-manes, I'm currently debugging, and have this setup of the cache

```java
    final RemovalListener<PageReference, KeyValueLeafPage> removalListener =
        (PageReference key, KeyValueLeafPage page, RemovalCause cause) -> {
          assert cause.wasEvicted();
          assert key != null;
          key.setPage(null);
          assert page != null;
          assert page.getPinCount() == 0 : "Page must not be pinned: " + page.getPinCount();
          page.clear();
        };

    cache = Caffeine.newBuilder()
                    .maximumWeight(maxWeight)
                    .weigher((PageReference pageRef, KeyValueLeafPage value) -> value.getPinCount() > 0
                        ? 0
                        : value.getUsedSlotsSize())
                    .scheduler(scheduler)
                    .evictionListener(removalListener)
                    .build();
```

I'm setting breakpoints in the eviction/removal listener, but it never stops there. However, an entry that is computed and was in the cache before is suddenly not in the cache anymore (for testing, the cache holds maybe two or three pages only, depending on the size).
