### ISSUE TITLE
I am using reactive version of caffeine cache version 3.1.8

### ISSUE THREAD

**Issue by Shanmugam-Chinnappaiyan** [ben-manes/caffeine#1777]
Hi Team,
      Observed below issue making the reactive java spring webflux application unresponsive 

com.github.benmanes.caffeine.cache.BoundedLocalCache file in performCleanUp() method is blocking 1 thread

Can you help advice , if this is resolved in later versions or what should be the right measure to resolve this?

**Comment by ben-manes** [comment]
That's not much information to go on. That method is called asynchronously by an executor. It's only blocking call is to evict an item, which could block in the ConcurrentHashMap operation. If you have very long Map computations then that can impede eviction and throttle writes from progressing. Typically that is resolved by performing the computation outside of the hash map, e.g. using AsyncCache, which stores a future to loading the value. This was only recently natively added to Spring 6.1. Are you using that [native support](https://docs.spring.io/spring-framework/reference/integration/cache/annotations.html#cache-annotations-cacheable-reactive) or a different implementation?

**Comment by Shanmugam-Chinnappaiyan** [comment]
Thanks for the prompt reply. I am using com.github.benmanes.caffeine.cache.AsyncLoadingCache. We use 40,000 key values for a particular use case where values are little heavy. We are not using native implementation and our spring version 3.2.3

**Comment by ben-manes** [comment]
Then you would need to share that implementation, the full stack traces, and optionally a jfr profile. It sounds like a usage mistake that is blocking the hash table from evicting due to a synchronous, long computation under the table’s lock.
