### ISSUE TITLE
Sometimes StackOverflowError (reflect.InvocationTargetException) occurs while init caffein cache with spring boot

### ISSUE THREAD

**Issue by injae-kim** [ben-manes/caffeine#1778]
![image](https://github.com/user-attachments/assets/d2a3ddd1-f24d-422a-abf3-852ade67a68e)

```java
Caused by: java.lang.IllegalStateException: com.github.benmanes.caffeine.cache.SSSMSW
```

Hi! recently I face above `StackOverflow` error while init caffeine cache with spring boot and failed to start spring appllication.
- JDK: 11, spring-boot: v2.2.4

Seems caffeine init `caffeine.cache.SSSMSW` by reflection but StackOverFlow is occurred due to recursive call on constructor.
This issue is not always reproduced and occurred recently.

Can I know is there any related issue or workaround? thank you! 🙇

**Comment by injae-kim** [comment]
Hmm maybe its bug on spring-boot side with relection..

**Comment by ben-manes** [comment]
What version of Caffeine? The line numbers don't match 3.1.8

**Comment by ben-manes** [comment]
yeah, this being an issue with Spring's custom classloader makes more sense. If somehow it has a recursive loop back into itself from a misconfiguration, then the reflective load would fail. In the current release we use MethodHandle to invoke the constructor instead of the older reflection api.

**Comment by injae-kim** [comment]
@ben-manes , I use `caffeine:2.9.1`!

> In the current release we use MethodHandle to invoke the constructor instead of the older reflection api.

oh~ thank you. I'll check spring side code and also consider to version-up caffeine to latest~!
