### ISSUE TITLE
[Docs] Update Wiki page about Statistics

### ISSUE THREAD

**Issue by lfgcampos** [ben-manes/caffeine#1779]
While looking deep into Statistics, I found that the links for Prometheus are outdated.

Prometheus simple client went through a huge refactoring and the "old" `simple_client` only exists until version `0.16.0`.
The new version, which started under version `1.x.x` has a different package, classes and all.

Migration guide is well documented on their website: https://prometheus.github.io/client_java/migration/simpleclient/

Caffeine support was introduced recently: https://github.com/prometheus/client_java/pull/983

---

## What I want with this issue?
To simply update the `Statistics` page (https://github.com/ben-manes/caffeine/wiki/Statistics) with more info (if possible) but, at least, the correct new Prometheus link: https://github.com/prometheus/client_java/tree/main/prometheus-metrics-instrumentation-caffeine

Ben, maybe also adding a `README` to the new package/module would be nice :)

**Comment by ben-manes** [comment]
Thanks! Maybe we should link to their [javadoc](https://prometheus.github.io/client_java/api/io/prometheus/metrics/instrumentation/caffeine/CacheMetricsCollector.html) example?

**Comment by lfgcampos** [comment]
Yes Ben, that is simple and efficient I'd say.
