### ISSUE TITLE
Caffeine cache, what happens when i try to read an entry which eviction is performing on

### ISSUE THREAD

**Issue by pratapjai143** [ben-manes/caffeine#1781]
Hi Team,

I have gone through the link https://github.com/ben-manes/caffeine/wiki/Refresh and can understand that, refreshing a key loads a new value for the key asynchronously. The old value (if any) is still returned while the key is being refreshed, in contrast to eviction, which forces retrievals to wait until the value is loaded anew.

But my question is, Regarding "The old value (if any) is still returned while the key is being refreshed" :-

If I get the object(old value) from the cache and now the key refresh is started and still going on. But once the key is refreshed (i.e. refresh is done), will the old value which I got earlier from cache will be refreshed as well or the old value state will be maintained as is and not touched?

As I need the old stale data which I got earlier from cache as I am doing some lookup logic with the old data and I don't want the state of that old data to be changed which I got before the key is being refreshed.

Any help would be highly appreciated.

Thanks.

**Comment by ben-manes** [comment]
Generally you want to store immutable values which allows readers to not worry about it being modified while in use. If the mapping is replaced or removed, the previous value is unchanged and may become eligible for garbage collection when the readers which already obtained it complete their usage of that reference. You can think of the cache as a ConcurrentHashMap with another thread performing these policy operations.

If the reader races to get a value just before it’s removed or replaced, typically that’s an okay interaction for a process. If the value is immutable then the readers are fine and the next time it will work with the new value. If you mutate the value, though, then those races are on you to sort out. It’s very rare that’s a worthwhile tradeoff.

The CacheLoader [reload](https://github.com/ben-manes/caffeine/blob/e32eccd57576f0155d1a5e57461b75be9fa50937/caffeine/src/main/java/com/github/benmanes/caffeine/cache/CacheLoader.java#L172) method calls the loading method which you define, and that obtains the new value. The cache won’t know how to modify your value, only how to update the mapping in the backing ConcurrentHashMap.

**Comment by pratapjai143** [comment]
Thanks @ben-manes. I have still further question on this thread.

If I have value retrieved from cache and using it. If the Caffein cache is refreshed then my question is whether the value which I have retrieved prior to the cache refreshed will be updated with the new data or will it maintained with the old data as it is. 

As we don't want the previous data which is retrieved from the cache shouldn't be altered regardless the cache refresh. However, for the new request from a different thread to the cache should retrieve the updated data.

Thanks heaps.

**Comment by ben-manes** [comment]
The cache won't modify your data behind the scenes. That would require something magical like reflection for introspection of your value and somehow update its fields based on newly discovered state. This is just a `ConcurrentMap` with `get` and `put` calls. It is basically like this,

```java
var entry = map.computeIfAbsent(key, mappingFunction);
if ((System.currentTimeMillis() > entry.refreshTime)
    && entry.reloading.compareAndSet(false, true)) {
  executor.execute(() -> {
    var newValue = mappingFunction.apply(key);
    boolean success = map.replace(key, entry, newEntry(key, newValue);
    if (success) {
      removalListener.notify(key, value, REPLACED);
    } else {
      removalListener.notify(key, newValue, REPLACED);
  });
}
return entry.value;
```

The `value` and `newValue` are separate objects being loaded. The internal cache entry holds policy metadata and is replaced in the `ConcurrentMap` in an optimistic and atomic way.
