### ISSUE TITLE
Question about refreshAfterWrite

### ISSUE THREAD

**Issue by ykhfree** [ben-manes/caffeine#1794]
Hello~

I'm checking the logic of using `refreshAfterWrite` to refresh the cache before it expires. 

If the cache contents are refreshed via DB, is there a feature that extends the expire-time of the cache we are trying to refresh if there is an error in the DB query (timeout, etc.)?

**Comment by ben-manes** [comment]
You could implement reload to return the old value instead of throwing the exception.

https://github.com/ben-manes/caffeine/blob/3457bf50994121ad924571e9987a39d672c06e1e/caffeine/src/main/java/com/github/benmanes/caffeine/cache/CacheLoader.java#L152-L174

**Comment by ykhfree** [comment]
> You could implement reload to return the old value instead of throwing the exception.
> 
> https://github.com/ben-manes/caffeine/blob/3457bf50994121ad924571e9987a39d672c06e1e/caffeine/src/main/java/com/github/benmanes/caffeine/cache/CacheLoader.java#L152-L174

Thanks you!!!
