### ISSUE TITLE
Loading error metric under CacheStats

### ISSUE THREAD

**Issue by adityamohan93** [ben-manes/caffeine#1804]
There should be a separate metric thrown when an exception is thrown while loading an entry. This can help identify when there are cache loading problems due to any issues with underlying database that Caffeine calls. This should be something like: `loadErrorCount = loadCount() - hitCount() - missCount()`. The existing metric `loadFailureCount` is a bit leading and can be interpreted as something failed when in fact getting no value is a legit scenario. People using Caffeine in high availability production systems can monitor and alarm on this metric.

**Comment by ben-manes** [comment]
The built-in statistics are simply the minimal, common set that may not be user implementable, like the hit/miss counts. There are numerous other metrics that might be reasonable for some scenarios, but as that adds memory overhead we leave it to users to instrument. If there is something unavailable to users then it’s worth considering changing our apis over. In this case, you should be able to add this metric yourself.

**Comment by adityamohan93** [comment]
Sounds right, Ben. Wanted to confirm from you for myself and any other user interested in loading errors specifically, is this formula the right one to approximately measure the errors/exception during cache load or is there any caveat?

`loadErrorCount = loadCount() - hitCount() - missCount()`

**Comment by ben-manes** [comment]
It doesn’t look correct in general terms. For example using `getIfPresent` will increment the hit/miss counts as and not the load counter. A `computeIfAbsent` would load on a miss, whereas a compute` loads always. That might be fine for your usage but might not be the general rule.
