### ISSUE TITLE
[Enhancment request] Observability for caffeine

### ISSUE THREAD

**Issue by patpatpat123** [ben-manes/caffeine#1809]
Hello team,

This is my first ticket here.
If not anything else, just wanted to say big thanks for this project.
I am using caffeine with SpringBoot, and it makes caching very easy.

Just wanted to reach out with a small enhancement request.
We are using this project in production, with some very critical business workloads.

We have observability on the web service layer, and observability for many components of our projects.
However, we find there is a lack of observability (metrics, tracing, JMX, etc.) for this project.

For instance, how much is the current cache size, and how much of non-miss cache (i.e. going to retrieve the data inside the cache directly) all those are hard to obtain, just to cite a few examples.

Would it be possible to enhance this project with observability on the cache layer?
I think it would make this project even more production-ready, and improve customer experience.

Thank you for your time.

**Comment by jacks-sam1010** [comment]
Hello, we tried to solve the issue.

This is what we did:

Create a new CacheMetrics class to track key metrics such as current size, hit count, and miss count. This will be the foundation for improved observability.

You can review changes in this commit: https://github.com/jacks-sam1010/ben-manes-caffeine-1809/commit/4a3070f3aed51969052f2c994968b0c4489b6baf.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by ben-manes** [comment]
Caffeine has [statistics](https://github.com/ben-manes/caffeine/wiki/Statistics) that you can enable to report on and SpringBoot has [support](https://docs.spring.io/spring-boot/reference/actuator/metrics.html#actuator.metrics.supported.cache) for this to expose it using their registry.

I don't think there is any feature to add here?

**Comment by patpatpat123** [comment]
Thank you @ben-manes for the answer.

I had a look at the links, and wanted to confirm few things if you are ok.

1) metrics. I am using SpringBoot, and indeed, from the link you provided, it seems there should be metrics using their registry.
However, I am not seeing any additional metrics from whether using or not using caffeine. Do you think it should be a SpringBoot issue and I should take it up with them?

2) tracing. On the first screenshot attached, you can see an expensive network call to a downstream service (9 seconds). 
Since the downstream system call is expensive and their response does not change regularly, caching their response seems to be a good technical solution.

The second screenshot shows a second call, an invocation to the cache this time. 
While the traces are technically correct (there is no network call), there is a cache call.

I was wondering if you would think the traces could be enhanced with a visual showing it went to the cache instead, and not as in this current state, which can lead to interpreting that "nothing happened".

**Comment by patpatpat123** [comment]
![Screen Shot 2024-12-20 at 00 59 39](https://github.com/user-attachments/assets/7d04372b-ef93-4204-9920-c8472ddda177)
![Screen Shot 2024-12-20 at 01 03 20](https://github.com/user-attachments/assets/bb49edb2-251a-4c2d-82a1-a0d400b8a4ce)

**Comment by ben-manes** [comment]
Yes, it seems like a SpringBoot question. I have not used it so I can’t advise there.

I think usually it’s inferred in traces, but you could add a custom span to denote it, which would incur some overhead.

Asking the spring community on what they do will hopefully answer both your questions. I believe most rely on Spring Cache and the default behavior.

**Comment by patpatpat123** [comment]
Hello @ben-manes ,

As this is my first message to you in 2025, I would like to start by wishing you a happy new year 2025 and all the best for this year.

The issue got closed in between, but I have some further findings, do you mind taking a look:

Issue 1 : regarding observability: I took a look at the links you provided, and wrote this as part of my SpringBoot framework:

```
import com.github.benmanes.caffeine.cache.Cache;
import com.github.benmanes.caffeine.cache.Caffeine;
import org.springframework.cache.CacheManager;
import org.springframework.cache.annotation.EnableCaching;
import org.springframework.cache.caffeine.CaffeineCacheManager;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
@EnableCaching
public class CacheConfig {

  @Bean
  public CacheManager cacheManager() {
    Cache<Object, Object> graphs = Caffeine.newBuilder()
            .recordStats()
            .build();
    CaffeineCacheManager caffeineCacheManager = new CaffeineCacheManager();
    caffeineCacheManager.registerCustomCache("test", graphs);
    return caffeineCacheManager;
  }

}
```

Questions
- is this correct?
- If it is, then there is an issue where the metrics always show 0 (please see screenshot as proof) May I ask why the count would not be incremented even if it went through the cache? (I can provide a simple reproducible, but please do believe the code went inside the @Cacheable)

<img width="1307" alt="Screenshot 2025-01-06 at 14 51 05" src="https://github.com/user-attachments/assets/b5840b49-3632-4371-b770-531cbf1f82da" />

Issue 2 : 
The current set of metrics shos are: 
cache gets total
cache puts total
cache evictions total
cache eviction weight total
cache size.

We are interested about:
The count of cache hit
The count of cache miss
The count of record eviction
the duration of load success time
the duration of load failure time.

Would it be possible for those metrics come baked in, instead of having the user implement some kind of ```interface CacheMeter extends StatsCounter``` class?

Those metrics are usually a base line in cache observability.

Thank you for your time.

**Comment by ben-manes** [comment]
Hi @patpatpat123, happy new year.

> Issue 1 : SpringBoot

I have not used Spring since 2009, back in Spring Framework 1.1 and its xml configuration. Unfortunately I can't help you with it other than point to its documentation or tutorials. I would guess that the cache is not being applied to your service, so a  quick search found this [video tutorial](https://www.youtube.com/watch?v=3McRajvmdlw) that has a github [sample](https://github.com/mvpjava/spring-caffeine-cache-tutorial/tree/master).

> Issue 2: Metrics

A search found this helpful [answer](https://stackoverflow.com/a/74683074/19450) and includes a code snippet.

> The metrics you are seeing are the common `CacheManger` metrics. To get Caffeine specific ones, you'll need to `monitor` those caches as they are created.

---

Since these are Spring related questions, I think its best to ask in that community. Caffeine exposes all of the necessary details, but I don't know that framework well enough to help you.
