### ISSUE TITLE
Caffeine.expireAfter exist incompatible type problem

### ISSUE THREAD

**Issue by zmyer** [ben-manes/caffeine#184]
When using caffeine in maven， there is a little problem that parameter mismatch in Expiry<Capture#1, Capture#2> to Expiry<? super K1, ? super V1>，How can I do with it?

@SuppressWarnings("unchecked")
    public <K1 extends K, V1 extends V> Caffeine<K1, V1> expireAfter(
            @Nonnull Expiry<? super K1, ? super V1> expiry) {
        requireNonNull(expiry);
        requireState(this.expiry == null, "Expiry was already set to %s", this.expiry);
        requireState(this.expireAfterAccessNanos == UNSET_INT,
                "Expiry may not be used with expiresAfterAccess");
        requireState(this.expireAfterWriteNanos == UNSET_INT,
                "Expiry may not be used with expiresAfterWrite");
        **Caffeine<K1, V1> self = (Caffeine<K1, V1>) this;**
        self.expiry = expiry;
        return self;
    }

**Comment by ben-manes** [comment]
The super types should let this call be more lenient. Can you provide an example causing problems?
