### ISSUE TITLE
API changes review for Caffeine

### ISSUE THREAD

**Issue by lvc** [ben-manes/caffeine#189]
The review of API changes for the Caffeine library since 1.0.0 version: https://abi-laboratory.pro/java/tracker/timeline/caffeine/

The report is updated three times a week. Hope it will be helpful for users and maintainers of the library.

The report is generated by the https://github.com/lvc/japi-compliance-checker tool.

Thank you.

![caffeine-2](https://user-images.githubusercontent.com/1517837/31003581-1f421958-a4f9-11e7-9980-629730c923ac.png)
![caffeine-1](https://user-images.githubusercontent.com/1517837/31003582-1f5213c6-a4f9-11e7-87b8-c8f3641f7c65.png)

**Comment by ben-manes** [comment]
Thanks. Glad to see I’ve mostly abided by semver, with exception of classes documented as exempt as beta. Perhaps a few lesser oversights early on, though.

Any recommendations for where you would want this reported? I don’t see an obvious spot in the wiki and it’s not an issue to resolve. It’s more a development tool like static analysis, which I assert in CI but don’t publish.

**Comment by lvc** [comment]
Hi,

> Any recommendations for where you would want this reported?

One can just open the issue tracker, find this issue by the `ABI` keyword and go to the report by the link provided to see reports for the latest releases or beta versions.

> It’s more a development tool like static analysis, which I assert in CI but don’t publish.

You can create the text ABI dump file for one of the past versions (say, `2.0.0`) and save it in the source tree:

    japi-compliance-checker -l caffeine \
    -dump caffeine-2.0.0.jar \
    -dump-path caffeine-2.0.0-API.dump

And then compare it with the latest API dump in the CI to generate report on compatibility (if you are expecting API changes):

    japi-compliance-checker -l caffeine \
    -dump caffeine-latest.jar \
    -dump-path caffeine-latest-API.dump
    
    japi-compliance-checker -l caffeine \
    -old caffeine-2.0.0-API.dump \
    -new caffeine-latest-API.dump \
    -report-path ./compat_report_2.0.0_to_latest.html

Thank you.

**Comment by ben-manes** [comment]
Great. Then I'll close this and refer to it if anyone asks for a diff.
