### ISSUE TITLE
Unexpected eviction with sized cache

### ISSUE THREAD

**Issue by rrodseth** [ben-manes/caffeine#205]
I must be missing something obvious, because in a simple size-limited cache items appear to be getting evicted when I don't expect them to. With a very old version of Guava I saw the same behavior, which is why I think I must be missing an obvious step.

```
    LoadingCache<UUID, Long> legacyChannelIdsCache = Caffeine.newBuilder()
    	       .maximumSize(legacyChannelIdsCacheSize)
    	       .recordStats()
    	       .build(key -> getLegacyId(key));
```
The cache is accessed in an Akka Streams app with a high degree of concurrency. One unusual thing is that we call getIfPresent() prior to calling get(). With a time-based eviction strategy CacheStats appears as expected, but with the above setup, the evictionCount starts increasing immediately, long before we're anywhere near the size.
```
CacheStats{hitCount=1710, missCount=872159, loadSuccessCount=435982, loadFailureCount=0, totalLoadTime=14094007887719, evictionCount=435482, evictionWeight=435482}
```
Thanks for any pointers.

**Comment by ben-manes** [comment]
Is it possible to reproduce in an isolated unit test that could be shared?

The first obvious check would be to inspect `legacyChannelIdsCacheSize` in case its near zero. You could print out the maximum using `cache.policy().eviction().get().getMaximum()` to see it from the cache's perspective.

**Comment by ben-manes** [comment]
`435982 - 435482 = 500`. Another possibility is that you are always passing in `UUID.randomUUID()` rather than an existing key.

**Comment by rrodseth** [comment]
My bad. I was initializing with a much smaller size than I thought.
