### ISSUE TITLE
Consider exposing isRecordingStats in Cache interface

### ISSUE THREAD

**Issue by anuraaga** [ben-manes/caffeine#207]
I am working on a cache that is initialized from a `CaffeineSpec` passed in as a system property - one reason is to allow users to set whether they want to record stats or not, which can have a reasonable performance penalty (this cache is on a very hot path).

However, I found that there doesn't seem to be a good way to know if this cache has stats recording enabled, aside from `String.indexOf("recordStats")`, so can't do something like `if (recordingStats) { exportStats(cache); }`

What do you think about exposing `isRecordingStats` in the public interface?

**Comment by ben-manes** [comment]
Please take a look at `Policy.isRecordingStats()`. :)

I try to not pollute the core interfaces to minimize the conceptual weight. `Policy` and `asMap` are nice escape hatches for lower-level behavior, with Policy being useful for all the ad hoc sort of things.

**Comment by anuraaga** [comment]
Oops, sorry for not checking there! Glad the method is there :)
