### ISSUE TITLE
Getting the maximum size for a cache

### ISSUE THREAD

**Issue by slovdahl** [ben-manes/caffeine#219]
In case a cache or cache builder is configured to use size-based eviction, I'd like to be able to get the maximum size of a cache during runtime. The maximum size is useful when monitoring cache performance. It's even more cumbersome if the cache is created from an external specification string, I have to parse the string myself in order to get the maximum size.

Am I missing something obvious here?

**Comment by ben-manes** [comment]
Please take a look at cache.policy(), which allows inspection and operations specific to a configuration. For example Policy.Eviction#getMaximum() is your use case.

**Comment by slovdahl** [comment]
Well, in hindsight that was pretty obvious. Sorry for that and thank you for the quick answer. :blush:
