### ISSUE TITLE
Disable logger in LocalAsyncLoadingCache - "Exception thrown during asynchronous load"

### ISSUE THREAD

**Issue by wkuranowski** [ben-manes/caffeine#227]
Hello.

Is there any way to disable printing a message and stack trace when LocalAsyncLoadingCache gets an Exception during load? I have my own method to handle this and to print useful information to logs.

Best Regards.

**Comment by ben-manes** [comment]
Yes, you can suppress it in your logger configuration. The exceptions from async logging as warnings in case you don't have any handling yourself, as it is a common oversight when using futures. You could raise the log level, e.g. to `ERROR` in `logback.groovy`

```groovy
logger('com.github.benmanes.caffeine.cache', ERROR)
```

**Comment by wkuranowski** [comment]
Thank you, it works! :)
