### ISSUE TITLE
Versioned objects

### ISSUE THREAD

**Issue by adamretter** [ben-manes/caffeine#231]
Hi Ben,

Sorry, but another... how might we achieve this question?

I am looking to have a Cache of versioned objects. For example something like:

```java
Cache<String, SortedSet<VersionedObject>>
```

VersionedObject.java:
```java
class VersionedObject<T> {
  final long version;
  final AtomicLong referenceCount;
  final T object;
}
```

I am thinking to use a `SortedSet` for the versioned objects so that I can maintain them ordered as latest version first, it is likely the most recent versions will be the hottest, and I need to iterate the versions to retrieve the correct one.

The actual object inside the `VersionedObject<T>` will be immutable, so there are no further concerns with concurrency there.

Ideally I would like to be able to inform the eviction from the cache. When the Cache needs to reclaim space through eviction, rather than just dropping an entire key/value pair, I would like to be able to first attempt to free up space by dropping VersionedObject(s) from the value in the cache.

So my eviction plan would look like:

1. Drop any VersionedObject(s) from which have a referenceCount of 0
2. If further eviction is required, for the LRU keys drop the VersionedObject(s) with the lowest version.
3. If further eviction is required, standard LRU eviction of Caffeine.

I looked at your https://github.com/ben-manes/multiway-pool and it has some of the properties we might need but not all. Is there any way in Caffeine to provide a function during eviction to control the policy, and/or perform eviction by reducing the value size rather than just dropping the key/value pair?

**Comment by ben-manes** [comment]
I don't recall much about my multiway-pool, except that I broke it in the last commit. You could resurrect it if you revert the last commit, as it had been working up to that point. It was pre-Java 8 and I am sure it could be improved upon.

Your use-case is too far outside of the norm for the cache to offer directly. The solution might be more complicated than you're willing to accept, but I think it could be done.

First you would need to create intermediate mappings. I think the cache would be normalized to a key/value pair, e.g. `Cache<VersionedObject, String>` where the value is a lookup to the Set. Your set is then a materialized view that is kept in sync with the cache. This could be done atomically using a `CacheLoader` and `CacheWriter`, or else could be done in a more racy/best-effort fashion.

To have the size policy ignore entries, you can use a `Weigher` and set the weight to zero when in use. This has to be computed up-front, so whenever acquiring you will need to do the increment/decrement within a cache computation. The size policy will then not count the zero weight entries in its capacity constraint and will ignore them on eviction.

So to do this with Caffeine, you'll probably want to use:
 - `CacheLoader` to fetch from storage and add to the Set
 - `CacheWriter` to remove from the set on eviction
 - `Weigher` to skip over referenced entries
 - `asMap()` to perform ad hoc computations

**Comment by ben-manes** [comment]
Happy to keep chatting, but closing otherwise.
