### ISSUE TITLE
Is LFU caching supported?

### ISSUE THREAD

**Issue by QubitPi** [ben-manes/caffeine#244]
We have a need to cache those that are most frequently used + most recently used. Does caffeine support this need?

**Comment by ben-manes** [comment]
Yes, and it has a higher than classic LFU hit rate.

**Comment by ben-manes** [comment]
https://github.com/ben-manes/caffeine/wiki/Efficiency

**Comment by QubitPi** [comment]
Thanks for the very quick reply, @ben-manes ! I'll promote caffeine to my team

**Comment by ben-manes** [comment]
Thanks!
