### ISSUE TITLE
Caffeine cache in multiple aws instances, how to sync up ?

### ISSUE THREAD

**Issue by omverma22** [ben-manes/caffeine#256]
We are running spring boot jar in 2 aws instances to scale up our server performance. When we use caffeine cache, it will make 2 copies of cached data. Which may be different based on the code execution. How we can sync the data in both the instances. Later on may be we will launch more instances.

We also have aws redis cache in place, that works when any key is missing in caffeine.

Please help. 

Thanks,
Op

**Comment by ben-manes** [comment]
As a local cache, distributed synchronization is outside of its scope. The ad hoc way is expiration and refreshing.

You could use the pub/sub feature of Redis to synchronize with. Then cache updates notifies other machines to invalidate the key (perhaps reloading it).

There are also distributed caches, though I don’t have experience using any. Infinispan uses caffeine underneath.

**Comment by omverma22** [comment]
OK Thanks for the info. I will try Infinispan.

**Comment by ben-manes** [comment]
Best of luck!
