### ISSUE TITLE
putIfAbsent returns wrong value

### ISSUE THREAD

**Issue by GenghisChen** [ben-manes/caffeine#26]
Using the cache in its ConcurrentMap form (.asMap()), when time-limited entries expire the .get() method returns null as is should, but the .putIfAbsent() method return the old-expired value.

Consider the following example:

        Cache<Integer, String> cache1 = Caffeine.newBuilder()
                .expireAfterWrite(1, TimeUnit.SECONDS)
                .build();
        ConcurrentMap<Integer, String> cache2 = cache1.asMap();

        cache2.put(1, "A");
        Thread.sleep(2000);
        System.out.println(cache2.get(1));  // Expect to see null (and see null)
        System.out.println(cache2.putIfAbsent(1, "B")); // Expect to see null (and see "A")

**Comment by ben-manes** [comment]
You're right! A million unit test executions and somehow I missed checking for this.

Thanks for the test case! I'll fix and release an update this evening.

**Comment by ben-manes** [comment]
Released v1.3.2 to Maven Central.
