### ISSUE TITLE
the maximum size problem

### ISSUE THREAD

**Issue by zjg88** [ben-manes/caffeine#262]
Hi,Ben ,i had read the issues from others about the size problem,and this is my test code

`

     SIZE=20000;

    graphs = Caffeine.newBuilder()
                .maximumSize(maxSize)
                .removalListener(removalListener)
                .build(key -> defaultValue);

     @Override
     public void onRemoval(RemovalCause cause, String s, String s2) {
                switch (cause) {
                    case SIZE: // exceed
                        removeCount++;
                        break;
                }
    }

    @Test
    public void setDoubleTimeSizeTest() {
        TestUtil.printDuration(() -> {
            for (int i = 0; i < 2 * SIZE; i++) {
                cache.put(String.valueOf(i), "test");
            }
            cache.graphs.cleanUp();   //  this is what you suggest
            try {
                TimeUnit.SECONDS.sleep(2);   //i guest if the cleanup progess is async,so let the main thread sleep
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            System.out.println(“removeCount:”+removeCount);
            System.out.println(“cache,size:”+cache.size());
            Assert.assertEquals(SIZE, removeCount);
        });
    }

`
I hope  Caffeine has invalid nums of SIZE key,but finally find 
Expected :20000
Actual   :19687
 and the test fail. so , how exactlly the cleanup strategy,thus it has a callback to tell us the cleanup progress is completed
and also:
removeCount:19520
cache,size:20315
the sum between (removeCount+cache.size) != 2*SZIE,so,where is other key?

**Comment by ben-manes** [comment]
I guess you figured it out. I usually set the executor to run on the caller thread in tests to disable any asynchronous behavior. Otherwise I use Awaitility to assert with to more robustly handle sleeping as the timing is non deterministic.
