### ISSUE TITLE
LoadingCache#getAll not maintaining order in returned map

### ISSUE THREAD

**Issue by marceloverdijk** [ben-manes/caffeine#267]
When I have an empty `LoadingCache` and I do something like:

```
var map = customerCache.getAll(List.of(1, 2, 3, 4, 5);
```

the returned map contains the keys (ordered) `1, 2, 3, 4, 5`.

Now,  when I do the following with an empty cache:

```
var map = customerCache.getAll(List.of(4, 5);
// map contains keys (ordered) `4, 5`

map = customerCache.getAll(List.of(1, 2, 3, 4, 5);
// map contains keys (ordered) `4, 5, 1, 2, 3` 
```

It seems the missing keys are added to the end as `4, 5` were already cached.
 
I would have expected the order as requested (`1, 2, 3, 4, 5`).

**Comment by ben-manes** [comment]
Yes, this is the same as #220 where I misread the Guava behavior. It wasn't a guarantee but we do try to be consistent with Guava, and I misread to emulate what I thought was a bug (but created one here instead!).

**Comment by marceloverdijk** [comment]
Oh I missed #220.
Is this something that will be fixed in Caffeine? 
Because of this I can't use the `loadAll` functionality unfortunately as I don't know the order of the keys I received... I was looking for `loadAll` to avoid key by key queries to a backend.

**Comment by ben-manes** [comment]
It will be fixed, but hasn't been yet. I've been swamped lately and I'm not sure when I'll get through the backlog of tasks here. Sorry for that.

Can you sort at the `getAll` call-site for now?

**Comment by marceloverdijk** [comment]
I unfortunately don't know the order on the all-site. But I will figure something out (maybe just not doing bulk loads at this time). Let's close this one and I will track #220.
