### ISSUE TITLE
onRemove handler

### ISSUE THREAD

**Issue by buckelieg** [ben-manes/caffeine#269]
Introduce some kind of handler that determines if the entry should be evicted/removed.
```java
Cache<Session, User> cache = Caffeine.newBuilder().expireAfterWrite().removingListener((key, value) -> /*determine if the entry shoud persist (return true or false)*/).build();

interface  RemovingListener<K, V> {
 public boolean onRemoving(K key, V value);
}
```
this should be invoked at the time when entry is preparing to be evicted/removed. 
If handler returns false - entry is not rmoved

**Comment by ben-manes** [comment]
The unfortunate problem with this is it may result in a full scan where nothing can be removed. Then the contract is broken and it is confusing. An alternative is to “pin” the entry by excluding it from the size / expiration policies (see FAQ for discussion). Would that fulfill your needs?

**Comment by buckelieg** [comment]
I've tried the faq proposal (https://github.com/ben-manes/caffeine/wiki/Faq#pinning-entries) but this states that weight is calculated at insertion time - i.e. "once and for all", for my use case I want to decide if the entry should be removed right at the moment of eviction stage after some condition is met.

Suppose you have a user session cached and cache configured.
Once expireAfterWrite trigger is on - the session object is evicted, but the session itself (i.e. session last accessed time - creation time is lower than its timeout) is still alive. so that it has to stay in cache.
May be it is meaningful to introduce such a functionality with exceptional state in the docs that its usage brakes contract and use it at own risk somehow

**Comment by Maaartinus** [comment]
> Once expireAfterWrite trigger is on - the session object is evicted, but the session itself (i.e. session last accessed time - creation time is lower than its timeout) is still alive. so that it has to stay in cache.

Shouldn't you use `expireAfterRead` instead?

> May be it is meaningful to introduce such a functionality with exceptional state in the docs that its usage brakes contract and use it at own risk somehow

The contract could be refined as the overhead being `O(1 + numberOfManuallyRefusedEvictions)` and this value could be reported in the stats. This doesn't sound as good as `O(1)`, but it's exactly the same for everyone not using the callback. Some time ago, I also [though I'd need it][a], but in the end, I did something different.

[a]: https://github.com/ben-manes/caffeine/issues/178#issuecomment-322868690

**Comment by ben-manes** [comment]
I think @Maaartinus is correct. You should be able to achieve your needs, as far as we can tell, using `expireAfterAccess` or a custom `expireAfter(Expiry)` policy.

> The contract could be refined as the overhead being O(1 + numberOfManuallyRefusedEvictions) and this value could be reported in the stats.

That's true. It would cause the cache to be aggressively re-evaluating each maintenance cycle but hopefully the custom check would be cheap. By using weight / expiration, there is the potential for the item(s) to be ordered such that they are not evaluated.

My biggest concern, though, is how easily error-prone this feels. A simple coding mistake could cause no eviction and, if not monitoring stats, a silent memory leak. So I'm hesitant until there is a really strong argument, because I'm afraid it might cause more harm than good.

**Comment by buckelieg** [comment]
@Maaartinus 
> Shouldn't you use expireAfterRead instead?

Yes. You're right. But it changes the things slightly according to the problem.

@ben-manes 
> My biggest concern, though, is how easily error-prone this feels. A simple coding mistake could cause no eviction and, if not monitoring stats, a silent memory leak. So I'm hesitant until there is a really strong argument, because I'm afraid it might cause more harm than good.

I think that there is no option to totaly avoid potential user bugs on this case. Clearly state this risks at the contract level (in javadocs, particularly) with detailed explanation could be a solution.

> By using weight / expiration, there is the potential for the item(s) to be ordered such that they are not evaluated.

Can you please show me how can I achieve this according to the example? I do not catch how can I re-weight entry dynamically.. is _compute_ method invoked everey time the entry is accessed?
Thank you.

**Comment by ben-manes** [comment]
> Can you please show me how can I achieve this according to the example? I do not catch how can I re-weight entry dynamically.. is compute method invoked everey time the entry is accessed?

You can't re-weigh outside of a write, so a `compute` on read would be necessary. That makes sense if you need to capture a resource that is pinned, e.g. a database lock. Your solution is what AddOn did with our older library, with a fork and interface called [EvictionMediator](https://github.com/addthis/basis/blob/5a821f41bbc0a27eb3b451c6179ac2be5b3b0219/basis-core/src/main/java/com/addthis/basis/concurrentlinkedhashmap/EvictionMediator.java). They used to have a blog post about why they made these changes, which I think was for a client-side lock in Hydra. 

If you need long-running hold of a resource then the compute to acquire & release are cheap in comparison. In that case you are basically doing reference counting, so it would become:

```java
class Reference<V> {
  int count;
  V value;
}
Cache<K, Reference<V>> cache = Caffeine.newBuilder()
    .weight((key, ref) -> (ref.count > 0) ? 0 : 1)
    .maximumWeight(10_000)
    .build();

V acquireShared(K key) {
  var reference = cache.asMap().compute(key, ref -> {
    if (ref == null) {
      return new Reference<V>(load(key), 1);
    }
    ref.count++;
    return ref;
  });
  return reference.value;
}

void releaseShared(K key) {
  cache.asMap().computeIfPresent(key, ref -> {
    ref.count--;
    return ref;
  });
}
```

Obviously this is uglier code, no doubt about it. However the life-cycle is very explicit and your usage code would have a clear lock-like idiom such as `acquireShared(key); try { ... } finally { releaseShared(key); }`. Internally the cache can then put all zero weight entries in a dedicated area where they are not evaluated for eviction.

I should also note that one reason I'm harsh on this is merely to follow the skeptical model set by the [Bumper-Sticker API Design](https://www.infoq.com/articles/API-Design-Joshua-Bloch) rules. It would be unfortunate to introduce an API too casually which is misused dangerously.
