### ISSUE TITLE
Support for setting variable refresh time for each entry 

### ISSUE THREAD

**Issue by eugenemiretsky** [ben-manes/caffeine#272]
Hi, 

Is there support for something similar to https://github.com/ben-manes/caffeine/issues/114, bit for refreshAfter. The use case is to prevent the data source from getting hit with many requests every refresh period, and instead spread the request more evenly. 
For example, if the refresh period is 20min, and the traffic is fairly uniform, than every 20min there will be a burst of request to the system behind the cache.

**Comment by ben-manes** [comment]
This was recently requested in #261, if I understand the requests correctly. Currently there isn't built-in support and I agree it's a pretty good idea. The implementation is probably not too difficult either, but I haven't had bandwidth to work on this library lately.

**Comment by ben-manes** [comment]
Consolidating into #504
