### ISSUE TITLE
The 'refresh' method can not update the latest value

### ISSUE THREAD

**Issue by chongyangxue** [ben-manes/caffeine#277]
I found an strange problem caused by 'refresh' method when migrating from guava cache to Caffeine. 

This test code shows the problem I encountered:

`public class TestCaffineCache {

    private AtomicInteger count = new AtomicInteger(0);

    LoadingCache<String, Integer> localCache = Caffeine.newBuilder()
            .maximumSize(100)
            .refreshAfterWrite(1, TimeUnit.DAYS)
            .build(new CacheLoader<String, Integer>() {
                @Override
                public Integer load(String key) throws Exception {
                    Integer value = count.get();
                    System.out.println("load value:" + value);
                    return value;
                }
            });

    @Test
    public void testRefresh() throws Exception {
        String key = "test";
        for (int i = 0; i < 10; i++) {
            localCache.refresh(key);
            if (i % 2 == 0) {
                System.out.println("value changed: " + count.addAndGet(1));
            }
        }

        TimeUnit.MILLISECONDS.sleep(1000);
        localCache.refresh(key);
        Assert.assertEquals(count.longValue(), localCache.get(key).longValue());
    }
}
`

**The results of this code:**
load value:0
value changed: 1
load value:1
load value:1
value changed: 2
load value:2
value changed: 3
load value:3
value changed: 4
load value:4
load value:4
load value:4
value changed: 5
load value:5
load value:5
load value:5

java.lang.AssertionError: 
Expected :5
Actual   :4

This test can always success when using guava cache.

**Comment by ben-manes** [comment]
Try setting `Caffeine.executor(Runnable::run)` in the builder. This would then match Guava's default behavior. Guava runs the refresh operation on the caller, as in synchronously, due to the default behavior in `CacheLoader#reload`. To make it asynchronous you have to supply the future and executor. Caffeine takes advantage of `ForkJoinPool#commonPool` to run operations asynchronously by default, so you are observing the race condition this imposes.

**Comment by ben-manes** [comment]
Oh, it’s because you have one final refresh at the end after the sleep and before the assertion.
