### ISSUE TITLE
我想配置这套代码，阿里云最近双11活动一折可以买云服务器，我该买哪一种呢，大家帮我看下？

### ISSUE THREAD

**Issue by zmssqqli** [ben-manes/caffeine#278]
地址在这里： https://m.aliyun.com/act/team1111/#/share?params=N.9g4CZ2TwSh.f3afagaq 
朋友分享给我的，登陆淘宝号进去发现折扣很大，优惠了很多，很心动，想入手一款自己学习用，麻烦大家帮我看下选择哪种划算，谢谢

**Comment by zmssqqli** [comment]
谢谢大家啦，拜托

**Comment by jbduncan** [comment]
@zmssqqli I don't believe any of us can read Chinese, but I've just Google-Translated your messages so far, and I'm unsure what your problem is with regards to Caffeine.

Can you clarify?

**Comment by jbduncan** [comment]
Oh no wait. AFAICT, this user has posted the same set of messages on at least one other repository, so I'm inclined to believe that this is spam.

So unless @zmssqqli can clarify their intentions, I'd suggest this issue be closed.

**Comment by ben-manes** [comment]
Thanks @jbduncan
