### ISSUE TITLE
Ticker.SystemTicker.read() may return a negative value

### ISSUE THREAD

**Issue by jentfoo** [ben-manes/caffeine#28]
It looks like Ticker is defined to only return non-negative nanoseconds, but is returning System.nanoTime() directly.  This call's timestamp is referenced from an arbitrary point, and as described in the javadocs this point may be in the future resulting in a negative value returned.

In addition this value even if starts as positive, it is possible for it to overflow.

http://docs.oracle.com/javase/8/docs/api/java/lang/System.html#nanoTime--

**Comment by ben-manes** [comment]
You're right, the `@Nonnegative` should be removed as an invalid constraint and there are no usages depending on this assumption.
