### ISSUE TITLE
caffeine:2.6.2 caused "Too Many open files"

### ISSUE THREAD

**Issue by NileshChaukade** [ben-manes/caffeine#281]
We have noticed that after adopting caffeine over Guava we faced "Too many open files" error.

We were using Caffeine like:
```java
    private LoadingCache<String, UserInfo> buildCache(){
    		return Caffeine.newBuilder()
    				.maximumSize(2000)
				    .expireAfterWrite(30, TimeUnit.MINUTES)
					.build(userToken -> findUserByToken(token));
    }
```

Where the function `findUserByToken` makes a HTTP call to a different system to fetch "User".

**Comment by NileshChaukade** [comment]
Yes Ben, the scan is limited to my package.
Also, the ulimit was increased to 65K ,but Caffeine crossed that as well.

**Comment by ben-manes** [comment]
Can you provide a small sample application with this failure? I think somewhere (maybe a dependency) it is scanning too broadly.

**Comment by ben-manes** [comment]
Please reopen if you can provide more information or sample to debug from.
