### ISSUE TITLE
On refresh failure mappingFunction is being called on every request of getIfPresent:- need a way to extend the next reload call time for that key

### ISSUE THREAD

**Issue by manoj13023** [ben-manes/caffeine#286]
What I am looking for is: in case of exception in mapping function, it should not call refresh function for next request until refresh time again counts the limit. Essentially I need to reset the timer so that It would not call again and again the reload function within the refresh time limit. Actually there is an expensive call of database in refresh function, in case of failure it would increase the number of thread and query execution, and we will have lots of logs as well.

Just wanted to know if we can tweak this. or if already a feature is available

I have added my test case below 

    public class TCacheRefreshExtensionTest {
       private AtomicInteger counter = new AtomicInteger(0);
    @Test
    public void testRefreshExceptionWhileLoading() throws InterruptedException {

      final LoadingCache<Object, Object> cache = Caffeine.newBuilder().maximumSize(10).refreshAfterWrite(Duration.ofSeconds(10)).build(k -> throwException(k));
      final String key = "key";
      cache.put(key, "values");
      Assert.assertNotNull(cache.getIfPresent(key));
      Thread.sleep(10100);
      cache.getIfPresent(key);
      Thread.sleep(100);
      cache.getIfPresent(key);
      Thread.sleep(100);
      cache.getIfPresent(key);
      Thread.sleep(100);
      cache.getIfPresent(key);
      Thread.sleep(100);
      cache.getIfPresent(key);
      Thread.sleep(100);
      cache.getIfPresent(key);
      Thread.sleep(100);
      cache.getIfPresent(key);
      Thread.sleep(100);
      Assert.assertEquals(counter.get(), 1);
        //after waiting time of 10 sec only counter should reach to 2
    }

    private Object throwException(Object k) {
      System.out.println("Refresh Called: " + counter.incrementAndGet());
      throw new RuntimeException("Some Exception");
    }
}

**Comment by manoj13023** [comment]
Current value anyway I am getting. Wanted to reset the refresh timer. When I call getIfPresent second time after exception, it should not call reload function for next 10 sec.

**Comment by ben-manes** [comment]
If the reload method doesn’t fail then the timer is reset. If you return the old value instead of propagating the exception then the cache will think it was successfully.

**Comment by manoj13023** [comment]
That looks an easy option. Thanks
