### ISSUE TITLE
Feature Request: Add expiration policy based on a function that accepts <K, V>

### ISSUE THREAD

**Issue by guidomedina** [ben-manes/caffeine#288]
I wonder if it is possible to have a `ExpirePolicy` using a `java.util.function.BiFunction<K, V, Duration>` where I'm able to compute a duration based on the `<K, V>` just loaded via `LoadingCache`, for example; let's say that I'm caching null value as:
```
private static final Object NULL_VALUE = new Object();
```

I'm not sure if this is doable and finally the API suggestion would be overload each `expireAfter...` method, this way I can set a shorter expiration time for null values vs real values so that when my cache is full it kicks null values before real values.

**Comment by guidomedina** [comment]
Ah, never mind, I see this feature is already present:
https://github.com/ben-manes/caffeine/wiki/Eviction#time-based

**Comment by guidomedina** [comment]
@ben-manes is this a proper implementation for the problem I described on this issue? or am I extending the cache duration with this implementation, what I'm trying to accomplish here is a counter part of `expireAfterAccess(time, unit)` but to expire cached null values in a 1/5th of the time of real values:
```
private static final Object NULL_VALUE=new Object();

static Expiry<String, Object> createVariableExpiry(long duration,TimeUnit unit)
{
  final long standardDuration=unit.convert(duration,NANOSECONDS);
  final long nullDuration=standardDuration / 5;

  return new Expiry<String, Object>()
  {
    @Override
    public long expireAfterCreate(@NotNull String key,@NotNull Object value,long currentTime)
    {
      return value!=NULL_VALUE ? standardDuration : nullDuration;
    }

    @Override
    public long expireAfterUpdate(@NotNull String key,@NotNull Object value,long currentTime,long currentDuration)
    {
      return value!=NULL_VALUE ? standardDuration : nullDuration;
    }

    @Override
    public long expireAfterRead(@NotNull String key,@NotNull Object value,long currentTime,long currentDuration)
    {
      return value!=NULL_VALUE ? standardDuration : nullDuration;
    }
  };
}
```

**Comment by ben-manes** [comment]
This looks right. It will extend the duration by X or 5X depending on the value.

I got stuck using the poor `long` types due to performance, as allocating `Duration` objects could cause a lot of GC churn until value types. So I know that makes it a bit unfriendly.

**Comment by guidomedina** [comment]
Oh, no worries about `long`, I would had probably done the same thing, too much GC JVM performance greatest enemy, in fact I would had hated returning a `new Duration(...)` per call ;-)
