### ISSUE TITLE
Cache bootstrap support

### ISSUE THREAD

**Issue by QubitPi** [ben-manes/caffeine#291]
We have cache that needs to be bootstrapped upon initialization, i.e. we read GB's of data from a database and load them into the cache.

Does caffeine cache support this in async way?

**Comment by ben-manes** [comment]
Nope. The cache is a fancy `ConcurrentHashMap` and that sounds more frameworky.

I use Guava's `ServiceManager` for startup/shutdown logic, e.g. start and wait until healthy before accepting http requests. Then let Guice aggregate all of the binded `Service` instances to register it, where each might do various work (such as initialize a spatial timezone index). Something like that might be more appropriate?

**Comment by QubitPi** [comment]
Ok. Thanks~
