### ISSUE TITLE
Understanding time calculation in Expiry::expireAfterCreate

### ISSUE THREAD

**Issue by jacekjab** [ben-manes/caffeine#295]
Hi!
For every entry of my cache I have an Instant which points moment in time to which this entry is valid. My current implementation for Expiry is:
```
Expiry<K, CacheEntry> expirator = new Expiry<K, CacheEntry>()
    {
      @Override
      public long expireAfterCreate(@Nonnull K key, @Nonnull CacheEntry cacheEntry, long currentTime)
      {
        Instant expiresAt = cacheEntry.getExpiresAt();
        Instant now = myClockInstance.instant();

        return Duration.between(now, expiresAt).toNanos();
      }

      @Override
      public long expireAfterUpdate(@Nonnull K key, @Nonnull CacheEntry cacheEntry, long currentTime, long currentDuration)
      {
        return Long.MAX_VALUE;
      }

      @Override
      public long expireAfterRead(@Nonnull K key, @Nonnull CacheEntry cacheEntry, long currentTime, long currentDuration
      )
      {
        return Long.MAX_VALUE;
      }
    };
```
I have some trouble understanding if time calculations for my expireAfterCreate are proper.
1. Since what moment shuld I calculate resulting nanoseconds?
   - Since cache entry was created?
   - Since running expireAfterCreate?
2. Is parameter currentTime applicable in my case?

I would be grateful for some clarifications. Thanks.

**Comment by ben-manes** [comment]
Your expireAfterCreate looks correct. The others should return `cuurentDuration`, as they are currently saying to never expire the entry if read or updated.

The `currentTime` is an unfortunate quirk due to the cache ticker using `System.nanoTime`. That isn’t good for most user calculations since it isn’t wall-clock time. So using your own clock is right, as you probably can’t use the timestamp from the ticker.

**Comment by ben-manes** [comment]
Please reopen, etc if you run into other difficulties.

**Comment by ViSilver** [comment]
Hello, how often is the `Expiry#expireAfterCreate` method called? Is it called only when the value is put into the cache graph, or is it periodically called in order to continuously validate the expiration of the cache value?

**Comment by ben-manes** [comment]
It is called on the entry insertion and the duration is stored on the entry as internal metadata. On access the cache checks if the entry expired by the current time vs the stored timestamp and acts accordingly.
