### ISSUE TITLE
Stale data when using Expiry

### ISSUE THREAD

**Issue by kojilin** [ben-manes/caffeine#298]
Recently we start to use Expiry but found some data keep in memory even it exceeds our setting.
After dump we saw stale data all has write time near 150 years later. And after checking source, I think it's from Async.MAXIMUM_EXPIRY.

Below is my sample code.
```
        final AsyncLoadingCache<String, String> cache = Caffeine
                .newBuilder()
                .expireAfter(new Expiry<String, String>() {
                    @Override
                    public long expireAfterCreate(@Nonnull String key, @Nonnull String value,
                                                  long currentTime) {
                        return Duration.ofDays(1).toNanos();
                    }

                    @Override
                    public long expireAfterUpdate(@Nonnull String key, @Nonnull String value, long currentTime,
                                                  long currentDuration) {
                        return currentDuration;
                    }

                    @Override
                    public long expireAfterRead(@Nonnull String key, @Nonnull String value, long currentTime,
                                                long currentDuration) {
                        return currentDuration;
                    }
                })
                .buildAsync((key, executor) -> CompletableFuture.supplyAsync(() -> {
                    return key + "'s value";
                }, executor));
```

I think there is a possibility that LocalAsyncLoadingCache#get -> BoundedLocalCache#computeIfAbsent may have race condition with create/update. 
If there is a read operation and stop at `isComputingAsync` until task thread finished(but keep it stop at BoundedLocalCache#replace).
<img width="733" alt="2019-02-16 1 28 01" src="https://user-images.githubusercontent.com/863983/52876664-37f4e900-319b-11e9-8876-18da192f43d4.png">
and
<img width="1136" alt="2019-02-16 1 30 32" src="https://user-images.githubusercontent.com/863983/52876698-50650380-319b-11e9-8ec4-8ed1a9939228.png">

Read thread may enter the block with long duration and make expireAfterRead return MAXIMUM_EXPIRY, so setVariableTime may write `now+MAXIMUM_EXPIRY`.

<img width="1839" alt="2019-02-16 1 29 47" src="https://user-images.githubusercontent.com/863983/52876690-47743200-319b-11e9-881f-bf01a7bdca67.png">

**Comment by ben-manes** [comment]
Thanks. I've been meaning to switch reads to use a compare-and-swap to update the timestamp, but thought it was a benign race so it was in the backlog. I hadn't thought of this case, obviously.

Do you think you can write a test case to demonstrate the race? I'm hoping to make a release this weekend when I merge the `async` branch (fix test cases). I'll try to fix this too for that release.

**Comment by kojilin** [comment]
I can't reproduce without pausing thread, a little hard to write test case.

**Comment by ben-manes** [comment]
Oh, take a look at [Awaitility](https://github.com/awaitility/awaitility) which is really handy for these cases. For example,

https://github.com/ben-manes/caffeine/blob/1c71c67dfafef0bcf95872e2df590116fc8669ed/caffeine/src/test/java/com/github/benmanes/caffeine/cache/AsyncCacheTest.java#L202-L218

but I can also give it a shot when I get free over the weekend. Its a 3 day'r in the U.S. so I should be able to find the time.

**Comment by kojilin** [comment]
I see. I tried it but looks like problem is Completable just finish but before calling BoundedLocalCache#replace, LocalAsyncLoadingCache#get -> BoundedLocalCache#computeIfAbsent need to check `isComputingAsync` and into block.(I mean I didn't find the place can let it await during completion of Completable and BoundedLocalCache#replace.

**Comment by ben-manes** [comment]
okay, thanks. I think this is an easy fix if I understand it correctly, as I've been meaning to get around to making the update on read stricter. Since you found its not easily testable, we can try testing using a thrashing approach, like the [MultiThreadedTest](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/test/java/com/github/benmanes/caffeine/cache/MultiThreadedTest.java) does.

**Comment by ben-manes** [comment]
I have a possible fix, but I need to manually verify like you did to see it fail and (maybe) succeed. Then devise if I can get a test case by thrashing it with threads until it breaks. Hopefully have this fixed and released over the weekend.
https://github.com/ben-manes/caffeine/tree/expiry

**Comment by ben-manes** [comment]
I wrote a test, got it to fail, and verified that my change passes it. This was using `Awaitility` to setup the at `Expiry` calls.

Technically I shouldn't call `expireAfterRead` if the `currentDuration` is greater than the user settable maximum (220yrs in-flight, 150yrs cap for user setting). That is both more correct if there is logic in the expiry (perhaps even expensive) and avoids this problem. It also breaks my test as I can't wait.

I'll take another crack at the test, but otherwise I'm close enough to promise a release over the weekend.

**Comment by kojilin** [comment]
Thanks, didn't notice my speculation can replay like the test case. 
I will try new version after new release.

**Comment by ben-manes** [comment]
Released 2.7

**Comment by kojilin** [comment]
Hi, just wanna give the result, seems the problem is solved. Thanks.

**Comment by ben-manes** [comment]
Great! Thank you for investigating and reporting the bug.
