### ISSUE TITLE
[Feature Request] Programmatically refresh all

### ISSUE THREAD

**Issue by bkuberek** [ben-manes/caffeine#306]
Hi,

First of all, thanks for creating this. Truly amazing. 

I'm a new user and I am not sure what I am trying to accomplish is possible.

My scenario, I have a readonly rest API. No writes. I want to add caffeine in all endpoints and have responses cached. I have lots of memory.

I don't want the cache to expire but I would like to manually tell the cache when to refresh everything.

I have an offline worker process that regenerates the database on a certain cadence and I want to notify the rest API that the database has been updated, which will trigger the cache to asynchronously refresh all keys.

I thought that perhaps I could get a list of all keys and call `refresh(key)` for each key, but I have not found a method to get a list of all keys. 

Could I call `asMap().keySet()`? Would that be expensive?

Is this possible and if not, would this be useful?

**Comment by ben-manes** [comment]
I had started to think through this in #7, but never finished. For now you are right we only support individual keys. If we added support for a `reloadAll` in `CacheLoader` then you could delegate to the cache a bulk operation. At the moment you could instead write a bulk load method and use `putAll` to insert them into the cache.

**Comment by bkuberek** [comment]
Sounds good. Thank you

**Comment by izimbra** [comment]
> I had started to think through this in #7, but never finished. For now you are right we only support individual keys. If we added support for a `reloadAll` in `CacheLoader` then you could delegate to the cache a bulk operation. At the moment you could instead write a bulk load method and use `putAll` to insert them into the cache.

I have a similar use case but the cache is used by multiple threads. I want the first `get` call to invoke `putAll` if the cache is empty, and to similarly reload all values after the expiration time. I wonder if `putAll` is thread-safe or I should implement additional locking so that at most one thread at a time can be writing to the cache.
