### ISSUE TITLE
Batching of AsyncCacheLoader calls

### ISSUE THREAD

**Issue by sheepdreamofandroids** [ben-manes/caffeine#309]
I'm using an async cache with an AsyncCacheLoader that delays loading until a certain period has elapsed or a maximum number of keys is collected. After that delay a bulk call is done because that is way more efficient than many single calls.
Would you be interested in a contribution of a generic version of this AsyncCacheLoader implementation? Or maybe a different approach to this problem?

**Comment by ben-manes** [comment]
Thanks, that makes sense. I would accept it in the `examples` directory and then we might consider if it should be promoted as a supported feature. That way others can benefit from your work without library design (e.g. scope) being a blocking consideration.

I do wonder if ReactiveX / Reactor would make this easy to implement, like it did in `write-behind-rxjava` for collecting writes to batch update? If so then it might not be much code and simpler as an example integration between libraries.

**Comment by sheepdreamofandroids** [comment]
Actually I did an implementation using rxjava and the buffer() operator but I'm not completely happy about it.
Firstly the buffer() operator produces useless empty batches. They can easily be ignored but it just doesn't feel right.
Secondly it's quite easy to miss completing some futures which makes the whole thing less robust than I like. This is the main reason I like to abstract it out.
Thirdly, after a batch of keys has been processed, the times shouldn't start right away, but only when the first key is received to avoid non-optimal small batches.

**Comment by ben-manes** [comment]
That makes sense and I agree those are the characteristics you'd expect. I haven't gotten used to the reactive-x libraries yet due to poor fits in my day-to-day work. Do you want to submit your implementation as an example?

**Comment by sheepdreamofandroids** [comment]
Sure, just have to get around to it.
I wasted some time trying to get the project to build; the javadoc task just wouldn't work. I'll just comment it out for now.

**Comment by ben-manes** [comment]
The project is built for JDK8 presently, though I suppose we could fix the Javadoc to conform to the later JDKs.

The `examples` are self-contained builds so you shouldn't be impacted if you go that route.

**Comment by ben-manes** [comment]
I'll close this and we can discuss again if you send a PR. 😄
