### ISSUE TITLE
cannot override ticker when using native expiry options

### ISSUE THREAD

**Issue by ItamarBenjamin** [ben-manes/caffeine#313]
Using the jcache extension, trying to override Ticker for unit tests.
I noticed in CacheFactory.Builder class the native caffeine builder is not getting the ticker instance, only CacheProxy, LoadingCacheProxy and JCacheLoaderAdapter.

this causes expiration logic to use the system ticker.

**Comment by ben-manes** [comment]
Good catch, sorry about that!

I would recommend against JCache if all else equal, mostly because it is more brittle and harder to work with than the native APIs.

**Comment by ItamarBenjamin** [comment]
Thanks for the quick response. I have to use jcache because a library im using only supports jcache.

**Comment by ben-manes** [comment]
Released in v2.8
