### ISSUE TITLE
Provide policy method in AsyncCache

### ISSUE THREAD

**Issue by ashishkujoy** [ben-manes/caffeine#315]
In my project, I am using AsyncCache(build using Caffeine.build) for caching. My requirement
is to add an expiry time while caching, currently, AsyncCache does not provide any method
to do that. However, providing a handle to Policy can help in achieving this.

As of now all implementation of AsyncCache except AsyncLoadingCache provide a handle to Policy, also implementation's of AsyncLoadingCache provides Policy.

Then it makes sense to provide Policy directly in AsyncCache.

**Comment by ben-manes** [comment]
For async caches, you can use the synchronous view to access the policy.
