### ISSUE TITLE
Best way to propagate load errors?

### ISSUE THREAD

**Issue by adamretter** [ben-manes/caffeine#318]
Hi Ben,

When using `Cache.get#(K, Function<K,V>)` I am wondering about the best (safest then cheapest) way to propagate an error from the `mappingFunction` to the caller.

For example if my cache entries are loaded on demand by an expensive IO operation, my load entry function might look like:

```java
public static Thing loadEntry(final String key) throws IOException, SAXException {
    return new Thing(key); // NOTE: would actually read the value from disk!
}
```

I can immediately see 3 possibilities, but I am wondering if there are better options that you might already know of?

<h2>1) Use a RuntimeException</h2>

```java
Thing thing = null;
try {
    thing = cache.get("key1", k -> {
        try {
            return load(k);
        } catch (final IOException | SAXException e) {
            throw ExceptionWrapper.wrap(e);
        }
    });
} catch (final ExceptionWrapper e) {
    System.out.println("Recovering from: " + e);
}


// ...utility class
public static class ExceptionWrapper extends RuntimeException {
    private ExceptionWrapper(final Exception e) {
        super(e);
    }

    public static ExceptionWrapper wrap(final Exception e) throws ExceptionWrapper {
        return new ExceptionWrapper(e);
    }
}
```

<h2>2) Local array to cross lamba-boundary</h2>

This is the trick you taught me previously ;-)

```java
final Exception[] exception = new Exception[1];
final Thing thing = cache.get("key1", k -> {
    try {
        return load(k);
    } catch (final IOException | SAXException e) {
        exception[0] = e;
        return null;
    }
});
if (thing == null && exception[0] != null) {
    System.out.println("Recovering from: " + exception[0]);
}
```

<h2>3) Holder to cross lamba-boundary</h2>

This is similar to (2), but on some VMs I have read that this might use less memory for the "holder" than an "Object[1]" array.

```java
final Holder<Exception> exception = new Holder<>();
final Thing thing = cache.get("key1", k -> {
    try {
        return load(k);
    } catch (final IOException | SAXException e) {
        exception.value = e;
        return null;
    }
});
if (thing == null && exception.value != null) {
    System.out.println("Recovering from: " + exception.value);
}
```

<h3> Thoughts?</h3>

Option (2) seems the simplest to me, with possibly (3) using less memory (if even noticeable) at the cost of an external dependency.

Whichever is your *recommended* approach might be worth adding to the Caffeine docs/examples?

**Comment by ben-manes** [comment]
I think 2/3 are the fastest, so they make sense when optimizing lower level code few would look at. I don’t have a preference between them.

1 is more common as checked exception wrapping to cross boundaries is a classic annoyance. The JVM has special optimizations to make this fast, like lazily computing the stack trace and memoizing the instance.

I would lean towards an exception in my work code for others while using the others where I think it’s warranted. This is just to be less surprising and boring application code.

There’s also cases where you cache the failures (negative caching) which is rarer but can improve performance and robustness at times.

All are good to know but I can’t say there’s a best practice to promote.

**Comment by adamretter** [comment]
@ben-manes Okay thanks for talking a look ben. Glad to know there isn't some other recommended way that I missed.
