### ISSUE TITLE
Use @CompatibleWith for increased type safety

### ISSUE THREAD

**Issue by s-nel** [ben-manes/caffeine#320]
I was surprised today when `invalidate` didn't take a `K` but an `Object` instead, and it caused me a bit of debugging before I realized I was passing the wrong key. There is nothing in the javadoc to justify using `Object`. Is there a reason `key` is not of type `K`?

https://github.com/ben-manes/caffeine/blob/4cf6d6e6a18ea2e8088f166261e5949343b0f2eb/caffeine/src/main/java/com/github/benmanes/caffeine/cache/Cache.java#L122-L129

Same with `invalidateAll(keys)`

https://github.com/ben-manes/caffeine/blob/4cf6d6e6a18ea2e8088f166261e5949343b0f2eb/caffeine/src/main/java/com/github/benmanes/caffeine/cache/Cache.java#L131-L138

**Comment by Stephan202** [comment]
Hi @s-nel, you might find these issues interesting:
- google/guava#1283
- google/guava#2227

In short, it is to be consistent with the JDK, where generics are only used to restrict the type that can be passed in if accepting arbitrary `Object`s could cause the  cache (collection, ...) to end up in an inconsistent state.

**Comment by Stephan202** [comment]
But it's still unfortunate that the compiler was thus unable to flag the bug you describe. For collections Error Prone has the [`CollectionIncompatibleType`](http://errorprone.info/bugpattern/CollectionIncompatibleType) check to guard against that. I [see](https://github.com/google/error-prone/blob/master/core/src/main/java/com/google/errorprone/bugpatterns/collectionincompatibletype/CollectionIncompatibleType.java) that right now this check doesn't flag Guava/Caffeine cache methods. Perhaps it should :)

**Comment by s-nel** [comment]
@Stephan202 that's unfortunate! Thanks for explaining it to me

**Comment by ben-manes** [comment]
Thanks for digging those up @Stephan202! I was trying to find them :)

This was one of the decisions in Guava, when the API was reviewed by Josh Bloch and Kevin Bourrillion. 

Guava recently added `@CompatibleWith(<type>)` everywhere, so perhaps that would let the tooling discover it? We could add those.

**Comment by ben-manes** [comment]
```java
// Guava
V getIfPresent(@CompatibleWith("K") Object key);

// Caffeine
V getIfPresent(@NonNull Object key);
```

We can add [@CompatibleWith](https://github.com/google/error-prone/blob/master/annotations/src/main/java/com/google/errorprone/annotations/CompatibleWith.java) to the API methods to let the warning be shown, which I think would be the desired compromise. I guess that I was busy and didn't catch when the annotations were added across Guava.

**Comment by ben-manes** [comment]
It looks like `@CompatibleWith` can't be used with a type parameter (e.g. `invalidateAll(Iterable< @CompatibleWith("K") ?> keys)`). You'd have to use ErrorProne to see the warnings.
