### ISSUE TITLE
I want a thread refresh the cache regularly 

### ISSUE THREAD

**Issue by initpassion** [ben-manes/caffeine#326]
I have a question I would like to ask:
I want to refresh the cache regularly (every two minutes). No matter if the cache is requested after two minutes, I hope that this refresh task will be executed every two minutes. After two minutes, I need the latest value.

**Comment by ben-manes** [comment]
In that case, you should schedule a task to do that. Caffeine does not spawn its own threads, so it does not have a scheduler to leverage.
