### ISSUE TITLE
[Feature Request] Strict getAll

### ISSUE THREAD

**Issue by spand** [ben-manes/caffeine#329]
Great library !

We use the `AsyncLoadingCache` (via. `.synchronous()` extensively and have particularly enjoyed that it is possible for `getAll` to return partial results unlike in guava. Today however I actually got the need to know if the result actually contains all the keys. Has this been considered for the API ? Maybe as a flag or another method ie. `getAllStrict`.

It seems a bit pointless to iterate and check all the keys when (looking into `LocalAsyncLoadingCache`) the cache has just done that.

**Comment by ben-manes** [comment]
If I understand correctly, it would be equivalent to

```java
var result = cache.getAll(keys);
checkState(result.keySet().containsAll(keys), "Missing keys %s", 
    Sets.difference(result.keySet(), keys));
```

If so, then I think an assertion like this isn't too bad to have in your code.

**Comment by spand** [comment]
I think you do.

Well, except that `keys` in my case is an `Iterable`. If it was a `Set` I assume a `result.size == keys.size` would be enough.

Thanks the response !

**Comment by ben-manes** [comment]
You could use `Iterable.size(keys)` and it will downcast if possible for a cheaper check. Lots of goodies in there :)

I appreciate the suggestion, but I think Guava has enough utilities to make this into a 1-liner. I'd rather keep the API trimmed down to powerful methods and leave small conveniences to composing with utilities like Guava's.

**Comment by spand** [comment]
No worries. I have read many of your responses here so I knew it was a bit of a stretch but given that most our work is funnelled through this method I would not mind having it sped up a bit.
