### ISSUE TITLE
Building process is failing (Error Prone static analysis plugin)

### ISSUE THREAD

**Issue by DiegoEliasCosta** [ben-manes/caffeine#330]
I am trying to build caffeine to reproduce an error on SpotJMHBugs and ended-up running into this error:

```
/home/diego/spotjmhbugs/caffeine/caffeine/src/main/java/com/github/benmanes/caffeine/cache/MpscGrowableArrayQueue.java:244: error: An unhandled exception was thrown by the Error Prone static analysis plugin.
            break;
            ^
```

This is happening with Java 8 and Java 12 during the compilation task of gradle.
I am attaching the full log to the issue. Am I missing a step on the building process?

[caffeine-build-error.txt](https://github.com/ben-manes/caffeine/files/3365769/caffeine-build-error.txt)

**Comment by ben-manes** [comment]
This seems to be a failure with Java 12. It looks like you when you switched to 8, your Gradle daemon wasn't moved across. Make sure to run `./gradlew --status stop` when switching JDKs, so that a new one will be started with the correct Java version.

**Comment by ben-manes** [comment]
Closing since JDK12+ seems to be broken with ErrorProne (https://github.com/google/error-prone/issues/1106). I'll watch it and if not fixed soonish, I'll disable ErrorProne when running on those JDKs. For now please run using Java 8-11 which works fine.

**Comment by ohadeytan** [comment]
Still broken on JDK13.

**Comment by ben-manes** [comment]
I have a meager start on v3 where it’s disabled. That will be 13+ baseline.

https://github.com/ben-manes/caffeine/commit/a477bba9e8b709bda64fe62881a6228173217097#diff-312b42d36f78c8a1a24ef6f72e0c7eae
