### ISSUE TITLE
Return the value from VarExpiration.putIfAbsent as in ConcurrentMap.putIfAbsent

### ISSUE THREAD

**Issue by gurkankaymak** [ben-manes/caffeine#341]
Hi,

I've a need for atomically read-through operation with a specific duration (read from cache if exist, if not put to cache and return). 
`VarExpiration.putIfAbsent` method provides this functionality but it checks the value returned from the `put` method and returns a boolean different from other putIfAbsent methods as in `ConcurrentMap.putIfAbsent`

is it ok to change the return type to the V type parameter, the clients can do the null check (I can provide a pull request if you agree with this change)

there is also `Cache.get`method which provides read-through functionality atomically but I couldn't figure out how to set duration with this method atomically

Thanks,

**Comment by ben-manes** [comment]
It seems that this was added in #163 and it was awkward because of async caches (see [comment](https://github.com/ben-manes/caffeine/issues/163#issuecomment-340664876)). In an async cache the mapping is to a future, which might be in-flight or resolve to `null`. The boolean meant that I didn't have to block until the results and could just return if the mapping was established or not.

**Comment by ben-manes** [comment]
It looks like the synchronous view of the async cache blocks, but doesn't handle the case where the in-flight future fails or resolves to null. That would incorrectly imply that the insert was successful. That method likely needs to run its work in a retry loop.

https://github.com/ben-manes/caffeine/blob/19f0911a78fa8096a4f610a24b756741dd4ed984/caffeine/src/main/java/com/github/benmanes/caffeine/cache/LocalAsyncCache.java#L631-L636

The options are then if we want to make `VarExpiration.putIfAbsent` similar. It looks like its unused in the OSS integrations, like PlayFramework's. Thus the compatibility break would be small and maybe acceptable.

We could also add the compute methods, like `computeIfAbsent(key, mappingFunction, expiry)` if you need more ad hoc control. However, I'd also wonder why you can't use the normal `Expiry` and cache loading functionality instead. For example to wrap `V` to hold the custom duration that the `expireAfter(Expiry)` can evaluate.

**Comment by gurkankaymak** [comment]
it seems wrapping `V` and using `expireAfter(Expiry)` as you suggested covers my case,
thanks for your help, your quick and detailed explanations were very helpful

although, I think `computeIfAbsent(key, mappingFunction, expiry)` method would be a useful addition, I would gladly help with this method
