### ISSUE TITLE
Tagging entries for clearing/refreshing sets of entries

### ISSUE THREAD

**Issue by dave08** [ben-manes/caffeine#347]
We have a key that is a (Kotlin) data class composed of a few properties, and we would like to clear/refresh based on one of those properties, would it make sense that the library could provide a way to "tag" entries that need to be cleared at the same time? Expiry doesn't really do the trick since the upstream data is being updated by one service and the others (that also have a cache) need to be notified and clear/refresh those keys without clearing/refreshing the whole cache.

Is there maybe a workaround you might suggest for this otherwise? Thanks!

**Comment by ben-manes** [comment]
We treat every entry independently (a fancy `Map`) so the semantics of multi-key operations is more awkward. For example one might expect with this feature that the removal of a group of keys is atomic, which is not supported by `Map#compute` methods. Some might have the explicit keys while others might have a filter predicate, which shifts the cost from O(1) to O(k) to O(n) on eviction. From a library perspective, I'm afraid this appears problematic to me.

Can you use a `RemovalListener` to asynchronously schedule the group operation based on the key/value/cause?

**Comment by ben-manes** [comment]
Also note that the `asMap()` method lets you iterate over the entries, etc providing similar semantics as `ConcurrentHashMap`.

**Comment by dave08** [comment]
Really I was thinking that on the implementation side it would be managing a seperate map with the (tag => list of keys or hashes) for each tag, then behind the scenes it would be invalidateAll(..) call for that list. Does that still cause the problems you mentioned (it wouldn't be going through all the keys to see that property anymore...)?

I don't quite understand how a `RemovalListener` would solve this problem though... since the invalidation request is coming in through a RabbitMQ subscriber (or the like) so that all the instances of the service can freshen their caches with the new data for that property.

**Comment by ben-manes** [comment]
Thanks, I see now. This is something you should be able to build on top using the atomic operations available already. I was concerned that there might be a limitation blocking you or that the requested feature was too complex to easily implement. In your case this feature should be straightforward and wrapped up into a higher level api than we provide.

I don’t think it’s a fit for us to offer directly, but I can help advise if you run into any problems.
