### ISSUE TITLE
Simulator jar corrupted

### ISSUE THREAD

**Issue by sigram** [ben-manes/caffeine#350]
Hi,
I'm trying to add a benchmark for Apache Solr cache implementations, so I added quite a bunch of jars as dependencies - solr-core, zookeeper, etc. I should probably trim this down but still a few large-ish jars will need to be added.

However, these additional dependencies produce a corrupted simulator-xxxx.jar - it's still being created, its size is ~200 MB but it's truncated - attempt to open it fail with `java.util.zip.ZipException: zip END header not found`. I verified that it's indeed corrupted using regular `zip- T` and `jar -t`.

I tried adding `zip64 = true` to various build files but I'm a total Gradle newbie, so I may not have used the right incantations... in any case, this didn't help.

The build itself doesn't stop because of that error when I run eg. `./gradlew jmh -PincludePattern=GetPutBenchmark`, it's just the execution of the benchmark that fails with rather confusing messages, like a missing `/META-INF/BenchmarkList` or `ClassNotFoundException` for some core Caffeine classes.

Full patch attached - I'm sure some of my changes to the build files are unnecessary and show only my Gradle ignorance. :)

**Comment by sigram** [comment]
[350.patch.gz](https://github.com/ben-manes/caffeine/files/3642842/350.patch.gz)

**Comment by ben-manes** [comment]
I'm sorry that you ran into trouble. Your patch is on an older checkout and doesn't include the solr usages. I can try to work those in if you can provide me references to the caches you would like to evaluate.

This seems to be a bug with the jmh plugin. For whatever reason, this works if you do:
```gradle
./gradlew clean caffeine:jmh -PincludePattern=GetPutBenchmark --no-daemon
```

**Comment by ben-manes** [comment]
@sigram, I have it working in my simulator so far and have not written the JMH bindings yet. I set the low watermark to be just under the maximum size, which is triggering an eviction on each cache miss, and I disabled its async cleanup thread. This is causing it to be extremely slow in a large trace, like S3.

Do you think this is a valid configuration when evaluating the hit rates against different traces?

```java
/**
 * Solr concurrent LRU cache implementation.
 *
 * @author ben.manes@gmail.com (Ben Manes)
 */
public final class SolrLruPolicy implements Policy {
  private final ConcurrentLRUCache<Object, Object> cache;
  private final PolicyStats policyStats;
  private final int maximumSize;

  public SolrLruPolicy(Config config) {
    policyStats = new PolicyStats("product.SolrLru");
    BasicSettings settings = new BasicSettings(config);
    maximumSize = settings.maximumSize();
    cache = new ConcurrentLRUCache<>(maximumSize, maximumSize - 1);
  }

  /** Returns all variations of this policy based on the configuration parameters. */
  public static Set<Policy> policies(Config config) {
    return ImmutableSet.of(new SolrLruPolicy(config));
  }

  @Override
  public void record(long key) {
    Object value = cache.get(key);
    if (value == null) {
      cache.put(key, key);
    }
  }

  @Override
  public PolicyStats stats() {
    return policyStats;
  }

  @Override
  public void finished() {
    policyStats.addHits(cache.getStats().getCumulativeHits());
    policyStats.addMisses(cache.getStats().getCumulativeMisses());
    policyStats.addEvictions(cache.getStats().getCumulativeEvictions());
    checkState(cache.size() <= maximumSize, "The cache exceeded the maximum size");
  }
}
```

**Comment by ben-manes** [comment]
For JMH, I also ran into your problem. I think the simplest might be to copy the classes over because they have interface dependencies but are mostly pure Java code. Rather than fight with zip64 issues, we could get some results by a copy without those bits. What do you think?

**Comment by ben-manes** [comment]
Attached is my patch to run Solr caches in JMH and the simulator.

I won't be merging this in because I had to copy the Solr code to workaround the JMH issue. When running directly in the trace simulator, the LRU cache is taking hours to complete on S3. It runs fast on a small trace (max=512) but slow on a large one (max=400k). It is simply unusable in this configuration.

Please review in case I made any mistakes. My analysis is that the JMH throughput is much worse than Caffeine, the hit rate is lower, and the runtime cost is higher. It may be good under low load, but can be a bottleneck in on a heavily loaded server.

[solr.patch.gz](https://github.com/ben-manes/caffeine/files/3644660/solr.patch.gz)

**Comment by ben-manes** [comment]
I'm sorry that was a partial patch, I always screw up that command. Just in case it helps, here was what I had.

[solr.patch.gz](https://github.com/ben-manes/caffeine/files/3649122/solr.patch.gz)
