### ISSUE TITLE
ERROR: Unable to find the resource: /META-INF/BenchmarkList

### ISSUE THREAD

**Issue by danielTechn** [ben-manes/caffeine#354]
I get this error when I run a benchmark from caffeine.
did you encounter this?
I can see the file in :caffeine/build/jmh-generated-resources/META-INF/BenchmarkList

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':caffeine:jmh'.
> A failure occurred while executing me.champeau.gradle.IsolatedRunner
   > ERROR: Unable to find the resource: /META-INF/BenchmarkList

**Comment by ben-manes** [comment]
Unfortunately it’s a bug with the jmh plugin. The following seems to work around whatever is going wrong,

```
./gradlew clean caffeine:jmh -PincludePattern=GetPutBenchmark --no-daemon

**Comment by danielTechn** [comment]
thank you, it worked!
