### ISSUE TITLE
What is the best GC algorithm

### ISSUE THREAD

**Issue by ajames-branch** [ben-manes/caffeine#355]
What is the best GC algorithm when Caffeine cache is extensively used in Spark streaming application?

Java version - 1.8
Spark - 2.2
Caffeine - 2.3.5

**Comment by ben-manes** [comment]
Typically Java 8 would use G1 or Parallel, depending on your need.
 - Parallel, aka "throughput collector" is best when you care about end-to-end execution time. This has the high pause times, making it poor for latency / user-facing work.
 - G1 is latency oriented by trying to have short pause times while maintaining high throughput. This has a good balance and many tuning parameters based on your goals.

Prefer G1 by default but consider Parallel if not real-time ETL. You might find better answers on StackOverflow, as its out of scope for us to advise.
