### ISSUE TITLE
LocalManualCache visibility

### ISSUE THREAD

**Issue by JohnZ1385** [ben-manes/caffeine#358]
Hi,
I'm converting an application which used Guava Cache via Spring to use Caffeine's cache via Spring. The backbone of the implementation is a subclass of Guava's ForwardingCache. The implementation contains a cache of caches which is keyed by a "client id:. When this cache receives a request it delegates the request to the cache selected by using the client id associated with the current thread. It would seem that Caffeine's LocalManualCache closely resembles Guava's ForwardingCache effectively acting as a delegator. Is there a reason for this interface not being public?

**Comment by ben-manes** [comment]
`LocalManualCache` and its cousins are to assist in the two backends, a lightweight unbounded cache and a bounded one. This way if not configured with a bounded there isn't a performance penalty over a raw `ConcurrentHashMap`.

Guava's `ForwardingCache` doesn't provide much meat and could easily be built by hand if you need it. It isn't used in Guava's cache implementation and was primarily added to be consistent with the rest of the collections which include delegators. I'd recommend writing your own based on our interfaces, which should be fairly trivial.

You could use our Guava adapters to migrate the internals of your custom cache to Caffeine, without impacting the surrounding logic. That would leave you bound to Guava's interfaces and being more surgical in your migration effort.

**Comment by JohnZ1385** [comment]
Thanks Ben I will probably just build one by scratch like you suggested in that event.
