### ISSUE TITLE
Thread BLOCKED while CaffeineCache.get(Object, Callable)

### ISSUE THREAD

**Issue by xujijun** [ben-manes/caffeine#359]
Every several days, all the threads in JVM got blocked while CaffeineCache.get(Object, Callable). Jstack info as follows (other threads blocked with the same info):

> Thread 183442: (state = BLOCKED)
> - java.util.concurrent.ConcurrentHashMap.compute(java.lang.Object, java.util.function.BiFunction) @bci=228, line=1868 (Compiled frame)
> - com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(java.lang.Object, java.lang.Object, java.util.function.Function, long[]) @bci=62, line=2037 (Compiled fram
e)
> - com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(java.lang.Object, java.util.function.Function, boolean, boolean) @bci=162, line=2020 (Compiled frame)
> - com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(java.lang.Object, java.util.function.Function) @bci=5, line=112 (Compiled frame)
> - com.github.benmanes.caffeine.cache.LocalManualCache.get(java.lang.Object, java.util.function.Function) @bci=8, line=54 (Compiled frame)
> - org.springframework.cache.caffeine.CaffeineCache.get(java.lang.Object, java.util.concurrent.Callable) @bci=15, line=99 (Compiled frame)
> - org.springframework.cache.interceptor.CacheAspectSupport.execute(org.springframework.cache.interceptor.CacheOperationInvoker, java.lang.reflect.Method, org.springframework.cache
.interceptor.CacheAspectSupport$CacheOperationContexts) @bci=84, line=352 (Compiled frame)
> - org.springframework.cache.interceptor.CacheAspectSupport.execute(org.springframework.cache.interceptor.CacheOperationInvoker, java.lang.Object, java.lang.reflect.Method, java.la
ng.Object[]) @bci=64, line=316 (Compiled frame)
> - org.springframework.cache.interceptor.CacheInterceptor.invoke(org.aopalliance.intercept.MethodInvocation) @bci=29, line=61 (Compiled frame)
> - org.springframework.aop.framework.ReflectiveMethodInvocation.proceed() @bci=101, line=185 (Compiled frame)
> - org.springframework.aop.framework.JdkDynamicAopProxy.invoke(java.lang.Object, java.lang.reflect.Method, java.lang.Object[]) @bci=386, line=212 (Compiled frame)

I am using spring-cache with the config as follows:

`    ArrayList<CaffeineCache> caches = new ArrayList<>();`
`			caches.add(new CaffeineCache("getBlockedProviderIds",`
`					Caffeine.newBuilder().recordStats()`
`							.expireAfterWrite(60, TimeUnit.SECONDS)`
`							.maximumSize(1000)`
`							.build())`
`			);`
`  SimpleCacheManager cacheManager = new SimpleCacheManager();`
`  cacheManager.setCaches(caches);`

`    @Cacheable(value = "getBlockedProviderIds", sync = true)`
`    Set<Integer> getBlockedProviderIds(int userId);`

Is there any way/config to let it expire and release the thread after  5 seconds rather than blocking it forever? Thanks.

**Comment by ben-manes** [comment]
This is synchronization inside of CHM, which we don’t control. The problem is usually caused by computations that callback into the map and perform a write, e.g. recursive computes. That isn’t supported and recent Java versions throw an exception if detected.

AsyncCache can often help by shifting the blocking call to the future, which can be timed out.

Otherwise this could be a bug if your computation never completes and blocks other map operations as a side effect.

**Comment by xujijun** [comment]
> This is synchronization inside of CHM, which we don’t control. The problem is usually caused by computations that callback into the map and perform a write, e.g. recursive computes. That isn’t supported and recent Java versions throw an exception if detected.
> 
> AsyncCache can often help by shifting the blocking call to the future, which can be timed out.
> 
> Otherwise this could be a bug if your computation never completes and blocks other map operations as a side effect.

Could you help how to config to utilize the AsyncCache? Thanks.

**Comment by ben-manes** [comment]
I don’t use spring so that aspect I cannot help with. AsyncCache does offer a synchronous view so you could configure with that.

**Comment by xujijun** [comment]
By the way, I saw several other blocks like this. Not sure if it is another hint:

>Thread 1359: (state = BLOCKED)
> - sun.misc.Unsafe.park(boolean, long) @bci=0 (Compiled frame; information may be imprecise)
> - java.util.concurrent.locks.LockSupport.parkNanos(java.lang.Object, long) @bci=20, line=215 (Compiled frame)
> - java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(long) @bci=78, line=2078 (Compiled frame)
> - java.util.concurrent.LinkedBlockingQueue.poll(long, java.util.concurrent.TimeUnit) @bci=62, line=467 (Compiled frame)
> - java.util.concurrent.ThreadPoolExecutor.getTask() @bci=134, line=1073 (Compiled frame)
> - java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) @bci=26, line=1134 (Compiled frame)
> - java.util.concurrent.ThreadPoolExecutor$Worker.run() @bci=5, line=624 (Compiled frame)
> - java.lang.Thread.run() @bci=11, line=748 (Compiled frame)

**Comment by ben-manes** [comment]
If you remove `sync = true` it will no longer be atomic and won’t lock, so that’s an option

**Comment by xujijun** [comment]
> If you remove `sync = true` it will no longer be atomic and won’t lock, so that’s an option

Many Thanks. I'v tested this option, and found that when the cache got expired all the queries went to database until one query succeeded.

**Comment by ben-manes** [comment]
Without the full stack traces, I can’t help beyond hint that this probably isn’t this library’s fault. The underlying computation is causing problems like never completing, which you’ll have to handle. If you use the native api then you’ll have more options.
