### ISSUE TITLE
invalidate() loops infinitely

### ISSUE THREAD

**Issue by panghy** [ben-manes/caffeine#36]
Found a weird issue in 2.0.2 (didn't check any older version but this could be JDK related)

We have a test case that shows a LoadingCache looping forever inside computeIfPresent() when invalidate() is called (line 74 of LocalManualCache) -> remove() (line 1579 of BoundedLocalCache) and then it loops in the computeIfPresent method of java.util.ConcurrentHashMap.

This is JDK 1.8.0u66

**Comment by ben-manes** [comment]
That is weird. Can you provide a test case and configuration so that we can try to debug it?

Note that if you have a recursive computation that can spin indefinitely (see [JDK-8062841](https://bugs.openjdk.java.net/browse/JDK-8062841)).

**Comment by ben-manes** [comment]
let me know how things turn out. I'm guessing your computation is trying to modify the cache and that's a known issue with CHM. I worked with Doug on the fixes to fail fast, but its been a year and they're still not in a JDK8 release.

If things look messy I can probably meet up over the weekend. I'm right by downtown Mountain View, so pretty close.

**Comment by panghy** [comment]
Cool, thanks for the help, I am trying to see what we are doing that could be triggering this. Simple tests pass for sure, so I am trying to make a self-contained reproduction.

**Comment by ben-manes** [comment]
Not sure if it will help, but you can use the existing testing infrastructure. The obvious recursive scenarios are disabled, e.g. [AsMapTest#computeIfAbsent_recursive](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/test/java/com/github/benmanes/caffeine/cache/AsMapTest.java#L908). Easiest is to run selectively in the IDE, which supply hundreds of permutations.

**Comment by panghy** [comment]
Looks like we are invalidating another cache when loading an entry of another cache, would that be considered recursive in that case?

**Comment by ben-manes** [comment]
I wouldn't expect it to, as there is no weird ThreadLocals floating around in Caffeine or CHM. That's reasonable to expect to be safe.

**Comment by panghy** [comment]
Oh, actually we found the issue. In some cases it actually invalidated another entry in the same cache which seems to cause the recursive issue. Thanks for the help.

**Comment by ben-manes** [comment]
Great! Hopefully Doug's fixes will get in and it will fail fast in a future JDK release.
