### ISSUE TITLE
Is the elimination logic basically based on capacity size randomly eliminated?

### ISSUE THREAD

**Issue by linlinisme** [ben-manes/caffeine#366]
When I do some test 
```
  LoadingCache<String, String> cache = Caffeine.newBuilder().maximumSize(2)
                .writer(new CacheWriter<String, String>() {
                    @Override
                    public void write(@NonNull String key, @NonNull String value) {
                        System.out.println("set key: " + key + " value: " + value);
                    }

                    @Override
                    public void delete(@NonNull String key, @Nullable String value, @NonNull RemovalCause cause) {
                        System.out.println(Thread.currentThread().getName() + " delete key: " + key + " value : " + value + " cause " + cause);
                    }
                }).build(new CacheLoader<String, String>() {
                    @Nullable
                    @Override
                    public String load(@NonNull String key) throws Exception {
                        System.out.println("load key " + key);
                        return key;
                    }

                    @NonNull
                    @Override
                    public Map<String, String> loadAll(
                            @NonNull Iterable<? extends String> keys) throws Exception {
                        Map<String, String> result = new HashMap<>();
                        Iterator<? extends String> iterator = keys.iterator();
                        while (iterator.hasNext()) {
                            String e = iterator.next();
                            result.put(e, e);
                        }
                        System.out.println("load All " + keys);
                        return result;
                    }


                });
        cache.get("hello0");
        cache.get("hello1");
        cache.get("hello2");
        cache.get("hello3");


        Thread.sleep(10000);
        Set<String> keys = new HashSet<>();
        keys.add("hello0");
        keys.add("hello1");
        cache.getAll(keys);
```
output
```
load key hello0
load key hello1
load key hello2
load key hello3
ForkJoinPool.commonPool-worker-1 delete key: hello0 value : hello0 cause SIZE
ForkJoinPool.commonPool-worker-1 delete key: hello1 value : hello1 cause SIZE
load All [hello0, hello1]
ForkJoinPool.commonPool-worker-1 delete key: hello0 value : hello0 cause SIZE
ForkJoinPool.commonPool-worker-1 delete key: hello3 value : hello3 cause SIZE
```
Why evicted 'hello0' element  ? It just be access.

**Comment by ben-manes** [comment]
It is a little simpler if you disable async behavior by using `Caffeine.executor(Runnable::run)`. The cache uses a frequency filter so we can add debugging to see whether the candidate's frequency is higher than the victim's. If higher then the candidate is chosen, else the LRU victim's is retained.

In a single-threaded case this gives a more optimal answer,
```
load key hello0
load key hello1
load key hello2
candidate(hello1: 1), victim(hello0: 0) => delete key: hello0
load key hello3
candidate(hello2: 1), victim(hello1: 1) => delete key: hello2
load All [hello0]
candidate(hello3: 1), victim(hello1: 3) => delete key: hello3
```

When concurrency is enabled like in your test, the eviction occurs after `hello3` has been loaded. This causes the evaluations to differ and behavior is less deterministic. The delays `ForkJoinPool` initializing threads, context switches, etc causes the evaluations to select different entries to evict. 
```
[RemoteTestNG] detected TestNG version 7.0.0
load key hello0
load key hello1
load key hello2
load key hello3
candidate(hello2: 1), victim(hello0: 0) => delete key: hello0
candidate(hello1: 1), victim(hello1: 1) => delete key: hello1
load All [hello0, hello1]
candidate(hello0: 1), victim(hello2: 1) => delete key: hello0
candidate(hello3: 1), victim(hello2: 1) => delete key: hello3
```

**Comment by linlinisme** [comment]
> load key hello1

Thank you very much Ben.
`candidate(hello3: 1), victim(hello1: 3) => delete key: hello3
`
How we decide who is `candidate` and who is `victim` ？ And `hello1: 3`  is the 3 is frequency? if is, it make me confused. In my code, It just was accessed twice. 
And I want to know how you are debug code and print something like  `candidate(hello3: 1), victim(hello2: 1) => delete key: hello3` :)

**Comment by linlinisme** [comment]
> It is a little simpler if you disable async behavior by using `Caffeine.executor(Runnable::run)`. The cache uses a frequency filter so we can add debugging to see whether the candidate's frequency is higher than the victim's. If higher then the candidate is chosen, else the LRU victim's is retained.
> 
> In a single-threaded case this gives a more optimal answer,
> 
> ```
> load key hello0
> load key hello1
> load key hello2
> candidate(hello1: 1), victim(hello0: 0) => delete key: hello0
> load key hello3
> candidate(hello2: 1), victim(hello1: 1) => delete key: hello2
> load All [hello0]
> candidate(hello3: 1), victim(hello1: 3) => delete key: hello3
> ```
> 
> When concurrency is enabled like in your test, the eviction occurs after `hello3` has been loaded. This causes the evaluations to differ and behavior is less deterministic. The delays `ForkJoinPool` initializing threads, context switches, etc causes the evaluations to select different entries to evict.
> 
> ```
> [RemoteTestNG] detected TestNG version 7.0.0
> load key hello0
> load key hello1
> load key hello2
> load key hello3
> candidate(hello2: 1), victim(hello0: 0) => delete key: hello0
> candidate(hello1: 1), victim(hello1: 1) => delete key: hello1
> load All [hello0, hello1]
> candidate(hello0: 1), victim(hello2: 1) => delete key: hello0
> candidate(hello3: 1), victim(hello2: 1) => delete key: hello3
> ```

I read your wiki https://github.com/ben-manes/caffeine/wiki/Cleanup. It seems that `Caffeine` clean up operation based on a back-end scheduler. How trigger the scheduler to clean up expired element? By fixed time duration Or Event notification？

**Comment by ben-manes** [comment]
> Thank you very much Ben.

You are very welcome.

>candidate(hello3: 1), victim(hello1: 3) => delete key: hello3
>How we decide who is candidate and who is victim?

This is a bit complex. In effect the cache is structured like, `LRU-1 | Frequency Filter | LRU-2`. A new entry is added to LRU-1, which evicts when full. This is a candidate entry that may be promoted into LRU-2. The frequency filter is used to choose between this LRU-1 candidate and the LRU-2 victim to decide which should be discarded. That allows us to capture both recency and frequency.

An overview of this is in [part 1](http://highscalability.com/blog/2016/1/25/design-of-a-modern-cache.html) blog post.

> And hello1: 3 is the 3 is frequency? if is, it make me confused. In my code, It just was accessed twice.

We store frequency in a compact array of counters, called a CountMin Sketch. This allows for hash collisions so it is an estimate, but a decently sized array would have a very small error rate. Since your cache is size 2, it has only 32 counters and by chance collided. Keeping the counters in this array lets us use less memory, operate on them more efficiently, and retain frequencies even when the entries are absent. However it does not have perfect accuracy.

>And I want to know how you are debug code and print something like candidate(hello3: 1), victim(hello2: 1) => delete key: hello3 :)

I hooked a debug line into the [admin](https://github.com/ben-manes/caffeine/blob/a698999b294d4cc64e10dd41ee081afe7ca40336/caffeine/src/main/java/com/github/benmanes/caffeine/cache/BoundedLocalCache.java#L763) method and ran your case in one of the unit tests.

You can apply this [patch](https://github.com/ben-manes/caffeine/files/3882074/issue366.txt) and run it, e.g. via Eclipse.

> And at last, I read your wiki https://github.com/ben-manes/caffeine/wiki/Cleanup. It seems that Caffeine clean up operation based on a back-end scheduler. How trigger the scheduler to clean up expired element? By fixed time duration Or Event notification？

You may call `Cache.cleanUp()` manually for unit tests. Otherwise it will run as a side effect of other read/writes to the cache. If you supply a scheduler thread, it will use the internal expiration order to schedule a task to perform a cleanup when that event would occur.

An overview of this is in [part 2](http://highscalability.com/blog/2019/2/25/design-of-a-modern-cachepart-deux.html) blog post.

**Comment by linlinisme** [comment]
> > Thank you very much Ben.
> 
> You are very welcome.
> 
> > candidate(hello3: 1), victim(hello1: 3) => delete key: hello3
> > How we decide who is candidate and who is victim?
> 
> This is a bit complex. In effect the cache is structured like, `LRU-1 | Frequency Filter | LRU-2`. A new entry is added to LRU-1, which evicts when full. This is a candidate entry that may be promoted into LRU-2. The frequency filter is used to choose between this LRU-1 candidate and the LRU-2 victim to decide which should be discarded. That allows us to capture both recency and frequency.
> 
> An overview of this is in [part 1](http://highscalability.com/blog/2016/1/25/design-of-a-modern-cache.html) blog post.
> 
> > And hello1: 3 is the 3 is frequency? if is, it make me confused. In my code, It just was accessed twice.
> 
> We store frequency in a compact array of counters, called a CountMin Sketch. This allows for hash collisions so it is an estimate, but a decently sized array would have a very small error rate. Since your cache is size 2, it has only 32 counters and by chance collided. Keeping the counters in this array lets us use less memory, operate on them more efficiently, and retain frequencies even when the entries are absent. However it does not have perfect accuracy.
> 
> > And I want to know how you are debug code and print something like candidate(hello3: 1), victim(hello2: 1) => delete key: hello3 :)
> 
> I hooked a debug line into the [admit](https://github.com/ben-manes/caffeine/blob/a698999b294d4cc64e10dd41ee081afe7ca40336/caffeine/src/main/java/com/github/benmanes/caffeine/cache/BoundedLocalCache.java#L763) method and ran your case in one of the unit tests.
> 
> You can apply this [patch](https://github.com/ben-manes/caffeine/files/3882074/issue366.txt) and run it, e.g. via Eclipse.
> 
> > And at last, I read your wiki https://github.com/ben-manes/caffeine/wiki/Cleanup. It seems that Caffeine clean up operation based on a back-end scheduler. How trigger the scheduler to clean up expired element? By fixed time duration Or Event notification？
> 
> You may call `Cache.cleanUp()` manually for unit tests. Otherwise it will run as a side effect of other read/writes to the cache. If you supply a scheduler thread, it will use the internal expiration order to schedule a task to perform a cleanup when that event would occur.
> 
> An overview of this is in [part 2](http://highscalability.com/blog/2019/2/25/design-of-a-modern-cachepart-deux.html) blog post.

Got it! Thanks
