### ISSUE TITLE
Manual cache requires Executor, contradicts docs

### ISSUE THREAD

**Issue by egerardus** [ben-manes/caffeine#367]
After reading the [Cleanup docs](https://github.com/ben-manes/caffeine/wiki/Cleanup) I understand that items will not be evicted from the cache immediately unless I separately provide a `Scheduler` run in another thread to keep it clean. 

I am fine with this and would prefer not creating another thread to immediately evict items when my cache has enough throughput to handle this itself.

I then created a manual loading cache with a time based eviction:

``` java
private final Cache<SocketAddress, Authentication> authentications = Caffeine.newBuilder()
            .expireAfterWrite(10_000, TimeUnit.MILLISECONDS)
            .build();
```

And was surprised to see that this creates a forkjoinpool thread once it is used.

Based on the first paragraph of the [Cleanup docs](https://github.com/ben-manes/caffeine/wiki/Cleanup) this should not happen, or the docs should be updated if this is no longer the default build for a manually loaded cache.

**Comment by ben-manes** [comment]
Caffeine does not create a `ForkJoinPool` but rather reuses the system-wide `ForkJoinPool.commonPool()`. This is the default setting of `Caffeine.executor`, though you can safely use your own or disable using `Runnable::run`. This is a simple `Executor` which means it does not have any scheduling capabilities, which is what expiration would require.

The executor is used for tasks that could be run not on the calling thread such as eviction, removal notifications, or `AsyncCache` future-based computations. For most cases, like eviction policy management, this is very cheap so disabling this executor is fine. For some users it is helpful to minimize the user-facing latency, so we defer to the executor when applicable.

This shouldn't counter the documentation. We do not create our own threads, but do use those supplied by the JVM when possible. For expiration this scheduling can now be done without our own thread if using JDK9, so we offer that as an opt-in.

**Comment by egerardus** [comment]
Brilliant, that explains it, and now switched to:
``` java
private final Cache<SocketAddress, Authentication> authentications = Caffeine.newBuilder()
            .expireAfterWrite(10_000, TimeUnit.MILLISECONDS)
            .executor(Runnable::run)
            .scheduler(Scheduler.systemScheduler())
            .build();
```
This is working and I can log cache entries being removed with a RemovalListener.

Though, I noticed that when using `Caffeine.scheduler(Scheduler)` I still have to manually disable executor with `Runnable::run` otherwise the `ForkedJoinPool` thread is used instead, is this intentional?

**Comment by ben-manes** [comment]
The scheduled task simply submits the work to the executor and, in this case, you are running that work on the Scheduler's thread. This is typically fine, but if you had expensive work it wouldn't be ideal.

The system scheduler is using a single-threaded `ScheduledExecutorService` buried away inside of `CompletableFuture`. This is basically,

```java
Executor delayedExecutor = CompletableFuture.delayedExecutor(delay, unit, executor);
CompletableFuture.runAsync(task, delayedExecutor);
```

That executor is mostly used for `CompletableFuture.orTimeout`, so many tiny tasks might be scheduled on its thread and performed in quick succession.

**Comment by egerardus** [comment]
OK understood, and thank you for the detailed explanation. This is a model OSS library.
