### ISSUE TITLE
An entry delete just after load

### ISSUE THREAD

**Issue by ly576078** [ben-manes/caffeine#368]
Hi, 
    Since the caffine use Window TinyLfu, it is not a normal LRU, when we use the entry just loading from DB, we found this entry has been evicted by size( set the maximumSize as 30000). Is there any way to avoid this circumstance? Do not evict the entries just been added. Thanks!

**Comment by ben-manes** [comment]
The cache starts with 1% reserved for new arrivals, and then hill climbs to a more optimal configuration based on the workload. This cannot be set externally.

You can pin entries if you work on them in a stateful manner, like a lock. That’s done by excluding the entry from an eviction policy (eg. weight of zero).

What is your situation/ problem?

**Comment by ly576078** [comment]
Thanks for your advice. The entries in our cache should has same weight, as it is the same object without statuful. We found a way to solve this situation: Our service get a request, the request require a entry, after adding the entry into cache, this entry should also be hold by the request until the request finish.

**Comment by ben-manes** [comment]
That sounds like a good approach. The cache might evict at anytime so not relying on its state across multiple queries in a single request is definitely ideal.
