### ISSUE TITLE
BoundedLocalCache#doComputeIfAbsent Need Double Syn Lock?

### ISSUE THREAD

**Issue by linlinisme** [ben-manes/caffeine#369]
When I read the code : `com.github.benmanes.caffeine.cache.BoundedLocalCache#doComputeIfAbsent`
I found 
 ```
Node<K, V> node = data.compute(keyRef, (k, n) -> {
      if (n == null) {
        newValue[0] = mappingFunction.apply(key);
        if (newValue[0] == null) {
          return null;
        }
        now[0] = expirationTicker().read();
        weight[1] = weigher.weigh(key, newValue[0]);
        n = nodeFactory.newNode(key, keyReferenceQueue(),
            newValue[0], valueReferenceQueue(), weight[1], now[0]);
        setVariableTime(n, expireAfterCreate(key, newValue[0], expiry(), now[0]));
        return n;
      }

      synchronized (n) {
        nodeKey[0] = n.getKey();
        weight[0] = n.getWeight();
        oldValue[0] = n.getValue();
        if ((nodeKey[0] == null) || (oldValue[0] == null)) {
          cause[0] = RemovalCause.COLLECTED;
        } else if (hasExpired(n, now[0])) {
          cause[0] = RemovalCause.EXPIRED;
        } else {
          return n;
        }

        writer.delete(nodeKey[0], oldValue[0], cause[0]);
        newValue[0] = mappingFunction.apply(key);
        if (newValue[0] == null) {
          removed[0] = n;
          n.retire();
          return null;
        }
        weight[1] = weigher.weigh(key, newValue[0]);
        n.setValue(newValue[0], valueReferenceQueue());
        n.setWeight(weight[1]);

        now[0] = expirationTicker().read();
        setVariableTime(n, expireAfterCreate(key, newValue[0], expiry(), now[0]));
        setAccessTime(n, now[0]);
        setWriteTime(n, now[0]);
        return n;
      }
    });
```
Be aware  **synchronized (n)**, the `ConcurrentHashMap` has promise the `compute()` method is thread-safe. So is the `synchronized` necessary here?

**Comment by ben-manes** [comment]
Yes, we have other cases that mutate the node outside of a map computation. However that means our locking is cheaper as most cases already have blocked via the map. We need this for faster puts and during eviction.

**Comment by linlinisme** [comment]
> Yes, we have other cases that mutate the node outside of a map computation. However that means our locking is cheaper as most cases already have blocked via the map. We need this for faster puts and during eviction.

em...  If the  node is modified, How we avoid the Cache pollution Problem?

**Comment by ben-manes** [comment]
What do you mean? Note that modifications might be to our metadata and not the user’s.

**Comment by linlinisme** [comment]
> What do you mean? Note that modifications might be to our metadata and not the user’s.

I mean, if not affect the user application. May be the lock can be omitted. I don't know  other cases that mutate the node outside of a map computation, so I have a little confusion. HaHa

**Comment by linlinisme** [comment]
Another tip
```
if ((nodeKey[0] == null) || (oldValue[0] == null)) {
          cause[0] = RemovalCause.COLLECTED;
        } else if (hasExpired(n, now[0])) {
          cause[0] = RemovalCause.EXPIRED;
        } else {
          return n;
        }

        writer.delete(nodeKey[0], oldValue[0], cause[0]);
```
The
`   writer.delete(nodeKey[0], oldValue[0], cause[0]);
`
`  void delete(@NonNull K key, @Nullable V value, @NonNull RemovalCause cause);
`
When  cause[0] = RemovalCause.COLLECTED; 
The `nodeKey[0], oldValue[0]` is null

**Comment by ben-manes** [comment]
We decouple the map operations from the policy, which is updated in batches. This lets us maintain global state without exclusive locking on every read or write. We use a lifecycle state (alive, retired, dead) to coordinate this under the node’s lock. Sometimes this can be outside of the map, which is cheaper than forcing it under the map’s lock.

**Comment by ben-manes** [comment]
Yes, the value may be null. A writer is not allowed when weakKeys are enabled, so a disabled instance is set that makes it a no-op.

**Comment by linlinisme** [comment]
> Yes, the value may be null. A writer is not allowed when weakKeys are enabled, so a disabled instance is set that makes it a no-op.

**Comment by linlinisme** [comment]
> Yes, the value may be null. A writer is not allowed when weakKeys are enabled, so a disabled instance is set that makes it a no-op.

If the user reloading the writer class ,  may be throw a  null point exception, when updating the cache,  Because they see `@NonNull`。 They might think key and value  is not null.

**Comment by ben-manes** [comment]
The value may be null, as described by the delete method. The null key would never be observed by a user because the builder rejects that feature combination. This means either we can guard the writer call or use a no-op instance to get the same effect. That’s mostly a style choice (see null object pattern).

**Comment by linlinisme** [comment]
> We decouple the map operations from the policy, which is updated in batches. This lets us maintain global state without exclusive locking on every read or write. We use a lifecycle state (alive, retired, dead) to coordinate this under the node’s lock. Sometimes this can be outside of the map, which is cheaper than forcing it under the map’s lock.

I still have a little confusion. 
1、Does `synchronized` Can be optimized to `volatile`？
2、`data.compute()` here relate only to the `key, value, weight, accessTime, writeTime、variableTime`.  I am not sure whether the updated policy will change them or not.

**Comment by ben-manes** [comment]
An uncontended lock is very cheap, so you won’t see a gain by removing it. By forcing other usages under the map’s lock there would be some performance loss. 

It’s been too long to recall numbers, but it significantly helped for an explicit put. In CLHM it used CAS style instead and this was slower due to excess retries. A put using compute was slower as well due to allocating a lambda and lock collisions.

The per-node lock may update the key where we encode it’s lifecycle state which is updated by removal or eviction.

There are a lot of factors and we split lock domains so it’s best to optimize against a benchmark. This hasn’t been a problem so far as we are very close to the map’s write throughput.

**Comment by linlinisme** [comment]
`An uncontended lock is very cheap
``There are a lot of factors and we split lock domains so it’s best to optimize against a benchmark. This hasn’t been a problem so far as we are very close to the map’s write throughput.`
I agree.  

All I talk about is  just my personal Suggestions :)
Never mind.

**Comment by ben-manes** [comment]
The questions are good and I am happy answer them. I only meant that sometimes one has to rely on benchmarks to drive decisions because it’s otherwise hard to tell based on guesswork in these types of problems. We’d have to run them through to know for certain if a change is beneficial or not, as I can’t be certain in this regard.
