### ISSUE TITLE
Allow weigher even when using maximumSize

### ISSUE THREAD

**Issue by gatesn** [ben-manes/caffeine#370]
It would be useful to have weights in cache stats even if it's not the metric being used for eviction.

**Comment by ben-manes** [comment]
I think the implications favor not doing this and letting users track that instead.

The cache always size evicts by weight, but `maximumSize` configures a weigher that always evaluates to `1`. In this setting the entry class drops the `weight` field to return the constant, to avoid the extra memory usage. The cache's evaluations, evictions, etc. are unaware so `maximumSize` is just an optimized version of `maximumWeight`.

This means we cannot bound by both size and weight, or track the `weight` but not use it. The logic could be changed to support these more complex cases, but I don't see a good justification yet. In your case it should be easy to maintain a separate field, e.g. Solr does this with its [ramBytes](https://github.com/apache/lucene-solr/blob/6a72b81ed308b56d7a5dae1fd42e811924572763/solr/core/src/java/org/apache/solr/search/CaffeineCache.java#L94).
