### ISSUE TITLE
AsyncCache eviction on loading error is executed AFTER user's completion handlers

### ISSUE THREAD

**Issue by sauthieg** [ben-manes/caffeine#372]
We're using Caffeine 2.8.0, and we have observed an unexpected behaviour when the mapping function for an entry completes exceptionally: the eviction (that happens **synchronously** when Caffeine detect that the mapping function failed) is executed after completion handlers that the user may have registered on the `CompletionStage` returned by `cache.get(key, function)`.

In our case, we were expecting the mapping function to be executed on the 2 calls to `.get(key, function)`, but that was not happening since the 2nd call was using the not-yet-evicted cache entry.

Here is a test case that show the issue when using Caffeine:

```java
  @Test
  public void shouldExecuteEvictionFirst() throws Exception {
    // This test's intent is to emphasis an issue where user's callbacks are executed first
    // This is especially an issue when the future completes exceptionally and the completion handler
    // responsible for eviction is executed **after** the user's completion handler.

    AsyncCache<String, String> cache = Caffeine.newBuilder().buildAsync();
    CompletableFuture<String> future = new CompletableFuture<>();

    // Uncompleted future is stored in the cache
    CompletableFuture<String> async = cache.get("A", (key, executor) -> future);
    // Register the user's callback that capture if the entry is evicted or not
    CompletableFuture<String> evicted  =
            async.exceptionally(e -> cache.getIfPresent("A") == null ? "evicted" : "not evicted");

    // Now trigger the future's completion that would initiate eviction ...
    future.completeExceptionally(new Exception("Boom"));
    // ... so that we can verify that the entry has been properly evicted
    //  - after all completion handlers have been executed (end state)
    assertThat(cache.getIfPresent("A"), nullValue());
    //  - before the user completion handler have been executed (captured during the handler execution)
    assertThat(evicted.get(), is("evicted"));
  }
```

After analysis, we think it comes down to the way `CompletableFuture` are implemented: they register completion handlers in a stack, and they pop-then-execute the handlers, having an execution order inverse of registration order.

See the following code snippet to see the difference:

```java
CompletableFuture<String> f;
List<String> collector = new ArrayList<>();
// Note the order of the List in the assertion

// Completion handlers added on the same CompletableFuture instance
f = new CompletableFuture<>();
f.whenComplete((r, e) -> collector.add("f1"));
f.whenComplete((r, e) -> collector.add("f2"));
f.complete("hello");
assertThat(collector).containsExactly("f2", "f1"); // inverse order

collector.clear();

// Completion handlers chained using the fluent API
f = new CompletableFuture<>();
f.whenComplete((r, e) -> collector.add("f1"))
 .whenComplete((r, e) -> collector.add("f2"));
f.complete("hello");
assertThat(collector).containsExactly("f1", "f2"); // same order
```

Let me jump (maybe too hastily) into a fix idea: what about storing in the cache, not the direct result of the mapping function, but a `CompletableFuture` resulting of the registration of the Caffeine completion handler for eviction, so that, when the future returned by the mapping function completes, it will execute first the eviction, then user's own handlers.

**Comment by ben-manes** [comment]
Unfortunately it would cause other surprises if we did not sure the user's future directly. Consider the case,

```
AsyncCache<String, String> cache = Caffeine.newBuilder().buildAsync();
CompletableFuture<String> future = new CompletableFuture<>();

CompletableFuture<String> async = cache.get("A", (key, executor) -> future);

// A conditional write requires reference equality for the future, which does not implement equals
cache.asMap().remove("A", future);
```

Or consider when propagating a cancel upstream, e.g. to an http client that supplied the future.
```
jshell> var f = new CompletableFuture()
f ==> java.util.concurrent.CompletableFuture@68be2bc2[Not completed]
jshell> var x = f.whenComplete((r, e) -> {});
x ==> java.util.concurrent.CompletableFuture@4678c730[Not completed]
jshell> x.cancel(true)
$5 ==> true
jshell> x
x ==> java.util.concurrent.CompletableFuture@4678c730[Completed exceptionally: java.util.concurrent.CancellationException]
jshell> f
f ==> java.util.concurrent.CompletableFuture@68be2bc2[Not completed, 1 dependents]
```

In those cases by not providing the future directly, we violate assumptions that fit more naturally when viewing the cache as an extension of `java.util.concurrent`.

**Comment by sauthieg** [comment]
Hmmm, do you have any other suggestions ?

**Comment by ben-manes** [comment]
The only thing we could do is to add a check and removal on every computing `cache.get` type, to determine if the fetched future failed. Then optimistically remove (via `remove(key, future)`) and retry once more. That would assist in the race but wouldn't resolve it. You could do this yourself by using the `asMap()` view prior to the retry.

In general, it is best not to make expectations on the cache's state. Whether we can or should do anything in the library is hard to judge.

**Comment by sauthieg** [comment]
Would that make sense to preemptively invalidate/remove the cache entry on failure?

```java
cache.get("A", (key, executor) -> future.exceptionally(e -> {
    cache.synchronous().invalidate("A");
    throw e;
}));
```

**Comment by sauthieg** [comment]
Turned out that it was not my best idea :)

```
java.lang.IllegalStateException: Recursive update
	at java.base/java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1167)
	at java.base/java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1102)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.removeNoWriter(BoundedLocalCache.java:2091)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.remove(BoundedLocalCache.java:2081)
	at com.github.benmanes.caffeine.cache.LocalAsyncCache$AbstractCacheView.invalidate(LocalAsyncCache.java:544)
	at org.forgerock.openig.filter.oauth2.CaffeineCacheAccessTokenResolver.lambda$resolve$1(CaffeineCacheAccessTokenResolver.java:119)
```

**Comment by ben-manes** [comment]
If you are retrying on failure, have you looked at libraries like Failsafe? That one has worked well for me for async, retryable calls.

**Comment by sauthieg** [comment]
No we don't retry on failure.

In fact, the pre-emptive cache entry invalidation mostly works ok for me, the constraints is that the future needs to be completed asynchronously: if the future is already completed, the completion handler would be called, throwing that IAE "Recursive modification". The trick is to make sure that the cache invalidation happen synchronously within the mapping function.

**Comment by ben-manes** [comment]
right, you can use `exceptionallyAsync` in recent versions of Java.

As you can see, we're in a bind in that the current behavior is correct but JDK implementation details may not always be ideal. Unless there are bright ideas, I don't think there are any changes we can make to greatly improve the situation.

At best we could make `get(key)` perform an invalidate if it retrieved a failed future and retry. However that could still suffer from races and the recomputation could fail as well. There are subtle interactions with futures which makes me hesitant to change in this way, not knowing if it actually helps anything.

**Comment by sauthieg** [comment]
Yes, I agree, this is caused by an unfortunate JDK implementation detail, don't see what we can really do here.

Feel free to close as won't fix, the explanations and details shared in this issue would still be interesting/useful for a future user.

Thanks

**Comment by ben-manes** [comment]
Thanks for the interesting discussions. We do have a [FAQ](https://github.com/ben-manes/caffeine/wiki/Faq), so if you have suggestions for a new entry we could try adding something there.

**Comment by honza-zidek** [comment]
@sauthieg, @ben-manes:

I use `exceptionallyCompose(e -> null)` and it seems to work.

My source of data is a `Mono` so I have to translate from `Mono` to `CompletableFuture` and back.

```java
public class MyService {
    private MyDataConnector connector;
    private AsyncLoadingCache<UUID, MyData> cache;
    ....
    @PostConstruct
    public void initCache() {
        cache = Caffeine.newBuilder()
            .buildAsync((key, executor) -> connector.getDataExpensiveOperation(key).toFuture()
                  // Here I am using the contract of buildAsync():
                  // "If the asynchronous computation fails or computes a null value then the entry will be automatically removed."
                  .exceptionallyCompose(e -> null)
            );
    }
    public Mono<MyData> getDataCached(UUID key) {
        return Mono.fromCompletionStage(cache.get(key));
    }
}

public class MyDataConnector {
    public Mono<MyData> getDataExpensiveOperation {
        ...
    }
}
```
Just I am not sure whether I should use `exceptionallyCompose()` or `exceptionallyComposeAsync()`.
