### ISSUE TITLE
Integer overflow in LIRS simulation

### ISSUE THREAD

**Issue by ohadeytan** [ben-manes/caffeine#377]
In few of my simulations, I had an integer overflow on the LIRS policy at the [`checkState` validation](https://github.com/ben-manes/caffeine/blob/aa0cdfad2e94e4a39432f7d27f43ff0a3e25755a/simulator/src/main/java/com/github/benmanes/caffeine/cache/simulator/policy/irr/LirsPolicy.java#L305):
```
305    checkState(data.size() <= (maximumSize + maximumNonResidentSize));
```
The values were:
```
                     16846919 <= (805306368 + 1610612736)
```
Would you think it will be reasonable to fix it by changing the variables to `long` or any other fix?
Maybe it's too rare so we shouln't change anything?

**Comment by ben-manes** [comment]
If you only care about this one line and it doesn't matter anywhere else, you could do
```java
checkState(data.size() <= ((long) maximumSize + maximumNonResidentSize));
```

Otherwise changing the fields would be fine.

**Comment by ohadeytan** [comment]
As far as I see that is the only problem so I'll fix it as you suggested.
