### ISSUE TITLE
keeping stale values in case the backend is offline

### ISSUE THREAD

**Issue by barkanido** [ben-manes/caffeine#385]
Hey,
First, thanks for this great library.
I would like to configure Caffeine to save stale values in case the backend is off. This means if you cache a DB query and the DB query, and the DB goes offline for some reason. The cache would preserve the same values **even after they are considered stale**. This is because, in a few use cases, a stale value is better than no value.
This is doable with `refreshAfterWrite` but this API is not as flexible as `expireAfter`. This might be a duplicate of #360 but I wonder if there is another way (even if less straightforward) of doing so.

**Comment by ben-manes** [comment]
Perhaps a victim cache would work? In that case when the writer synchronously evicts, you capture it into a secondary cache. A subsequent loader call could fetch it, resurrecting the entry. That might provide the lifecycle hack that you’re looking for.

**Comment by barkanido** [comment]
> in that case when the writer synchronously evicts...

which writer? do you mean an external thread that invalidates the cache?

**Comment by ben-manes** [comment]
I meant if you supply a `CacheWriter`.

**Comment by barkanido** [comment]
do you mean a configuration like [your comment here](https://github.com/ben-manes/caffeine/issues/147#issuecomment-288453253)?

**Comment by ben-manes** [comment]
Yes, something like that might work?

**Comment by barkanido** [comment]
I think it might work. thanks!

**Comment by VytautasSer** [comment]
Hello,

Have you found a solution to this problem? Could you share a solution? Sad that there is no such thing out of the box.

**Comment by barkanido** [comment]
Look in the example above by @ben-manes . also, note that with a loadingCache, a backend failure will throw an exception and the mapping is unchanged so you get the old value by default (if it was there already)
