### ISSUE TITLE
how can set expire time for each key 

### ISSUE THREAD

**Issue by forfuns** [ben-manes/caffeine#386]
hello, can I use caffeine set expire time for each key 

I need cache keys not same expire time

consider adding a new feature ?

**Comment by ben-manes** [comment]
Yes, you can use `expireAfter(Expiry)`. Please see the [wiki](https://github.com/ben-manes/caffeine/wiki/Eviction#time-based) for an example.

**Comment by forfuns** [comment]
@ben-manes 
I need set expire for each key but not some time , like :
```
caches.put(key1,value1,1,TimeUnit.HOURS);
caches.put(key2,value2,30,TimeUnit.MINUTES);
caches.put(key3,value3,1,TimeUnit.DAYS);
```

**Comment by ben-manes** [comment]
Typically you should determine the expiration time based on the value. This way you can use an atomic load, rather than a racy `get-compute-put`.

You can, however, use `cache.policy().expireVariably()` which provides those manual methods.
