### ISSUE TITLE
Springboot integration

### ISSUE THREAD

**Issue by Docjones** [ben-manes/caffeine#389]
Hello! 

we are using caffeine to replace the ConcurrentHashMap cache, which is default in current springboot. We are dynamically creating caches using the `@Cacheable(cacheNames = { "..." })` annotation.

I am trying to set the `recordStats` property, since we are using the springboot actuator package to monitor various aspects of our applications.

I tried to set `spring.cache.caffeine.spec=expireAfterAccess=3600s,recordStats` in `application.properties`, which does not work. 

Setting it in a `@Configure` class did not work either:

```
@Configuration
public class CacheConfig {

  public CacheManager cacheManager() {
    CaffeineCacheManager cacheManager = new CaffeineCacheManager();
    cacheManager.setCacheSpecification("expireAfterAccess=3600s,recordStats");
    return cacheManager;
  }
}
```

The cache statistics does not appear in the `/actuator/cache/{caches}` endpoint or in our springboot-admin server.

Taking from the current api documentation, i found:

> The string syntax is a series of comma-separated keys or key-value pairs, each corresponding to a Caffeine builder method.
> 
>     initialCapacity=[integer]: sets Caffeine.initialCapacity.
>
> ...
>
>     recordStats: sets Caffeine.recordStats(). 
> 
> Durations are represented by an integer, followed by one of "d", "h", "m", or "s", representing days, hours, minutes, or seconds respectively. There is currently no syntax to request expiration in milliseconds, microseconds, or nanoseconds.
> 
> Whitespace before and after commas and equal signs is ignored. Keys may not be repeated; it is also illegal to use the following pairs of keys in a single value:
> 
>     maximumSize and maximumWeight
>     weakValues and softValues 

And the relevant point:

> CaffeineSpec does not support configuring Caffeine methods with non-value parameters. These must be configured in code. 

Is there no possibility to achieve my task? 

thanks

**Comment by ben-manes** [comment]
From a quick Google search, I think you want to annotate the method with `@Bean`. For example [1](https://stackoverflow.com/questions/56428380/expireafterwrite-using-caffeinecachemanager-instead-of-guavacachemanager), [2](https://stackoverflow.com/questions/51890588/configuration-for-specific-caffeine-caches-in-spring), and [3](https://stackoverflow.com/q/56905704/19450) all show this usage.

The `non-value` parameters include class instances like `CacheLoader` or `RemovalListener`, which would have to be reflectively loaded. That's not what you want to do here, so its moot. The specification should throw an exception for any setting it does not understand.

I would expect your case to be solvable, but unfortunately not by me. I am not a Spring user and only assisted in porting their prior Guava adapter to Caffeine (nearly 1-to-1). As an aside, you may be interested in an improved Spring integration provided by https://github.com/stepio/coffee-boots.

I would suggest asking on a Spring forum, like StackOverflow. This sounds like a generic issue

**Comment by ben-manes** [comment]
A few more links to look at,

- https://stackoverflow.com/questions/56158365/register-caffeine-cache-in-spring-actuator-cachemanager
- https://www.javadevjournal.com/spring-boot/spring-boot-with-caffeine-cache/
- https://stackoverflow.com/questions/56158365/register-caffeine-cache-in-spring-actuator-cachemanager

**Comment by ben-manes** [comment]
Sorry, that exhausts my abilities!

**Comment by Docjones** [comment]
Thanks much for your help! 

Basically i had to do this:

```
@Configuration
public class CacheConfig {

  @Bean
  public CacheManager cacheManager() {
    CaffeineCacheManager cacheManager = new CaffeineCacheManager(<insert-list-of-used-cachenames-here>);
    cacheManager.setCacheSpecification("recordStats");
    return cacheManager;
  }
}
```

This works, but downside is to have the `@Cacheable` cachenames and the list of names in sync.
