### ISSUE TITLE
Cache save when shutting down, load when starting up

### ISSUE THREAD

**Issue by Amosss** [ben-manes/caffeine#398]
Hi

I'm now using ehcache and realized they removed the option for persistence when the system shuts down.  My purpose is simple (Or so I hope):

Create a cache and work with it. When I shut down tomcat (via tomcat manager/eclipse stop etc), I want to save the caching into a file on the disk.

When tomcat restarts, I want it to check if the file exists and if so, to load it back and continue from there as if nothing happened.

Is the above possible? 
If so, where can I read how to implement this?
Thanks!

**Comment by ben-manes** [comment]
We don't implement a persistence layer, but you could implement one yourself. The `asMap` view could be used to iterate over the entries. If you perform an orderly startup and shutdown, you should be able to persist and reload the cache data.

Another project that might be of interest is [MapDB](https://github.com/jankotek/mapdb).

**Comment by Amosss** [comment]
Thanks for the tip, I will try it.
