### ISSUE TITLE
Multiple async requests for same key

### ISSUE THREAD

**Issue by ncvijovic** [ben-manes/caffeine#399]
Hello, 

I am trying to solve an issue which is identical to the one mentioned in #297 but I am having problems defining the cache correctly. As mentioned in the issue what I need is an `asyncLoadingCache` which will store a `CompletableFuture` on first hit and then load the actual value asynchronously while at the same time holding other requests for the same key on hold until the future is completed. 
Since I am using spring boot 2, I defined the cache as a bean and let springs autoconfiguration to create a SimpleCacheManager for it. The cache configuration is:
```
@Bean
    public AsyncLoadingCache<String, OAuth2Authentication> asyncCaffeineCache(CachableRemoteTokenServices tokenServices) {
        return Caffeine.newBuilder()
                       .initialCapacity(100)
                       .maximumSize(500)
                       .expireAfterWrite(4, TimeUnit.MINUTES)
                       .recordStats()
                       .buildAsync((key, executor) -> CompletableFuture.supplyAsync(() -> tokenServices.loadAuthentication(key), executor));
    }
```
After that I used the springs `@Cacheable` annotations to mark a method i would like cached. 
Upon testing (jmeter, http requests, 20 simultaneous requests in two iterations) I can see that the cache is being invoked but the first few calls are missing the cache and actually calling the cachable method. This number varies, sometimes 5, sometimes 15, but always greater than 1. What I would expect to see is only one call to the method and the rest of the requests waiting until the completable future is completed and the actual value is stored in the cache. 
I am probably missing something about the way the cache works, any help with this would be very appreciated. Thanks in advance!

**Comment by ben-manes** [comment]
I have not used Spring since 2.x days, so that aspect is foreign to me now. I am unsure how AOP, Spring Cache, DI scoping, and Caffeine interact.

Otherwise I agree the cache should work as you are expecting. For any given key, it should only have one in-flight computation for a single cache instance.

I would modify it slightly for debugging purposes. Below I added a removal listener so that you see if it was evicted and an instance counter in case it is a prototype bean.

```java
AtomicInteger counter = new AtomicInteger();

@Bean
public AsyncLoadingCache<String, OAuth2Authentication> asyncCaffeineCache(CachableRemoteTokenServices tokenServices) {
  int instance = counter.getAndIncrement();
  return Caffeine.newBuilder()
      .initialCapacity(100)
      .maximumSize(500)
      .expireAfterWrite(4, TimeUnit.MINUTES)
      .recordStats()
      .removalListener((key, value, cause) -> {
        System.out.printf("%s: %s on cache #%d%n", cause, key, instance);
      })
      .buildAsync(key -> {
        OAuth2Authentication value = tokenServices.loadAuthentication(key);
        System.out.printf("Loaded %s on cache #%d%n", key, instance);
        return value;
      });
}
```

**Comment by ncvijovic** [comment]
Hi Ben,

thanks for the answer. It helped point me in the right direction. The problem turned out to be in the spring integration for the Caffeine cache. The exposed cache bean i created was not picked up by the spring auto-configuration so it was not actually used. Instead spring created a default caffeine cache and used that one instead, resulting in multiple cache loads. 
Looking into the spring support for caffeine i see that it would only support Springs wrapped`CaffeineCache` beans that are supplied with the `com.github.benmanes.caffeine.cache.Cache` instances, which the AsyncLoadingCache is not.

For anyone who is coming against the same problem, my solution was to give up on the springs caching system altogether and use the caffeine cache directly. There may be some custom solution possible with extending Spring caching mechanism but in my case it was overkill. Possible solution could be found in the comments [here](https://stackoverflow.com/questions/56239146/is-it-possible-to-adapt-a-caffeine-loadingcache-for-use-with-spring-boots-cach)

Again, thanks Ben for the help in identifying the real problem.
