### ISSUE TITLE
Use caffeine as a map rather than a cache

### ISSUE THREAD

**Issue by asad-awadia** [ben-manes/caffeine#402]
Is using caffeine as a replacement for CHM as a better, faster map an anti pattern? I basically want to have a size bounded map where values do not expire based on time

Or should I just stick with CHM?

**Comment by ben-manes** [comment]
Caffeine is built on top of CHM to add features like a size bound. It is only faster in some cases, like computeIfAbsent, do to optimizations favoring a cache use-case. You can use it in an unbounded case as just a wrapper without a performance loss. However when you really do just want a map then there is no reason to prefer Caffeine and can use CHM directly.
