### ISSUE TITLE
CompletableFuture Support

### ISSUE THREAD

**Issue by justtonytone** [ben-manes/caffeine#406]
Apologies if this has been discussed in a different thread, I was not able to find it.

I see that the AsyncLoadingCache supports a `buildAsync()` function where we can return a future. Is there an equivalent `cache.get(key, func)` where func can also return a future?

**Comment by ben-manes** [comment]
`AsyncLoadingCache` extends `AsyncCache`, which has this method.

If you are asking if the synchronous `Cache` types offer future-based methods, then no. However you can use `AsyncCache.synchronous()` to utilize its `Cache` view, and mix appropriately.

**Comment by justtonytone** [comment]
Sorry, was just looking through the code and saw that there is an equivalent functionality to return a future while calling `cache.get()`: https://github.com/ben-manes/caffeine/blob/614fe6053e343481c15c55f1d696517d73baae0d/caffeine/src/main/java/com/github/benmanes/caffeine/cache/AsyncCache.java#L101.

**Comment by ben-manes** [comment]
The other way I can read your question, `buildAsync(loader)` accepts either an `AsyncCacheLoader` or a `CacheLoader`. The former returns a future.
