### ISSUE TITLE
Incorrect removal cause when expiration races with removal

### ISSUE THREAD

**Issue by ben-manes** [ben-manes/caffeine#412]
@rangadi discovered an issue and described it over email as,

> We have a cache with `expireAfterAccess()`, there are no other limits. Occasionally `removalListener()` gets called with 'COLLECTED' and value is null. This happens on the order of single digit times in 1M removals. It always happens for an element being explicitly removed (the listenerGets triggered since remove()).

When reviewing the code I spotted a race condition, wrote a test to demonstrate it, and @rangadi kindly verified the fix. The optimized path for `remove(key)` when no `CacheWriter` is enabled had a racy read, where setting a dummy writer caused it to utilize a correct implementation. The fix is then to remove this incorrectly optimized method.

**Comment by rangadi** [comment]
Thank you so much for looking into this.
