### ISSUE TITLE
Expire question

### ISSUE THREAD

**Issue by Amosss** [ben-manes/caffeine#414]
Hi

The scenario:  A caching mechanism that holds a list of key->Object.
When accessing a key that is not there, I collect its data and `write` it to the cache.
When accessing a key that is there, I `read` it from the cache and do what needs to be done with it.
Every 30 minutes, using a daemon, I loop the cache to do something with its content.

Plan A: Ideally, a key will be removed if not accessed for 7 days.
Problem: the daemon is considered as "access" causing the timer to reset every 30 minutes.
Workaround: Is there one?

Plan B: Remove the key 7 days after its creation.
Problem: I only saw expireAfterWrite method, meaning each time I update a property in the object, the write timer is reset and again, the key will never be removed.

Plan C: Use expireAfter with my own mechanism. I was thinking that if I have to use plan C, I'd go with implementing plan A myself but I'm not sure how to do it.

Any ideas?
Thanks

**Comment by ben-manes** [comment]
When you loop the cache, do you mean,
1. Loop over the contents using an iterator from `asMap`, such as `entrySet`? If so, those should not reset the access timestamp.
2. Loop over a different set of keys and query the cache, e.g. `getIfPresent`? If so, that would update the access timestamp.

Regarding Plan C, the simplest mechanism is to use a ThreadLocal variable in the expiration logic. When the TL is `true` then it returns the `currentDuration`, whereas if `false` then it returns the new duration to set. When accessing the cache you in your daemon you would set the flag before and unset it afterwards. This isn't the prettiest, but very clear code.

#413 also asked a similar question. If there is strong demand then we could add a method into `Cache.policy()` for this. The semantics is a little unclear, but that is our escape hatch for unblocking these ad hoc needs without polluting the core apis.

**Comment by Amosss** [comment]
Thanks for your reply.

I read the link you posted and there I saw that `cache.asMap().get("key");` resets the timer. 
I also read about a getIfPresentQuiet request.

So if I understand correctly, what I do now resets the timer:
```
dbData.asMap().keySet().forEach(entry -> keys.add(entry));
for (String key: keys) {
    		obj = dbData.getIfPresent(key);
...
}
```
What I should do in order not to reset the timer is
entries = dbData.asMap();
for (Map<Object, Object> entry: entries) {
    		obj = entry.getValue();
...
}
```
I understood correctly?
Assuming this won't reset the timer, it will mean doubling the data/memory for this operation. So maybe a getIfPresentQuiet can be a good idea. Just a thought.

If I misunderstood, let me know.
Thanks!

**Comment by ben-manes** [comment]
> What I should do in order not to reset the timer is...

Yes.

> Assuming this won't reset the timer, it will mean doubling the data/memory for this operation.

Why do you think that?

Both traverse the internal `ConcurrentHashMap` and the second one avoids an extra map lookup per iteration. That would be considered a best practice for any map. It is also safer since you won't risk a race condition of the entry disappearing between the iterator and the lookup.

**Comment by ben-manes** [comment]
Also, if you only need the value and not the key, as in the second example, you can use `Map.vaues()` of course. The `keySet`, `values`, and `entrySet` are all efficient iterators of the map view.

**Comment by Amosss** [comment]
So `cache.asMap().get("key");` does not reset the timer? That was the reason I posted my question, I thought it does.

Regarding the memory, I thought it creates a new map. So based on what you wrote, it answers both https://github.com/ben-manes/caffeine/issues/413 and the getIfPresesntQuiet request.

Regarding the .values() etc... Ofcourse.

**Comment by ben-manes** [comment]
> So cache.asMap().get("key"); does not reset the timer?

It does reset the timer.

An iteration does not reset because you are scanning all entries, whereas most cache usages are point queries to lookup by key. Since it didn't seem to match a reasonable use-case, in Guava we decided to not reset the timestamp. Hence Caffeine doesn't either.

> Regarding the memory, I thought it creates a new map.

No, it is not a copy. It is a view of the cache as a map, where you can use any of its methods to operate against it (e.g. `compute`).

**Comment by Amosss** [comment]
Great, thanks a lot!

**Comment by ben-manes** [comment]
Released 2.8.3 which includes `cache.policy().getIfPresentQuietly(key)` which skips updating any cache metadata.

**Comment by Amosss** [comment]
Thank you very much, what I do now is (itemsData is the cache)
```
Collection<ItemData> items = itemsData.asMap().values();    	
for (ItemData sd: items) { //loop the items
...
}
```
The new method is preferrable from performance or other aspect?
Thanks

**Comment by ben-manes** [comment]
No, your current code is preferable since it doesn’t perform a redundant lookup or suffer from race conditions.

**Comment by Amosss** [comment]
ok, thanks a lot!
