### ISSUE TITLE
How do I invalidate entries in an AsyncLoadingCache?

### ISSUE THREAD

**Issue by lwshuo** [ben-manes/caffeine#422]
There is an invalidate() method in the Cache interface, but AsyncCache doesn't seem to have it, is it on purpose?

**Comment by ben-manes** [comment]
It is a little subtle, but the intent is to use one of the views. The API provides 

```java
// Invalidate using the cache method, non-blocking as void response
asyncCache.synchonous().invalidate(key);

// Invalidate using the map method, non-blocking as void future
var future = asyncCache.asMap().remove(key);

// Invalidate using the map method, blocking as it joins the future for the value
var value = asyncCache.synchronous().asMap().remove(key);
```

Of course rarely would one use the 3rd case, as that naturally falls out due to the `Cache` having a map view also.
