### ISSUE TITLE
Can I save the content of caffeine to a file and later restore it from there?

### ISSUE THREAD

**Issue by ksilz** [ben-manes/caffeine#424]
Hi,

Thank you for caffeine! I use it in a Spring Boot application to cache results of API calls that I need to pay for. One way of saving money is to save the content of caffeine to a file and later restore it from there. Is that possible conveniently? If not, then I could go through all entries and save them myself instead.

**Comment by ben-manes** [comment]
We only provide the in-memory cache, but you could certainly integrate with a file-based cache. For example [mapdb](https://github.com/jankotek/mapdb) was popular, maybe there are other good options too. Some offer in-memory caches as well, though at lower hit rates and throughput than our own.

You can use a `CacheWriter` if you want a victim cache only (evict to file), or store it as part of your cache loader, or persist a snapshot using the `asMap()` view to iterate. The integration style is your choice and we should expose enough to not block you.

**Comment by ksilz** [comment]
Thank you for the recommendation! I'll give mapdb a shot because it seems to fulfill my requirements.
