### ISSUE TITLE
Unbounded queue of threads waiting for CacheLoader

### ISSUE THREAD

**Issue by izrobin** [ben-manes/caffeine#425]
Hey!
We've seen some interesting behaviour of the caffeine cache in our production systems.
We have one very request heavy application, in which we use caffeine to store some resources usually loaded from yet another service.

We've noticed that when our CacheLoader (the actual service-to-service call to fetch these resources) takes a bit longer to complete, the other threads waiting for the same cache key hangs. This will put any threads requesting the same key in a waiting queue, which is unbounded and indefinite.

Putting a reasonable timeout on the action in your CacheLoader only partly solves the issue. Let me give you an example:

You get a blip of 10 requests to your web application. This means 10 threads, and all of these threads requires the same entry from the cache.
The first thread will invoke the CacheLoader, and try to fetch the value. Let's say you have a set timeout of your CacheLoader action of 1s. Let's also say you fail to get the value within 1s, so your code will probably throw an exception. This first thread now lets go of the synchronization, and exits.
So what does the other 9 threads do here? Well, the next thread in line will try and do the same thing. It'll also invoke the CacheLoader to try and resolve your value. Let's say that also fails. Now you have 8 threads (and subsequently requests) that have waited 2 full seconds. This can really build up! If all 8 threads will fail to resolve the cache value, the last thread will have been blocked a whole 10 seconds.
All of this, whilst you're still accepting connections to your service. This can really make you run out of threads fast!

My proposal is to introduce some kind of bulkhead (Setting a max nr of allowed threads to wait for a CacheLoader), or a max wait duration for new threads who also requires the same cache key.
We solved our issue by wrapping the `cache.get()` call in a resilience4j bulkhead operation, but it feels a bit weird to do it at that place.

**Comment by ben-manes** [comment]
The synchronization is controlled by `ConcurrentHashMap` and its compute methods. This is built on `synchronize`, which doesn't offer that type of control of limits.

Another approach is to use `AsyncCache`, which stores a `CompletableFuture<V>` as the underlying map's value. This supports operations like `copy()` and `timeout(duration)`, letting you perform a long-running computation that is decoupled from your request's which can cancel early. It also means multiple requests will share the same in-flight future, which avoids the queuing problem. A copy + timeout ensures that you don't accidentally cancel the in-flight future and only the request's.

I think that approach is likely preferrable to your bulkhead workaround. What do you think?

**Comment by izrobin** [comment]
Hmm interesting thought. But setting a low timeout on the `CompletableFuture<>` would still build up right? Probably not as fast, but if you'd let all threads wait 1s on the `CompletableFuture<>`, you'd have `nr of waiting threads == nr of total requests per sec`

**Comment by ben-manes** [comment]
You would have one request to the external service, and N requests against that in-flight future. When the request times out it is an early exit for that caller only. A subsequent call might be served in time when the future completes. The copy decouples the user-facing request from the cache load operation, letting them have different lifecycle requirements.

Like you said, your first N requests would timeout if they came at once. But they wouldn’t block each other or suffer the sequential timeout problem you observed.

**Comment by ben-manes** [comment]
I don’t think there is any changes needed here, so closing for now.
