### ISSUE TITLE
[Feature Request] provide additional validity check in get()

### ISSUE THREAD

**Issue by martinariehm** [ben-manes/caffeine#426]
Sometimes the validity check of an entry can only be done during access. That's for example the case if you need to compare a timestamp read from the database with one stored in the entry.

Right now this needs to be written like this:

```java
Entry entry=cache.getIfPresent(key);
if (entry==null || entry.changed.isBefore(changed)) {
  cache.put(nr,entry=generateEntry(nr, changed));
}
return entry;
```

It would be useful to be able to write this like

```java
return cache.get(key, entry->!entry.changed.isBefore(changed), 
  nr->generateEntry(nr, changed));
```

So there should be another `get` method with an additional parameter Predicate<Entry> that an existing entry is checked against and discarded if the predicate returns false.

**Comment by ben-manes** [comment]
The asMap view offers compute methods which can serve this purpose. However it is atomic, so that incurs entry locking.

You can use a custom Expiry to have a per entry duration which often a match for your case.

If neither of those work, your sample code isn’t that bad for an uncommonly needed behavior. It seems less confusing to read than multiple lambdas which is unclear at the call site until reading the method’s javadoc.

**Comment by martinariehm** [comment]
As far as I can see, neither of those work for my use case, since (a) only one key is accessed and (b) the expiry parameters are not know at time of entry creation.

But you are right, the code block that is replaced by the suggestion isn't that difficult and might not be harder than the replacement. I was just afraid that it might have concurrency issues that a standardized version might not have. :-)

**Comment by ben-manes** [comment]
Expiry does let you set the lifetime on create, update, and read. However it returns the value after evaluating, so its not a filter but rather updates when the entry will expire.

A compute would work, though?

```java
cache.compute(key, (k, v) -> {
  return isValid(v) ? v : load(k);
});

**Comment by martinariehm** [comment]
Yes, that works, thanks! isValid needs to be null-safe in that case, in my suggestion it would only be called when the key is present. 

But really, the difference is so small that I also don't see a strong need for the feature.

Thanks for you help!
