### ISSUE TITLE
 Memory leak！！！

### ISSUE THREAD

**Issue by charmby** [ben-manes/caffeine#429]
hi，I use Caffeine as my cache, as follows:
```
primarySyncCache = Caffeine.newBuilder()
                .expireAfterWrite(10, TimeUnit.MINUTES)
                .refreshAfterWrite(1, TimeUnit.MINUTES)
                .initialCapacity(500000)
                .maximumSize(8000000)
                .recordStats()
                .executor(ThreadPoolUtils.DATA_THREAD_POOL)
                .build(
                        new CacheLoader<String, Map<String, String>>() {
                            @Nullable
                            @Override
                            public Map<String, String> load(@NonNull String key) throws Exception {
                                log.debug("<<<<<load key={} from redis", key);
                                return buildCache(key);
                            }

                            @Override
                            public @NonNull Map<String, Map<String, String>> loadAll(@NonNull Iterable<? extends String> keys) throws Exception {
                                log.debug("<<<<<loadAll key={} from redis", keys);
                                return RedisClusterClient.jedisClusterPipeline.getBatchHashData(Lists.newArrayList(Lists.newArrayList(keys)));
                            }

                            @Override
                            public @NonNull CompletableFuture<Map<String, String>> asyncLoad(@NonNull String key, @NonNull Executor executor) {
                                log.debug("<<<<<asyncLoad key={} from redis", key);
                                return asyncBuildCache(key, executor);
                            }

                            @Override
                            public @NonNull CompletableFuture<Map<String, Map<String, String>>> asyncLoadAll(@NonNull Iterable<? extends String> keys, @NonNull Executor executor) {
                                log.debug("<<<<<asyncLoadAll key={} from redis", keys);
                                return asyncBuildCacheBatch(keys, executor);
                            }

                            @Nullable
                            @Override
                            public Map<String, String> reload(@NonNull String key, @NonNull Map<String, String> oldValue) throws Exception {
                                log.debug("<<<<<reload key={} from redis", key);
                                return load(key);
                            }

                            @Override
                            public @NonNull CompletableFuture<Map<String, String>> asyncReload(@NonNull String key, @NonNull Map<String, String> oldValue, @NonNull Executor executor) {
                                log.debug("<<<<<asyncReload key={} from redis", key);
                                return asyncBuildCache(key, executor);
                            }
                        }
                );
```

A memory leak occurred after running online for one day，I dumped the heap and analyzed it with the tool MemoryAnalyzer.As follow:
![image](https://user-images.githubusercontent.com/6927947/85203505-d3bed800-b340-11ea-9ccc-42ef0bcaa3d2.png)

com.github.benmanes.caffeine.cache.PSWRMS takes up a lot of space, my jvm old generation is full
![image](https://user-images.githubusercontent.com/6927947/85203537-0cf74800-b341-11ea-97cf-4778ed6334ba.png)

I stopped online request traffic, but the cache was not cleared, even after half an hour. This is my memory status:
![image](https://user-images.githubusercontent.com/6927947/85203703-1208c700-b342-11ea-9374-767ec8aa254a.png)

![image](https://user-images.githubusercontent.com/6927947/85203720-28168780-b342-11ea-99bd-bf33c2bc700a.png)

**Comment by ben-manes** [comment]
The number of objects is 2.5M where the cache maximum size is 8M.

If you want proactive expiration, e.g. a scheduling thread rather than piggybacking on other cache operations, you can set Caffeine.scheduler.

It looks like you may have oversized the cache but it is within the bounds of the configuration.

**Comment by ben-manes** [comment]
You might also consider using a weighted cache since your value is an unbounded Map. A Weigher that counts the number of map entries would limit that growth.

**Comment by charmby** [comment]
Thank you very much for your reply. Thanks so much.
There are 23 servers deployed on my cluster online, and several of them have problems. I have set the past time, and the memory has not been released. I removed the online traffic of these  problem's servers, which means that the cache key will not be used again. 8 hours later, the memory is still full. Is it the way I use it wrong? Why doesn't it expire automatically?
```
 .expireAfterWrite(10, TimeUnit.MINUTES)
                .refreshAfterWrite(1, TimeUnit.MINUTES)
```

**Comment by ben-manes** [comment]
By default removal of expired entries is performed as a side effect of other cache operations. For example after a write or an accumulation of reads. This triggers a maintenance cycle which applies them to the eviction policy and discards expired entries. When you halt all operations on the cache then this clean up is not performed.

The scheduler option specified a thread that performs the cleanup based on the next expiration time. This is useful when the cache has low activity or you require a timely expiration, e.g. for a removal listener. This scheduler thread is then able to invoke the cache without requiring other application access.

**Comment by ben-manes** [comment]
> Expiration is performed with periodic maintenance during writes and occasionally during reads. Scheduling and firing of an expiration event is executed in amortized O(1) time.
>
>For prompt expiration, rather than relying on other cache activity to trigger routine maintenance, use the Scheduler interface and the Caffeine.scheduler(Scheduler) method to specify a scheduling thread in your cache builder. Java 9+ users may prefer using Scheduler.systemScheduler() to leverage the dedicated, system-wide scheduling thread.

**Comment by charmby** [comment]
> > Expiration is performed with periodic maintenance during writes and occasionally during reads. Scheduling and firing of an expiration event is executed in amortized O(1) time.
> > For prompt expiration, rather than relying on other cache activity to trigger routine maintenance, use the Scheduler interface and the Caffeine.scheduler(Scheduler) method to specify a scheduling thread in your cache builder. Java 9+ users may prefer using Scheduler.systemScheduler() to leverage the dedicated, system-wide scheduling thread.



-----
Thank you, you are the best author I have been to on github, and solve problems very fast.
I give it a try.
I used guava before, and the cache holding size is much larger than this without problems. Under the same memory usage, can Caffeine hold fewer records?

**Comment by ben-manes** [comment]
For 2.5M instances, the class itself takes up 120mb. However the retained heap size, which includes the overhead of the key and value, consumes 8.75gb. This means even if Guava had no overhead, you are only seeing a reduction of 120mb.

A simple calculation is 8.75gb / 2.5M instances, which means you average entry size is 3.5kb. At a maximum size (number of entries) of 8M, then you would need 28gb dedicated to the cache. This indicates that your data volume grew beyond your original estimates.

The maximumSize setting only takes into account the number of entries in the cache. It does not discern how much memory the entry consumes. A cache weigher lets you calculate an estimate, so that one entry consumes N units of capacity. For example,

```java
Caffeine.newBuilder()
    .maximumWeight(100)
    .weigher((key, map) -> Math.max(1, map.size())
```

This setting says that every entry consumes at least one unit of capacity (if an empty map) or map.size() units, with a maximum total of 100 units. If the value is small, e.g. 5 entries, then it consumes 5 units. If the value is very large, e.g. 500 units, then it will be immediately discarded as not cachable. If it is somewhat large, e.g. 50 units, then it may force multiple entries to be evicted to free up enough space. The logical concept of you unit is left to you to discern, e.g. some can estimate a byte size while others cannot.

**Comment by charmby** [comment]
In order to recover expired keys in time, I carefully read the documentation and unit tests related to Caffeine.scheduler.
```
https://github.com/ben-manes/caffeine/blob/78fdc65b0bfaf0ed29f1a94629e161323351f6fe/caffeine/src/main/java/com/github/benmanes/caffeine/cache/Scheduler.java
https://github.com/ben-manes/caffeine/blob/53f81d74743275d9d4b37fe99bcae5afc0062574/caffeine/src/test/java/com/github/benmanes/caffeine/cache/PacerTest.java
https://github.com/ben-manes/caffeine/blob/786acf59dd4587fdfd8fdee408e06b8c298153a7/caffeine/src/test/java/com/github/benmanes/caffeine/cache/CaffeineTest.java
```
but I did not find a related demo. How can I start a background thread so that it can clean up expired keys in time? Can you help me? Thanks a lot

**Comment by charmby** [comment]
This is my implementation.
```
 Scheduler scheduler = Scheduler.systemScheduler();
            scheduler.schedule(DATA_THREAD_POOL,  () -> primarySyncCache.cleanUp(), 10, TimeUnit.SECONDS);
            primarySyncCache = Caffeine.newBuilder()
                    .scheduler(scheduler)
```
but it does not take effect

**Comment by charmby** [comment]
or this???
```
            ScheduledExecutorService scheduledExecutorService = Executors.newScheduledThreadPool(3);
            scheduledExecutorService.schedule( () -> primarySyncCache.cleanUp(), 10, TimeUnit.SECONDS);
            Scheduler scheduler = Scheduler.forScheduledExecutorService(scheduledExecutorService);

            primarySyncCache = Caffeine.newBuilder()
                    .scheduler(scheduler)
```

**Comment by ben-manes** [comment]
Please note, the primary problem you are facing is due to you `maximumSize` setting. The prompt expiration wrt the scheduler is to explain why the cache does not shrink after you removed all activity. I would strongly recommend focusing on improving your capacity setting.

If you are on Java 9+ then you can use `Scheduler.systemScheduler()`. However if you are on Java 8 this will do nothing, as that JDK feature isn't available. Below is an example and the outputs.

```java
import java.time.Duration;
import java.time.LocalTime;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

import com.github.benmanes.caffeine.cache.Cache;
import com.github.benmanes.caffeine.cache.Caffeine;
import com.github.benmanes.caffeine.cache.Scheduler;

public class SchedulerExample {

  public static void main(String[] args) throws InterruptedException {
    ScheduledExecutorService executor = Executors.newSingleThreadScheduledExecutor();
    Scheduler scheduler;
    scheduler = Scheduler.forScheduledExecutorService(executor);
    // or...
    scheduler = Scheduler.systemScheduler();

    LocalTime startTime = LocalTime.now();
    Cache<Integer, Integer> cache = Caffeine.newBuilder()
        .expireAfterWrite(1, TimeUnit.SECONDS)
        .scheduler(scheduler)
        .removalListener((key, value, cause) -> {
          System.out.printf("%s: key %s after %,dms%n", cause, key,
              Duration.between(startTime, LocalTime.now()).toMillis());
        }).build();
    for (int i = 0; i < 3; i++) {
      cache.put(i, i);
    }
    System.out.printf("Sleeping... %d entries%n", cache.estimatedSize());
    TimeUnit.SECONDS.sleep(2);
    executor.shutdown();
    System.out.printf("Done... %d entries%n", cache.estimatedSize());
  }
}
```

In Java 8 with `systemScheduler` (unsupported, so defaults to disabled):
```
Sleeping... 3 entries
Done... 3 entries
```

Java 8+ using a `ScheduledExecutorService`:
```
Sleeping... 3 entries
EXPIRED: key 2 after 1,155ms
EXPIRED: key 1 after 1,155ms
EXPIRED: key 0 after 1,155ms
Done... 0 entries
```

Java 9+ using `systemScheduler`:
```
Sleeping... 3 entries
EXPIRED: key 2 after 1,153ms
EXPIRED: key 0 after 1,153ms
EXPIRED: key 1 after 1,153ms
Done... 0 entries
```

**Comment by charmby** [comment]
I understand finally，Thank you very much！！！
