### ISSUE TITLE
Last access to an item without affecting access timer

### ISSUE THREAD

**Issue by Amosss** [ben-manes/caffeine#438]
Hi

Is it possible to know when an item in the cache was last accessed?
If so, how can this be done without resetting the access timer of that item?
Thanks

**Comment by ben-manes** [comment]
`cache.policy()` contains these types of methods. The access time is retained by expireAfterAccess if that is enabled, and getIfPresentQuietly will obtain an entry without updating the policy.

Does that help?

**Comment by Amosss** [comment]
Thanks, I might be missing something but I didn't find a method in .policy() that shows when an item was last accessed.

**Comment by ben-manes** [comment]
expiresAfterAccess [ageOf()](https://www.javadoc.io/doc/com.github.ben-manes.caffeine/caffeine/latest/index.html) would provide that. We only retain the timestamp if expiration is enabled, otherwise you’d need to capture it.

**Comment by Amosss** [comment]
I don't see any ageOf() for .policy().expiresAfterAccess()
![image](https://user-images.githubusercontent.com/17168621/87660308-854a0100-c767-11ea-82a3-7d1b0dbedf01.png)

**Comment by ben-manes** [comment]
It’s an optional because the feature might not be enabled, so you have to unwrap it first.

**Comment by Amosss** [comment]
Sorry for being slow here but nothing I do brings up ageOf(...)
```
Optional<Expiration<String, ItemData>> afterAccess = itemsData.policy().expireAfterAccess();
Optional<Duration> item = afterAccess.

```

**Comment by ben-manes** [comment]
Something like,
```
var policy= itemsData.policy().expireAfterAccess().get();
var age = policy.ageOf(key).orElse(null):

**Comment by Amosss** [comment]
Silly me, forgot the get()... 
Thanks

**Comment by Amosss** [comment]
Just want to make sure
policy.ageOf(key)
does not reset the access timer, right?

**Comment by ben-manes** [comment]
Nope, it just reads the metadata
