### ISSUE TITLE
CaffeineCacheMetrics.putCount() returns incorrect value

### ISSUE THREAD

**Issue by DanielYWoo** [ben-manes/caffeine#440]
In CaffeineCacheMetrics, the counter for put(...) is loadCount(). But the loadCount works with get(key, mappingFunc) 
, it seems not working with put(...)
```
    @Override
    protected long putCount() {
        return cache.stats().loadCount();
    }
```
I did not see any call to cache().statsCounter().recordPutSuccess() or recordLoadSuccess() in put(...)

Guess I misunderstood something? Shall we have a recordPutSuccess() and a putCount() method in CaffeineCacheMetrics?

**Comment by ben-manes** [comment]
`CaffeineCacheMetrics` is from Micrometer, so you'll have to open a bug on their side. We don't actually capture that metric and generally shouldn't be useful (as ideally one should load via the cache to avoid races). If additional metrics are desired beyond the ones we capture then that has to be done client-side. I don't know why they decided it was useful, but did the same with Guava.

**Comment by DanielYWoo** [comment]
Thanks, and I will check it with micrometer guys.

**Comment by DanielYWoo** [comment]
BTW, which time zone are you in? Why can you always respond and help so quickly?

**Comment by ben-manes** [comment]
PST and insomnia :)
