### ISSUE TITLE
Events out of order when expiring objects / Add support for soft-expiry behaviour

### ISSUE THREAD

**Issue by argibbs** [ben-manes/caffeine#443]
When using the cache, I noticed some behaviour around removalListener callbacks that was not what I expected. I can guess / understand _why_ it's the way it is, but I thought I'd raise it if only so you can update the docs if you don't want to change anything.

## Brief summary

If I have expire on access set, and I query the cache for a key that's very recently expired, the cache will expire the existing value and create a new one. However, it will call the cache loader to create the new object _before_ it fires the removal listener.

The behaviour I would expect is that the removal listener would fire _before_ the cache loader. However, the opposite is true.

I've tested this on Caffeine 2.8.5 and Java versions 8 & 14.

## Example code

Code (n.b. uses guava DirectExecutor to guarantee behaviour):
```java
import java.time.Duration;
import java.time.LocalTime;
import java.util.ArrayList;

import com.github.benmanes.caffeine.cache.Caffeine;
import com.github.benmanes.caffeine.cache.LoadingCache;
import com.google.common.util.concurrent.MoreExecutors;

public class DemoCaffeineExpiryBehaviour {

    public static void main(String[] args) throws InterruptedException {

        ArrayList<String> eventLog = new ArrayList<>();

        LoadingCache<String, Integer> cache = Caffeine.newBuilder()
                .expireAfterAccess(Duration.ofMinutes(1))
                .executor(MoreExecutors.directExecutor())
                .removalListener((key, value, cause) -> eventLog.add(String.format("%s [%s] - Key %s removed due to %s",
                                LocalTime.now(), Thread.currentThread(), key, cause)))
                .build((key) -> {
                    eventLog.add(String.format("%s [%s] - Key %s added", LocalTime.now(), Thread.currentThread(), key));
                    return key.length();
                });

        System.out.println(LocalTime.now() + " - Seeding cache");
        cache.get("abc");
        cache.get("def");

        System.out.println(LocalTime.now() + " - Sleeping for 61 secs");
        Thread.sleep(61_000);

        System.out.println(LocalTime.now() + " - Polling cache again");
        // querying for "abc" will trigger a recreate of "abc" as it's just expired
        cache.get("abc");

        System.out.println(LocalTime.now() + " - Contents of event list");
        for (int i = 0; i < eventLog.size(); ++i) {
            System.out.println((i+1) + ":\t" + eventLog.get(i));
        }
    }
}
```

Output:
```
08:56:38.104 - Seeding cache
08:56:38.117 - Sleeping for 61 secs
08:57:39.119 - Polling cache again
08:57:39.124 - Contents of event list
1:	08:56:38.110 [Thread[main,5,main]] - Key abc added
2:	08:56:38.117 [Thread[main,5,main]] - Key def added
3:	08:57:39.121 [Thread[main,5,main]] - Key abc added
4:	08:57:39.122 [Thread[main,5,main]] - Key abc removed due to EXPIRED
5:	08:57:39.124 [Thread[main,5,main]] - Key def removed due to EXPIRED
```

## Additional comments

1. This was primarily a problem for me because I was using the cache to help maintain a list of "subscription" objects. When the cache created an object, a subscription was created, and when the cache removed an object, I unsubscribed. The behaviour above created bug - occasionally I'd request an object just after it expired, and the event ordering meant I repeated the subscription, then unsubscribed. Obviously I can work around this (and have done so), but the ordering was not what I expected. 
    - I'd suggest you either explicitly document that the removal listener will not be fired before the cache loader
    - Or change behaviour s.t. it's guaranteed to fire first.
2. While I've only tested this against expire on access, I assume expire on write would have the same problem.

## Related feature suggestion (soft-expiry behaviour)

If you look at my example code above, fetching from the cache just after expiration is triggering a check and subsequent expiration of the object. So what you're currently doing here is making a hard guarantee that nothing will stay in the cache longer than the expireAfterAccess limit.

This means your effective ordering is:
1. Evaluated the access times for all the keys
2. Expire anything old
3. Create the key requested by get.

An alternative (optional?) behaviour would be to refresh the access time on `get` _before_ evaluating candidates for expiration. This would mean that if an object is queried in the (potentially brief) window between expiration, and the next actual check for objects to evict that you do not end up evicting them.

In the use case I have above, this would mean that if one of my subscriptions had just expired, but the key had not yet been evicted, re-querying for the key would keep the subscription alive, rather than triggering an unsubscribe and immediate re-subscribe.

This is very much an edge case, and as always with this sort of thing - your library, your choice as to whether this is a thing you'd like to add.

## P.S.

Thanks for the library, it's very cool.

**Comment by ben-manes** [comment]
The RemovalListener is documented as asynchronous, so it occurs outside of the entry’s lock. That’s often the right choice, but as in your case not always desired.

We therefore have a synchronous approach, CacheWriter, which is invoked as part of the map compute methods. This is what you want to use.

In retrospect, I think borrowing the writer type from other caches was a mistaken api choice. We really only needed a synchronous eviction listener option, and any other case could be emulated using the asMap() view’s compute methods to expand explicit writes. Then the api would be lambda friendly, compatible with async cache, and feel less frameworky. Someday maybe we’ll deprecate to try to cleanup this overly complex concept.

**Comment by argibbs** [comment]
Blimey, thanks for the fast response. 

>it occurs outside of the entry’s lock  

Right, this totally explains it; by necessity you're going to have to fire the removal event after releasing the lock by which time you've processed the event.


Ahha, CacheWriter is a listener interface. Totally missed that previously.  
For reference, I changed my cache definition in the example above to
```java
        LoadingCache<String, Integer> cache = Caffeine.newBuilder()
                .expireAfterAccess(Duration.ofMinutes(1))
                .writer(new CacheWriter<String, Integer>() {

                    @Override
                    public void write(@NonNull String key, @NonNull Integer value) {
                        eventLog.add(String.format("%s [%s] - Key %s written", LocalTime.now(), Thread.currentThread(), key));
                    }

                    @Override
                    public void delete(@NonNull String key, @Nullable Integer value, @NonNull RemovalCause cause) {
                        eventLog.add(String.format("%s [%s] - Key %s removed due to %s", LocalTime.now(), Thread.currentThread(), key, cause));
                    }
                })
                .build(key -> {
                    eventLog.add(String.format("%s [%s] - Key %s loaded", LocalTime.now(), Thread.currentThread(), key));
                    return key.length();
                });
```

(note the lack of a direct executor, as it all still works even with an async executor). This does indeed fix the problem. N.B. for future generations, the `write` method is never called in my example, I just put it in for completeness.
