### ISSUE TITLE
Treemap/Submap range query

### ISSUE THREAD

**Issue by asad-awadia** [ben-manes/caffeine#444]
Hey @ben-manes ,

I am trying to get something like a TreeMap but with cache properties such as maximum size/time based eviction.

I am looking for a DS that allows for submaps like TreeMap and other efficient prefix scans but that is bounded in size

Any way I can use caffeine since it has half the pieces I need?

If not do you have any suggestions on how I can get a DS like this?

Thanks!

**Comment by ben-manes** [comment]
I'm not aware of any in-memory caching library that offers that. There are a few off-heap / on-disk that do, but features vary a lot.

For Caffeine, you could maintain a secondary mapping in a `ConcurrentSkipListMap` by ensuring all of the writes to the cache maintain this index. This can be done in a `CacheWriter` for puts/removes and a `CacheLoader`/`compute` for loads. You might want to use a `Scheduler` to promptly remove expired entries, and/or filter them out during you range scan. It certainly should all be possible, just requires a bit of care to ensure the desired behavior.

**Comment by asad-awadia** [comment]
I see. So 

1) have a class that has Caffeine and a ConcurrentSkipListMap
2) Every read and write to Caffeine also duplicates to the CSLM
3) When doing a range scan - delegate the scan to CSLM but check every return value to see if it is still in caffeine
3a) if it is in caffeine that means it hasn't been evicted - proceed as normal
3b) if it is not in caffeine that means it has been expired - do not return that value and also remove from the CSLM

Is that right?

**Comment by asad-awadia** [comment]
What would the scheduler logic look like if I go that route? I can add periodic triggers easily 

every X seconds reconcile the two DS? I would have to iterate and scan through all of caffeine?

**Comment by ben-manes** [comment]
I would probably have a range scan not call back into Caffeine, if possible, which is faster but loses any eviction policy updates. For example iterating over the cache entries doesn't count towards a policy's updates since that's rarely the intent.

The `scheduler` uses a background `ScheduledExecutorService` to trigger a `cache.cleanUp()` based on the next entry to expire, paced at 1s intervals between invocations. That means an entries that expire at time 1s, 1.5s, 1.7s, 2s, 4s will cause 1.5 and 1.7 to reside in the cache until time 2s, since the pacing tries to avoid thrashing. If you don't use a scheduler then its similar, except it is triggered by the activity on the cache. In both cases the cache will hide the entry as a miss if queried for, but your index won't be updated. You can either re-check in Caffeine or maintain a timestamp to validate against, the latter being cheaper of course.

```java
NavigableMap<K, V> index = new ConcurrentSkipListMap<>();
Cache<K, V> cache = Caffeine.newBuilder()
    .scheduler(Scheduler.systemScheduler())
    .expireAfterWrite(10, TimeUnit.MINUTES)
    .maximumSize(10_000)
    .writer(new CacheWriter<K, V>() {
        public void write(K key, V value) {
          index.put(key, value);
        }
        public void delete(K key, V value, RemovalCause cause) {
          index.remove(key, value);
        }
    })
    .build(key -> {
      var value = // load
      index.put(key, value)
      return value;
    });

// key lookup and load on miss
cache.get(key) or manual using cache.asMap() compute methods.

// range scan
var range = new TreeMap<>(index.subMap(high, low));
// validate range, e.g. check a timestamp
long now = System.currentTimeMillis();
range.values().removeIf(value -> value.expiresAt() <= now);

// explicit removal
cache.invalidate(key);

----

The CacheWriter will expand the internal `Map.compute` methods to invoke the write/delete method as part of the operation. This way the index is updated just prior to the cache's mapping being modified. It keeps the two in sync, but exposes that expiration is non-deterministic and there is no proper transaction to combine the two and just best effort.

**Comment by asad-awadia** [comment]
thank you for the code! that makes a lot of sense

what does the following piece mean?
```
  .build(key -> {
      var value = // load
      index.put(key, value)
      return value;
    });
```

**Comment by ben-manes** [comment]
If you use a LosdingCache it has the ability to load the value, so you can use get(key). Otherwise you have to provide the loader at the call site, get(key, mappingFunction). Whenever a value enters/exits the cache then the index must be updated in the same atomic action

**Comment by asad-awadia** [comment]
Thanks!
