### ISSUE TITLE
Unsafe Access to Volatile `accessTime` does not use `Unsafe.{get|put}LongVolatile`

### ISSUE THREAD

**Issue by jamesdbowman** [ben-manes/caffeine#446]
Hi,

My colleague @caoman has discovered that the generated code to get/put `accessTime` does not properly use the `Unsafe.{get|put}LongVolatile` methods.

Would it be possible to pass the volatility of a given field to `newGetter` and `newSetter` methods such that the proper `Unsafe.*Volatile` method could be used for interaction? E.g. [here](https://github.com/ben-manes/caffeine/blob/801e532935dd822aab75e9625a520df7b62bb0b0/caffeine/src/javaPoet/java/com/github/benmanes/caffeine/cache/node/AddExpiration.java#L117-L120) for `accessTime`?

Thanks in advance for your thoughts,
James

**Comment by ben-manes** [comment]
I think the expectation was that it would piggyback on other memory barriers, so strictly wasn't necessary. Was an issue observed?

**Comment by jamesdbowman** [comment]
[Java TSAN](https://wiki.openjdk.java.net/display/tsan/Main) found a (theoretical) data race between one thread calling `BoundedLocalCache.setAccessTime` and another thread (running the cleanup task) calling `BoundedLocalCache.expireAfterAccessEntries` (getting the `accessTime` value).

**Comment by ben-manes** [comment]
right, that makes sense. It is benign because if a stale read views it as expired, the call to `evictEntry` will validate within the computation. That read piggybacks on the lock's barrier to have a updated read and [resurrects](https://github.com/ben-manes/caffeine/blob/ecd5e13e1b8abe9796e0ec5c9ac30aa691f7d472/caffeine/src/main/java/com/github/benmanes/caffeine/cache/BoundedLocalCache.java#L913-L927) the entry.

**Comment by jamesdbowman** [comment]
Ok, thanks for the clarification Ben.

Then it does seem that the absence of `Unsafe.*Volatile` methods is unrelated, that such races are inherently built into the concurrency model of the library, and that running Java TSAN on this library will find false positives.

Closing for now, thanks for taking a look.

**Comment by caoman** [comment]
I not convinced this is benign. The bigger issue is the atomicity violation on a long variable. [JLS 17.7 Non-Atomic Treatment of double and long](https://docs.oracle.com/javase/specs/jls/se8/html/jls-17.html#jls-17.7) says "a single write to a non-volatile long or double value is treated as two separate writes", and "Writes and reads of volatile long and double values are always atomic." 

If it does not use `Unsafe.*Volatile`, the loads and stores to the `accessTime` are not atomic. Theoretically word tearing can happen, and load might return a half-stale value of the 64-bit long (i.e. only 32 bits of the 64 bits are stale).

This can be seen in JDK 8 x86's implementation of `Unsafe.setLong` and `Unsafe.setLongVolatile`:
- `Unsafe.setLong` is a [plain pointer dereference and store  (*p = v)](http://hg.openjdk.java.net/jdk8u/jdk8u/hotspot/file/0943ff57e154/src/share/vm/prims/unsafe.cpp#l174).
- `Unsafe.setLongVolatile` is [`OrderAccess::release_store_fence`](http://hg.openjdk.java.net/jdk8u/jdk8u/hotspot/file/0943ff57e154/src/share/vm/prims/unsafe.cpp#l185), which is implemented by [`xchgq`](http://hg.openjdk.java.net/jdk8u/jdk8u/hotspot/file/0943ff57e154/src/os_cpu/linux_x86/vm/orderAccess_linux_x86.inline.hpp#l176) or [`Atomic::store`](http://hg.openjdk.java.net/jdk8u/jdk8u/hotspot/file/0943ff57e154/src/os_cpu/linux_x86/vm/orderAccess_linux_x86.inline.hpp#l84).

**Comment by ben-manes** [comment]
yes, 32-bit JVMs may allow for word tearing. From a pragmatic perspective, this library would not be used on those types of environments (e.g. embedded devices) and 32-bit is almost absent in server-side environments. The timestamps are best effort, allowing for stampedes to gradually resolve the value.

I'm not against updating to use volatile, but when originally making that choice it had appeared to be a violation only actionable if trying to make the theoretical argument.

**Comment by caoman** [comment]
Word tearing can also happen on 64-bit system if the data is not aligned. Also, as the data race is now in C++ land, it is undefined behavior according the C++ spec. Good code should always program according to the language spec, but not to the JVM/compiler implementation details.

It is best to fix this with plain Java load and store on the `accessTime` variable. The use of `Unsafe` is discouraged in general and it's best to avoid it as much as possible.

**Comment by ben-manes** [comment]
Sure, but we lacked VarHandles at that time and j.u.c. had switched to direct usages of Unsafe and piggybacking on MHs for performance. I was following the style that Martin Buchholz applied, with a small liberty here due to the problem domain where this wouldn't cause an adverse effect. For 64-bit environments, the JVM's field alignment rules avoid the behavior. So while I am not against changing it, I disagree that the assumptions were wrong.

**Comment by jamesdbowman** [comment]
I'll reopen this issue and work on a PR to add an optional volatility argument to the getter and setter generators, if that's OK with everyone.

**Comment by ben-manes** [comment]
Closing due to lack of feedback. This would be done slightly differently in the v3 branch where we have replaced Unsafe with VarHandles. Thanks for the code and discussions, though.

@caoman please reopen if you have feedback and would like to revisit.
