### ISSUE TITLE
Allow the CaffeineCachingProvider to be used with OSGi DS

### ISSUE THREAD

**Issue by raducotescu** [ben-manes/caffeine#447]
Although the `jcache` module is an OSGi bundle, the `CaffeineCachingProvider` can only be used directly, by tying the consumer to the `com.github.benmanes.caffeine.jcache` implementation. If the `CaffeineCachingProvider` would be an OSGi `Component`, a consumer would only depend on the `javax.cache` API and the `CaffeineCachingProvider` would be an opaque implementation.

Ehcache has a similar approach for their JSR-107 implementation.

**Comment by ben-manes** [comment]
Released in 2.8.6
