### ISSUE TITLE
RemovalListener behaves incorrectly

### ISSUE THREAD

**Issue by CDFN** [ben-manes/caffeine#452]
With code: 
```kt
val userCache: AsyncLoadingCache<UUID, DropPlayer> = Caffeine.newBuilder()
        .expireAfterAccess(1, TimeUnit.MINUTES)
        .expireAfterWrite(2, TimeUnit.MINUTES)
        .removalListener { key: UUID?, value: DropPlayer?, _ ->
            println("Removed!")
        }
 ```

entry doesn't expire after 1 minute neither 2 minutes. It exists until it's manually removed by userCache.invalidate(key).

**Comment by ben-manes** [comment]
> Expiration is performed with periodic maintenance during writes and occasionally during reads. Scheduling and firing of an expiration event is executed in amortized O(1) time.
>
>For prompt expiration, rather than relying on other cache activity to trigger routine maintenance, use the Scheduler interface and the Caffeine.scheduler(Scheduler) method to specify a scheduling thread in your cache builder. Java 9+ users may prefer using Scheduler.systemScheduler() to leverage the dedicated, system-wide scheduling thread.

You can add `scheduler(Scheduler.systemScheduler())` and the cache will remove the entry and invoke the listener regardless of activity.
