### ISSUE TITLE
GET method Rest call is not returning any data even if POST call is done and data is stored in Caffeine cache

### ISSUE THREAD

**Issue by namangupta19** [ben-manes/caffeine#454]
I have the issue in which I am using Caffeine cache manager and trying to store the data in the caffeine it gets stored but when I will try to make a GET call from the browser then it returns null.
What could be the issue here ? 

NOTE : 
1) If I do Get operation right after PUT operation it returns data
2) If I make a Rest call for Get operation directly, it returns NULL

Config file 
@Configuration
public class CaffeineConfig {

    @Bean
    public CacheManager cacheManager(){
        System.out.println("Loading Cache Manager");
        CaffeineCacheManager cacheManager = new CaffeineCacheManager();
        cacheManager.setCaffeine(caffeineCacheBuilder());
        return cacheManager;
    }

    Caffeine<Object, Object> caffeineCacheBuilder() {
        System.out.println("Loading Cache Builder");
        return Caffeine.newBuilder()
                .initialCapacity(5)
                .maximumSize(5)
                .expireAfterAccess(10, TimeUnit.SECONDS)
                .weakKeys()
                .removalListener(new CustomRemovalListener())
                .recordStats();
    }

controller 
	@GetMapping("/student/{id}")
	public Student findStudentById(@PathVariable String id) {
		System.out.println("Searching by ID  : " + id);
		return studentService.getStudentByID(id);
	}

	@PostMapping("/student/{id}")
	public Student putStudentById(@PathVariable String id) {
		System.out.println("Put by ID  : " + id);
                // Get operation right after PUT operation it returns data
		return studentService.getStudentByID(id);
	}

Service File 
@Service
public class StudentService {
	@Cacheable("student")
	public Student getStudentByID(String id) {
		return null;
		
	}

	@CachePut("student")
	public Student putStudentByID(String id) {
		return new Student(id,"MockUser" ,"MockCity");
           }
}

**Comment by ben-manes** [comment]
Please remove `weakKeys` from your configuration. This uses reference equality (identity) so the exact same key instance must be used to look up with. Spring Cache generates a key each time so it will never match.

**Comment by namangupta19** [comment]
Okk, Thanks Ben...

**Comment by ben-manes** [comment]
Feel free to reopen if that didn't solve your problem. I closed only because of no reply for two days, but happy to help if you're still stuck.
