### ISSUE TITLE
use caffeine to report oom exception

### ISSUE THREAD

**Issue by ck-jesse** [ben-manes/caffeine#461]
ForkJoinPool$WorkQueue will occupy a lot of memory, resulting in oom.
The specific error message is as follows:

`One instance of "java.util.concurrent.ForkJoinPool" loaded by "<system class loader>" occupies 5,558,167,608 (92.67%) bytes. The instance is referenced by com.github.benmanes.caffeine.cache.SSMSW @ 0x65df18318 , loaded by "org.springframework.boot.loader.LaunchedURLClassLoader @ 0x659ff25e0". The memory is accumulated in one instance of "java.util.concurrent.ForkJoinPool$WorkQueue[]" loaded by "<system class loader>".

Keywords
java.util.concurrent.ForkJoinPool
java.util.concurrent.ForkJoinPool$WorkQueue[]
org.springframework.boot.loader.LaunchedURLClassLoader @ 0x659ff25e0`

**Comment by ck-jesse** [comment]
The maximumsize is limited to 10000. The specific configuration is as follows.

>  initialCapacity=256,maximumSize=10000,refreshAfterWrite=24h,recordStats

**Comment by ben-manes** [comment]
The maximumSize is the number of entries. If your entries are too large, then it will run out of memory. The best approach is to look at a heap dump (e.g. `-XX:+HeapDumpOnOutOfMemoryError`) and open it in a tool like JMC or YourKit.
