### ISSUE TITLE
Using stale content in refreshAfterWrite

### ISSUE THREAD

**Issue by royteeuwen** [ben-manes/caffeine#475]
I have browsed through the docs / java docs but it's not clear to me if it is possible. I want to use the refreshAfterWrite that it automatically refreshes the cache after one hour, but sometimes the 3rd party system where the content is fetched from throws an exception. Is it possible to keep using the stale content when an exception happens in the refresh function?

**Comment by ben-manes** [comment]
Yes, see the JavaDoc on CacheLoader.reload below. The exception won’t cause removal since the data can be served. An expiration would make it unusable, though.

```java
   * Computes or retrieves a replacement value corresponding to an already-cached {@code key}. If
   * the replacement value is not found then the mapping will be removed if {@code null} is
   * returned. This method is called when an existing cache entry is refreshed by
   * {@link Caffeine#refreshAfterWrite}, or through a call to {@link LoadingCache#refresh}.
   * <p>
   * <b>Note:</b> <i>all exceptions thrown by this method will be logged and then swallowed</i>.
