### ISSUE TITLE
Getting this error after an object is removed

### ISSUE THREAD

**Issue by iarepandemonium** [ben-manes/caffeine#477]
Caused by: java.lang.LinkageError: com/github/benmanes/caffeine/cache/RemovalCause
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.put(BoundedLocalCache.java:2029) ~[?:?]
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.put(BoundedLocalCache.java:1953) ~[?:?]
        at com.github.benmanes.caffeine.cache.LocalManualCache.put(LocalManualCache.java:130) ~[?:?]

This error occurs after 5 minutes.
        cache = Caffeine.newBuilder()
                .expireAfterAccess(5, TimeUnit.MINUTES)
                .maximumSize(10_000).build();

It happens when i try to put an object into the cache that is similiar or equal to most likely one that has expired.

**Comment by ben-manes** [comment]
`LinkageError` indicates a classloader problem, where the thread executing the work does not have access to that class.

By default, Caffeine delegates any work that can be async to ForkJoinPool.commonPool(). This can be overridden, e.g. to run on a calling thread you can use `Caffeine.executor(Runnable::run)`. Most likely the FJP thread does not have the same classloader and is unable to perform the work. Either the library needs to be available via some scaffolding on your side, or you should direct the execution elsewhere. This is one of those annoying issues commonly found in application servers, like Tomcat, which use classloaders to isolate and load/unload multiple independent applications. That docker-style container idea isn't super relevant anymore, but leads to these types of linkage problems.

Regardless, it's not an issue with this library directly. Someone on your team is probably the expert on this type of setup and can advise. That, or merely disable async execution and move on. 😄

**Comment by iarepandemonium** [comment]
@ben-manes Yea I realized I am loading it as compile 2 seconds after I made this.
