### ISSUE TITLE
Missing atomic operations?

### ISSUE THREAD

**Issue by danhyun** [ben-manes/caffeine#48]
First of all thanks for this awesome project.

I may just be approaching this wrong but I was wondering if there was anyway to get `computeIfAbsent` like behavior with `Cache`. I see the methods available in `LocalCache` but I can't seem to get to it. I would like to compute the value for the cache only once in a highly concurrent environment especially with expensive computations.

I could always put a guard on the cache object itself but I was hoping for something at the api level.

Thanks again!

**Comment by danhyun** [comment]
It looks as though we can get access to `ConcurrentHashMap` methods via `Cache#asMap`. Is this the way to go?

**Comment by ben-manes** [comment]
Ideally you would use `LoadingCache#get(key)`, which uses a `CacheLoader` to fetch the value if not present. This provides additional power and reduces the clutter in your code if you have multiple places where you lookup in the cache.

The `Cache#get(key, mappingFunction)` is the next best. This is the same as `computeIfAbsent` except domain oriented and guaranteed to be atomic.

Lastly `Cache#asMap` is an escape hatch, where the provided `computeIfAbsent` is atomic (the Map's contract doesn't require this!). The map lets you do things that would make less sense in the context of a cache (e.g. iterate over the keys), but trusts that users know why they need this without burdening the contextual API.

Do you have any suggestions for helping to clarify this? The [user guide](https://github.com/ben-manes/caffeine/wiki/Population) and [javadoc](http://www.javadoc.io/doc/com.github.ben-manes.caffeine/caffeine/2.1.0) try to nudge the user in the above preferences.

**Comment by danhyun** [comment]
No this is excellent, I knew I was missing something. Thanks again!
