### ISSUE TITLE
Cache sharing

### ISSUE THREAD

**Issue by wuyuejiang** [ben-manes/caffeine#483]
I want to know how to deal with cache sharing. I have inquired about all kinds of documents. I don't know how to deal with this because there is too little information. I don't know if you can provide ideas or examples here. Thank you

**Comment by ben-manes** [comment]
What do you mean by sharing?

The cache is a fancy `ConcurrentMap`. This means that a value may be read by multiple threads. This differs from an object pool which has an explicit acquire/release for exclusive access to the object. If you would like to mutate the value, e.g. use the cached version as a prototype, then a copy would be required in your code. Does any of that help?

**Comment by wuyuejiang** [comment]
I want to use this cache in combination with AOP

**Comment by wuyuejiang** [comment]
> 分享是什么意思？
> 
> 缓存是花哨的`ConcurrentMap`。这意味着一个值可以被多个线程读取。这不同于对象池，对象池具有显式获取/释放以独占访问对象的权限。如果您想更改该值，例如使用缓存的版本作为原型，那么在您的代码中将需要一个副本。有什么帮助吗？

I want to implement the combination of this cache and AOP, which will involve cache sharing

**Comment by ben-manes** [comment]
Are you using Spring? If so, then there are many tutorials on [Spring Cache](https://www.baeldung.com/spring-boot-caffeine-cache).

If you prefer [JCache (JSR107)](https://www.novatec-gmbh.de/en/blog/three-approaches-to-using-jcache-without-javaee-8/), there are AOP adapters. I am not a fan of the spec and personally avoid it.

You might consider Alibaba's [JetCache](https://github.com/alibaba/jetcache). I don't know much about it, but it sounds popular in China.

This library itself does not offer AOP directly, but is supported by those 3 frameworks which do.
