### ISSUE TITLE
Is there a way to invalidate the in-memory portion of the BoundedLocalCache without notifying a CacheWriter?

### ISSUE THREAD

**Issue by suchintan** [ben-manes/caffeine#484]
Let's say I have a relatively simple cache (In Kotlin):

```
val rawCache = Caffeine.newBuilder()
        .ticker { clock.nanoTime() }
        .applyIfNotNull(refreshAfter) { refreshAfterWrite(it) }
        .maximumSize(maximumSize)
        .applyIf(recordStats) { recordStats() }
        .executor(executorService)
        .apply {
          when (expireStrategy) {
            ExpiryStrategy.AFTER_ACCESS -> expireAfterAccess(expireAfter)
            ExpiryStrategy.AFTER_WRITE -> expireAfterWrite(expireAfter)
          }
        }
        .writer<K, V>(cacheWriter)
        .build(cacheLoader)
```

This cache is backed by a Redis instance. In this particular case, we load the cache by doing a `rawCache.put(key, value)` in on a separate node, expecting the `cacheWriter` to propagate those entries into our Redis instance.

Then, in other nodes, when the key is requested (ie `rawCache.get(key)`), it is fetched from Redis. The Redis TTL is set to be equal to `expireAfter`.

So basically goes like this:
```
Node A: cache.put(key, value)
Node B: cache.get(key) => returns value (by going to Redis), put it in memory
```

Now, let's say this sequence of event happens:
```
Node A: cache.put(key, value)
Node B: cache.get(key) => return value, put it in memory
Node A: cache.put(key, value2)
Node B: cache.get(key) => return value, from in memory even though the true value is now "value2"
```

I want to do this, but I couldn't figure out a great way to:
```
Node A: cache.put(key, value)
Node B: cache.get(key) => return value, put it in memory
Node A: cache.put(key, value2)
Node A tells Node B to: cache.invalidateInMemory(key)
Node B: cache.get(key) => return value, from in memory even though the true value is now "value2"
```
Reading through the code, it seems like all invalidate calls send an EvictionCause.EXPLICIT. Unfortunately, our CacheWriter reads that and removes that entry from Redis, which I don't want to happen here.

I could remove the current CacheWriter functionality and not evict on EXPLICIT evictions in this specific case. I was just wondering if there's another way to specifically nuke the in-memory cache directly or if that's the best way to go about this.

**Comment by ben-manes** [comment]
I am wondering if we should deprecate `CacheWriter`, add a synchronous `evictionListener(RemovalListener)` option, and remove it in v3? The concept was borrowed from other caching frameworks and I don't feel like it fits correctly. We mostly needed a `RemovalListener` that would be called atomically with eviction.

Instead we offer a lot of flexibility thanks to `asMap().compute` methods. It can be much more obvious by using those for your writes and deletes to include your custom logic. The only case being when an eviction occurs to intercept, which a minimal listener would allow. What do you think?

**Comment by suchintan** [comment]
I think I understand what you're saying.

I quite like `CacheWriter` -- it serves our use case well. It allows us to propagate put events to our distributed cache (in this case, Redis).
I also like your `evictionListener(RemovalListener)` approach -- it lets us decide on a per cache basis what to do with the eviction. 

I guess my question can really be drilled down to this: Is there a way of interacting directly with the in memory cache without replying events (via `evictionListener` or `CacheWriter` in the older versions of this library)?
For example:
RemovalCause.EXPLICIT -> this is a very useful thing if you want to remove an item from your cache, but this used to get propagated via `delete` in `CacheWriter`, and now via `evictionListener`
 
Specifically, you included this method signature:
```
  /**
   * See {@link Cache#put(Object, Object)}. This method differs by allowing the operation to not
   * notify the writer when an entry was inserted or updated.
   */
  @Nullable
  V put(@NonNull K key, @NonNull V value, boolean notifyWriter);
```
Does something similar exist for `invalidate`? Where we don't `notifyWriter` or notify the `evictionListener`

**Comment by ben-manes** [comment]
The external API tries to avoid "death by a thousand cuts" by having every special case option, even though the internals might need to bypass. When we do want to externalize those, we often stash them into `Cache.policy()` under an `Optional` to conditionalize support.

The alternative of using `compute` methods might be more obvious. Would this fit what you are trying to do?

```java
public void put(K key, V value) {
  cache.asMap().compute(key, (k, v) -> {
    redis.put(key, value);
    return value;
  });
}

public void delete(K key) {
  cache.asMap().computeIfPresent(key, (k, v) {
    redis.delete(key);
    return null;
  };
}

public void deleteLocally(K key) {
  cache.invalidate(key);
}
```

**Comment by suchintan** [comment]
Yep, that's along the lines of what I was thinking. I'll just suppress the deletes in the CacheWriter for my specific case, effectively accomplishing the same thing. Thanks!
