### ISSUE TITLE
 Failed to instantiate [org.springframework.cache.caffeine.CaffeineCacheManager] because of StackOverflowError

### ISSUE THREAD

**Issue by Vod9nou** [ben-manes/caffeine#491]
Hi!

Could you help to solve this problem?
It's a float bug(reproduced from time to time).

<caffeine.version>2.7.0</caffeine.version>

`import org.springframework.boot.autoconfigure.cache.CacheProperties;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.cache.caffeine.CaffeineCacheManager;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
@EnableConfigurationProperties(CacheProperties.class)
public class CaffeineCacheConfig {

  @Bean
  public CaffeineCacheManager caffeineCacheManager(CacheProperties cacheConfiguration) {
    CaffeineCacheManager cacheManager = new CaffeineCacheManager("caffeine_operation_cache",
        "caffeine_report_cache", "caffeine_single_operation_cache", "caffeine_single_task_cache",
            "caffeine_execution", "caffeine_workflow_by_names", "caffeine_workflow");
    cacheManager.setAllowNullValues(false);
    cacheManager.setCacheSpecification(cacheConfiguration.getCaffeine().getSpec());
    return cacheManager;
  }
}`

`  spring:
   cache:
      caffeine:
         spec: "maximumSize=${CAFFEINE_CACHE_SIZE:150},recordStats,expireAfterWrite=${CAFFEINE_CACHE_VALUE_LIFETIME:1}s"`

`Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cache.caffeine.CaffeineCacheManager]: Factory method 'caffeineCacheManager' threw exception; nested exception is java.lang.IllegalStateException: com.github.benmanes.caffeine.cache.SSSMSW
--
  | at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
  | at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
  | ... 27 common frames omitted
  | Caused by: java.lang.IllegalStateException: com.github.benmanes.caffeine.cache.SSSMSW
  | at com.github.benmanes.caffeine.cache.LocalCacheFactory.newBoundedLocalCache(LocalCacheFactory.java:101) ~[caffeine-2.7.0.jar!/:na]
  | at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:3341) ~[caffeine-2.7.0.jar!/:na]
  | at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:3337) ~[caffeine-2.7.0.jar!/:na]
  | at com.github.benmanes.caffeine.cache.Caffeine.build(Caffeine.java:936) ~[caffeine-2.7.0.jar!/:na]
  | at org.springframework.cache.caffeine.CaffeineCacheManager.createNativeCaffeineCache(CaffeineCacheManager.java:205) ~[spring-context-support-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
  | at org.springframework.cache.caffeine.CaffeineCacheManager.createCaffeineCache(CaffeineCacheManager.java:192) ~[spring-context-support-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
  | at org.springframework.cache.caffeine.CaffeineCacheManager.refreshKnownCaches(CaffeineCacheManager.java:221) ~[spring-context-support-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
  | at org.springframework.cache.caffeine.CaffeineCacheManager.doSetCaffeine(CaffeineCacheManager.java:212) ~[spring-context-support-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
  | at org.springframework.cache.caffeine.CaffeineCacheManager.setCacheSpecification(CaffeineCacheManager.java:135) ~[spring-context-support-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
  | at com.netcracker.mano.gateway.configuration.CaffeineCacheConfig.caffeineCacheManager(CaffeineCacheConfig.java:19) ~[classes!/:11.0.1]
  | at com.netcracker.mano.gateway.configuration.CaffeineCacheConfig$$EnhancerBySpringCGLIB$$6761fbeb.CGLIB$caffeineCacheManager$0(<generated>) ~[classes!/:11.0.1]
  | at com.netcracker.mano.gateway.configuration.CaffeineCacheConfig$$EnhancerBySpringCGLIB$$6761fbeb$$FastClassBySpringCGLIB$$515edd07.invoke(<generated>) ~[classes!/:11.0.1]
  | at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
  | at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
  | at com.netcracker.mano.gateway.configuration.CaffeineCacheConfig$$EnhancerBySpringCGLIB$$6761fbeb.caffeineCacheManager(<generated>) ~[classes!/:11.0.1]
  | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
  | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
  | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
  | at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
  | at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
  | ... 28 common frames omitted
  | Caused by: java.lang.reflect.InvocationTargetException: null
  | at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
  | at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:na]
  | at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
  | at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[na:na]
  | at com.github.benmanes.caffeine.cache.LocalCacheFactory.newBoundedLocalCache(LocalCacheFactory.java:98) ~[caffeine-2.7.0.jar!/:na]
  | ... 47 common frames omitted
  | Caused by: java.lang.StackOverflowError: null
  | at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[na:na]
  | at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[na:na]
  | at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[na:na]
  | at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550) ~[na:na]
  | at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458) ~[na:na]
  | at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452) ~[na:na]
  | at java.base/java.security.AccessController.doPrivileged(Native Method) ~[na:na]
  | at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451) ~[na:na]
  | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[na:na]
  | at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92) ~[app.jar:11.0.1]
  | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
  | at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[na:na]
  | at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[na:na]
  | at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[na:na]
  | at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550) ~[na:na]
  | at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458) ~[na:na]
  | at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452) ~[na:na]
  | at java.base/java.security.AccessController.doPrivileged(Native Method) ~[na:na]
  | at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451) ~[na:na]
  | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[na:na]
  | at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92) ~[app.jar:11.0.1]
  | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
  | at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[na:na]
  | at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[na:na]
  | at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[na:na]
  | at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550) ~[na:na]
  | at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458) ~[na:na]
  | at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452) ~[na:na]
  | at java.base/java.security.AccessController.doPrivileged(Native Method) ~[na:na]
  | at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451) ~[na:na]
  | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[na:na]
  | at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92) ~[app.jar:11.0.1]
  | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
  | at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[na:na]
  | at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[na:na]
  | at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[na:na]
  | at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550) ~[na:na]
  | at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458) ~[na:na]
  | at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452) ~[na:na]
  | at java.base/java.security.AccessController.doPrivileged(Native Method) ~[na:na]
  | at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451) ~[na:na]
  | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[na:na]
  | at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92) ~[app.jar:11.0.1]
  | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
  | at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[na:na]
  | at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[na:na]
  | at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[na:na]
  | at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550) ~[na:na]
  | at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458) ~[na:na]
  | at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452) ~[na:na]
  | at java.base/java.security.AccessController.doPrivileged(Native Method) ~[na:na]
  | at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451) ~[na:na]
  | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[na:na]
  | at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92) ~[app.jar:11.0.1]
  | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
  | at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[na:na]
  | at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[na:na]
  | at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[na:na]
  | at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550) ~[na:na]
  | at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458) ~[na:na]
  | at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452) ~[na:na]
  | at java.base/java.security.AccessController.doPrivileged(Native Method) ~[na:na]
  | at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451) ~[na:na]
  | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[na:na]
  | at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92) ~[app.jar:11.0.1]
  | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
  | at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[na:na]
  | at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[na:na]
  | at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[na:na]
  | at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550) ~[na:na]
  | at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458) ~[na:na]
  | at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452) ~[na:na]
  | at java.base/java.security.AccessController.doPrivileged(Native Method) ~[na:na]
  | at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451) ~[na:na]
  | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[na:na]
  | at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92) ~[app.jar:11.0.1]
  | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
  | at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[na:na]
  | at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[na:na]
  | at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[na:na]
  | at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550) ~[na:na]
  | at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458) ~[na:na]
  | at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452) ~[na:na]
  | at java.base/java.security.AccessController.doPrivileged(Native Method) ~[na:na]
  | at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451) ~[na:na]
  | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[na:na]
  | at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92) ~[app.jar:11.0.1]
  | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
  | at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[na:na]
  | at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[na:na]
  | at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[na:na]
  | at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550) ~[na:na]
  | at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458) ~[na:na]
  | at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452) ~[na:na]
  | at java.base/java.security.AccessController.doPrivileged(Native Method) ~[na:na]
  | at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451) ~[na:na]
  | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[na:na]
  | at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92) ~[app.jar:11.0.1]
  | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
  | at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[na:na]
  | at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[na:na]
  | at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[na:na]
  | at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550) ~[na:na]
  | at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458) ~[na:na]
  | at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452) ~[na:na]
  | at java.base/java.security.AccessController.doPrivileged(Native Method) ~[na:na]
  | at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451) ~[na:na]
  | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[na:na]
  | at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92) ~[app.jar:11.0.1]
  | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
  | at com.github.benmanes.caffeine.cache.SSSMS.<init>(SSSMS.java:78) ~[caffeine-2.7.0.jar!/:na]
  | at com.github.benmanes.caffeine.cache.SSSMSW.<init>(SSSMSW.java:41) ~[caffeine-2.7.0.jar!/:na]
  | ... 52 common frames omitted`

**Comment by ben-manes** [comment]
I am not sure. You might try the latest release where we switched to `Class.forName`. I am not familiar with Spring's `LaunchedURLClassLoader` which seems to be recursing on itself. If version 2.8.8 does not work, I'd recommend asking on StackOverflow or a Spring forum. This has to do with Spring's custom classloader handling.

**Comment by Vod9nou** [comment]
Okay, thank you
I'll let you know if I find anything

**Comment by Vod9nou** [comment]
2.8.8 version doesn't work too

**Comment by ben-manes** [comment]
I'm not sure what is wrong in your setup. In Spring's samples it works. For example, in another issue a user provided this [sample](https://github.com/srividrs/spring-caffeine-redis) which runs locally. I don't know enough about your setup to help debug.
