### ISSUE TITLE
Obtaining parent CaffeineCache instance in Expiry#expireAfterCreate()

### ISSUE THREAD

**Issue by mugikura** [ben-manes/caffeine#492]
Hello.
I'm using Caffeine in Spring environment.
I want to change ttl by CaffeineCache.name property not by a key.
Is there any way to obtain the parent CaffeineCache instance in Expiry#expireAfterCreate()?
Example Code:
```Java
var caffeine = Caffeine.newBuilder().expireAfter(new Expiry<Object, Object>() {
    @Override
    public long expireAfterCreate(@NonNull Object key, @NonNull Object value, long currentTime) {
        var caffeineCache = ...; 
        if ("cache1".equals(caffeineCache.getName()) {
            return TimeUnit.HOURS.toNanos(1);
        } else {
            return TimeUnit.DAYS.toNanos(1);
        }
        ......
```

**Comment by ben-manes** [comment]
The cache doesn't have a concept of names, etc. We leave that management layer to the application framework, like Spring Cache. That provider is directly based on the prior one for Guava. Their intent is for developers to [register](https://stackoverflow.com/a/54571018/19450) multiple, named `CaffeineCache` instances with your unique configuration programmatically. They didn't want a property-based approach to uniquely configure with, which is available by using an alternative [provider](https://github.com/stepio/coffee-boots). In your case the first link should fit nicely with what you are trying to do.

**Comment by mugikura** [comment]
Thank you so much.
I'll try them later.
