### ISSUE TITLE
cache.asMap().keySet().size() == 1 for empty cache

### ISSUE THREAD

**Issue by chrisoldiges** [ben-manes/caffeine#494]
Cache<String, String> instance build using Caffeine.newBuilder().expireAfterWrite(Duration.ofMinutes(60)).build();

Entries are added and invalidated over time using:

put(key, value) and invalidate(k);

Set of keys retrieved via cache.asMap().keySet() returns size = 1 for empty caches.
Iterator also confirms the set is empty.

**Comment by ben-manes** [comment]
The `size()` calls all have the caveat as described in `Cache.estimatedSize()`. The count is precalculated by the map operations, so pending removals aren't detected until a maintenance operation (`cleanUp`) is triggered. That is done automatically during reads and writes, but you can call it directly (e.g. for tests).

```java
* Returns the approximate number of entries in this cache. The value returned is an estimate; the
* actual count may differ if there are concurrent insertions or removals, or if some entries are
* pending removal due to expiration or weak/soft reference collection. In the case of stale
* entries this inaccuracy can be mitigated by performing a {@link #cleanUp()} first.
```
