### ISSUE TITLE
caffeine in kubernetes

### ISSUE THREAD

**Issue by RobinsChens** [ben-manes/caffeine#495]
can you guys suppport caffeine cache in kubernetes like hazelcast-kubernetes

**Comment by ben-manes** [comment]
I don't think so. Caffeine is a fancy `ConcurrentHashMap`, not a distributed cache with an external API. Instead this library can be used as a building block, allowing other projects to tackle other hard problems like distributed consistency. Infinispan and Redisson are distributed caches that use Caffeine internally, perhaps one of them might be of interest?
