### ISSUE TITLE
Supporting 2.x

### ISSUE THREAD

**Issue by anuraaga** [ben-manes/caffeine#505]
Hi @ben-manes - congrats on v3 release! I'm curious if you have any thoughts on supporting the 2.x branch going forward. Totally reasonable if it's best-effort community support meaning that new versions could still come out if needed.

Main reason it comes to mind is the Java 11 floor, while you'd think is reasonable in 2021, is still going to block using v3 in a lot of libraries since Java 8 is still just too popular (unfortunately), so hoping v2 is still a reasonable alternative. Though if the new logging API usage is the main reason to go for Java 11, I'd give a soft recommendation of sticking with jul for a bit more to give a bit more reach. I see mention of Unsafe and VarHandle in the release notes, so I'm guessing that is still Java 8 compatible via Unsafe.

Finally, any thoughts on renaming the package / artifact to allow both v2 and v3 in the same app? Or is caffeine expected to be shaded when used in libraries? Just confirming.

Thanks!

**Comment by ben-manes** [comment]
Yes, 2.x will be supported in a maintenance perspective. I don't plan on implementing new functionality there, but bugs will be fixed if reported. Last week version 2.9 was released to make the migration to 3.0 a tad easier and include some of the fixes discovered in its development.

While the release notes may seem scary by highlighting the incompatibilities, but those in fact are very minor and won't affect most projects. They fall into either interfaces that we implement have cruft removed or niceties added, or slight changes to the rarely used (mostly unknown) inspections in `cache.policy()`. When reviewing open-source usages, most are not affected or can make a trivial change on the 2.x line to be compatible.

Any modifications likely to impact a lot of users were rejected, like fixing `Cache.estimatedSize()` to mirror `Spliterator.estimateSize()`. The two incompatibilities that may be potentially problematic seem acceptable at the moment:
1. Almost all open-source usages of `CacheWriter` can switch to an eviction listener, the rest to a Map computation. This is a rarely used feature most used it for the atomic eviction hook. Updating those projects to v2.9 is recommended.
2. Micronaut uses `Policy.Expiration` for dynamic tuning which was renamed to `FixedExpiration`. They did not seem phased when trying a snapshot and patching their code, and gave the green light to proceed.

Note that the Platform Logging API defaults to JUL unless explicitly overridden. I believe only log4j has this optional dependency, which I doubt many use. This should be a transparent.

The main reason for v3 was to remove Unsafe (VarHandles introduced in Java 9) and improve refresh. Both were popular requests but required a major version bump to do so. The rest was touch-ups while I had the opportunity to clean up.

I am hopeful that the user-facing incompatibilities were limited enough to not be a problem in practice. If some do occur, we'll see if a bridge in 2.x can assist, or what should be re-introduced in 3.x. If it had been more invasive then I agree switching to a new package / artifact would have been my preference too.

Please give v3 a whirl and let me know what you think! 🙂

**Comment by anuraaga** [comment]
Thanks @ben-manes - yeah I saw `For best performance Unsafe may be used if available, otherwise falls back to VarHandles` so was hoping `Unsafe` may still be used where possible, but maybe not. As much as I want to give it a whirl, most of my time right now is in libraries with baseline of Java 8 ><

**Comment by ben-manes** [comment]
Unfortunately it would have been too hard to have parallel variants in all cases. Most volatile field usages, like the codegen cache entry fields, now use VarHandles instead of Unsafe for operations like CAS (as obviously Atomic wrappers would have been too much bloat). JCTools' `MpscGrowableArrayQueue` and our own `StripedBuffer` support both strategies as straightforward and hot paths. It seemed harmless to allow for Unsafe in those cases since JCTools' still prefers them due to their benchmarks showing a small benefit.

I believe more projects are going to drop Java 8 support this year. Quarkus/Infinispan teams mentioned that when I discussed v3 with them. Hopefully that means we'll see a stronger nudge to get developers to upgrade.

I'm going to close this as not actionable yet. If you do hear of problems please let me know.

**Comment by ben-manes** [comment]
I reorganized the release notes to make it clearer. I was listing any API changes that semantic version considered an incompatible under that section. For example changing the return value of `LoadingCache#refresh` from `void` to the future is not user-breaking, but is API breaking for any implementers (of which there would be none except maybe a test stub). That came across as too scary, so now its split up to better communicate what users should be interested in. I hope that clarifies things.
