### ISSUE TITLE
java 1.7 support

### ISSUE THREAD

**Issue by gogainda** [ben-manes/caffeine#51]
Can I use it with java 1.7?

**Comment by ben-manes** [comment]
No, sorry. The library is intended for server-side Java 1.8+. The API and implementation take advantage of features that cannot be easily back ported (e.g. using [retrolambda](https://github.com/orfjackal/retrolambda)). I'd recommend,

- If you are on Android then prefer [LruCache](http://developer.android.com/reference/android/util/LruCache.html).
- If you want features, then use [Guava's cache](https://github.com/google/guava/wiki/CachesExplained).
- If performance matters most, then use [ConcurrentLinkedHashMap](https://github.com/ben-manes/concurrentlinkedhashmap).

**Comment by guidomedina** [comment]
Hi Ben, sorry for using this issue to ask a quick question:

I have been using Guava and now for small caches I just switched to Caffeine as I don't need Guava features, there are some concurrent maps I'm using for very specific caches which are growing to a finite level not a big number, mostly load almost all at start up and then just read, am I better of with `ConcurrentHashMapV8` or `ConcurrentLinkedHashMap` ?

I mean, most of my caches are say 95%+ times read ops hence I'm using computeIfAbsent when writing and few times computeIfPresent for specialized writes.

**Comment by ben-manes** [comment]
You're welcome to send me a private email, or create / add onto an issue. As long as you get answers I don't mind what mechanism.

I'm a little confused with your last statement about compute methods, which are Java 8 only. Or do you mean that you'd use `ConcurrentHashMapV8` for a back port of that feature to Java 7?

**Comment by guidomedina** [comment]
Ah, I confused you there when I mentioned the CHMv8, what I meant was that I'm already using Java 8 and AFAIK its CHM is better than older versions (v8) correct?

So what I'm trying to figure out is Java 8 CHM performance vs CLHM and Caffeine counter parts (if any present which I didn't find), for specific expiring/loading caches I'm already using Caffeine cache which I migrated from Guava's cache.

**Comment by ben-manes** [comment]
Oh okay. Adding this to the Java 7 issue was confusing.

CLHM doesn't handle computations natively, so you would fallback to the looping retrials from the default method. Or you could use a [decorator](https://github.com/ben-manes/concurrentlinkedhashmap/blob/wiki/SelfPopulatingCache.md), but more work than you'd prefer.

CLHM is built on [CHMv8 backport](http://gee.cs.oswego.edu/cgi-bin/viewcvs.cgi/jsr166/src/jsr166e/ConcurrentHashMapV8.java) and Caffeine on CHM, so the raw hash table will always win. I included that as "unbounded" in my [benchmark](https://github.com/ben-manes/caffeine/wiki/Benchmarks#compute-1) results. Note that CHM is pessimistic about computations, so I pre-screen to avoid unnecessary locking. That has a big benefit for fewer than 32-cores and is less pronounced on larger machines. Caffeine has an [unbounded version](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/main/java/com/github/benmanes/caffeine/cache/UnboundedLocalCache.java) that is CHM with prescreening, interface adaptions, and optional listener/writer/stats.

I think the answer you're looking for is that CHM is fine to use and really great.
