### ISSUE TITLE
Odd ArrayIndexOutofBounds

### ISSUE THREAD

**Issue by nheitz** [ben-manes/caffeine#52]
Caffeine: 2.1.0
JUnit: 4.11
Gradle: 2.4
java: 1.8.0_72

Apologies if I am doing something peculiar or silly, but I've been tripping over the following cache error for a while now in unit test:

--setting up cache--
```
    Cache<String, Profile> profileDefinitionCache = 
                Caffeine.newBuilder()
                             .maximumSize(1)
                             .build();
    }
```
and later...
```
profileDefinitionCache.put(PROFILES_CONFIG_KEY, new Profile("Some text"));
```
throws the following stack:

```
    java.lang.ArrayIndexOutOfBoundsException: 1
    	at com.github.benmanes.caffeine.cache.Ticker.disabledTicker(Ticker.java:52) ~[caffeine-2.1.0.jar:na]
    	at com.github.benmanes.caffeine.cache.BoundedLocalCache.expirationTicker(BoundedLocalCache.java:336) ~[caffeine-2.1.0.jar:na]
    	at com.github.benmanes.caffeine.cache.BoundedLocalCache.putFast(BoundedLocalCache.java:1337) ~[caffeine-2.1.0.jar:na]
    	at com.github.benmanes.caffeine.cache.BoundedLocalCache.put(BoundedLocalCache.java:1296) ~[caffeine-2.1.0.jar:na]
    	at com.github.benmanes.caffeine.cache.LocalManualCache.put(LocalManualCache.java:64) ~[caffeine-2.1.0.jar:na]
```

I realise my cache definition is quite spare, but I just wanted a simple, thread safe cache containing one item that never expires.  Any ideas?

NOTE: this doesn't fail in IDE, only on the command line.

**Comment by ben-manes** [comment]
That is really weird, since it's failing on an [enum field](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/main/java/com/github/benmanes/caffeine/cache/Ticker.java#L52). Are you running anything like proguard to minify the jar?

**Comment by nheitz** [comment]
Argh, sorry for the misdirect....after further excavation, it seems like jacoco instrumentation was interfering with the caffeine execution.  Bumping to the latest jacoco (0.7.5.201505241946) seems to have eliminated the failure.

I will close, and continue to lament the usage of jacoco.  :-)

**Comment by ben-manes** [comment]
By the way, for your use case you probably want [Suppliers.memoize](docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/base/Suppliers.html#memoize(com.google.common.base.Supplier)) from Guava.

**Comment by nheitz** [comment]
Is Guava's implementation safe for recursive functions?

**Comment by ben-manes** [comment]
Guava's is an abstraction of the [double-checked locking](https://en.wikipedia.org/wiki/Double-checked_locking#Usage_in_Java) idiom. The caller or the delegate function may be recursive, but neither library supports recursive calls into its code (e.g. cache.get(a) --> cache.get(b)). I think for your case the answer should be yes given you don't need any input key.

**Comment by nheitz** [comment]
You are absolutely right in my case such protection would be unnecessary.  I did find this interesting solution to support recursion, using a Reentrant lock, towards the bottom:
https://www.opencredo.com/2015/08/19/lambda-memoization-in-java-8/

**Comment by ben-manes** [comment]
I think that solution is [broken](https://bugs.openjdk.java.net/browse/JDK-8071667) as well. It may appear to work, except if the table resizes. The more verbose solution (get, compute, put) is the only safe one for a recursive map operation.

**Comment by nheitz** [comment]
That bug claims to have been resolved in build 59 and only affecting 8u31.  I will check it on 8u71 tomorrow, as this is where I am currently.

**Comment by ben-manes** [comment]
The fix was to throw an `ConcurrentModificationException` so it would force the recursive logic to fail. So the solution is broken, just fails fast instead of corrupting the hash table during a resize operation.
