### ISSUE TITLE
Ordered async cache get completion

### ISSUE THREAD

**Issue by avgustinmm** [ben-manes/caffeine#525]
I have an async loading cache which is used to create a kafka producer, which then is used to send events. Basically, I do:

`producers().get().thenCompose(producer -> producer.send(x))`

However, called even in a loop (with some delay for creation) leads to calling thenCompose in reverse order. Is there any way to ensure order for calling thenCompose?

Simple reproduce code:
```
 @Test
  public void test() throws InterruptedException {
    final CountDownLatch latch = new CountDownLatch(10);
    
    final ScheduledExecutorService scheduler = Executors.newScheduledThreadPool(1);
    final AsyncCache<String, String> cache = Caffeine.newBuilder().buildAsync();
    for (int i = 0; i < 10; i++) {
      final int iF = i;
      cache
        .get(
          "key", 
          (k, e) -> {
            final CompletableFuture<String> future = new CompletableFuture<>();
            scheduler.schedule(() -> future.complete("val"), 2, TimeUnit.SECONDS);
            return future;
          })
        .thenRun(() -> {
          System.out.println("--> " + iF);
          latch.countDown();
        });      
    }
    
    latch.await();
  }
```
This will print indexes in reverse order. Could I arrange, somehow, order?

**Comment by ben-manes** [comment]
Unfortunately this is by design of CompletableFuture, which does not specify a call order. It was used a stack for efficiency. I asked Doug about the rationale and he [replied](cs.oswego.edu/pipermail/concurrency-interest/2021-January/017278.html),
> There was some implicit discussion of this when people discovered that the initial trial versions tended to blow call stacks and retain 
unneeded heap pointers in recursive usages. As others have noted, 
there's no guarantee about triggering order, so choosing one that tends to use fewer resources (in the trampoline-like postComplete() method) seems to be the best option. In some applications, the triggering order can be surprising, but his would be true no matter what choice was made.

**Comment by avgustinmm** [comment]
Hm, I didn't realized that actually Caffeine just returns same cached CompletableFuture and actually reverse order is due to dependents processing order. I suppose I'll have to ensure ordering by different means.
Thanks for fast response.

**Comment by ben-manes** [comment]
Yes, we try to be transparent in the future to avoid surprises, as futures are instance equality. This way behavior like asMap are very obvious. We only create a future directly for bulk operations.

**Comment by avgustinmm** [comment]
I found a workaround if I use ConcurrentHashMap. Something like:
```
    final ConcurrentHashMap<String, CompletableFuture<String>> cache = new ConcurrentHashMap<>();
    for (int i = 0; i < 10; i++) {
      final int iF = i;
      final CompletableFuture<String> res = cache
        .compute(
          "key", 
          (k, v) -> {
            if (v == null) {
              final CompletableFuture<String> future = new CompletableFuture<>();
              scheduler.schedule(() -> future.complete("val"), 2, TimeUnit.SECONDS);
              return future.thenApply(Function.identity());
            } else {
              if (v.isDone()) {
                return v;
              } else {
                return v.thenApply(Function.identity());
              }
            }
          });
       res.thenRun(() -> {
         System.out.println("--> " + iF);
         latch.countDown();
       });      
    }
```
I still want to use Caffeine because of size limit, expiration and removal hooks. So I think about using AsyncLoadingCache.asMap for querying values, e.g.:
```
    final AsyncCache<String, String> cache = Caffeine.newBuilder().buildAsync();    
    final ConcurrentMap<String, CompletableFuture<String>> cCmap = cache.asMap();
    cMap.get(...)
```
Do you have any concerns regarding that approach?

**Comment by ben-manes** [comment]
I think your `thenApply` is equivalent to the `copy()` method.

`asMap().get` is functionally the same as `AsyncCache.getIfPresent`, if that helps a bit.

My main concern is that `compute` takes out an exclusive lock, making it slower for read operations. It may be fine depending on your performance needs and that these are tiny critical sections. This differs from `AsyncCache.get` which maps to `Map.computeIfPresent`, which only locks if the entry is absent or invalid. You might consider performing a prescreen `getIfPresent(key)` that checks `future.isDone()` as a fastpath to skip compute.

**Comment by avgustinmm** [comment]
It seems that ordering I want to have is too complicated to be implemented that way. 
I'm not even sure why that 'workaround' works in my tests and if it would work on different CompletableFuture versions.
Thank you for your input.
