### ISSUE TITLE
Add support for cache expire/refresh on condition

### ISSUE THREAD

**Issue by StephenFlavin** [ben-manes/caffeine#536]
It would be useful to be able to have a custom condition that causes expiry of a cache entry.

For my use case I have a app which steams data from kafka and maintains an in memory buffer which is flushed (written to a zip file) based on two criteria time and size.

I'm currently handling this logic manually and was looking to tidy up the code by using a LoadingCache making use of the RemovalListener to write the files however its currently not possible to expire entries for custom conditions. 

e.g.
```
LoadingCache<Key, List<Value>> cache = Caffeine.newBuilder()
    .maximumSize(...)
    .expireAfterWrite(5, TimeUnit.MINUTES)
    .expireOnCondition((key, value) -> value.size() >= 10000)
    .removalListener(new BatchWriter())
    .build(...); 
```

**Comment by ben-manes** [comment]
How well could `expireAfter(expiry)` fit your use-case? That returns a duration, which may be zero to indicate immediate expiration. For example,

```java
LoadingCache<Key, List<Value>> cache = Caffeine.newBuilder()
    .expireAfter(new Expiry<Key, List<Value>>() {
      public long expireAfterCreate(Key key, List<Value> values, long currentTime) {
        return TimeUnit.MINUTES.toNanos(5);
      }
      public long expireAfterUpdate(Key key, List<Value> values, 
          long currentTime, long currentDuration) {
        return (values.size() > 10_000) ? 0L : TimeUnit.MINUTES.toNanos(5);
      }
      public long expireAfterRead(Key key, List<Value> values,
          long currentTime, long currentDuration) {
        return currentDuration;
      }
    })
    .build(key -> new ArrayList<Value>());
```

The expiration time is calculated during a cache operation, so modifying the value has to inform the cache for reevaluation. This can be done atomically using a compute, e.g.

```java
cache.asMap().compute(key, (k, values) -> {
  if (values == null) {
    values = new ArrayList<>();
  }
  values.add(...);
  return value;
});
```

**Comment by StephenFlavin** [comment]
Ah awesome, I didn't think this would be possible without code changes to the library, this should do the trick for my refractor however I do think having some syntactic sugar of `expireOnCondition` in the builder would be nice.

Big thanks for the suggestion 🙂

**Comment by ben-manes** [comment]
In that case it is composing multiple policies within the builder, which gets messy. I'd prefer to have a builder on `Expiry`, e.g. how `Comparator.comparing(...).thenComparing(...)` can succinctly define the strategy. Something like that would make it easier and clearer to define the conditions in a composable fashion.

**Comment by ben-manes** [comment]
Closing for now, but open to API improvements if someone wants to sketch out improvements to `Expiry`.

**Comment by StephenFlavin** [comment]
Thanks again 🙏
