### ISSUE TITLE
Updating cache with a List<String> value

### ISSUE THREAD

**Issue by macksclark** [ben-manes/caffeine#545]
I have a cache<String, List<String>> on top of a Cloud Datastore object and I need to update the List<String> value atomically, and call the CacheWriter.write function.

When I update my cache, I want to append the new value to the existing list of values. Similar to in issue #395, [option 1] I can use .get() followed by .put(), which calls the CacheWriter.write function but is not atomic and will have issues with parallelization. Or [option 2] as shown in that issue, to use a combination of .asMap(), .putIfAbsent(), and .computeIfPresent() which does not call CacheWriter.write because it uses the .asMap() functionality, and thus does not send the update to the Cloud Datastore as I need it to.

[option 1] 
```
List<String> values = cache.get("key");
values.add("new");
cache.put("key", "values");
```

[option 2]
```
cache.asMap().computeIfPresent("key",
        (key, values) -> {
          values.add("new");
          return values;
        });
cache.asMap().putIfAbsent("key", ImmutableList.of("value"));
```

Is there any way I can update the values list and the Datastore at the same time? Or if there's any other options for mapping multiple values to a single key please let me know.

**Comment by ben-manes** [comment]
Hi @macksclark,

We deprecated `CacheWriter` in 2.x and removed it in 3.x. It was simply a poor abstraction that did not mesh well with the Collections Framework, as you noticed. It is a concept in other caching frameworks, but a `Map.compute` serves a similar purpose and is more powerful. The one use case of a synchronous listener for automatic evictions was replaced by `Caffeine.evictionListener` which accepts the `RemovalListener` interface. Please upgrade to 2.9+ or 3.0+ and remove your `CacheWriter` usages.

The most obvious code is to use one of the compute methods and invoke the logic in your `CacheWriter.write` explicitly.

**Comment by macksclark** [comment]
Ah I was on 2.8.8, thanks for the tip! So after the upgrade to 2.9.0, I have 2 small questions for you:
1. I can expect this block of code to operate the same as usual without the `.writer()` right?
```
Caffeine.newBuilder()
  .maximumSize(MAXIMUM_CACHE_SIZE)
  .expireAfterAccess(CACHE_DURATION_IN_MINUTES, TimeUnit.MINUTES)
  .build(...);
```

2. In places where I use a `.put(key, value)`, which used to inherently call the writer, what is the best method of getting the `CacheWriter.write` logic I had previously when I'm not using a Map.compute function?

**Comment by ben-manes** [comment]
1. That code looks fine. I meant that most users of `CacheWriter` wanted a synchronous removal listener for evictions, via `#delete`, so that case was added as `evictionListener`. You don't need that, so that should work fine.
2. The best is to replace `put(key, value)` with a compute and call your write logic directly. Since it is generally better to encapsulate the cache instance within your class using it, there is usually only a couple calls needing this.

**Comment by macksclark** [comment]
Thank you for the help @ben-manes ! Looks so far like 2.9.0 will solve my issues.
