### ISSUE TITLE
Eviction behavior

### ISSUE THREAD

**Issue by lwshuo** [ben-manes/caffeine#547]
I noticed an eviction behavior that I would like to find out more details
We define our cache as below:
` libraryCache =
     Caffeine.newBuilder()
    .removalListener((String key, Library library, RemovalCause cause) -> 
                  System.out.println("Caffeine cache removal listener for library id " + library.getId()))
     .maximumSize(2000)
    .expireAfterAccess(Duration.ofMinutes(10))
    .scheduler(Scheduler.systemScheduler())
    .buildAsync(libraryId -> retrieveLibraryFromStorage(libraryId)));`

Usually the eviction rate is pretty stable, but sometimes it would drop low for a while and then spike, for example in the log when we search for `Caffeine cache removal listener` , we might see such distribution
![image](https://user-images.githubusercontent.com/25490314/117154488-e4761200-ad89-11eb-8bc2-eaabab6b5fff.png)

Is it normal?

**Comment by ben-manes** [comment]
I think it is hard to tell with that information. A few questions to investigate,
- What type of evictions (size, expired)?
- Is there a spike of insertions (e.g. some periodic external activity)?
- Does the hit rate change significantly?
- Is the default executor (FJP's commonPool) overloaded, causing a delayed catch-up for expiration?

My best guess:
Given the leading period of zero evictions, it may be that the FJP is flooded as it is the default used in `CompletableFuture`. When the scheduler's clean up is finally run, it has a larger number of expiration events to discard than usual. That causes a spike in activity from your logs. I'd recommend using `recordStats` and instrumenting your app via metrics to better understand what is happening.

**Comment by lwshuo** [comment]
Thank you! these are good leads.
