### ISSUE TITLE
Need class file version 55.0

### ISSUE THREAD

**Issue by fredsuvn** [ben-manes/caffeine#548]
version 3.0.2, in JDK8 runtime, it shows: `com/github/benmanes/caffeine/cache/Caffeine has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

Did version 3.x need java11+ ?

**Comment by Stephan202** [comment]
@fredsuvn indeed, version 3.x requires Java 11; see the [release notes](https://github.com/ben-manes/caffeine/releases/tag/v3.0.0). Note that version 2.x is still supported.

**Comment by fredsuvn** [comment]
sadly!!

**Comment by mouday** [comment]
thank you.
