### ISSUE TITLE
What's the best way to update the expiry time of an entry in CaffeineCache?

### ISSUE THREAD

**Issue by kincsescsaba** [ben-manes/caffeine#554]
Hi,
What's the best way to update the expiry time of an entry in CaffeineCache?
Is there anything better than removing the entry than re-adding it with a new TTL?
Or should I just simply call a .put again with the existing key?

Thanks,
Csaba

**Comment by ben-manes** [comment]
You can use [Policy.VarExpiration](https://www.javadoc.io/doc/com.github.ben-manes.caffeine/caffeine/latest/com.github.benmanes.caffeine/com/github/benmanes/caffeine/cache/Policy.VarExpiration.html) to update it directly. This is obtained through `cache.policy().expireVariably()`, which returns an optional if `Caffeine.expiresAfter(expiry)` is set. For a fixed expiration interval then you would have to perform the appropriate action, such as a mutation if `expireAfterWrite`.

**Comment by kincsescsaba** [comment]
Thanks, I'll try that
