### ISSUE TITLE
Why get & getAll behave differently for computations resulting null values

### ISSUE THREAD

**Issue by shriyog** [ben-manes/caffeine#557]
I've observed that `get` & `getAll` methods seem to have different behavior while handling `null` results from the supplied computation functions. 

The `get` returns `null` without throwing any exception
```
cache.get("foo", k -> functionReturningNull())
```

While `getAll` throws an NPE when the computation function returns a Map containing `null` values
```
// throws NullPointerException
cache.getAll(Arrays.asList("foo", "bar"), k -> functionReturningMapWithNullValues())
```

Why is the contract different? Can't `getAll` accept `null` values returned by the function just like `get` does? If this seems opposite to the idea that `put` can never accept `null` values, `get` should also throw NPE.

I'm using version 2.9.1

**Comment by ben-manes** [comment]
A null value in a map is different than an absent entry, which makes the Map api confusing as it mixes the two. It is considered a bad practice to have a null mapping and tends to cause bugs. We treat it like `cache.put(key, null)` which is not allowed. If instead you return a map with only the present keys then it will work as you expected.

```java 
var map = new HashMap();
map.put(1, “a”);
map.put(2, null);

cache.getAll(List.of(1, 2, 3), k -> map); // not accepted
cache.getAll(List.of(1, 2, 3), k -> Map.of(1, “a”)); // returns [1, a]

**Comment by ben-manes** [comment]
For get, see Map.computeIfAbsent. This indicates the mapping does not exist which is not an error, but a fact of the underlying data source. Guava does throw an exception, but it is not exceptional and caused more trouble than helped. The two are a little different because getAll can simply not include the null entry to indicate that no data exists for the same behavior.

**Comment by shriyog** [comment]
@ben-manes Thank you for explaining the rationale behind this. Yes, returning a map with only existing keys works & makes sense that way instead of having `null` mappings.
