### ISSUE TITLE
 Strange thread stack, when used with vertx gateway

### ISSUE THREAD

**Issue by jr981008** [ben-manes/caffeine#559]
use caffine single instance as global buffer with vertx ，

Application is gateway. PerRequest will cache.get  5-10 times. The interface request is stable at 10k tps. After running few days, I observed that the cpu risen has by 30%, and the interface delay has risen by more than 100ms. Jstack shows that almost all vertx eventloop threads are in the offer method of caffeine.

I am very confused about the request processing includes time-consuming operations such as encryption and decryptio and access some middleware , but all of usefull thread stack show in offer method running.

a snapshot of stack:
"vert.x-eventloop-thread-32" #572 prio=5 os_prio=0 tid=0x0000fffd68b91800 nid=0x1bf8 runnable [0x0000fffb8c3fd000]
   java.lang.Thread.State: RUNNABLE
	at com.github.benmanes.caffeine.cache.StripedBuffer.offer(StripedBuffer.java:145)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.afterRead(BoundedLocalCache.java:1153)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2319)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:54)

JDK 1.8.0_172 mixed mode
caffeine 2.8.8

**Comment by ben-manes** [comment]
It's hard to say without more threads. An offer is attempted only a few times and continues on by dropping the read event. The event is recorded in the ring buffer to replay later under the lock, as the eviction policy is not thread-safe. This approach allows for efficient request sampling so that the policy can make good eviction decisions and the client can have a high concurrency.

It looks like the cache hit occurred and it is trying to record that event and return back. It's unclear if the threads are stuck in an outer infinite loop, or if it is a livelock within the method. Perhaps by enabling cache stats you'll see if the hitCount increases rapidly. The sampled line is not inside a loop within this library.

**Comment by jr981008** [comment]
Thanks reply.
no outer infinite loop,because request return in less than 200ms (normal should be around 60ms).
i run jstack many times in different time got same result,This is an inevitable phenomenon.

another  thing not all instance have these phenomenon

 jmap diff
health instance:
 105:         58005        1856160  com.github.benmanes.caffeine.cache.PSMS
 285:          7400         414400  com.github.benmanes.caffeine.cache.BoundedLocalCache$$Lambda$2061/1439368020
 420:          7401         177640  [Lcom.github.benmanes.caffeine.cache.RemovalCause;
 421:          7400         177600  [Lcom.github.benmanes.caffeine.cache.Node;
 750:            80          22400  com.github.benmanes.caffeine.cache.BoundedBuffer$RingBuffer
 953:            18           9936  com.github.benmanes.caffeine.cache.MpscGrowableArrayQueue
1159:            18           5472  com.github.benmanes.caffeine.cache.SSMS
1772:            54           1296  com.github.benmanes.caffeine.cache.AccessOrderDeque
2167:            18            576  com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalLoadingCache
2168:            18            576  com.github.benmanes.caffeine.cache.FrequencySketch
2318:            18            432  com.github.benmanes.caffeine.cache.BoundedBuffer
2319:            18            432  com.github.benmanes.caffeine.cache.BoundedLocalCache$PerformCleanupTask
2430:             3            368  [Lcom.github.benmanes.caffeine.cache.Buffer;
2583:            18            288  com.github.benmanes.caffeine.cache.BoundedLocalCache$$Lambda$361/1545098604
2584:            18            288  com.github.benmanes.caffeine.cache.LocalLoadingCache$$Lambda$362/1852656228
4388:             2             64  com.github.benmanes.caffeine.cache.References$WeakKeyReference
6261:             1             24  [Lcom.github.benmanes.caffeine.cache.DisabledTicker;
6262:             1             24  [Lcom.github.benmanes.caffeine.cache.DisabledWriter;
6263:             1             24  [Lcom.github.benmanes.caffeine.cache.SingletonWeigher;
6264:             1             24  [Lcom.github.benmanes.caffeine.cache.stats.DisabledStatsCounter;
6531:             1             24  com.github.benmanes.caffeine.cache.DisabledTicker
6532:             1             24  com.github.benmanes.caffeine.cache.DisabledWriter
6533:             1             24  com.github.benmanes.caffeine.cache.RemovalCause$1
6534:             1             24  com.github.benmanes.caffeine.cache.RemovalCause$2
6535:             1             24  com.github.benmanes.caffeine.cache.RemovalCause$3
6536:             1             24  com.github.benmanes.caffeine.cache.RemovalCause$4
6537:             1             24  com.github.benmanes.caffeine.cache.RemovalCause$5
6538:             1             24  com.github.benmanes.caffeine.cache.SingletonWeigher
6539:             1             24  com.github.benmanes.caffeine.cache.stats.DisabledStatsCounter
7612:             1             16  com.github.benmanes.caffeine.cache.Caffeine$$Lambda$359/538602365


unhealth instance :
 131:         53774        1720768  com.github.benmanes.caffeine.cache.PSMS
 717:           361          20216  com.github.benmanes.caffeine.cache.BoundedLocalCache$$Lambda$2058/1001170939
 966:            18           9936  com.github.benmanes.caffeine.cache.MpscGrowableArrayQueue
1037:           362           8704  [Lcom.github.benmanes.caffeine.cache.RemovalCause;
1038:           361           8664  [Lcom.github.benmanes.caffeine.cache.Node;
1287:            20           5600  com.github.benmanes.caffeine.cache.BoundedBuffer$RingBuffer
1292:            18           5472  com.github.benmanes.caffeine.cache.SSMS
1946:            54           1296  com.github.benmanes.caffeine.cache.AccessOrderDeque
2327:            18            576  com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalLoadingCache
2328:            18            576  com.github.benmanes.caffeine.cache.FrequencySketch
2479:            18            432  com.github.benmanes.caffeine.cache.BoundedBuffer
2480:            18            432  com.github.benmanes.caffeine.cache.BoundedLocalCache$PerformCleanupTask
2698:            18            288  com.github.benmanes.caffeine.cache.BoundedLocalCache$$Lambda$355/1555557228
2699:            18            288  com.github.benmanes.caffeine.cache.LocalLoadingCache$$Lambda$356/1530670681
3652:             2            112  [Lcom.github.benmanes.caffeine.cache.Buffer;
4437:             2             64  com.github.benmanes.caffeine.cache.References$WeakKeyReference
6322:             1             24  [Lcom.github.benmanes.caffeine.cache.DisabledTicker;
6323:             1             24  [Lcom.github.benmanes.caffeine.cache.DisabledWriter;
6324:             1             24  [Lcom.github.benmanes.caffeine.cache.SingletonWeigher;
6325:             1             24  [Lcom.github.benmanes.caffeine.cache.stats.DisabledStatsCounter;
6592:             1             24  com.github.benmanes.caffeine.cache.DisabledTicker
6593:             1             24  com.github.benmanes.caffeine.cache.DisabledWriter
6594:             1             24  com.github.benmanes.caffeine.cache.RemovalCause$1
6595:             1             24  com.github.benmanes.caffeine.cache.RemovalCause$2
6596:             1             24  com.github.benmanes.caffeine.cache.RemovalCause$3
6597:             1             24  com.github.benmanes.caffeine.cache.RemovalCause$4
6598:             1             24  com.github.benmanes.caffeine.cache.RemovalCause$5
6599:             1             24  com.github.benmanes.caffeine.cache.SingletonWeigher
6600:             1             24  com.github.benmanes.caffeine.cache.stats.DisabledStatsCounter
7678:             1             16  com.github.benmanes.caffeine.cache.Caffeine$$Lambda$353/756647219


jstack result is same ,all vertx service thread is in offer method.
Is it possible that an abnormal insatnce triggers the eviction policy cause  that? Is it so different to the CPU usage if the eviction policy is triggered.

init code:
 Caffeine.newBuilder()
                .maximumSize(30000)
                .build();

**Comment by ben-manes** [comment]
That's still not much to go on. If you can provide the full jstack traces of an unhealthy instance privately over email, maybe I'll spot the issue. Even better if to capture a [JFR profile](https://www.baeldung.com/java-flight-recorder-monitoring) of a running instance which would avoid all guesswork. I'd also recommend tracking your cache stats to see if anything abnormal is occurring when comparing machines.

You might be observing a high number of async tasks, as we delegate work like removal notifications and policy handling to the configured executor. By default that is `ForkJoinPool.commonPool()`. This is to avoid penalizing the calling thread, because while the cache's operations are fast the callbacks to user code might not be. You can try using a same-thread executor, `Caffeine.executor(Runnable::run)`, and see if that helps at all. This might since Vertx is event loop based and might frown upon other threads being involved.

**Comment by ben-manes** [comment]
Hope that means you found the problem and fixed it.

**Comment by jr981008** [comment]
i didnt find problem，but rpoduction env cant wait ，so  just change to other memcache temporary

**Comment by jr981008** [comment]
[t2.txt](https://github.com/ben-manes/caffeine/files/6623367/t2.txt)

**Comment by jr981008** [comment]
decomplie byte code  145 line like ：
  public int offer(E e) {
    int result = 0;
    boolean uncontended = true;
    Buffer<E>[] buffers = this.table;
    int mask;
    Buffer<E> buffer;
 145   if (buffers != null && (mask = buffers.length - 1) >= 0 && (
      
147      buffer = buffers[getProbe() & mask]) != null) {
 148     if (!(uncontended = ((result = buffer.offer(e)) != -1))) {
 149       expandOrRetry(e, uncontended);
        return result;
      } 
      return result;
    } 
    expandOrRetry(e, uncontended);
    return result;
  }

need to consider jit, 145 lines are likely contains all these：
 145   if (buffers != null && (mask = buffers.length - 1) >= 0 && (buffer = buffers[getProbe() & mask]) != null) {

just change cache instance to guava ，nothing else change  it  fixed

**Comment by ben-manes** [comment]
None of that is a loop or blocking, but rather reading volatile fields. Glad to hear you found a workaround.

**Comment by jr981008** [comment]
these are Fake code we use caffeine  as head cache，and mapdb as directmem cache huage data，just 
Keep some needed in heap。
    DB db = DBMaker
            .memoryDirectDB()
            .allocateStartSize(1024*1024*100) // 初始申请100M
            .make();
    HTreeMap<String, String> map = db.hashMap("table1")
            .keySerializer(Serializer.STRING)
            .valueSerializer(Serializer.STRING)
            .createOrOpen();
    LoadingCache<String, String> cache = Caffeine.newBuilder()
            .maximumSize(30000)
            .recordStats()
            .build(k -> map.get(k));
