### ISSUE TITLE
 Question about loading the cache in refresh

### ISSUE THREAD

**Issue by aschuhl** [ben-manes/caffeine#562]
When the cache time exceeds for refresh, if multiple hits to the cache occur, will only one async call be sent to the executor or will each hit cause a call until the value is updated?

**Comment by ben-manes** [comment]
A single async reload will be performed with subsequent triggers for that entry being suppressed.

In v2 this disabled expiration, could not detect ABA races, and explicit `LoadingCache#refresh(key)` calls could cause duplicates. Those flaws were resolved in v3 with an improved implementation.
