### ISSUE TITLE
Can we make sync call in the cache

### ISSUE THREAD

**Issue by dwivedianurag** [ben-manes/caffeine#571]
Can we make synchronous calls to this cache operations like get,put,delete

**Comment by ben-manes** [comment]
Yes. You might find the asMap view useful where you can use operations like compute as well.

**Comment by dwivedianurag** [comment]
ok if possible can you please provide us an example how to do the same?

**Comment by ben-manes** [comment]
```
Cache<Key, Graph> graphs = Caffeine.newBuilder().build();

graphs.asMap().compute(key, (k, v) -> {
  // do fancy stuff…
  return graph;
});

**Comment by dwivedianurag** [comment]
ok @ben-manes thanks a lot I will try this and if have some queries I will ask you
