### ISSUE TITLE
How do I register a custom cache that uses generics?

### ISSUE THREAD

**Issue by benrebakpublic** [ben-manes/caffeine#574]
I'm trying to create a `org.springframework.cache.CacheManager` using Caffeine as the implementation.

```
	@Bean
	public CacheManager cacheManager() {
		CaffeineCacheManager manager = new CaffeineCacheManager();
		manager.registerCustomCache("", myCustomCache());
		return manager;
	}
```

How do I register `myCustomCache()` when the object that's returned is, for example, of type `Cache<String, MyCustomObject` rather than `Cache<Object, Object>`? I cannot find a way to do this.

This is important to me because, in the definition of `myCustomCache()`, I want to define a custom `Expiry` that uses the key, WITHOUT having to cast it. For example:

```
Caffeine.newBuilder()
    .expireAfter(new Expiry<String, MyCustomObject>() {
	@Override
	public long expireAfterCreate(@NonNull String key, @NonNull MyCustomObject value, long currentTime) {
		return 100 * key.length();
	}
    })
    .build();
```

Thanks.

**Comment by ben-manes** [comment]
I'm sorry, but I am not familiar with Spring (I haven't used it for over a decade). I helped port their Guava adapters to Caffeine to add support, but it was their implementation design for the `CaffeineCacheManager`. You will get better support on a Spring forum, like their StackOverflow tag.

Spring Cache uses a [KeyGenerator](https://github.com/spring-projects/spring-framework/blob/main/spring-context/src/main/java/org/springframework/cache/interceptor/KeyGenerator.java) that by default wraps all method parameters into a [SimpleKey](https://github.com/spring-projects/spring-framework/blob/main/spring-context/src/main/java/org/springframework/cache/interceptor/SimpleKey.java). For the value is is [wrapped](https://github.com/spring-projects/spring-framework/blob/ce6217be8536944201a1215679870a57c414381d/spring-context/src/main/java/org/springframework/cache/interceptor/CacheAspectSupport.java#L455-L467) by an `Optional` to support negative caching. This means that your application key/value differ from what is actually stored in the cache. This is likely why they want the generics to be raw `Object`.

In past discussions, the Spring authors indicated that their abstraction is meant only for the simple cases. As they don't intend to handle complex scenarios, instead users are supposed to switch to the vendor's apis directly. Hopefully that still lets you plug the cache in for monitoring, etc. I don't know at what threshold the cutover should be made, though.
