### ISSUE TITLE
Lazy putIfAbsent

### ISSUE THREAD

**Issue by asarkar** [ben-manes/caffeine#576]
My use case is that the values in the cache are put by a Redis Topic listener. Another thread wants the value from the cache. 

Thread x:

```
redisson.getTopic("responseTopic", codec)
    .addListener(Response.class, (channel, msg) -> {
        var old = responseMap.putIfAbsent(msg.getSessionId(), CompletableFuture.completedFuture(msg));
        if (old != null) {
            LOG.debug("Listener is late");
            old.complete(msg);
        }
    });
```

Thread y:
```
var future = new CompletableFuture<Response>();
var old = responseMap.putIfAbsent(sessionId, future);
if (old != null) {
    future = old;
}
future.get((maxAttempts - 1) * sleepTimeMillis, TimeUnit.MILLISECONDS)
```

This works, but notice that one of the two `putIfAbsent` will lose and the default value will be thrown away. It'll be nice to have something like `putIfAbsent(key, Supplier<Value>)`, so that the value is only evaluated if need be.

**Comment by ben-manes** [comment]
Why not use computeIfAbsent?

**Comment by asarkar** [comment]
Completely missed that, thanks.
