### ISSUE TITLE
Question: Modelling long lived resource cache

### ISSUE THREAD

**Issue by asad-awadia** [ben-manes/caffeine#577]
Hey Ben,

I am trying to model something and think that Caffeine would be the best way to go but there is 1 piece that is tripping me up.

I am trying to model a long lived resource [file/db/channel etc] being cached. There are many -  1 for each user. Should only be created if not exist and reused for every request. Eventually should be closed.

For the fetch - that piece doesn't seem too difficult - I can use the get API with the function being the create if the resource doesn't exist

it is the release part that feels might cause race conditions

I can ensure that the resource is released using the onEvict functionality - but what happens when I do a fetch and have a reference to the resource somewhere in the code logic and it gets evicted from the cache thus closing it while it is being used elsewhere

Any idea how to deal with this situation?

**Comment by ben-manes** [comment]
It sounds like you would want to use reference counting to manage the resource's lifecycle. This can be done using Java reference types, e.g. phantom references replace `Object.finalize`, but these rely on the GC which will run at an unpredictable time. Therefore explicit reference counting is preferred, with implicit being useful as a failsafe if you are concerned with application code forgetting to close the resource. For example, you could return a proxy which decrements a counter on `close()` and destroys the resource when the count reaches zero. The loading into the cache would initialize the count to 1 and an eviction would decrement it. In the simple case then the cache eviction would destroy the resource or else the last usage would do so on close.

If your case is to exclusively acquire and release a stateful resource then it sounds more like an object pool than a cache. In that case then then libraries like [vibur](http://www.vibur.org/) or [stormpot](https://github.com/chrisvest/stormpot) might be useful. If you need to scope it by a lookup key then there are fewer libraries, e.g. Apache's [KeyedObjectPool](https://commons.apache.org/proper/commons-pool/apidocs/org/apache/commons/pool2/KeyedObjectPool.html). I wrote a prototype [multiway-pool](https://github.com/ben-manes/multiway-pool) and trashed in the last few commits, but it could be resurrected if needed.

**Comment by asad-awadia** [comment]
It is only one object per key though... would it still be an object pool?

**Comment by ben-manes** [comment]
You're right, it wouldn't be a pool but might have characteristics to draw from. The reference counting trick that the jdbc pools use sounds like the solution to your problem, though.

**Comment by asad-awadia** [comment]
I see.. Hmm :thinking: 

Don't see any off the shelf implementation that I can bring in :/

Googling reference counting is difficult given its context in GC

Thanks as always!
