### ISSUE TITLE
about future plans

### ISSUE THREAD

**Issue by killersteps** [ben-manes/caffeine#578]
Is there any plan to provide users with a simple implementation of Bloom filter?

**Comment by ben-manes** [comment]
Sorry, but I think that the scope will stay limited to only in-memory caching. There is a simple [implementation](https://github.com/ben-manes/caffeine/blob/master/simulator/src/main/java/com/github/benmanes/caffeine/cache/simulator/membership/bloom/BloomFilter.java) that you could copy, I suppose. You should probably look at [fast filter](https://github.com/FastFilter/fastfilter_java) which provides high quality implementations and closely tracks current research.

**Comment by killersteps** [comment]
> Sorry, but I think that the scope will stay limited to only in-memory caching. There is a simple [implementation](https://github.com/ben-manes/caffeine/blob/master/simulator/src/main/java/com/github/benmanes/caffeine/cache/simulator/membership/bloom/BloomFilter.java) that you could copy, I suppose. You should probably look at [fast filter](https://github.com/FastFilter/fastfilter_java) which provides high quality implementations and closely tracks current research.

thanks!

**Comment by killersteps** [comment]
At the same time,thank you for providing Chinese documents for caffeine.  :)

**Comment by ben-manes** [comment]
Thanks to @tydhot 😊

**Comment by tydhot** [comment]
@ben-manes @killersteps u are welcome:)

**Comment by gorankarlic** [comment]
CCP is bad for your health.
