### ISSUE TITLE
Is Caffeine Thread Safe? (Question)

### ISSUE THREAD

**Issue by KushagraBindal** [ben-manes/caffeine#585]
Dear Experts,

We are evaluating caffeine data loading mechanism using Manual flow, we are currently using 2.8 version of caffeine. As per our requirement we have multiple READ and WRITE activities, obviously read lock are much more than write lock. 

Now we are trying to evaluate if Caffeine can manage all such activities without any stale data or do we need to perform any specific operation on the same. 

Our legacy code was using Guava and we are replacing the same with Caffeine. We are explicitly using ReentrantReadWriteLock to manage the atomicity of the operation. Please do let us know if we really need the explicitly locking to deal with Caffeine.

Your early feedback will help us in finalizing the things.

Regards
Kushagra

**Comment by ben-manes** [comment]
Both Caffeine and Guava are threadsafe. They should behave like ConcurrentHashMap when unbounded, so if you used that would your code still needed locking? The cache offers per entry atomicity, whereas your locking sounds to be global across all entries.
