### ISSUE TITLE
Update cache configuration at runtime

### ISSUE THREAD

**Issue by DVD27** [ben-manes/caffeine#589]
Hello,

I search to modify the cache configuration (maximumSize, refreshAfterWrite....) at runtime without recreate a new cache object and keep in memory all object already in the cache.

My objective is to set this properties into a dedicated file ou db and create some route in my war to change it if necessary dynamicaly without undeploy/redeploy.

Have-you some idea, suggestion ?

**Comment by ben-manes** [comment]
Please look at [Cache.policy()](https://www.javadoc.io/doc/com.github.ben-manes.caffeine/caffeine/latest/com.github.benmanes.caffeine/com/github/benmanes/caffeine/cache/Policy.html) for these runtime knobs. These will let you modify a configuration if the cachewas created with a feature enabled, such as a maximum size.

**Comment by DVD27** [comment]
Thank you, that work like a charm.
