### ISSUE TITLE
Can't compile with jdk1.8  caffeine tag2.9.0

### ISSUE THREAD

**Issue by zyong2004** [ben-manes/caffeine#595]
checksum-dependency-plugin is disabled since checksumIgnore property is present
> Task :caffeine:downloadCaffeineLocal UP-TO-DATE
> Task :caffeine:compileJavaPoetJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':caffeine:compileJavaPoetJava'.
> Illegal/unsupported escape sequence near index 8
  D:\work\git\caffeine\caffeine\build/generated-sources/.*
          ^

**Comment by ben-manes** [comment]
I believe this is [fixed](https://github.com/ben-manes/caffeine/commit/a7b18fa5ed56ceda5be783dd6cd267568b0334d0) on master, but was not backported to the v2.dev branch as primarily for maintenance. Would using v3 be acceptable for your use-case?

**Comment by ben-manes** [comment]
Oh, master removed this `excludedPaths` since then so that generated code is statically analyzed. You can apply the same fix in v2,

https://github.com/ben-manes/caffeine/blob/a7b18fa5ed56ceda5be783dd6cd267568b0334d0/gradle/codeQuality.gradle#L134

**Comment by zyong2004** [comment]
> I believe this is [fixed](https://github.com/ben-manes/caffeine/commit/a7b18fa5ed56ceda5be783dd6cd267568b0334d0) on master, but was not backported to the v2.dev branch as primarily for maintenance. Would using v3 be acceptable for your use-case?

**Comment by zyong2004** [comment]
> Oh, master removed this `excludedPaths` since then so that generated code is statically analyzed. You can apply the same fix in v2,
> 
> https://github.com/ben-manes/caffeine/blob/a7b18fa5ed56ceda5be783dd6cd267568b0334d0/gradle/codeQuality.gradle#L134

it's ok  thank you for guidance
