### ISSUE TITLE
getAll returns partial results

### ISSUE THREAD

**Issue by cheehonglee-lazada** [ben-manes/caffeine#598]
https://javadoc.io/doc/com.github.ben-manes.caffeine/caffeine/2.9.2/com/github/benmanes/caffeine/cache/LoadingCache.html#getAll-java.lang.Iterable-

`RuntimeException - or Error if the CacheLoader does so, if CacheLoader.loadAll(java.lang.Iterable<? extends K>) returns null, returns a map containing null keys or values, or fails to return an entry for each requested key. In all cases, the mapping is left unestablished
 `

From the documentation, I thought that when loadAll has missing values, it should give a RuntimeException. But it seems like it simply returns a partial result..

**Comment by ben-manes** [comment]
Yes, I noticed this recently as well and fixed the [JavaDoc](caffeine/src/main/java/com/github/benmanes/caffeine/cache/LoadingCache.java) on master. I’ll backport that to 2.x as well.

I think this was an oversight when first flushing out the api and deciding on how to handle absent results. The behavior is correct.
