### ISSUE TITLE
Bulk load and blocking

### ISSUE THREAD

**Issue by cruftex** [ben-manes/caffeine#601]
I recently completed (blocking) bulk loading support in cache2k. Just looked at Caffeines implementation, which seems to be non-blocking. However, the documentation at `LoadingCache.getAll` is ambivalent, so I am not sure whether I did look at the right places:

````
  /**
   * [...]
   * Returns a map of the values associated with the {@code keys}, creating or retrieving those
   * values if necessary. The returned map contains entries that were already cached, combined with
   * the newly loaded entries; it will never contain null keys or values.
   * <p>
   * Caches loaded by a {@link CacheLoader} will issue a single request to
   * {@link CacheLoader#loadAll} for all keys which are not already present in the cache. All
   * entries returned by {@link CacheLoader#loadAll} will be stored in the cache, over-writing any
   * previously cached values. If another call to {@link #get} tries to load the value for a key in
   * {@code keys}, implementations may either have that thread load the entry or simply wait for
   * this thread to finish and returns the loaded value. In the case of overlapping non-blocking
   * loads, the last load to complete will replace the existing entry. Note that multiple threads
   * can concurrently load values for distinct keys.
   * [...]
   */
  Map<K, V> getAll(Iterable<? extends K> keys);
````

Which `implementations` is this referring to and which one is blocking or non-blocking?

**Comment by cruftex** [comment]
Thanks for the explanation! I did not check the async implementation. I suggest adding the above to the Java doc, since others might stumble there as well. Close the issue at your own discretion.

**Comment by ben-manes** [comment]
Okay, I'll ponder a bit about how to improve the docs and see where it could be made clearer.

**Comment by ben-manes** [comment]
Updated the [FAQ](https://github.com/ben-manes/caffeine/wiki/Faq#bulk-loads) to explain the behavior more clearly.
