### ISSUE TITLE
put top(k) entry

### ISSUE THREAD

**Issue by Stulcc** [ben-manes/caffeine#608]
this is my scene:I use caffeine as a localCache ,use redis as a remoteCache。There is many keys。 first I get data from  caffeine, if not exists,Iwill get from remoteCache,when response I put to caffeine（but not really put，I want caffeine begin record this key visit frequency，If max，will really put）,  next time i will get data from  caffeine， I will put many keys。memory is expensive，I only want to put Top(K) visit entry into  caffeine。caffeine support it？

**Comment by ben-manes** [comment]
The cache will intelligently keep entries based on recency and frequency. You shouldn’t need to provide any hints. Instead load and store through the cache and trust it to make good decisions. Internally we maintain a histogram to filter out new arrivals that are less popular than the victim, which is similar to what you described.

**Comment by Stulcc** [comment]
static Cache<String, String> cache;

    static {
        cache = Caffeine.newBuilder().maximumSize(10)
                .executor(Runnable::run)
                .removalListener(new RemovalListener<String, String>() {
                    @Override
                    public void onRemoval(@Nullable String key, @Nullable String value, @NonNull RemovalCause cause) {
                        System.out.println("remove："+key+":"+cause);
                    }
                })
                .build();
    }

    public static void main(String[] args) throws InterruptedException {
        for (int i = 0; i < 10; i++) {
            cache.put(String.valueOf(i), String.valueOf(i));
        }
        for (int i = 0; i < 10; i++) {
            for (int j = i; j < 100; j++) {
                cache.getIfPresent(String.valueOf(i));
            }
        }
        // I put a new Key,but I don't want it really put,because maybe it will not visit high frequency
        // it maybe replace a old key I very needed
        cache.put("10","10");
        Thread.sleep(3000);
        System.out.println(cache.estimatedSize()+"："+cache.asMap());
    }

**Comment by ben-manes** [comment]
That has a uniform distribution, as we retain history outside of the working set. A zipfian distribution would have a hit rate like below, as web pages follow that request pattern. We use the W-Tinylfu policy.


![](https://raw.githubusercontent.com/ben-manes/caffeine/master/wiki/efficiency/wikipedia.png)
