### ISSUE TITLE
Provide documentation on best practices for testing `Weigher` functionality

### ISSUE THREAD

**Issue by drcrallen** [ben-manes/caffeine#61]
As per https://github.com/metamx/druid-cache-caffeine/pull/7 , being able to properly unit test if a `Weigher`s eviction is behaving as expected is not straight forward. This ask is to add documentation for best practices for how to properly ensure a project's cache `Weigher` is behaving as intended when used in the caffeine cache.

**Comment by ben-manes** [comment]
Added a [Testing](https://github.com/ben-manes/caffeine/wiki/Testing) wiki page. Hope that's helpful. Thanks!
