### ISSUE TITLE
`Weigher` creation using lambdas is highly sensitive to typing at compile time.

### ISSUE THREAD

**Issue by drcrallen** [ben-manes/caffeine#62]
As a simple example:

```java
Caffeine<String, String> builder = Caffeine.newBuilder().recordStats();
builder = builder.weigher((String key, String val) -> key.length() + val.length());
```

Fails to assign the first builder from: `incompatible types: com.github.benmanes.caffeine.cache.Caffeine<java.lang.Object,java.lang.Object> cannot be converted to com.github.benmanes.caffeine.cache.Caffeine<java.lang.String,java.lang.String>`

```java
Caffeine<Object, Object> builder = Caffeine.newBuilder().recordStats();
 builder = builder.weigher((String key, String val) -> key.length() + val.length());
```
fails with 

```
incompatible types: inference variable K1 has incompatible bounds
equality constraints: java.lang.Object
upper bounds: java.lang.String,java.lang.Object
```

```
Caffeine builder = Caffeine.newBuilder().recordStats();
builder = builder.weigher((String key, String val) -> key.length() + val.length());
```

fails weigher assignment with `incompatible types: incompatible parameter types in lambda expression`

The following behaves as expected with assigning a weigher:

```
@SuppressWarnings("unchecked")
Caffeine<String, String> builder = (Caffeine)Caffeine.newBuilder().recordStats();
builder = builder.weigher((String key, String val) -> key.length() + val.length());
```

**Comment by ben-manes** [comment]
True, but why are you reassigning the builder? It becomes a moot point if you don't, e.g.

```java
Caffeine<Object, Object> builder = Caffeine.newBuilder().recordStats();
if (maximum >= 0) {
  builder.maximumWeight(maximum)
         .weigher((String key, String val) -> key.length() + val.length());
}
Cache<String, String> cache = builder.build();
```

**Comment by drcrallen** [comment]
@ben-manes yes, you are a faster typer than I am. This issue is an attempt at documenting some of the (minor) issues I came across implementing a weigher. Hopefully someone searching for similar problems will find this thread later and use your suggestion in https://github.com/ben-manes/caffeine/issues/62#issuecomment-204101123

**Comment by ben-manes** [comment]
Oh! Sorry, I didn't realize that was a documentary issue and not a question.
