### ISSUE TITLE
Doubts about the reload method under CacheLoader

### ISSUE THREAD

**Issue by zkj1374960803** [ben-manes/caffeine#622]
Dear expert, Hello

My code is as follows:
```java
LoadingCache<String, Object> cache = Caffeine.newBuilder()
                .refreshAfterWrite(4, TimeUnit.SECONDS)
                .expireAfterWrite(3, TimeUnit.SECONDS)
                .build(new CacheLoader<String, Object>() {
                    @Override
                    public Object load(String key) throws Exception {
                        return key + "_load";
                    }

                    @Override
                    public Object reload(String key, Object oldValue) throws Exception {
                        return key + "_reload";
                    }
                });
```
When the reload method is triggered,
The value I fetched from the `cache` is oldValue the first time, and newValue the second time. 
I want to know why this is? 
Is there any way to get newValue the first time?

**Comment by ben-manes** [comment]
The `expireAfterWrite` setting has to be larger than the `refreshAfterWrite` setting. In your configuration the entry expires first, and an expired value cannot be returned as it is no longer valid. Therefore the caller is penalized by waiting for the load to complete and a refresh will never take effect.

The intent is for refresh to be shorter than the expiration time. When an entry is present, eligible for refresh, not expired, and queried for, then the reload method is called asynchronously. The callers are not blocked and receive the existing (old) value until the reload completes and replaces the entry. The intent is to return valid but possibly stale content while hiding the loading latency.

An example might be configuration flags used by every request and stored in the database. A query to the db for every request for the latest setting might be excessive so a client-side cache is used with a short expiration time to reduce the inconsistencies. This creates a periodic delay when the entry expires and all requests block waiting on a fresh load. By adding `refreshAfterWrite` with a shorter duration, the request latency smooths out as it always finds a cached entry which is kept consistent from the reloads happening behind the scene. If user activity drops, e.g. the machine is removed from rotation, then the expiration will discard the entry and a fresh, blocking load will occur when activity starts up again.

**Comment by zkj1374960803** [comment]
Thank you very much for your reply.

As you said, the time settings of `expireAfterWrite` and `refreshAfterWrite` are problematic. I made a mistake by accident, sorry.
You mentioned above that the `reload `method is called asynchronously, but I see the `asyncLoad `method under the CacheLoader. Since reload is already called asynchronously, why provide an `asyncLoad` method?

Another question is, do you have any good methods to solve the problem of cache penetration? Taking the above code as an example, when there are a large number of nonexistent key requests (malicious attacks), the `load `method will be called, and the `load `method will query the DB, which may crush the database. However, the load method has to query the database, because I can't distinguish whether the key is normal or maliciously attacked.

Do you have any good ideas?

**Comment by ben-manes** [comment]
> You mentioned above that the reload method is called asynchronously, but I see the asyncLoad method under the CacheLoader. Since reload is already called asynchronously, why provide an asyncLoad method?

The cache never actually calls `reload` and only invokes `asyncLoad`. `CacheLoader` has a default implementation which wraps its `reload` method with an `CompletableFuture.supplyAsync` call. This makes the `reload` a convenience method if your logic can be expressed synchronously, but if not then `asyncLoad` could be overridden instead.

> do you have any good methods to solve the problem of cache penetration?

A simple solution to your scenario of a query storm for absent entries is to use _negative caching_. An `Optional<V>` value can be cached instead of `V` and unwrapped by the caller. This will avoid redundant queries when absent and is inexpensive when present.

**Comment by zkj1374960803** [comment]
> A simple solution to your scenario of a query storm for absent entries is to use negative caching.
I tried it. The code is as follows:
`LoadingCache<String, Optional<Boolean>> cache = Caffeine.newBuilder()
                .refreshAfterWrite(6, TimeUnit.SECONDS)
                .expireAfterWrite(10, TimeUnit.SECONDS)
                .build(new CacheLoader<String, Optional<Boolean>>() {
                    @Override
                    public Optional<Boolean> load(String key) throws Exception {
                        boolean suspended = notifyMetaDao.getMeta(key).getSuspended();
                        return Optional.ofNullable(suspended);
                    }
                    @Override
                    public Optional<Boolean> reload(String key, Optional<Boolean> oldValue) throws Exception {
                        boolean suspended = notifyMetaDao.getMeta(key).getSuspended();
                        return Optional.ofNullable(suspended);
                    }
                });`

However, this does not solve the problem of cache penetration.
Am I wrong?

**Comment by ben-manes** [comment]
Why not? If `suspended` is not in the database then you would cache `Optional.empty()`. If it is then you have value in `Optional<Boolean>` to perform action on. The cache will hold the entry until it expires, and reloading it if accessed within the refresh period. In either case it can return without performing a database call while in the cache.

**Comment by zkj1374960803** [comment]
Yes, you are not wrong.
The `notifyMetaDao.getMeta(key)` step is to query the DB. Note that there is nothing in the `cache `variable at this time. Now I call` cache.get("someKey")`, then the `load `method will be called, and the `load `method will query the DB. If there are a large number of such keys, wouldn't the db crash? (These keys are not real in the db, they are malicious attacks)

**Comment by ben-manes** [comment]
I see, you mean distinct keys. That would be a different problem than what the cache is trying to solve. Typically one would solve that using a variety of approaches. A classic example is a membership sketch, such as a Bloom filter, which allows you to probabilistically know if the key exists (false positives, but negative is absolute). This can be stored compactly, e.g. some databases maintain these internally to avoid disk I/O. Of course in the end a flood of malicious queries can overload an upstream proxy, so anomaly detection and traffic shaping to limit malicious actors might afford most of the protection needed.

**Comment by zkj1374960803** [comment]
Thank you very much, Ben, for solving my doubts, I confused these two questions together.

**Comment by ben-manes** [comment]
you're very welcome.
