### ISSUE TITLE
RefreshAfterWrite and short lived cache

### ISSUE THREAD

**Issue by pierre-leonard** [ben-manes/caffeine#626]
Hi,

I'm having some issues with caffeine and I was wondering if this was a limitation of the library or (more likely) if I was using it the wrong way. 

We have a short lived cache (5 seconds) to keep some values that take a couple of seconds to generate (network access and some calculations). When a value is queried, It's better for us to return an old value than to wait for a fresh value so we use refreshAfterWrite and not expire. Still, we don't want this value to be too old.

I could reproduce our issue by running the following code (it has to run for some seconds):

```
public class Main {

    private final LoadingCache<Integer, Instant> cache = Caffeine.newBuilder()
            .maximumSize(500)
            .refreshAfterWrite(Duration.ofSeconds(5))
            .build(key -> getInstant(key));

    public static void main(String[] args) throws Exception {
        Main main = new Main();
        main.runTest();
    }

    void runTest() throws Exception{
        //Init the values before the test
        for(int i = 0; i < 500; i++){
            cache.put(i, Instant.now());
        }
        do{
            //Simulates client requests (one every 1/10 sec)
            Thread.sleep(100);
            new Thread(() -> {
                for(int i = 0; i < 500; i++){
                    Instant cacheValue = cache.get(i);
                    if(cacheValue != null && Instant.now().isAfter(cacheValue.plusSeconds(6))){
                        System.out.println("returned data for key " + i + " is " + Duration.between(cacheValue, Instant.now()).getSeconds() + " s. old");
                    }
                }
                System.out.print(".");
            }).run();

        }while(true);
    }

    public Instant getInstant(Integer key) throws Exception{
        Thread.sleep(2000); //Simulates a network connection
        return Instant.now();
    }
}
```

Is there a better way to proceed? I noticed that the issue disappears if we remove the sleep in the getInstant, everything seems fine.

**Comment by ben-manes** [comment]
It looks like your test is flooding the executor by blocking its limited number of threads. The default is the `ForkJoinPool.commonPool()` which has a fixed number of threads (based on the number of cpu cores) and is not optimal for blocking operations. This causes only a few reloads to be in-flight at once, so the refreshes drag out longer than desired. When setting to `Caffeine.executor(Executors.newCachedThreadPool())` then it behaves as you would expect (max 7s old).

**Comment by pierre-leonard** [comment]
Thank you so much for the fast answer. I confirm this does the trick for me as well!
