### ISSUE TITLE
Safety of recursive Get operation

### ISSUE THREAD

**Issue by superyuuki** [ben-manes/caffeine#631]
I'm a newbie to threadsafety. Let's say i have a Cache<K, List<V>> where V is a recursive key of the cache. Users can request all children of a key K. The children will have their sub-children retrieved, and the sub-children have their sub-sub-children retrieved until no more nodes can be located. This works adequately with a loading function which, upon not having a value for K, will request a database for only the immediate children, and stays within the cache function's expected atomic operation. However, i want to reduce the amount of queries to the database, since if a key is missing, potentially a query must be run for every single child and their descendants. I'd like to perform a modified get function that has the power to update multiple keys at once, but that breaks the expected contract of the get operation. Will it still function safely?

**Comment by superyuuki** [comment]
Additionally, assuming these database queries are heavy, would it be optimal to use an AsyncCache instead, or use a Cache and manually schedule the cache interactions (recursive searching) in a separate executor. That way, more work can be done in a single runnable and potentially avoid the costs of lots of asynchronous tasks being spawned?

**Comment by ben-manes** [comment]
That is a complex example. I think to understand it better we might need to expand on it into more concrete code. If you're free right now, I'd be fine chatting on a Zoom if that helps.

The underlying `ConcurrentHashMap` does not support recursive computations. This means that an atomic load for K1 cannot itself perform an atomic load for K2. That could lead to deadlocks if another thread locks in the reverse order (and this is true even for the regular HashMap which will corrupt itself).

Most of the time instead of locking through the map, you can insert a placeholder value that is locked on separately to load the value (e.g. a future). If that usage then ensures a correct ordering of lock acquisitions there is no fear of a deadlock. This can be done using `AsyncCache` as you mentioned, and does not require extra threads for loading. The [FAQ entry](https://github.com/ben-manes/caffeine/wiki/Faq#recursive-computations) shows a simple example using a recursive factorial. Does that help your scenario?

**Comment by superyuuki** [comment]
Hey, I'd be down for a zoom call, if you don't mind dealing with an utter newbie.

**Comment by ben-manes** [comment]
> That way, more work can be done in a single runnable and potentially avoid the costs of lots of asynchronous tasks being spawned?

Yes, this is how the `getAll` works for an async cache. It can insert incomplete futures for the missing entries, perform a bulk load, and complete them. Unfortunately a synchronous cache suffers from the the above mentioned issue since it uses the map's computations, so it side loads (thereby allowing for a cache stampede).

> Hey, I'd be down for a zoom call, if you don't mind dealing with an utter newbie.

Great,
https://zoom.us/my/ben.manes

**Comment by ben-manes** [comment]
glad to have helped, good luck! 😃

**Comment by ben-manes** [comment]
It seems only the user guide mentioned the tidbit about bulk loading more than requested. I'll update the JavaDoc to provide that hint in the various places. The below applies to both the synchronous and asynchronous caches, and the cache loaders merely delegate with a mapping function to the `getAll` methods so equivalent behaviors. 

> Note that you can write a AsyncCacheLoader.asyncLoadAll implementation that loads values for keys that were not specifically requested. For example, if computing the value of any key from some group gives you the value for all keys in the group, asyncLoadAll might load the rest of the group at the same time.

**Comment by superyuuki** [comment]
One more question: getAll only returns a map view of the keys explicitly requested, even if more are loaded. Is there a way to return a map view containing all keys loaded, or is that unsafe?

**Comment by ben-manes** [comment]
It would make the API very confusing because the number of mappings could change across calls. The first call causing a load would receive the group, whereas the subsequent ones wouldn't as the key is cached. Therefore it acts more like prefetching additional data that is likely useful sometime in the future.

If you are trying to capture only for that load then you could infer it by using a capturing lambda. The lambda could write to a mutable thread-scoped field, e.g.
```java
var group = new AtomicReference<Map<K, V>>();
var result = cache.getAll(List.of(key), keys -> {
  var loaded = ...
  group.set(loaded);
  return loaded;
});

var loaded = group.get();
if (loaded == null) {
  // cache read, use result
} else {
  // cache load, use loaded
  // (if multiple query keys, result + loaded)
}
```

**Comment by ben-manes** [comment]
I think from your original question and our discussion, you'll probably need to do more orchestration yourself to coerce the exact behavior that you want regarding bulk loads and recursive computes. See the factorial example, which you could redo into setting up the bulk load operation. 

```java
AsyncCache<Integer, Integer> cache = Caffeine.newBuilder().buildAsync();

int factorial(int x) {
  var future = new CompletableFuture<Integer>();
  var prior = cache.asMap().putIfAbsent(x, future);
  if (prior != null) {
    return prior.join();
  }
  int result = (x == 1) ? 1 : (x * factorial(x - 1));
  future.complete(result);
  return result;
}
```

**Comment by superyuuki** [comment]
That may work, however, i've noted some issues with using getAll even as intended. I run a getAll operation loading a map with keys 1,2,3 and values 1,2,3, with the official query id as 1. The query returns a sub-map with key 1 mapped to value 1, however when further queries to the cache are made (via method Get), they all are made to the cache loading function instead of cached values, suggesting that the extra keys and values loaded from the getAll map are not being cached. Any suggestions?

**Comment by superyuuki** [comment]
Actually would turn out that my test was broken lol

**Comment by ben-manes** [comment]
I wrote a quick unit test, and will likely check to see if an existing one exists or needs to be added. This runs against Caffeine and Guava across various configurations. It passes, so can you write one that fails and to help us debug?

```java
@CacheSpec
@Test(dataProvider = "caches")
public void getAll_function_exceeds(Cache<Int, Int> cache, CacheContext context) {
  var key = context.absent().keySet().iterator().next();
  var value = context.absent().get(key);
  var results = cache.getAll(Set.of(key), keys -> context.absent());
  assertThat(results).containsExactlyEntriesIn(Map.of(key, value));

  var expected = new ImmutableMap.Builder<Int, Int>()
      .putAll(context.original())
      .putAll(context.absent())
      .build();
  assertThat(cache).containsExactlyEntriesIn(expected);
}
```

**Comment by superyuuki** [comment]
Your test works. My test was broken in that it made the assumption that the future returned by loading cache's getAll would be completed when the function providing the map was completed. It seems to me with the code

```
AsyncLoadingCache<Integer, List<Integer>> testCache = Caffeine.newBuilder().buildAsync(new MockCacheLoader());

        testCache.getAll(List.of(1)).thenRun(() -> {

            logger.info(() -> "running");

            Objects.requireNonNull(testCache.get(2)).thenAccept(li -> {
                logger.info(() -> String.valueOf(li));
            });

            logger.info(() -> "end");


        })
        
public class MockCacheLoader implements AsyncCacheLoader<Integer, List<Integer>> {
    @Override
    public CompletableFuture<? extends List<Integer>> asyncLoad(Integer key, Executor executor) throws Exception {
        throw new IllegalStateException("NO: Key loaded: " + key); //TODO impl
    }

    @Override
    public CompletableFuture<? extends Map<? extends Integer, ? extends List<Integer>>> asyncLoadAll(Set<? extends Integer> keys, Executor executor) throws Exception {
        return CompletableFuture.supplyAsync(() -> Map.of(
                1, List.of(2,3),
                2, List.of(4,5),
                3, List.of(6,7),
                4, List.of(8),
                5, List.of(),
                6, List.of(9),
                7, List.of(),
                8, List.of(),
                9, List.of()
        ));
    }
}

 ```
        the completablefuture from testCache.get in the thenAccept block seems to make a call to asyncLoad and therefore throws an exception, even though in my head it should be using a future derived from asyncLoadAll's returned map.

**Comment by superyuuki** [comment]
Would you mind calling?

**Comment by superyuuki** [comment]
Interestingly enough, the test works fine when i use CompletableFuture.completedFuture.

**Comment by ben-manes** [comment]
> Would you mind calling?

pardon?

**Comment by superyuuki** [comment]
zoom call, sorry

**Comment by ben-manes** [comment]
oh of course.
https://zoom.us/my/ben.manes

**Comment by ben-manes** [comment]
The async bulk loads is fairly simple logic and you might manage that yourself to handle loading the tree's children. Here are the steps it performs,

```
For every key requested:
  try to insert key->future into cache
  if added:
    track for keys to load
  else:
    track for results

If keys to load:
  perform the bulk load
  for keys to load:
    complete the key's future with its value or error
    add to results
  for any extra mappings:
    insert into the cache

return results
```

The first block is performed by this [getAll](https://github.com/ben-manes/caffeine/blob/a681c680072d377f40fb9d724f70030652339c24/caffeine/src/main/java/com/github/benmanes/caffeine/cache/LocalAsyncCache.java#L118-L148) code, while the second is done by the [async completer](https://github.com/ben-manes/caffeine/blob/a681c680072d377f40fb9d724f70030652339c24/caffeine/src/main/java/com/github/benmanes/caffeine/cache/LocalAsyncCache.java#L222-L292). Your own version could be simpler as fewer edge cases to handle. The cache's implementation returns to the caller only the keys requested, but yours could return more if desired.

To avoid the future's LIFO behavior of invoking dependent actions, your bulk loader could insert the additional mappings into the cache immediately before returning the results. For example,

```java
cache.getAll(List.of(1, 2, 3), keys -> {
  var results = db.load(keys); // 1-5
  cache.putAll(results);
  return results;
}).thenRun(() -> {
  cache.get(5); // high chance to be present (but could be evicted!)
  ...
);
```

That matches your code, but avoids the ordering problem by inserting directly. Of course the cache can evict at any time so it might miss, which would force another database load (but probably unlikely to occur).

**Comment by superyuuki** [comment]
This seems interesting, but wouldn't cache.putAll defeat the purpose of the getAll? Alternatively, i could try to manually reimplement the code you linked me from localAsyncCache, except i don't have access to internal methods provided by LocalCache

**Comment by ben-manes** [comment]
The putAll would fix the dependent action ordering to let you know that the entries were in the cache by the time your action runs. Ideally the getAll would do that, but the LIFO execution meant you observed a gap.

I don't think you need the internal methods, most are equivalent to `asyncCache.asMap()` calls. The stats, weight, expiration, etc should be picked up by the cache automatically if using the asMap view, but for efficiency were handled more in batch here so ignorable.

**Comment by superyuuki** [comment]
Hey ben! I've decided to avoid the getAll putAll operation in favor of using modified getAll code. I'd like your consensus on it if you aren't busy to make sure i'm not making the same mistake as i did before. Additionally, i have some unrelated questions (that you can opt to skip) about the lifo vs fifo architecture and also looking into redisson.

**Comment by superyuuki** [comment]
Thanks so much for the links and examples by the way. Really makes this a lot easier!

**Comment by ben-manes** [comment]
oh that's great! I can chat now,
https://zoom.us/my/ben.manes

**Comment by ben-manes** [comment]
I was thinking you could use something like [maxwells-daemon.io](http://maxwells-daemon.io/) to track the database changes. Then replicate to the client and store in an embedded H2. Your queries would then run locally, letting the embedded db handle the in-memory vs disk side. That might be overly complex, but could also be a fast way to have local caches to avoid long network hops, etc.

**Comment by superyuuki** [comment]
That seems like an interesting solution to look into! There are so many interesting ways to solve this problem that i think i'm going to have to take a bit longer to look at this haha. Currently considered are

- getAll, putAll
- redis
- anti-stampede simple one time load (and then put all children and their children...)
- replicated database

Furthermore after more consideration of how other game systems handle their data loading and saving, a primarily in-memory-oriented storage solution with some kind of message pubsub to handle changes may or may not be a solution to pursue, although i'll need to weight the pros and cons of that too. I definitely have a lot more architecture changes to make, including some kinds of opportunistic pre-loaders so that for the most part these recursive cache queries never happen in the first place!

**Comment by superyuuki** [comment]
BEN BEN I FIGURED IT OUT (pardon my excitement)

What do you notice here? I noticed something.

```
var completer = new AsyncBulkCompleter<K, V>(cache(), proxies);
    try {
      mappingFunction.apply(proxies.keySet(), cache().executor()).whenComplete(completer);
      return composeResult(futures);
    } catch (Throwable t) {
      completer.accept(/* result */ null, t);
      throw t;
    }
```

You see, in the implementation of LocalAsyncCache's getAll, i've noticed something about what happens when values need to be loaded. The future returned by composeResult **only takes into consideration futures that are already cached.** In no way is the future returned from the mappingFunction or whenComplete ever taken into consideration by the future being returned. As a result of that, of course the future returned from the getAll call is going to be unreliable as an indicator of when component loading is being done. It isn't being returned!

Now i still have my concerns about the Lifo stack, since even if we make sure that the returned future takes into consideration the mapping function i do not know enough about the architecture of futures to guarantee to my mind that the future at the end will still be accurate, but i do believe that based on my understanding on futures this would resolve the issue. However, i do not know if this fix would be in accordance with the contract you've set for the getAll method.

**Comment by superyuuki** [comment]
I'll be preparing a pull request after I review the documentation of getAll some more to see whether getAll explicitly states that it will return a result that takes into consideration the values loaded during the scope of the mappingFunction.

**Comment by ben-manes** [comment]
haha, congrats! I'm not sure that I totally grok your observation yet (since I read but did not try to think about it). I'd be happy to jump on a zoom call again once you're ready.

Okay, thinking about it a tiny bit and I see your point. The `composeResult(futures)` completes when the per-entry futures are completed. That could be before the completer finishes its work, e.g. due to extra entries, since the two are decoupled. It does take into account the futures for requested keys that will be loaded (the added `proxy` futures). Still, this does open up a race condition if you expect the extra entries to be observed by the time the requested group is completed.

**Comment by superyuuki** [comment]
Unable to hop in a call right now since i am eating, but will be free in aprox. 1-2 hours to have a discussion about both this and my solution to the recursion problem. I was under the impression that the getAll method would return a future representing a map that is accurate to every key requested, so even without extra entries taken into consideration, the current implementation violates that by only guaranteeing locally cached values to be present in the resulting future, and relies on the assumption that any values computed in the getAll call will be loaded into cache in time for the cache user to read.

**Comment by ben-manes** [comment]
oh that is not true. The `futures` variable is a mapping of every requested key to its future value. That includes both the entries found and those inserted for loading. See the `if (future == null)` below.

https://github.com/ben-manes/caffeine/blob/a681c680072d377f40fb9d724f70030652339c24/caffeine/src/main/java/com/github/benmanes/caffeine/cache/LocalAsyncCache.java#L118-L134

**Comment by superyuuki** [comment]
Oh, i see. Not sure how I missed that!
