### ISSUE TITLE
Caused by: java.lang.IllegalStateException: com.github.beanmanes.caffeine.cache.SIMSA

### ISSUE THREAD

**Issue by HuiWang1995** [ben-manes/caffeine#633]
HI!
I face the issue that like this: https://github.com/ben-manes/caffeine/issues/491
But my caffeine version is **2.9.2**, and SpringBoot version is **2.0.8.RELEASE**

code:
![61c76f9e217dcddaa793ac785c50965](https://user-images.githubusercontent.com/23615350/145218738-14cda6ac-d9e6-4196-a50b-8808c9623877.jpg)

I'm not sure this issue appear because of `LaunchedURLClassLoader` in SpringBoot.
Sincerely ask for your help

stack:
![1c3ac80d89554cefcdd6a7a23e98c65](https://user-images.githubusercontent.com/23615350/145218339-90cd35bd-0893-43e2-8b71-5d30af37dc72.jpg)
![dbecf7fa1a30206a024dbfda3ca4894](https://user-images.githubusercontent.com/23615350/145218686-37e0cc4a-0717-4d0b-b168-3bc5123ebcc7.jpg)

**Comment by potatoxf** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，我已经收到您的邮件

**Comment by HuiWang1995** [comment]
sorry, the code is in inner network, that i cannot parse it. So I provide photos

**Comment by HuiWang1995** [comment]
> It would be helpful to know what the recursive calls for `loadClass` are trying to obtain. If you were able to reproduce in a minimal project then I could investigate, but unfortunately like with the prior issue this is not enough for me to assist on.
> 
> Caffeine code generates optimized classes based on the configurations to avoid extra fields, e.g. per-entry metadata. This is very simple and straightforward reflection to load the class. If you have some security layer that restricts this then you'll need to whitelist the classes. You can start tracing from `NodeFactory.newFactory`.

Thank you for your reply!

I have solved this problem, although I don't know the specific reason.



This problem doesn't exist on all my servers. I've looked at it and set the size of all JVM virtual machine stacks to -Xss256k, which is four times smaller than the default -Xss1m.



When I try to set it to -Xss1m, the problem is solved, although it seems to be called recursively from the stack.

**Comment by ben-manes** [comment]
Congrats! I’m not sure why caffeine would have been the trigger since the generated type hierarchy is shallow and simple. I’m glad it’s working now.
