### ISSUE TITLE
Binary compatibility between 2.x and 3.x

### ISSUE THREAD

**Issue by zeldigas** [ben-manes/caffeine#636]
Hello,

I have a library that depends on caffeine. Library is built against java 8 because current clients are both java 8 and 11, so I need to use caffeine 2.x with it.

The question I have - if caffeine binary compatible in api (minus removed deprecations) between 2.x and 3.x? The reason I'm asking  - this would let clients that rely on java 11+ to configure dependency on latest caffeine version thus overriding transitive dependency from my module. Without that I'll have to provide 2 versions.

I understand that I can go and check myself, but decided to ask first + that might be helpfull for others as well.

**Comment by ben-manes** [comment]
Yes, for almost all usages it is drop-in compatible. There is only a little work if you implemented a StatsCounter or CacheWriter, but otherwise it’s the same from a user’s perspective.

**Comment by zeldigas** [comment]
Thank you!
