### ISSUE TITLE
Caffeine can cause a dead cycle

### ISSUE THREAD

**Issue by jerryMouse7** [ben-manes/caffeine#638]
operate system: win10
jdk version: 1.8
caffeine version: 2.9.2
When I used spring to integrate caffeine, I found that it would cause an endless loop.
code example:
``` 
    static Cache<Object, Object> deptAndGroupCache = Caffeine.newBuilder().expireAfterWrite(5, TimeUnit.SECONDS).maximumSize(10).build();
    public static void main(String[] args) {
        Map<String,String> nameToDeptMap = (Map<String, String>) deptAndGroupCache.get("allDept", (obj1) ->{
            List<String> allDepts = new ArrayList<>(Arrays.asList("1","2"));
            Map<String,String>  CachedNameToDeptMap = allDepts.stream().collect(Collectors.toMap(orgUnit -> orgUnit, orgUnit -> orgUnit));
            deptAndGroupCache.put("allDept",CachedNameToDeptMap);
            return CachedNameToDeptMap;
        });
        System.out.println(nameToDeptMap);
    }
```
When I put data into the cache, it will cause boundedlocalcache.data(which is a concurrentHashMap)  endless loop. 
I noticed that in this concurrenthashmap, the key of a node is null and the value is null.

**Comment by ben-manes** [comment]
ConcurrentHashMap does not allow writes within a computation. In Java 9+ this is detected and throws an error. See this [answer](https://stackoverflow.com/a/28845674) for more details.

The faq describes a possible workaround.

**Comment by jerryMouse7** [comment]
ok. thank you
