### ISSUE TITLE
Async Load All result is ignored when its size matches the cache size 

### ISSUE THREAD

**Issue by jonathannaguin** [ben-manes/caffeine#655]
Hello,

When my application starts I want to fill the cache with items so I am running this:
```
var cache = Caffeine.newBuilder()
                             .refreshAfterWrite(Duration.ofMinutes(5))
                             .buildAsync(this);
cache.getAll(List.of("*")) .get();
```

Disclaimer: I can't use a empty list, otherwise the `AsyncCacheLoader` never gets invoked (see https://github.com/ben-manes/caffeine/blob/5e834f8fdcf3819a242da7a44d7e62c7fde0ab2a/caffeine/src/main/java/com/github/benmanes/caffeine/cache/LocalAsyncCache.java#L138-L140).

So my only option is to use a dummy key like "*", this works fine and my `asyncLoadAll` gets called and I can return a map of items.
The problem I have is when this method returns one single item as this piece of code assumes the entry returned is the same as the one used in the getAll invocation: https://github.com/ben-manes/caffeine/blob/5e834f8fdcf3819a242da7a44d7e62c7fde0ab2a/caffeine/src/main/java/com/github/benmanes/caffeine/cache/LocalAsyncCache.java#L278-L280

**Comment by ben-manes** [comment]
Oh, that's a good catch. I agree that size comparison looks unnecessary and wrong. I was able to confirm your problem and fix in a unit test. My weekdays are hectic so more often I work on a release over the weekend, so hopefully I can get that to you by next Monday.

**Comment by jonathannaguin** [comment]
Thanks a lot @ben-manes !

**Comment by ben-manes** [comment]
Hi @jonathannaguin,

I apologize but it looks like I won't be ready to release this weekend. I have been assisting two other teams privately which require have minor API changes in the `Cache.policy() extensions (one is a persistent and the other is a distributed cache). Those discussions and iterations have split my free time for this project. I'll try to make their changes over this coming week and have something ready soon.

In the meantime if this is causing trouble then you might either (a) return an extra dummy unreachable entry to skip this guard or (b) use jitpack.io to temporarily depend on the fixed commit.

Thanks again for the bug report and your patience.

**Comment by jonathannaguin** [comment]
Hey @ben-manes, no problem, I am using a dummy value until this gets released.
Thanks a lot for your support.

**Comment by ben-manes** [comment]
Sorry for the long delay, this has been released.
