### ISSUE TITLE
AsyncLoadingCache has no stats method

### ISSUE THREAD

**Issue by iroh** [ben-manes/caffeine#66]
Does the AsyncLoadingCache support collecting stats? If it does, it is not well documented how to use it.

**Comment by ben-manes** [comment]
It is a hop away through `AsyncLoadingCache#synchronous()` which provides a `LoadingCache` view. This allowed keeping the interface small and focused with minimal pain for the less frequently used calls, which usually means its easier to grok. So you can write,

```java
CacheStats stats = cache.synchronous().stats();
```
I think that is a good compromise for now. If there are requests for an `AsyncCache` (non-loading) then for symmetry the view's methods would be promoted as default methods doing the above. I made it easy to extract that interface, but didn't see a good need for it. Given that I might be wrong, its easy to add based on feedback.

Do you have any recommendations for where to improve the documentation to make this more apparent?

**Comment by ben-manes** [comment]
Closing. If you have recommendations to improve the documentation and/or API, please let me know.
