### ISSUE TITLE
Deterministic removal of entries

### ISSUE THREAD

**Issue by asad-awadia** [ben-manes/caffeine#669]
Hey Ben,

Is it possible to achieve deterministic removal of entries on caches that are separate instances given the same set of writes but differing reads such that they are always in sync?

I would like to have a maximum size so that the cache is bounded but I think with max size the eviction can be different if the keys were accessed differently on the two instances

**Comment by asad-awadia** [comment]
what if they are on multiple machines?

For more context - I am trying to build a replicated cache using raft and want to make sure that the caches will stay in sync

**Comment by ben-manes** [comment]
In that case I'd use map computations and a listener to broadcast invalidations. The complexity is of course in your distribution layer and how strongly you want to handle consistency. Caffeine is just the in-memory store. When I first started exploring caching, at that role I implemented a simple scheme using a message topic to invalidate local caches with a memcached remote layer. That was good enough for that product's use-case where the remote cache absorbed the cost of local misses.

You could look at other distributed caches for inspiration. Caffeine is used by Infinispan and Redisson, and a switch by Coherence is in development. Other distributed Java caches are Geode, Ignite, Hazelcast, and Gigaspaces. I think Infinispan uses JGroups with Raft under the hood. Redis' recent [server-assisted client side caching](https://redis.io/topics/client-side-caching) might be good enough for many use-cases. There are a lot of tradeoffs and how deep one goes, so Caffeine's only objective is to offer enough hooks to allow for a broader framework to solve those other hard problems.

**Comment by asad-awadia** [comment]
hmm - ok ok I see thank you!
