### ISSUE TITLE
About Memory

### ISSUE THREAD

**Issue by MrLi2018** [ben-manes/caffeine#675]
I tried to use weight to control the total amount of memory the cache consumes, but it didn't work.

**Comment by ben-manes** [comment]
That’s too bad. It sounds like a configuration problem. Please provide more details or else I’ll have to close as too vague.

**Comment by MrLi2018** [comment]
![25245683-C10E-4CA4-AFBB-83345A0A04A0](https://user-images.githubusercontent.com/39287657/155964039-0e1c5fa1-4a1c-4648-ba19-f6c91ffc6e59.png)
![9FBE68BC-3ABC-4741-B34D-92B1DC3E4C78](https://user-images.githubusercontent.com/39287657/155964186-444b8a9e-f840-48d6-b7c5-215411f1910a.png)
I don't understand why it was so much more than the maximum weight, it seems that the expulsion didn't take effect. @ben-manes

**Comment by MrLi2018** [comment]
150*1024*1024 I've dealt with it myself.

**Comment by MrLi2018** [comment]
My weight calculation for each piece of data is done by calculating the length of bytes in all objects, and I'm not sure if that's controllable or what I should do now to make evictions take effect.

**Comment by ben-manes** [comment]
Measuring the actual object size is tricky. The JAMM library is a decent attempt, but it will be error prone regardless. That is why the JEP was suggested and discusses some of the challenges.

**Comment by MrLi2018** [comment]
OK, I think I understand. Thank you for your answer.
