### ISSUE TITLE
java.lang.NoClassDefFoundError: com.github.benmanes.caffeine.cache.Caffeine$$ExternalSyntheticLambda2

### ISSUE THREAD

**Issue by rohit5ram** [ben-manes/caffeine#676]
I am unable to import and use the library in Android targeting SDK 19

`java.lang.NoClassDefFoundError: com.github.benmanes.caffeine.cache.Caffeine$$ExternalSyntheticLambda2         at com.github.benmanes.caffeine.cache.Caffeine.<clinit>(Caffeine.java:140)`

Can you please help me with a solution?

**Comment by ben-manes** [comment]
Caffeine 3.x uses Java 11, whereas 2.x is on Java 8. My guess is if you downgraded then it might be more compatible with Android's Java support.

However, we don't support or optimize for Android. Our design decisions are for server-side Java, whereas mobile has very different concerns. Instead Google offers [android.util.LruCache](https://developer.android.com/reference/android/util/LruCache) or Guava's Cache from their android build (also not designed for Android but supported). A library intended for Android is your best choice, where the NYTimes/Dropbox's [Store](https://github.com/dropbox/store) library appears to be a popular choice.

**Comment by rohit5ram** [comment]
I used 2.x but still it didn't work. I can use Store.
Thanks for the recommendation

**Comment by rohit5ram** [comment]
@ben-manes Store didn't suit my use case. FYI, This https://github.com/jhalterman/expiringmap did the job.
