### ISSUE TITLE
Add a feature to allow for computation of current cache weight

### ISSUE THREAD

**Issue by jhominal** [ben-manes/caffeine#683]
I am currently using the `weight` feature to limit the memory consumption of my `LoadingCache` instance.

It works pretty well, but I would like to have a built-in feature to allow for computation of the current cache weight.

Right now, I can think of two ways it could be modeled in the API:

  1. Adding an `estimatedWeight()` method on the `Cache` object - which would return an estimation of the sum of the weights in the cache;
  2. Adding `loadSuccessWeight` and `removalWeight` fields in the `CacheStats` object:
    * Every time an entry is loaded, its weight would be added to `loadSuccessWeight`;
    * Every time an entry is removed, whether by eviction, invalidation, (or after a refresh), its weight would be added to `removalWeight`;
    * With `loadSuccessWeight - removalWeight`, I would be able to compute either, the current cache weight, or the net change of cache weight between two stat collections;
    * If `evictionWeight` actually takes in account explicit invalidation, then there may be no need to add `removalWeight`

Would you be open to a PR implementing such a feature? And do you have an idea of what approach would be appropriate?

**Comment by jhominal** [comment]
I am sorry, I have just read through issue #572 - and I see that an equivalent of my first idea (`Cache.estimatedWeight` == `cache.policy().eviction().get().weightedSize()`) is actually already implemented.

I would still be interested in whether or not you think that my second idea has merit to it.

**Comment by ben-manes** [comment]
My hesitation with the second idea is that everyone wants different statistics. Instead we try to offer the most common and those that would be hard to obtain otherwise. For more adding custom metrics is perfectly fine.
