### ISSUE TITLE
Not evict if a certain codition is met

### ISSUE THREAD

**Issue by Tofpu** [ben-manes/caffeine#685]
Hey! I hope this is the right place to ask this kind of question. If it's not, I apologize.

Is it possible to have an entry *not* get evicted if a certain condition is met?

**Comment by ben-manes** [comment]
Yes, we refer to this as [pinning the entry](https://github.com/ben-manes/caffeine/wiki/Faq#pinning-entries). That opts it out of the policy while still honoring the semantics, e.g. by setting an infinite expiration time so it all works as usual but never triggers its automatic removal.

**Comment by Tofpu** [comment]
Ahh, I see! I assume it's not possible to do the following within a single cache?

> Pin Entry -> Unpin Entry -> Start the expiration of Entry for whatever defined duration

**Comment by ben-manes** [comment]
I'm not sure what you mean. The expectation would be to define an `Expiry` that can evaluate the entry to calculate the expiration time. For example if you cached locks then you would not want one to expire if held,

```java
... // expiry
long expireAfterUpdate(K key, ReentrantLock lock, long currentDurationNanos, long currentTimeNanos) {
  return lock.isLocked() ? Long.MAX_VALUE : Duration.ofMinutes(5).toNanos();
}
...
// pin
cache.asMap().compute(key, (k, lock) -> {
  if (lock == null) {
    lock = new ReentrantLock();
  }
  lock.lock();
  return lock;
};

// unpin
cache.asMap().compute(key, (k, lock) -> {
  lock.unlock();
  return lock;
});
```

The next release (any day, just need the time) will offer a related feature that might simplify this slightly. You can use a [compute(key, mappingFunction, duration)](https://github.com/ben-manes/caffeine/blob/8d51164b9d697f307640d131b9f281115e6f64df/caffeine/src/main/java/com/github/benmanes/caffeine/cache/Policy.java#L631-L659) to override the `Expiry` evaluation. This is useful if you don't want to query the value for the new duration. That convenience was added for simplifying an integration and can be used by `cache.policy().expireVariably()`.

Does any of that help?

**Comment by Tofpu** [comment]
That makes a lot of sense actually! That is exactly what I wanted, thank you very much for the detailed response & explanation, Ben! Hope you have a nice day/night

**Comment by Tofpu** [comment]
That makes a lot of sense actually! That is exactly what I wanted, thank you very much for the detailed response & explanation, Ben! Hope you have a nice day/night

**Comment by Tofpu** [comment]
That makes a lot of sense actually! That is exactly what I wanted, thank you very much for the detailed response & explanation, Ben! Hope you have a nice day/night
