### ISSUE TITLE
modify get cache object， cache updated in caffeine

### ISSUE THREAD

**Issue by bijialin** [ben-manes/caffeine#687]
springboot version： 2.6.3,
caffeine version： 2.9.3

when i use spring cache mananger  to operate data in caffeine，i get data from caffeine， if i modify this object， cache data also updated

**Comment by ben-manes** [comment]
Caffeine is a bounded ConcurrentHashMap. It doesn’t copy objects, that’s outside of its responsibilities.

**Comment by bijialin** [comment]
thank you ben， maybe i need ask spring team to fix it cache manager impl
