### ISSUE TITLE
How to set the configuration to print statistics

### ISSUE THREAD

**Issue by ycy1991** [ben-manes/caffeine#702]
Caffeine<Object, Object> caffeine = Caffeine.newBuilder()
                .initialCapacity(100)
                .maximumSize(20000)
                .expireAfterWrite(6000, TimeUnit.SECONDS)
                // 开启状态监控
                .recordStats()
                .weakValues();
test
     Caffeine<Object, Object> caffeine = Caffeine.newBuilder()
                .initialCapacity(100)
                .maximumSize(20000)
                .expireAfterWrite(6000, TimeUnit.SECONDS)
                // 开启状态监控
                .recordStats()
                .weakValues();
        Cache<Object, Object> cache = caffeine.build();
        cache.put("test", "test");
print stats
 public void print() {
        Map<String, Object> map = new HashMap<>();
        CacheStats stats = cache.stats();
        map.put("请求次数", stats.requestCount());
        map.put("命中次数", stats.hitCount());
        map.put("未命中次数", stats.missCount());
        map.put("加载成功次数", stats.loadSuccessCount());
        map.put("加载失败次数", stats.loadFailureCount());
        map.put("加载失败占比", stats.loadFailureRate());
        map.put("加载总耗时", stats.totalLoadTime());
        map.put("回收总次数", stats.evictionCount());
        map.put("回收总权重", stats.evictionWeight());
        System.out.println(map);
    }
print result: 
{加载失败占比=0.0, 加载总耗时=0, 回收总次数=0, 命中次数=0, 未命中次数=0, 加载失败次数=0, 请求次数=0, 回收总权重=0, 加载成功次数=0}

**Comment by ben-manes** [comment]
yeah, `CacheStats` implements toString() for convenience here, but something like [Micrometer](https://micrometer.io/) is generally better for production (e.g. for use with a dashboard like [Grafana](https://grafana.com/grafana/)).

**Comment by ycy1991** [comment]
Thank you. Later, combined with the source code, it is inferred that colleagues configured multiple caches
