### ISSUE TITLE
BoundedLocalCache$ValueIterator not found

### ISSUE THREAD

**Issue by ItsKlork** [ben-manes/caffeine#704]
When accessing .asMap().values() I get the following exception thrown:
`java.lang.NoClassDefFoundError: com/github/benmanes/caffeine/cache/BoundedLocalCache$ValueIterator`
With the stacktrace pointing to:
`at com.github.benmanes.caffeine.cache.BoundedLocalCache$ValuesView.iterator(BoundedLocalCache.java:3229)`

Any ideas on what could be causing this?

**Comment by ben-manes** [comment]
Do you do anything unconventional like use Proguard, Graal, fatjars, or custom classloaders? Anything that manipulates and rewrites jars or classes in weird ways have a tendency to make mistakes and cause surprising failures.

**Comment by ItsKlork** [comment]
Nevermind, I had an issue with my maven configuration.
