### ISSUE TITLE
Is there a way to add entries to a cache that will expire sooner (based on some kind of a delta param) than the time window the cache was initialize with?

### ISSUE THREAD

**Issue by ghevge** [ben-manes/caffeine#708]
Hi,

Is there a way to add entries to a cache that will expire sooner than the time window the cache was initialize with?

So I have something like this:

```
rateLimitCache = Caffeine.newBuilder()
                            .expireAfterWrite(1000, TimeUnit.MILLISECONDS)
                            .build();
rateLimitCache.put("key1", X);
```

What I want is to call the put, with some king of a delta param  so that the entry will be expired in (1000 - delta) milliseconds, and not in 1000 milliseconds as it does by default.

The reason I want this is because I have a significant delay from the moment I'm collecting the X value and the moment I'm pushing it into the cache (it involves some distributed envs). 

Is this possible ? or some new functionality will be required?

Thanks

**Comment by ben-manes** [comment]
You can do this using [variable expiration](https://github.com/ben-manes/caffeine/wiki/Eviction#time-based). This allows for custom durations per entry and evaluates using a callback to favor loading through the cache (to avoid get-load-put races). There is also a grab bag of [additional methods](https://www.javadoc.io/doc/com.github.ben-manes.caffeine/caffeine/latest/com.github.benmanes.caffeine/com/github/benmanes/caffeine/cache/Policy.VarExpiration.html) from `cache.policy().expiresVariably()` that might be of interest.
