### ISSUE TITLE
Add listener to resurrect entries which were to be evicted.

### ISSUE THREAD

**Issue by kyngs** [ben-manes/caffeine#709]
Currently, Caffeine only offers a listener which informs you when an item was evicted. However, it does not allow you to override the eviction and resurrect the item. IMO it would be best to add another listener that would decide whether to evict the item. This listener would return a long with the following values:

If the listener returns 0, proceed evicting the item.
If the listener returns a positive number, resurrect the item and set the expiry by the number returned by the listener.
If the listener returns a negative number, resurrect the item and set the expiry as the same that was set before this eviction.

I hope you understand what I mean, if not, please ask clarifying questions.

**Comment by ben-manes** [comment]
A callback to decide whether to evict can degrade the process to be O(n), whereas today we use only amortized O(1) algorithms. That makes it an inefficient and error prone api. It could also imply incorrect assumptions, such as if an entry has expired but not yet removed, what should a reader observe? This is treated as a cache miss, so the callback would need to perform that evaluation to possibly resurrect and return it on read.

Generally for expiration one can use an `Expiry` to set per-entry lifetimes which can extend the duration when the entry is operated on through the cache. To opt out of eviction one can set an infinite timestamp. See [pinning entries](https://github.com/ben-manes/caffeine/wiki/Faq#pinning-entries) in the FAQ. By performing the operation through the cache upfront, it can reorder the entry on its data structures to manage the data efficiently.

Similar asks,
- Skip the entry from size eviction by a callback, e.g. if a resource was marked as locked. That could decide to never evict, which could cause the cache to keep retrying as it exceeds the threshold. An example of this ask is https://github.com/apache/solr/pull/580. 
- An inverse of this is https://github.com/ben-manes/caffeine/issues/707 to validate that the entry is still valid or else evict it early.

Do you have a problem using `Expiry` and informing the cache of the entry's state change upfront? This avoids many quirks and stays efficient.

**Comment by kyngs** [comment]
> A callback to decide whether to evict can degrade the process to be O(n), whereas today we use only amortized O(1) algorithms. That makes it an inefficient and error prone api. It could also imply incorrect assumptions, such as if an entry has expired but not yet removed, what should a reader observe? This is treated as a cache miss, so the callback would need to perform that evaluation to possibly resurrect and return it on read.
> 
> Generally for expiration one can use an `Expiry` to set per-entry lifetimes which can extend the duration when the entry is operated on through the cache. To opt out of eviction one can set an infinite timestamp. See [pinning entries](https://github.com/ben-manes/caffeine/wiki/Faq#pinning-entries) in the FAQ. By performing the operation through the cache upfront, it can reorder the entry on its data structures to manage the data efficiently.
> 
> Similar asks,
> 
> * Skip the entry from size eviction by a callback, e.g. if a resource was marked as locked. That could decide to never evict, which could cause the cache to keep retrying as it exceeds the threshold. An example of this ask is [SOLR-15964: Transient cores: don't evict open ones apache/solr#580](https://github.com/apache/solr/pull/580).
> * An inverse of this is [Value validation before return #707](https://github.com/ben-manes/caffeine/issues/707) to validate that the entry is still valid or else evict it early.
> 
> Do you have a problem using `Expiry` and informing the cache of the entry's state change upfront? This avoids many quirks and stays efficient.

Nope, not at all.
Thanks for the detailed response, this seemed like a practical addition but I can see it would introduce more issues than it fixes.
