### ISSUE TITLE
Eviction weight not getting populated in stats

### ISSUE THREAD

**Issue by drcrallen** [ben-manes/caffeine#71]
https://github.com/metamx/druid-cache-caffeine/commit/a7bda78ea022a66a679adb1262c7594eb688a6d9 adds a unit test which checks the `cache.stats().evictionWeight()`. But the stat doesn't seem to increase when an entry is evicted.

**Comment by ben-manes** [comment]
Thanks. I had some tests but didn't update everywhere, so perhaps the wiring is wrong. I was a bit swamped given Pesach started on Friday, so I might have rushed that to focus on the other issues. I'll take a look during my commute home and get a fix ready.

**Comment by ben-manes** [comment]
The [evict_weighted](https://github.com/ben-manes/caffeine/blob/f11108a85091a13867e9e79d17f81e45eaeefcf3/caffeine/src/test/java/com/github/benmanes/caffeine/cache/EvictionTest.java#L127) test looks right and attaching a debugger I see its correct.

It looks like you have two `cache` instances, method and class scoped. I suspect that is the problem.

**Comment by ben-manes** [comment]
Looks like your tests pass now, glad I could help. :-)
