### ISSUE TITLE
RefreshAfterWrite does seem to be refreshing certain keys even after the duration (v2.9.3)

### ISSUE THREAD

**Issue by ashwinrs** [ben-manes/caffeine#711]
First off, thank you for writing and maintaining this cache. It has been very useful to us.

We are using this library internally to cache decisions from another pod. We only use Size based eviction and do not expire keys by default. Here is our Cache initialization:

```
        Caffeine<AxeCacheKey<?>, AxeCacheValue<?>> c = Caffeine.newBuilder()
                .maximumSize(200000)
                .refreshAfterWrite(Duration.ofMinutes(1))
                .evictionListener((AxeCacheKey<?> key, AxeCacheValue<?> value, RemovalCause cause)
                        -> this.metrics.addCount(Utils.InfoMetricsPrefix + "evictionListener." + key.getAxeMethod() + "." + cause.name(),1))
                .removalListener((AxeCacheKey<?> key, AxeCacheValue<?> value, RemovalCause cause)
                        -> this.metrics.addCount(Utils.InfoMetricsPrefix + "removalListener." + key.getAxeMethod() + "." + cause.name(),1));
```

However the refreshAfterWrite does not seem to work in certain cases. We store the time the value was set in the cache and we print it when we call get() and we are seeing some stale values that are not getting refreshed even after 1 minute. They are not refreshed even after days. 

We read the notes about :
```
Note: all exceptions thrown during refresh will be logged and then swallowed.
```

But we do not see any exceptions being logged in and around the stale values.

Any insight would be greatly appreciated. Thank you again.

**Comment by ben-manes** [comment]
Can you provide a minimal project with a unit test showing the behavior? This would avoid us each coming in from different expectations. I believe this is a misunderstanding of what this feature does.

The cache does not reload every entry after a duration, e.g. 200,000 entries every minute. That can be done by using a periodic task on a `ScheduledExecutorService` that iterates over the `asMap()` view to perform the reloads.

This feature will asynchronously reload an entry as a reaction to cache reads for it after the duration has passed, returning the current value to the caller. If expiration was used then the entry would be unusable and evicted, which for hot data can create periodic bottlenecks (e.g. a configuration flag read on every request). The refresh period sits between the last write and expiration, allowing the cache to try to keep hot data current and hide that reload penalty from callers. By using expiration the cold entries will fade away, forcing a fresh load on a cache miss. In your case, by not having an expiration threshold the cache will serve old content as it is still deemed usable.

Does that help?

**Comment by ashwinrs** [comment]
The use of `MaximumSize` is intended to work as a safety because we do not want to blow up our heap. Our use case does not let us have so many keys and it is working as expected, as we dont see any evictions.

You are right on me misunderstanding the feature.
I had understood it as, the key being reloaded after the duration regardless of a cache read.

So to fix this, all I have to do is to add an expiry, that should evict old enough keys, regardless of them receiving a cache read.

We have around thousand instances of these caches running on different containers and I guess some of them are not receiving traffic for this particular key consistently enough. Leading to us seeing the stale values even after a long time.

**Comment by ben-manes** [comment]
yep, adding expiration should solve this nicely.

If the cache did blindly reload based on a timeout, that could lead to a denial of service attack as each instance fetches up to 200k keys concurrently from your backend. An explicit scheduled task makes that behavior more explicit in your code, perhaps hinting towards using bulk loader or limiting the fanout. As polling can impose scaling hurdles, the alternative is to broadcast (push) a notification to invalidate a cache entry, where the handler can then call `LoadingCache.refresh(key)` if the key is present.
