### ISSUE TITLE
`asyncLoad` occasionally called with `Object` due to race between `refreshAfterWrite` and `expireAfterAccess`

### ISSUE THREAD

**Issue by wiggzz** [ben-manes/caffeine#715]
We're seeing some `ClassCastExceptions` (in our code) after our cache loader `asyncLoad` seems to be invoked with an `Object` instead of the expected key type `K`. We are using the cache configured with `refreshAfterWrite` and `expireAfterAccess` and I suspect this may be happening because the `expireAfterAccess` will cause the cache `Node` to eventually be evicted and then die, which will set the Node `key` to `DEAD_STRONG_KEY` (`new Object()`). At the same time, the node is being refreshed, and so the `asyncLoad` method is called with the dead key.

I'll take a look if I can reproduce in a unit test, but wanted to open this issue to see if you had seen this before or if we are using it wrong.

Our cache is roughly configured like this

```
Caffeine.newBuilder()
        .refreshAfterWrite(10, TimeUnit.MINUTES)
        .expireAfterAccess(15, TimeUnit.MINUTES)
        .maximumSize(325_000)
        .recordStats(/* custom StatsCounter, not doing anything really special */ )
        .scheduler(forScheduledExecutorService(/* scheduled executor for the application */))
        .buildAsync(/* our loader, which does coalescing similar to the `CoalescingBulkLoader` */);
```

**Comment by ben-manes** [comment]
Thanks! Yes, if you can put a unit test together that would be really great.

**Comment by ben-manes** [comment]
The logic to trigger the refresh reads the key but doesn't check afterwards that `Node.isAlive()` is true. The bug makes sense, testing could be hard due to races.

https://github.com/ben-manes/caffeine/blob/fa552a5bcef523db4ed6508342390952ebe8db9c/caffeine/src/main/java/com/github/benmanes/caffeine/cache/BoundedLocalCache.java#L1265-L1268

**Comment by wiggzz** [comment]
> The logic to trigger the refresh reads the key but doesn't check afterwards that `Node.isAlive()` is true. The bug makes sense, testing could be hard due to races.
> 
> https://github.com/ben-manes/caffeine/blob/fa552a5bcef523db4ed6508342390952ebe8db9c/caffeine/src/main/java/com/github/benmanes/caffeine/cache/BoundedLocalCache.java#L1265-L1268

Yep that is exactly what I was thinking. And also agree testing is tricky. Need to get the node to be evicted _while_ the read is happening. Could possibly hook into the `StatsCounter` to tick the ticker and then call cleanup all during a read?

**Comment by wiggzz** [comment]
Ah - but it could be `RETIRED_STRONG_KEY`. Thinking out loud here.

**Comment by ben-manes** [comment]
right. Since those are two different fields so one could be set before the other is and cause it to pass the visibility check. Those nulls are mostly for weak/soft reference collection and not liveliness.

**Comment by ben-manes** [comment]
I was able to write a unit test using your idea of stats as a hook. I also made the sentinel keys proper classes so that it will be easier to debug in the future. Would you be able to canary 3.1.1-SNAPSHOT? If not, I can release and we can verify as a follow-up.

Thankfully this should be a benign bug since the `ClassCastExceptions` is logged, swallowed, and the entry left discarded by its removal. Other than log noise it shouldn't be causing any problems.

**Comment by wiggzz** [comment]
Interesting. In our case the error is not being fully swallowed by caffeine because we are coalescing the refreshes and normal loads. So once an invalid key is requested to be refreshed, it is added to a batch, then every other key that is requested with it also fails because of the class cast exception because the batch is polluted.

So in our case it is more than noise, although it's probably not having much of a customer impact since it is fairly infrequent.

I will see if we can canary this. If not, I will definitely follow up if it still happens after we upgrade.

**Comment by ben-manes** [comment]
> I will see if we can canary this. If not, I will definitely follow up if it still happens after we upgrade.

Any updates? I'm all set on my side
 - #714 as won't do (working as intended)
 - #716 fixed (weird gradle metadata stuff)

**Comment by wiggzz** [comment]
> > I will see if we can canary this. If not, I will definitely follow up if it still happens after we upgrade.
> 
> Any updates? I'm all set on my side
>  - #714 as won't do (working as intended)
>  - #716 fixed (weird gradle metadata stuff)

I wasn't able to get to this today and will be on leave for a week, so feel free to cut the release and I will followup when I get a chance.

**Comment by ben-manes** [comment]
thanks, will do!

**Comment by ben-manes** [comment]
Released 3.1.1

**Comment by wiggzz** [comment]
@ben-manes Hey sorry for the delayed follow up on this. We finally got this out into production and it's fixed the issue. Thanks for the quick resolution!

**Comment by ben-manes** [comment]
awesome 🥳
