### ISSUE TITLE
Problem when adding Caffeine to a Tar in Gradle

### ISSUE THREAD

**Issue by alkamo** [ben-manes/caffeine#716]
Gradle Version: 6.3
Java Version: 11.0.11 (Amazon.com Inc. 11.0.11+9-LTS)
Caffeine Version: 3.0.3

This is probably a configuration problem on my part, but I'm not sure where else to ask about it.

I have a gradle sub-project that gets caffeine as a transitive dependency (from jdbi). It builds without issue. However, I have a separate gradle sub-project that pulls the first artifact and its dependencies into a tar using the distribution plugin, using the following configuration:

```
configurations {
    library
}

dependencies {
    library(project(':my-project:project-jar'))
}

distributions {
    main {
        contents {
            into('/lib') {
                from configurations.library.files
            }
        }
    }
}
```

When the caffeine version is 3.x and I run the distTar task for this configuration, I get the following error:

```
Could not resolve com.github.ben-manes.caffeine:caffeine:3.0.3.
      Required by:
          project :my-project:project-tar > project :my-project:project-jar > org.jdbi:jdbi3-core:3.29.0
       > Cannot choose between the following variants of com.github.ben-manes.caffeine:caffeine:3.0.3:
           - runtimeElements
           - shadowRuntimeElements
```

If I bring the dependency down to the point where the Caffeine dependency resolves to 2.x, this issue goes away.

**Comment by alkamo** [comment]
This project isn't using the shadow plugin at all, but maybe it goes the other way and the distribution plugin builds on the shadow plugin.

**Comment by ben-manes** [comment]
hmm, then I don't know why that configuration would exist? The shadow plugin is external, whereas the distribution is internal.

It is used by the JMH plugin for benchmarks, which might mean it leaks into Caffeine's gradle metadata file. I'm not sure why that would cause breaks though.

**Comment by ben-manes** [comment]
yeah, I see it in the [module descriptor](https://repo1.maven.org/maven2/com/github/ben-manes/caffeine/caffeine/3.0.3/caffeine-3.0.3.module). I don't know enough about how Gradle uses this and why it would conflict.
```json
{
  "name": "shadowRuntimeElements",
  "attributes": {
    "org.gradle.category": "library",
    "org.gradle.dependency.bundling": "shadowed",
    "org.gradle.libraryelements": "jar",
    "org.gradle.usage": "java-runtime"
  },
  "files": [
    {
      "name": "caffeine-3.0.3-all.jar",
      "url": "caffeine-3.0.3-all.jar",
      "size": 1098775,
      "sha512": "8a42cff3abb1ffa60616504f0af75cac75dbe15137e777188926d76b23d1865a36f3f773946426c3f11e834932bc1161d9828a209885799b41d9f32241386119",
      "sha256": "a2d5edfb572bf47da90c68b55195baa84f9f1ae81a4fa13e2151b29e44f8021b",
      "sha1": "206aa3f4706839ac2970c447ce6575f716a99e06",
      "md5": "9597edf3a8a476607c33d14582621c7d"
    }
  ]
}
```

**Comment by ben-manes** [comment]
Trying to remove the shadow plugin from the build and it seems fine. Unfortunately I did not describe the issue very well in the [git commit](https://github.com/ben-manes/caffeine/commit/bb7a42c0550848a36ec23a110d8b3c6154b2b297). I think it was an issue with Ehcache2 + Ehcache3, which later became incompatible dependencies. Whatever was wrong, a jmh benchmark with Ehcache3 seems to run fine so I could remove that going forward. We could try a snapshot build and see if that resolves your problem. Wdyt?

**Comment by ben-manes** [comment]
@alkamo please try 3.1.1-SNAPSHOT and let me know if that resolves the problem

**Comment by ben-manes** [comment]
I find the new resolution behavior very confusing and frustrating. It breaks the [gradle-versions-plugin](https://github.com/ben-manes/gradle-versions-plugin) even though that uses apis since 1.0 and does simple version lookups. I think they might have tried to evolve to solve too many problems (android, native).

I'll try to have this out by next Monday. Just waiting to see if the fix for #715 can be verified by the user before cutting the release.

**Comment by ben-manes** [comment]
Released 3.1.1

**Comment by manishkrishan** [comment]
same issue with 2.9.3 with java 8, any workaround ?

**Comment by ben-manes** [comment]
I think you can tell gradle which to [select](https://docs.gradle.org/current/userguide/dependency_capability_conflict.html#sub:selecting-between-candidates).

**Comment by manishkrishan** [comment]
Thankyou, can you pls give an example of selecting Variant 'runtimeElements' capability in 
   configurations {
      all {
             resolutionStrategy.capabilitiesResolution.withCapability('com.github.ben-manes.caffeine:caffeine:2.9.3') {
               . . . 
               . . .

**Comment by ben-manes** [comment]
It might take me a while to have free time to look into that. A broader approach that I have used to workaround gradle plugin portal outages is to [disable the metadata](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:supported_metadata_sources) entirely. It isn't useful for server-side builds most of the time and seems to be mostly for kotlin and android quirkiness.

```gradle
repositories {
    maven {
        url "http://repo.mycompany.com/repo"
        metadataSources {
            mavenPom()
            artifact()
        }
    }
}
```

**Comment by ben-manes** [comment]
Here is what chatgpt said, might work too.

> In Gradle, when you encounter dependency resolution issues like the one you've described, where there are multiple variants of a dependency available and > the build system cannot decide which one to use, you can use dependency constraints to guide Gradle's selection process. To force Gradle to select the > `runtimeElements` variant of the `com.github.ben-manes.caffeine:caffeine:3.0.3` dependency, you can add a dependency constraint to your project's `build.> gradle` file.
> 
> Here's an example of how you can do that:
> 
> ```groovy
> dependencies {
>     // Add a dependency constraint for caffeine to force using the runtimeElements variant
>     constraints {
>         implementation("com.github.ben-manes.caffeine:caffeine:3.0.3") {
>             because "We want to use the runtimeElements variant"
>         }
>     }
>     
>     // Other dependencies...
> }
> ```
> 
> By adding this constraint, you're explicitly telling Gradle that you want to use the `implementation` (which corresponds to the `runtimeElements` variant) > of the `caffeine` library with version `3.0.3`. The `because` clause is optional but can be helpful to provide a reason for the constraint.
> 
> After adding this constraint, Gradle should prioritize the `runtimeElements` variant when resolving dependencies and resolving conflicts.
> 
> Remember that dependency resolution can be complex, and conflicts might still arise due to other factors in your project configuration. If you're still > facing issues after adding the constraint, you might need to further investigate your project's dependencies and configurations to ensure there are no > conflicting dependencies or other issues causing the resolution problem.

**Comment by manishkrishan** [comment]
thankyou for response but the above solution from ChatGPT does works with gradle 6.7.1. Error "Could not set unknown property 'classifier' for object of type org.gradle.api.internal.artifacts.DefaultExcludeRule"

**Comment by ben-manes** [comment]
how about the `metadataSources` approach? That should just use the poms which is almost always what you want in a server project

**Comment by manishkrishan** [comment]
It was already there under "buildscript" in my build.gradle
`buildscript {
  repositories {
    maven {
        url "http://repo.mycompany.com/repo"
        metadataSources {
            mavenPom()
            artifact()
        }
    }
 }
}`

I also tried adding it outside buildscript scope like 

`   repositories {
      maven { 
         url repo1
         metadataSources {
            ignoreGradleMetadataRedirection()
            mavenPom()
            artifact()
         }
      }
      maven { 
         url repo2 
         metadataSources {
            ignoreGradleMetadataRedirection()
            mavenPom()
            artifact()
         }
      }
   }`

**Comment by ben-manes** [comment]
odd.. did you try with `--refresh-dependencies` or delete your `~/.gradle/caches` to make sure it did not pick up somewhere else?

I can't reproduce this problem so unfortunately I don't know how to debug this.

**Comment by manishkrishan** [comment]
does not work with `--refresh-dependencies` or after deleting gradle cache

**Comment by ben-manes** [comment]
since all I can do is guess, what about using an attribute to force the selection?

```
dependencies {
  implementation('com.github.ben-manes.caffeine:caffeine:2.9.3') {
    attributes {
      attribute(Attribute.of("org.gradle.dependency.bundling", String), "external")
    }
  }
}
```
