### ISSUE TITLE
Cache key equality problem

### ISSUE THREAD

**Issue by dylan-tao** [ben-manes/caffeine#720]
When the key is the same string number, it is considered to be unequal, there are multiple caches, ps: "10000", Ref: com.github.benmanes.caffeine.cache.LocalManualCache#put

data:
`{
    "serialVersionUID": 1,
    "cache": {
        "10000": [
            {
                "id": 2002,
                "createdTime": "2022-04-08 16:48:02",
                "updatedTime": "2022-05-30 11:24:33",
                "outsideServiceId": 10000,
                "type": 1,
                "createdUser": "admin",
                "updatedUser": "admin"
            },
            {
                "id": 2003,
                "createdTime": "2022-04-08 16:48:02",
                "updatedTime": "2022-05-30 10:48:18",
                "outsideServiceId": 10000,
                "type": 2,
                "createdUser": "admin",
                "updatedUser": "admin"
            }
        ],
        "10000": [
            {
                "id": 2002,
                "createdTime": "2022-04-08 16:48:02",
                "updatedTime": "2022-05-30 11:24:33",
                "outsideServiceId": 10000,
                "type": 1,
                "createdUser": "admin",
                "updatedUser": "admin"
            },
            {
                "id": 2003,
                "createdTime": "2022-04-08 16:48:02",
                "updatedTime": "2022-05-30 10:48:18",
                "outsideServiceId": 10000,
                "type": 2,
                "createdUser": "admin",
                "updatedUser": "admin"
            }
        ]
    },
    "isWeighted": false,
    "policy": null
}`

**Comment by ben-manes** [comment]
I am sorry, but I do not understand your question.

For a strong key cache it is identical to `ConcurrentHashMap`. An equal string will map to a single key.
For a weak key cache it is by instance identity. A string instance will map to a unique key.

Does that help?

**Comment by dylan-tao** [comment]
this is a strong key, but cache appear two same key cache data, I am also confused.

**Comment by ben-manes** [comment]
Can you provide sample code? A self-contained unit test is ideal. Otherwise you can send me code confidentially over email or we can hop on a video conference (I can provide a Zoom link). Whatever helps.

**Comment by dylan-tao** [comment]
com.github.benmanes.caffeine.cache.References.LookupKeyReference，i found equals and hashCode， wait me write juint

**Comment by ben-manes** [comment]
That is if you configured your cache with `Caffeine.weakKeys()`, which will then use identity semantics (`==`).

**Comment by dylan-tao** [comment]
my caffeine builder: 
`  Caffeine<Object, Object> caffeine = Caffeine.newBuilder().initialCapacity(finalConfig.getInitialCapacity()).maximumSize(finalConfig.getMaximumSize());
            if (finalConfig.isOpenStats()) {
                caffeine.recordStats();
            }
            if (finalConfig.isOpenRemoveListener()) {
                caffeine.evictionListener((key, value, cause) -> {
                    handlerFriendlyTipLog(key, value, cause);
                });
            }`

**Comment by ben-manes** [comment]
okay, then the cache will use the key's `equals` and `hashCode` method, via `ConcurrentHashMap`. The key will not be wrapped.

**Comment by ben-manes** [comment]
Figured it out?

**Comment by dylan-tao** [comment]
Brother, it's done. Under the spring@Cacheable annotation, when Spel determines whether a Long key exists, the cacheName key equals and hashcode are inconsistent. Solution: splice the SPEL keys into string types. Sorry, unit tests don't have this problem. I'm Sorry I wasted my brother's time ~~~

**Comment by ben-manes** [comment]
no problem, glad you figured it out.
