### ISSUE TITLE
Change Wiki Description.

### ISSUE THREAD

**Issue by sinsuren** [ben-manes/caffeine#723]
Hi @ben-manes 

Just wanted to change one thing into Wiki page.

keys automatically wrapped in [weak references](https://github.com/ben-manes/caffeine/wiki/Eviction#reference-based)
values automatically wrapped in [weak or soft references](https://github.com/ben-manes/caffeine/wiki/Eviction#reference-based)

Above lines creates confusion that `keys/values` are  by default wrapped in WeakReference. A better description would be:
in built ability to wrap keys with [weak references](https://github.com/ben-manes/caffeine/wiki/Eviction#reference-based) if required.
in built ability to wrap values [weak or soft references](https://github.com/ben-manes/caffeine/wiki/Eviction#reference-based) if required.

**Comment by sinsuren** [comment]
<img width="664" alt="Screenshot 2022-06-04 at 5 40 22 PM" src="https://user-images.githubusercontent.com/6632645/171998398-7747e3a4-db47-409d-8c5a-d4d02de35db7.png">

**Comment by ben-manes** [comment]
I understand the confusion, though the current wording also makes sense since if configured it matches that dictionary definition. The wording comes from Guava's [CacheBuilder](https://github.com/google/guava/blob/e7b86f4767ad1cfa58c5bcad1f7ca9358d52ee45/guava/src/com/google/common/cache/CacheBuilder.java#L86-L100),

```java
 * {@code CacheBuilder} builds caches with any combination of the following features:
 *
 * <ul>
 *   <li>automatic loading of entries into the cache
 *   <li>least-recently-used eviction when a maximum size is exceeded (note that the cache is
 *       divided into segments, each of which does LRU internally)
 *   <li>time-based expiration of entries, measured since last access or last write
 *   <li>keys automatically wrapped in {@code WeakReference}
 *   <li>values automatically wrapped in {@code WeakReference} or {@code SoftReference}
 *   <li>notification of evicted (or otherwise removed) entries
 *   <li>accumulation of cache access statistics
 * </ul>
 *
 * <p>These features are all optional; caches can be created using all or none of them. By default,
 * cache instances created by {@code CacheBuilder} will not perform any type of eviction.
```

**Comment by ben-manes** [comment]
Reworded by adding "optional" into the lead in,
> Caffeine provide flexible construction to create a cache with a combination of the following optional features:
