### ISSUE TITLE
Caffeine support for Session

### ISSUE THREAD

**Issue by HelloTo4x** [ben-manes/caffeine#725]
Hi Ben, I am not sure about this problem. Does Caffeine support by  spring-data-session project.? Thank u

**Comment by ben-manes** [comment]
From their [docs](https://github.com/spring-projects/spring-session/blob/aaed973d270f6cf2375fd4c5f2d6bd3100cf0da0/spring-session-docs/modules/ROOT/pages/index.adoc#community-extensions), it seems to be a community extension:
https://github.com/gotson/spring-session-caffeine

**Comment by HelloTo4x** [comment]
thank u so much, i was confused something
