### ISSUE TITLE
Question: Why does recordStats() need a StatsCounter Supplier?

### ISSUE THREAD

**Issue by iroh** [ben-manes/caffeine#74]
While building cache with Caffeine builder, recordStats() either accepts a statsCounter supplier, or uses a default supplier internally. My question is why it needs a supplier instead of just a statsCounter instance? Does it need a fresh instance of StatsCounter everytime?

**Comment by ben-manes** [comment]
Yes, a fresh `StatsCounter` instance should be assigned to every cache. It holds the counters.

Technically someone could reuse the builder. If they did then the same `StatsCounter` would be used by multiple instances. The intent was to nudge anyone who did reuse it to realize that potential mistake. I don't think anyone really does reuse it, but also very few supply their own StatsCounter. The ability to configure your own was to make it a little friendlier for integrating with a metrics library (e.g. Dropwizard's).

**Comment by iroh** [comment]
That makes sense. I am not reusing the builder. I just wondered if the same cache instance requires a new StatsCounter instance periodically. But I guess it doesn't and the purpose of supplier was to protect against builder reuse.

I am using my own StatsCounter supplier which returns the same instance every time its get() is called. I did this in order to have a handle on the statsCounter through which I could get a snapshot of stats and publish metrics using Dropwizard's metrics library (I didn't know back then that I could get stats snapshot even with an async cache by calling cache.synchronous.stats()). I have a scheduled poller which gets latest cache snapshot periodically from the statsCounter and stores it. My registered gauge metrics basically read off this stored snapshot instead of calling statsCounter.snapshot(). I did this because I have multiple metrics and I wanted to reuse the same snapshot for all the metrics instead of each metric triggering a snapshot request. Is this the right way to do it? Or should I not worry about storing the snapshot and reusing it across all my metrics?

**Comment by ben-manes** [comment]
Why not push the updates through the counter to Dropwizard? Something like,

```java
public final class MetricsStatsCounter implements StatsCounter {
  private final Meter hitsMeter;
  private final Meter missesMeter;

  public MetricsStatsCounter(String metricsPrefix, MetricRegistry registry) {
    hitsMeter = registry.meter(metricsPrefix + "." + "hits");
    missesMeter = registry.meter(metricsPrefix + "." + "misses");
  }

  @Override
  public void recordHits(final int count) {
    hitsMeter.mark(count);
  }

  @Override
  public void recordMisses(final int count) {
    missesMeter.mark(count);
  }

  // ...

  @Override
  public CacheStats snapshot() {
    return CacheStats.empty();
  }
}
```

**Comment by iroh** [comment]
That would surely be a better way to do it. 👍

**Comment by ben-manes** [comment]
This turned out to be easily overlooked, so I added an [example](https://github.com/ben-manes/caffeine/tree/master/examples/stats-metrics). The visualizer, like Graphite, should be able to perform calculations like hit rates and averages, so I think that I used the correct primitives.
