### ISSUE TITLE
Adding expireAfterWrite and refreshAfterWrite on cache ojbects

### ISSUE THREAD

**Issue by abhisheksurve45** [ben-manes/caffeine#755]
Hi @ben-manes,

Had a query on using `expireAfterWrite` and `refreshAfterWrite` together on cache

Lets say a particular object has 

refreshAfterWrite: 10m
expireAfterWrite: 20m

Timeline:

| Minute 	| Action                                                                                                                 	|
|--------	|------------------------------------------------------------------------------------------------------------------------	|
| 0      	| Object is queried for the first time and loaded into cache with refreshAfterWrite: 10m & expireAfterWrite: 20m         	|
| 5      	| Cache hit                                                                                                              	|
| 10     	| Object would become stale now                                                                                          	|
| 12     	| Query for object, since refreshAfterWrite is passed, cache would return the stale response and init a background fetch 	|
|        	| background fetch successful                                                                                            	|
| 15     	| Cache hit                                                                                                              	|
| 20     	| The object would expire since expireAfterWrite is met       	|
| 22     	| Query for object, request would be blocked and coalesced      	|

Not sure if the understanding here is correct.

Please help with the same. Thanks.

**Comment by abhisheksurve45** [comment]
Also what would happen if the background fetch fails?

Would the object still be in the stale state?

**Comment by abhisheksurve45** [comment]
Hi @ben-manes 

I ran a few tests to observe the mentioned behavior

### Observations 

### `expireAfterWrite` and `refreshAfterWite` with `LoadingCache`

### Test 1

| Secs 	| Action                                                                                                                 	|
|--------	|------------------------------------------------------------------------------------------------------------------------	|
| 0      	| Object is loaded into cache with `refreshAfterWrite` `30s`        	|
| 15      	| Object queried, cache hit                                                                                                              	|
| 35     	| Object queried, even though `refreshAfterWrite` passed caffeine did a blocking sync req to fetch new value obj                                                                                          	|
| 40     	| Object queried, cache hit	|
| 65     	| Object queried, now caffeine did a async req to fetch new value	|

Questions:
- Why blocking call on `T-35`?

### `expireAfterWrite` and `refreshAfterWite` with `AsyncLoadingCache`

### Test 1
 
| Secs 	| Action                                                                                                                 	|
|--------	|------------------------------------------------------------------------------------------------------------------------	|
| 0      	| Object is loaded into cache with `refreshAfterWrite` `30s`        	|
| 15      	| Object queried, cache hit                                                                                                              	|
| 35     	| Object queried, since `refreshAfterWrite` reached, caffeine returned a stale response and did async call and stored new value                                                                                          	|
| 40     	| Object queried, cache hit	|

Running as expected


### Test 2

| Secs 	| Action                                                                                                                 	|
|--------	|------------------------------------------------------------------------------------------------------------------------	|
| 0      	| Object is loaded into cache with `refreshAfterWrite` `30s` & `expireAfterWrite` `60s`         	|
| 15      	| Object queried, cache hit                                                                                                              	|
| 35     	| Object `refreshAfterWrite` reached but did a blocking syncrhonous call to fetch from backend                                                                                           	|


Questions:
- Why blocking call on `T-35`? (noticed that async calls were made thereafter)

If possible can you please help with the same. Thanks

**Comment by abhisheksurve45** [comment]
Basically my expectation is to keep minimal thread blocking on caffeine lookups. If the object is not in cache (explicitly evicted or reached write expiry) then there is no way other than doing a blocking backend request which is fine. In case of stale objects, expectation is that caffine should return the stale value, and asyncronously fetch the new value.

**Comment by ben-manes** [comment]
What was the `expireAfterWrite` setting? If it was set to the same value as `refreshAfterWite` then it takes precedence and the entry is evicted. This would explain T-35 being a blocking call.

Also note that there were improvements in v3, so if you are on v2 the edge case behavior is a bit different. I am assuming v3 but please clarify otherwise.

**Comment by ben-manes** [comment]
In `Test 2` which specified `expireAfterWrite`, that should have been a non-blocking call. You can write a unit test with Guava's `FakeTicker` to control time. I think test code would be easiest for us to debug from.

**Comment by ben-manes** [comment]
`AsyncLoadingCache` Test 2 passes for me.

```java
@Test
public void issue755_test2() {
  int key = 0;
  int value1 = 1;
  int value2 = 2;

  var ticker = new FakeTicker();
  var loading = new AtomicBoolean();
  var done = new AtomicBoolean();
  AsyncLoadingCache<Integer, Integer> cache = Caffeine.newBuilder()
      .ticker(ticker::read)
      .expireAfterWrite(Duration.ofSeconds(60))
      .refreshAfterWrite(Duration.ofSeconds(30))
      .buildAsync(k -> {
        loading.set(true);
        Awaitility.await().untilTrue(done);
        return value2;
      });

  cache.synchronous().put(key, value1);

  ticker.advance(Duration.ofSeconds(15));
  assertThat(cache.getIfPresent(key).join()).isEqualTo(value1);

  ticker.advance(Duration.ofSeconds(20));
  assertThat(cache.getIfPresent(key).join()).isEqualTo(value1);
  await().untilTrue(loading);
  assertThat(cache.getIfPresent(key).join()).isEqualTo(value1);

  done.set(true);
  await().untilAsserted(() -> assertThat(cache.getIfPresent(key).join()).isEqualTo(value2));
}
```

**Comment by abhisheksurve45** [comment]
Tried to verify the cases with the `FakeTicker`, seems fine
