### ISSUE TITLE
why do you use ConcurrentLinkedHashMap

### ISSUE THREAD

**Issue by fizz12344321** [ben-manes/caffeine#761]
Hi, i am newbie and I am reading your project, I have a question. why do you use ConcurrentLinkedHashMap, why do not you choose other collections like HashMap, ConcurrentHashMap or something else. Thank u so much

**Comment by ben-manes** [comment]
ConcurrentLinkedHashMap is built on top of ConcurrentHashMap. That project (circa 2008) was focused on how to write a fast, concurrent, O(1) cache. The approach led to Guava's cache, where we tried to retrofit MapMaker with better policies. The Guava project was focused on features and apis. Caffeine is an evolution by taking the best of those projects, as well as incorporating in the latest research. It builds on the ideas from those projects, but implementation-wise it does not use them and decorates a ConcurrentHashMap.
