### ISSUE TITLE
Feature request: unlimited weak/soft victim cache

### ISSUE THREAD

**Issue by Pr0methean** [ben-manes/caffeine#765]
It would be handy if we had the option to have a strong-key cache retain, with weak or soft keys, entries that had been evicted because of the size or weight limit. This would allow apps to run with smaller heap sizes, but still take advantage of larger heap sizes effectively. In https://github.com/Pr0methean/OcHd-KotlinBuild I accomplish this with a custom cache-key class (https://github.com/Pr0methean/OcHd-KotlinBuild/blob/0e336a5f9acc02964cf38981705dc2cf7c9feb59/src/main/kotlin/io/github/pr0methean/ochd/tasks/caching/SemiStrongTaskCache.kt) and it works really well (100% hit rate for previously-run tasks with just 64 entries at the typical weight per entry, and 90%+ with 16 entries). An interesting feature of this kind of cache is that it lets Shenandoah outperform the older parallel GC even on makespan (conventional wisdom is that parallel GC maximizes throughput at the expense of latency).

**Comment by ben-manes** [comment]
You can use `Caffeine.evictionListener` to accomplish this with a strong referenced cache (size) that evicts to a weak/soft reference ([docs](https://github.com/ben-manes/caffeine/wiki/Compute)). The compute / cache loader can retrieve from this cache on a miss. This approach is very little code, follows clear layering (e.g. if instead using a remote / disk tier), and requires no changes in the library.

Unfortunately soft references can cause a lot of problems and are generally not recommended. At least historically it caused more frequent full, stop-the-world collection cycles. I don't recall exactly, but I think weak references are generally okay but may not be as useful for a victim cache as they are collectable once there are no more strong usages.

**Comment by Pr0methean** [comment]
Part of the problem with soft refs is probably that Shenandoah only clears them in degen/full GCs (those with more than O(1) pause time).

**Comment by Pr0methean** [comment]
Weak references are useful in my case because I have the flexibility to reorder tasks to achieve temporal locality of reference. I do this with a greedy algorithm, since it lets me take into account the cache's actual contents (including those that are weakly reachable).

**Comment by Pr0methean** [comment]
For a web service that did a handful of these tasks per request and had a response-time target, I agree that weak references probably wouldn't help much.

**Comment by ben-manes** [comment]
An example of how this can be done is below. For simplicity the victim cache is inclusive, but making it exclusive is not much harder. The only quirk is if you explicitly want to remove an entry from both caches atomically then the primary cache does so in a compute to ensure an exclusive write lock of that entry being discarded (whether it is present or not in the primary cache does not matter).

It could be a useful pattern, but I don't think we need any new APIs and can be left to users to implement.

```java
Cache<Key, Graph> victimCache = Caffeine.newBuilder().softValues().build();
Cache<Key, Graph> cache = Caffeine.newBuilder()
    .evictionListener((Key key, Graph graph, RemovalCause cause) -> {
      if (cause == RemovalCause.SIZE) {
        victimCache.put(key, graph);
      } else {
        // other causes, e.g. expiration, may not be usable
        victimCache.invalidate(key);
      }
    })
    .maximumSize(10_000)
    .build();

// load the value
var value = cache.get(key, k -> {
  return victimCache.get(key, this::loadGraph);
});

// invalidate as unusable
cache.asMap().compute(key, (k, v) -> {
  victimCache.invalidate(key);
  return null;
});
```

**Comment by ben-manes** [comment]
I’m glad you found a nice solution and thanks for sharing. If someone wants to do similarly we now have some examples to reference. I don’t see a feature addition being needed so closing

**Comment by Pr0methean** [comment]
FYI, I've since determined that I can get the same benefits as a Caffeine cache provides by the combination of:

* Using weak references as the only caching mechanism.
* Refactoring some tasks so that they generate animation frames all at once rather than separately. (This is for Minecraft Java Edition, where animated textures have the frames stacked as a column in one image.)
* Using `com.sun.prism.GraphicsPipeline.getDefaultResourceFactory().getTextureResourcePool().prepareForAllocation(bytes)` as the throttling mechanism under memory pressure. 

I suspect that this probably mainly works because it reduces the number of garbage collections and the amount of GC done under STW pause in Shenandoah.

https://github.com/Pr0methean/OcHd-KotlinBuild/runs/8180096598?check_suite_focus=true
