### ISSUE TITLE
Add methods with Stream parameters.

### ISSUE THREAD

**Issue by drcrallen** [ben-manes/caffeine#78]
Many of the cache methods take `Iterable` as a parameter. This ask is that methods be added which can take `Stream`

**Comment by drcrallen** [comment]
Minor feature request

**Comment by ben-manes** [comment]
What about using `stream::iterator`? That's all I'd do if added as a default method to the interfaces.

**Comment by drcrallen** [comment]
Sounds reasonable to me.

**Comment by drcrallen** [comment]
As a concrete example, right now I have some code which is doing this:

`cache.asMap().keySet().stream().filter(key -> key.namespace.equals(namespace)).forEach(cache::invalidate);`

because `cache.invalidateAll(cache.asMap().keySet().stream().filter(key -> key.namespace.equals(namespace)))` doesn't work, and I can't pass in a predicate to `invalidateAll` either.

**Comment by ben-manes** [comment]
I'm hesitant at providing an `invalidateAll(predicate)` because then might imply a more optimal approach than a linear scan. What about using `removeIf` instead? The `Map` view is a great escape hatch.

```java
cache.asMap().keySet().removeIf(key -> key.namespace.equals(namespace));
```

**Comment by drcrallen** [comment]
@ben-manes would that cause concurrent modification exceptions by chance?

**Comment by ben-manes** [comment]
Nope. Its backed by a `ConcurrentHashMap.

**Comment by ben-manes** [comment]
Closing as I think `removeIf` was a good compromise. Thanks for the feedback!
