### ISSUE TITLE
duplicated records

### ISSUE THREAD

**Issue by testereg** [ben-manes/caffeine#786]
I use annotation like following,

	@RetryableService
	@Cacheable(value= "getClientCredential" , key = "{#clientCredId}")
	public OauthClientDetails getClientCredential(String token, String clientCredId)

Somehow the cache saves duplicated records which have exactly the sam key and value, so my implementation were called overtime. but the same codes works with Redis or other providers.

Daniel

**Comment by ben-manes** [comment]
Is that Spring Cache? I think you'd need to ask them as I am not very familiar with it.

**Comment by ben-manes** [comment]
Also what is the configuration? I know that Spring Cache is not compatible with `weakKeys` since they generate a synthetic key for each call, so it is always a miss and never a hit (as reference identity, not Object.equals)

**Comment by testereg** [comment]
ok, thx

**Comment by testereg** [comment]
"since they generate a synthetic key for each call, so it is always a miss and never a hit (as reference identity, not Object.equals)"   this was what I guessed too.
