### ISSUE TITLE
Question: how to implement "cached set" with caffeine cache?

### ISSUE THREAD

**Issue by luxiaoxun** [ben-manes/caffeine#791]
My use case is: filter millions of string key within 6 hours, if one string key has occured in pasted 6 hours, I will ignore it.
So I try to implement the cache like this:
`Cache<String, Boolean>cache = Caffeine.newBuilder().maximumSize(maxSize).expireAfterWrite(expireDuration).recordStats().build();`
But I am not sure if it's the best way to do it ? Because I want to save memory as much as possbile (My APP is running on a single machine). 

Maybe best option is "Bloom Filter with item expiring", But Bloom Filter doesn't support "item expiring". So maybe I can ignore the "cached value" something like this: Cache<String, NULL>, just a "cached set" which support "item expiring". 

So what's the best way to do this with caffeine cache? (Redis is not my option for now)

Thanks in advance.

**Comment by ben-manes** [comment]
You could use two bloom filters, flipping as primary/historical every 3 hours and clear the historical when it becomes the primary. All new adds go to the primary and lookups check both. This way an item ages out based on your time window and you have low space overhead.

The main cost is the string so the value and cache metadata won’t be much overhead in comparison. If you can use a sketch data structure then that will be much better.

**Comment by luxiaoxun** [comment]
Yes, I already use a "hash" for the "cached key" to save memory space.
Thanks for the solution, I will try it.
