### ISSUE TITLE
Document nullability of RemovalListener#onRemoval parameters

### ISSUE THREAD

**Issue by pniederw** [ben-manes/caffeine#81]
Please document under which circumstances parameters `key` and `value` can be null. (They are both marked as `@Nullable`, which causes Kotlin to enforce null-handling in client code.)

**Comment by ben-manes** [comment]
Good point. A null reference may be provided only for `RemovalCause.COLLECTED` (weak or soft collection). For any other cause a null should not be passed through.

P.S. Long time, hope you're doing well.
