### ISSUE TITLE
Cache value lost

### ISSUE THREAD

**Issue by China-Dwan** [ben-manes/caffeine#811]
In conjunction with spring's annotations, the method is successfully cached the first time it returns a List \<Long\>, but the second time it returns an empty value. 

However, when the return value of the method is changed to List\<String\>, it hits the cache every time. 

It looks like a serialization problem. What configuration should I make?

version  2.9.3

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/43984599/199558261-99f487d3-d9de-42bc-8e40-211f1bcc34ee.png">

<img width="951" alt="image" src="https://user-images.githubusercontent.com/43984599/199557640-a68de3d4-9c37-4331-8587-b7644ecdc925.png">

**Comment by ben-manes** [comment]
Is your code modifying the cached list value? The cache doesn't serialize or otherwise manipulate the value, so offhand I don't know how to help you.

**Comment by China-Dwan** [comment]
> 

Thank you very much. Your warning is very important. Have been looking for a problem on this issue for hours. It's finally settled.

> Is your code modifying the cached list value? The cache doesn't serialize or otherwise manipulate the value, so offhand I don't know how to help you.
