### ISSUE TITLE
Question: how to configure to ignore look-up failures

### ISSUE THREAD

**Issue by alexec** [ben-manes/caffeine#812]
This is my use-case:

1. Cache entries expire after 5m and a refresh should be attempted.
1. Refresh asks a REST API for entries. This may fail, in which case old entry should be used.

**Comment by ben-manes** [comment]
That should be the default behavior, per `CacheLoader.reload`.

https://github.com/ben-manes/caffeine/blob/66c340db7074c010d238780d488380cfc94ded72/caffeine/src/main/java/com/github/benmanes/caffeine/cache/CacheLoader.java#L150-L172
