### ISSUE TITLE
 New features: about out-of-heap

### ISSUE THREAD

**Issue by dylan-tao** [ben-manes/caffeine#823]
Out-of-heap cache support? Avoids JVM garbage collection. Is there a plan?

**Comment by ben-manes** [comment]
Not by this project, but others are welcome implement that and use Caffeine where appropriate. I'd rather try to do a good job with a narrow focus than on a poor one broadly, and learn from others who focused on those other areas. There are many negative costs by trying to do too much, such as to the APIs or project support.

There are multiple caches that provide this. For example, Infinispan and Coherence both use Caffeine on-heap and offer combining with an off-heap tier. A research project, Robusta, used Caffeine with the values migrated onto persistent memory to allow for warm jvm restarts. Or you can combine yourself using dedicated projects like [OHC](https://github.com/snazy/ohc) or [Oak](https://github.com/yahoo/Oak).
