### ISSUE TITLE
导致docker mem cahce不断增大

### ISSUE THREAD

**Issue by wind0926** [ben-manes/caffeine#825]
public AsyncLoadingCache<Integer, Object> test() {
        return Caffeine.newBuilder()
                // 设置最后访问后间隔多久淘汰
                .expireAfterAccess(60 * 60, TimeUnit.SECONDS)
                // 缓存的最大条数
                .maximumSize(30)
                .recordStats()
                .buildAsync(new AsyncCacheLoader<Integer, Object>() {
                    @Override
                    public CompletableFuture<Object> asyncLoad(Integer key, Executor executor) {
                        return CompletableFuture.supplyAsync(() -> {
                            //TODO
                            return null;
                        }, executor);
                    }

                    @Override
                    public CompletableFuture<Map<Integer, Object>> asyncLoadAll(Iterable<? extends Integer> keys, Executor executor) {
      
                        return CompletableFuture.supplyAsync(() -> {
                            //TODO
                           return null;
                        }, executor);
                    }
                });
    }

**Comment by ben-manes** [comment]
Closing as this is not a question or bug report.
