### ISSUE TITLE
Use local SSD as secondary cache

### ISSUE THREAD

**Issue by ucasfl** [ben-manes/caffeine#833]
Currently, I want to use local SSD as secondary cache for remote files, but I did not find to much information about how to implement it with caffeine.

According to the wiki, this is possible, but it does not have more detail information about how to implement it.
> Layering
A layered cache loads from and writes to an external cache that is backed by the system of record. This allows having a small fast cache that falls back to slow large cache. Typical tiers are off-heap, file-based, and remote caches.
A victim cache is a layering variant where the evicted entries are written to the secondary cache. The eviction listener's RemovalCause allows for inspecting why the entry was removed and reacting accordingly.`

**Comment by ben-manes** [comment]
This project only provides an on-heap cache, so other tiers have to be composed with it. That is done using map computations for loads, removals, evictions to tie the different storage layers together. Those are the hooks, but further details is out of scope for us. There are projects like Infinispan and Coherence which use Caffeine for on-heap and offer offheap/disk/distributed tiers. Does any of that help?

**Comment by ucasfl** [comment]
> This project only provides an on-heap cache, so other tiers have to be composed with it. That is done using map computations for loads, removals, evictions to tie the different storage layers together. Those are the hooks, but further details is out of scope for us. There are projects like Infinispan and Coherence which use Caffeine for on-heap and offer offheap/disk/distributed tiers. Does any of that help?

You mean if I want to do this, I need to implement some interface api based on it?

**Comment by ben-manes** [comment]
Yes, you would need to decide on a tech stack, apis, and perform the integration. Caffeine offers a good on-heap cache as part of that solution. There are solutions from other projects that you use if you want an off the shelf framework.

**Comment by ucasfl** [comment]
OK, thanks!
