### ISSUE TITLE
Add Caffeine.recordStats variant which accepts boolean

### ISSUE THREAD

**Issue by sslavic** [ben-manes/caffeine#84]
To make configuring/externalizing recordStats flag nicer (avoid ugly if), please consider adding recordStats variant which accepts boolean. When false, clear any statsCounterSupplier, when true call recordStats without parameters.

**Comment by ben-manes** [comment]
I don't think it would carry its weight and be an inconsistent one-off. I agree ifs around builder methods are ugly, but you'll see them for size and expiration too. When externalized then you might take advantage of `CaffeineSpec`.

**Comment by Maaartinus** [comment]
I surely agree with you, but what do you think about this?

    .conditional(onceInABlueMoon())
        .recordStats() // gets mostly ignored
        .maxSize(1000) // also conditional
    .conditional(true) // revert to normal

Sadly, the IDE autoindent knows nothing about `conditional` and destroys the formatting.

**Comment by ben-manes** [comment]
Its an interesting idea. I think nested builder syntax shows the limits of using a builder as a DSL, but its an okay compromise at times. JavaPoet being a good example where it feels like the right trade off.

A generalization of your idea would be a utility to model an execution chain.
```java
LoadingCache<K, V> cache = ExecutionChain
    .start(Caffeine::newBuilder())
    .when(hasStats, builder -> builder.recordStats())
    .when(hasMaxSize, builder -> builder.maximumSize(maxSize))
    .end(builder -> builder.build(cacheLoader));
```

Then you could have a reusable abstraction with its own DSL that could work anywhere there is a lot of if-else verbosity.

**Comment by ben-manes** [comment]
Closing because I think there isn't a clean DSL for the builder to provide. The best options seem to be either ifs, `CaffeineSpec`, or some utility above. The utility is out of scope, but might be justifiable for a functional library (e.g. @danieldietrich's javaslang)
