### ISSUE TITLE
Cache not refreshing with LoadingCache

### ISSUE THREAD

**Issue by Ravindra-a** [ben-manes/caffeine#862]
Hi,

I have following caching configuration in my spring boot application and what I can see, it works only for the first call and subsequently data in cache never expires/refreshes.

```
import java.util.concurrent.TimeUnit;
import org.springframework.cache.annotation.EnableCaching;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.cache.caffeine.CaffeineCacheManager;
import com.github.benmanes.caffeine.cache.CacheLoader;
import com.github.benmanes.caffeine.cache.Caffeine;
import com.github.benmanes.caffeine.cache.LoadingCache;

@EnableCaching
@Configuration
public class ConfigCache {
   @Bean
    public LoadingCache<Object, Object> caffeineConfig() {
		return Caffeine.newBuilder()
        		.refreshAfterWrite(1, TimeUnit.SECONDS)
        		.recordStats() 
        		.build(cacheLoader());
    }
	
    @Bean
    public CacheLoader<Object, Object> cacheLoader() {
    	return new CacheLoader<Object, Object>() {
    	      @Override
    	      public Object load(Object key) throws Exception {
    	    	  		return null;
              }
    	    };
    }

    @Bean
    public CaffeineCacheManager cacheManager(LoadingCache<Object, Object> caffeine) {
        CaffeineCacheManager caffeineCacheManager = new CaffeineCacheManager(); 
        caffeineCacheManager.setCacheLoader(cacheLoader());
        return caffeineCacheManager;
    }
}
```

This use to work before but suddenly it stopped working. Can see this issue in my current 2.x version and also able to reproduce  this issue in a new simpler spring boot application with latest version of Caffeine library. 

Temporarily to fix this I have changed it to this i.e. use `com.github.benmanes.caffeine.cache.Caffeine` instead of `com.github.benmanes.caffeine.cache.LoadingCache` and also doing `setCaffeine` on `CaffeineCacheManager`

```
@EnableCaching
@Configuration
public class ConfigCache {
   @Bean
    public Caffeine<Object, Object> caffeineConfig() {
		return Caffeine.newBuilder()
        		.refreshAfterWrite(1, TimeUnit.SECONDS)
        		.recordStats(); 
    }
	
    @Bean
    public CacheLoader<Object, Object> cacheLoader() {
    	return new CacheLoader<Object, Object>() {
    	      @Override
    	      public Object load(Object key) throws Exception {
    	    	  		return null;
              }
    	    };
    }

    @Bean
    public CaffeineCacheManager cacheManager(Caffeine<Object, Object> caffeine) {
        CaffeineCacheManager caffeineCacheManager = new CaffeineCacheManager();        
        caffeineCacheManager.setCaffeine(caffeine); // Without this line even this code doesn't refresh
        caffeineCacheManager.setCacheLoader(cacheLoader());
        return caffeineCacheManager;
    }
}
```

What exactly I am missing here with `LoadingCache` ?

**Comment by ben-manes** [comment]
Sorry, but my lack of familiarity with Spring means you will need to reach out to them for help. If you can reproduce as a pure Java test with our apis then I can debug it, but once you depend on another framework to coordinate the cache calls then it is out of scope.

I believe in their case, they expect the `CaffeineCacheManager` to create the cache instances. Otherwise you would need to call [registerCustomCache](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/cache/caffeine/CaffeineCacheManager.html#registerCustomCache(java.lang.String,com.github.benmanes.caffeine.cache.Cache)) explicitly. It sounds like they changed their integration logic and broke your old approach, but that your newer style works so I suppose that is the right solution.

**Comment by Ravindra-a** [comment]
Thank you for quick response. For now going ahead with second approach, if I can create a test with this behaviour will add those details here.
