### ISSUE TITLE
what is the maximun allow key size and vaule size?

### ISSUE THREAD

**Issue by river320** [ben-manes/caffeine#881]
what is the maximun allow key size and vaule size?
thank you

**Comment by ben-manes** [comment]
The Weigher returns an int, so the valid range is 0 to Integer.MAX_VALUE. This is the entry’s size (key & value). The total for the cache is a long and ranges from 0 to (Long.MAX_VALUE - Integer.MAX_VALUE). This minor restriction avoids overflow to simplify our logic.

If you need more than an int per entry, simply divide to change the base unit (e.g. byte -> kilobyte). The cache simply knows the numeric weight and has no concept of the unit, so `Math.max(e.bytes() / 1000, 1)` is perfectly fine. Note that a zero weight is valid and used to exclude the entry from size eviction.
