### ISSUE TITLE
No such method error occurred, when use LoadingCache.refresh

### ISSUE THREAD

**Issue by ShinJJang** [ben-manes/caffeine#891]
Hi,

I want to refresh `LoadingCache` manually in scheduled context already. This is why I don't use expireAt~, refreshAt~.
So, I use `LoadingCache.refresh(key)`, but no such error occurred. 
(Caffeine build instance of `UnboundedLocalCache.UnboundedLocalLoadingCache`)

> No such instance method: 'refresh'

I think, because `LocalLoadingCache.refresh` is overridden with default accessor.
Do I need to implement custom LoadingCache? or is there wrong usage?

Thanks.

**Sample code**
- Caffeine version: 3.1.1
```java
// set up cache
LoadingCache<K, V> cache = Caffeine
            .newBuilder()
            .build(key -> getValue(key));

// in scheduled method, if failed reload use old value
// but no such method occured.
cache.refresh(key);
```

**Comment by ben-manes** [comment]
Sorry, I don't understand. Can you provide a minimal failing unit test? It sounds like a compilation problem? Are you using a non-standard JDK?

An explicit `LoadingCache.refresh(key)` will reload if present (`CacheLoader.reload(key, oldValue)`) or load if absent (`CacheLoader.load(key)`). If your logic assumes it only calls the loader when present then I could imagine it might cause some confusion.

**Comment by ShinJJang** [comment]
Oh yes, I have overridden reload too in real code.

Hmm, In new project it was work without error, with same JDK. I will check my project setup.

**Comment by ben-manes** [comment]
okay, good luck. I'll close for now but reppen if I can be of help.
