### ISSUE TITLE
Data race detected by TSAN in MpscGrowableArrayQueue.java line 519

### ISSUE THREAD

**Issue by jlavallee** [ben-manes/caffeine#892]
We recently upgraded from Caffeine 2.x to 3.1.5 and TSAN has detected a data race at MpscGrowableArrayQueue.java:519

Stack trace below, I can provide a more detailed one privately if desired.  

> WARNING: ThreadSanitizer: data race (pid=8703)
  Write of size 4 at 0x0000c93fb424 by thread T31 (mutexes: write M0):
    #0 com.github.benmanes.caffeine.cache.BaseMpscLinkedArrayQueue.resize(J[Ljava/lang/Object;JLjava/lang/Object;)V MpscGrowableArrayQueue.java:519 
    #1 com.github.benmanes.caffeine.cache.BaseMpscLinkedArrayQueue.offer(Ljava/lang/Object;)Z MpscGrowableArrayQueue.java:276 
    #2 com.github.benmanes.caffeine.cache.BoundedLocalCache.afterWrite(Ljava/lang/Runnable;)V BoundedLocalCache.java:1520 
    #3 com.github.benmanes.caffeine.cache.BoundedLocalCache.replace(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Z)Z BoundedLocalCache.java:2612 
    #4 com.github.benmanes.caffeine.cache.LocalAsyncCache.lambda$handleCompletion$7(Ljava/util/concurrent/atomic/AtomicBoolean;JLjava/lang/Object;Ljava/util/concurrent/CompletableFuture;ZLjava/lang/Object;Ljava/lang/Throwable;)V LocalAsyncCache.java:219 
    #5 com.github.benmanes.caffeine.cache.LocalAsyncCache$$Lambda$495.accept(Ljava/lang/Object;Ljava/lang/Object;)V ?? 
    #6 java.util.concurrent.CompletableFuture.uniWhenComplete(Ljava/lang/Object;Ljava/util/function/BiConsumer;Ljava/util/concurrent/CompletableFuture$UniWhenComplete;)Z CompletableFuture.java:859 
    #7 java.util.concurrent.CompletableFuture.uniWhenCompleteStage(Ljava/util/concurrent/Executor;Ljava/util/function/BiConsumer;)Ljava/util/concurrent/CompletableFuture; CompletableFuture.java:883 
    #8 java.util.concurrent.CompletableFuture.whenComplete(Ljava/util/function/BiConsumer;)Ljava/util/concurrent/CompletableFuture; CompletableFuture.java:2251 
    #9 com.github.benmanes.caffeine.cache.LocalAsyncCache.handleCompletion(Ljava/lang/Object;Ljava/util/concurrent/CompletableFuture;JZ)V LocalAsyncCache.java:200 
    #10 com.github.benmanes.caffeine.cache.LocalAsyncCache.put(Ljava/lang/Object;Ljava/util/concurrent/CompletableFuture;)V LocalAsyncCache.java:193 
    #11

**Comment by ben-manes** [comment]
Hi Jeff,

Please see #556. This and the other TSAN issue are benign so closing, but please reopen if you believe otherwise.

**Comment by jlavallee** [comment]
Thanks!  I expect we may come across a few more of these following our Caffeine update, should I open new issues for them as they arise, or perhaps re-use this bug for all 3.1.5 TSAN issues?

**Comment by ben-manes** [comment]
Sure, whatever you prefer. I'll look at them regardless.
