### ISSUE TITLE
Throw exception when cache size limit is reached

### ISSUE THREAD

**Issue by adityavikasd** [ben-manes/caffeine#895]
Hi,

Is it possible to not evict any entries already in the cache and just throw some exception when the cache reached the size limit set during creation?

**Comment by ben-manes** [comment]
Nope, but in that case it doesn't really sound like you want or need a cache? A `ConcurrentHashMap` where every `put` or `compute` is followed with a `size() > maximum` check to log if the threshold was passed might be equivalent.
