### ISSUE TITLE
SingleConsumerQueue::poll does not fully obey Queue interface

### ISSUE THREAD

**Issue by nitsanw** [ben-manes/caffeine#9]
"Retrieves and removes the head of this queue, or returns null if this queue is empty."
But I believe SingleConsumerQueue::poll can return null when queue is not empty.
This is due to:
    
    /** Adds the linked list of nodes to the queue. */
    void append(Node<E> first, Node<E> last) {
      for (;;) {
        Node<E> t = tail;
        if (casTail(t, last)) {
          /** Imagine a producer thread is interrupted here **/
          t.next = first;
          for (;;) {
            first.complete();
            if (first == last) {
              return;
            }
            first = first.getNextRelaxed();
          }
     }

This will cause a 'bubble' in the queue. In poll we'll get:

    public E poll() {
      Node<E> next = head.getNextRelaxed();
      if (next == null) {
        // next is null, but head != tail ...
        return null;
      }
      lazySetHead(next);
      E e = next.value;
      next.value = null;
      return e;
    }

**Comment by ben-manes** [comment]
Good point. It seems like there are two obvious choices, either fix `size()` or `poll()`. I think either of the following snippets would work, with the first being my preference for performance reasons. Thoughts?

```java
  @Override
  public boolean isEmpty() {
    return (head.next == null);
  }
```

```java
  public E poll() {
    if (isEmpty()) {
      return null;
    }
    for (;;) {
      Node<E> next = head.getNextRelaxed();
      if ((next == null) && ((next = head.next) == null)) {
        continue;
      }
      lazySetHead(next);
      E e = next.value;
      next.value = null;
      return e;
    }
  }
```

**Comment by nitsanw** [comment]
The problem is:
(head.getNextRelaxed() == null) doesn't mean the queue is empty.
The real indicator for empty queue is (head != tail)
This sucks, but there's really no way around it AFAIK.
The solution I arrived at in JCTools MpscLinkedQueue :

    public final E poll() {
        LinkedQueueNode<E> currConsumerNode = lpConsumerNode(); // don't load twice, it's alright
        LinkedQueueNode<E> nextNode = currConsumerNode.lvNext();
        if (nextNode != null) {
            // we have to null out the value because we are going to hang on to the node
            final E nextValue = nextNode.getAndNullValue();
            spConsumerNode(nextNode);
            return nextValue;
        }
        else if (currConsumerNode != lvProducerNode()) {
            // spin, we are no longer wait free
            while((nextNode = currConsumerNode.lvNext()) == null);
            // got the next node...
            
            // we have to null out the value because we are going to hang on to the node
            final E nextValue = nextNode.getAndNullValue();
            consumerNode = nextNode;
            return nextValue;
        }
        return null;
    }

The conventions are slightly different (sp = store plain, lp = load plain, lv = load volatile), but I think the intentions are clear.

**Comment by ben-manes** [comment]
If the state hasn't been fully materialized, why is it incorrect to use `head.getNextRelaxed() == null` until the elements become visible to the consumer?

**Comment by nitsanw** [comment]
Imagine 2 threads.
T1 is a producer and has been interrupted at the line pointed in first comment.
T2 is a producer and the single consumer:
T2 offers -> no problem, wins the CAS and sets the next pointer on the tail that T1 set up
T2 polls -> queue is empty

**Comment by ben-manes** [comment]
Oh, of course. Sorry, I'm working on unrelated stuff so I keep switching contexts. =)

Good catch. I'll make the fix shortly. Feel free to borrow any of the arena code if that interests you.

**Comment by nitsanw** [comment]
I'll have a proper look at some point. This is a recurring bug, happened to me too.
The thing is that Mr. Vyukov is not bound by the Java Queue contract and we are, so need extra care when assuming offer == offer and poll == poll.
