### ISSUE TITLE
Preventing eviction

### ISSUE THREAD

**Issue by andrewbaxter** [ben-manes/caffeine#920]
I need to maintain a cache of open files to avoid fd limits.  With Caffeine AFAICT an entry could be evicted while a file is being read, leading to additional fd usage beyond the cache size limit.  Is there any way to avoid this?

Ideally it would block if a `get` occurs for a new file with a full cache, where all entries are in use.

Things I looked at:
- Using a weigher to reduce weight of in-use files
- A `compute()` method that would bound the usage
- Some sort of `reject` method in a remove listener
- Externally keeping a `in-use` semaphore to block before calling `get()` - this wouldn't guarantee that in-use entries aren't evicted though
- Custom eviction policy (it appears tinylfu is hardcoded?)

**Comment by ben-manes** [comment]
Have you tried [pinning the entry](https://github.com/ben-manes/caffeine/wiki/Faq#pinning-entries)? That is to use a compute to reduce the weight to zero, therefore opting it out of eviction. The policy will skip over pinned entries.

**Comment by andrewbaxter** [comment]
Oh, that looks perfect! Thanks!

It might make sense to note this operation mode in the eviction section.
