### ISSUE TITLE
expireAfterWrite and refreshAfterWrite

### ISSUE THREAD

**Issue by maitwakrim** [ben-manes/caffeine#930]
Hi,
I'm trying to use both `expireAfterWrite` and `refreshAfterWrite` on my cache this way:
```
Caffeine.newBuilder()
                .maximumSize(10)
                .scheduler(Scheduler.systemScheduler())
                .expireAfterWrite(10, TimeUnit.SECONDS)
                .refreshAfterWrite(5, TimeUnit.SECONDS)
                .removalListener((String key, Integer value, RemovalCause cause) -> {
                    log.info("Cache expired! Reloading...");
                    cache.get("validationCache");
                })
                .build(new CacheLoader<String, Integer>() {
                          @Override
                           public Integer load(String s) throws Exception {
                               log.info("Loading cache.");
                               // Heavy work here ...
                                 
                           }

                           @Nullable
                           public Integer reload(@NonNull String key, @NonNull Integer oldValue) throws Exception {
                               log.info("reloading...");
                               return load(key);
                           }
                       }
                );
```

`refreshAfterWrite` has been introduced to avoid waiting too long for the synchronous `cache.get("key")` which solves the issue when the item needs to be refreshed but not expired. In that case the old value is returned while the refresh is performed in background. However when an item is both stale (needs a refresh) and expired it seems like the expiration logic wins and the call takes too long just like if the `refreshAfterWrite` logic is not there.

Any suggestion is much appreciated.

Many thanks.

**Comment by ben-manes** [comment]
Correct, an item that is eligible for refresh is stale but usable. An item that expired is not usable and must be loaded anew. The intent is that if an item is refreshable and accessed then it is reloaded to hide that miss penalty (e.g. a configuration needed by all requests) whereas if it is unused then it expires and fades away (making room for more popular content). If a reload is in-flight but the entry expires then the cache has to throw away the refresh's result to maintain consistency and avoid ABA scenarios.

Sometimes people want a proactive reload, where they want the entire contents to be kept warm. That is best done using a scheduled executor and a periodic task, e.g. by calling `cache.refreshAll(cache.asMap().keySet)`.

I am not sure what your question is, but I hope that helps explain and confirm the behavior expectations.

**Comment by maitwakrim** [comment]
Thank you for your prompt reply @ben-manes.
That explains the actual behaviour.
My questions is: is there a way to periodically refresh the cache without waiting for the heavyweight refresh method to complete if the item is requested while the cache is getting refreshed? In my case the items are still usable even when they are expired.
Perhaps `refreshAll` used with scheduled executor with a periodic task is a good fit for my case. I’ll give it a try and let you know.
Thank you so much.

**Comment by ben-manes** [comment]
wonderful. Let me know if you have any questions or problems.
