### ISSUE TITLE
Feature request: AsyncLoadingCache#estimatedSize()

### ISSUE THREAD

**Issue by bbc-tomfitzhenry** [ben-manes/caffeine#95]
`Cache` has an estimatedSize method: http://static.javadoc.io/com.github.ben-manes.caffeine/caffeine/2.3.1/com/github/benmanes/caffeine/cache/Cache.html#estimatedSize--

`AsyncLoadingCache` does not have an equivalent method, as far as I can see: http://static.javadoc.io/com.github.ben-manes.caffeine/caffeine/2.3.1/com/github/benmanes/caffeine/cache/AsyncLoadingCache.html

It would be nice if `AsyncLoadingCache` did have `estimatedSize()`!

**Comment by bbc-tomfitzhenry** [comment]
Just realised I can do:
`asyncLoadingCache.synchronous().estimatedSize()`

**Comment by ben-manes** [comment]
Good eye! 😀
