### ISSUE TITLE
How to use this in Android

### ISSUE THREAD

**Issue by rookie-iosers** [ben-manes/caffeine#959]
When i use this in Android. it will crash. the crash message is 
     java.lang.NoSuchMethodError: No virtual method findClass(Ljava/lang/String;)Ljava/lang/Class; in class Ljava/lang/invoke/MethodHandles$Lookup; or its super classes (declaration of 'java.lang.invoke.MethodHandles$Lookup' appears in /apex/com.android.art/javalib/core-oj.jar)

what should i do when i use it in android. Thank you

**Comment by ben-manes** [comment]
Unfortunately Android lacks Java compatibility, with many of these hidden gotchas. For example, they decided to not support Java's logger abstraction (`System.Logger`) in favor of their own, which would cause you further trouble. This library is designed for server-side Java where concurrency and hit rates are very important, whereas for Android those are less important than the binary size. I would recommend using a library targeting Android and not Java.

If your usage is pure Android then NY Times and Dropbox collaborated on [Store](https://github.com/MobileNativeFoundation/Store), which uses a kotlin port of Guava's Cache behind the scenes. There are lighterweight alternatives like Android's [LruCache](https://developer.android.com/reference/android/util/LruCache). Guava's Cache is also reasonable, though we didn't design it for Android hence Jesse wrote LruCache for a small binary solution.

If you need to share the code across mobile and server, then abstractions like [cache-api](https://github.com/Xanthic/cache-api) may be useful. Those provide a facade that bridges to the platform specific library. You can easily write your own adapter if an existing one isn't suitable.

Hope that helps!
