### ISSUE TITLE
Incorrect logging of errors in LocalAsyncLoadingCache

### ISSUE THREAD

**Issue by zml2008** [ben-manes/caffeine#96]
In [LocalAsyncLoadingCache.put](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/main/java/com/github/benmanes/caffeine/cache/LocalAsyncLoadingCache.java#L247), the message indicating an error is logged whether or not the error is actually present -- the field that should probably be checked for being non-null is `error` here, not `value`.

**Comment by ben-manes** [comment]
You're right. It was meant to be in the other block, like `get`. That's probably a little wrong too because the value could be null but not an error, indicating that the result was not computable. So both places should be checking the exception, thanks!
