### ISSUE TITLE
Infinite loop of ConcurrentHashMap in recursive scene caused by JDK-8062841

### ISSUE THREAD

**Issue by vernalces** [ben-manes/caffeine#960]
Under recursive scene of caffeine, we are experiencing deadlocks in caffeine version 2.9.0(java version is 1.8.0_152).

threaddump:
at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1868)
-  locked java.util.concurrent.ConcurrentHashMap$ReservationNode@3af73a29 <---- but blocks 130 other threads!
at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2339)
at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2322)
at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)

cache configuration:
Cache<Object, Object> cache = Caffeine.newBuilder()
                .initialCapacity(25)
                .maximumSize(500)
                .expireAfterWrite(60 * 1000L, TimeUnit.MILLISECONDS)
                .recordStats()
                .softValues()
                .build();
problem code:
public Object a(String key,Cache<Object, Object> cache) {
        return cache.get(key, o -> b(key,cache));
    };

public Object b(String key,Cache<Object, Object> cache) {
    return cache.get(key, o -> "BBBB");
};

When run a("AaAa",cache) deadlock happened.

**Comment by ben-manes** [comment]
This is briefly discussed in our FAQ on [recursive computations](https://github.com/ben-manes/caffeine/wiki/Faq#recursive-computations). This is a Java bug that I found during the original code review (2011), rediscovered in Java 8 and helped to fix in Java 9 (2014), and helped fix the last known occurence in (iirc) Java 12 (2018). In Java 9 onward it will throw an exception when detected but livelocks in Java 8, and unfortunately it was not backported to Java 8 even though I think it should have been.

ConcurrentHashMap briefly states within its JavaDoc that a recursive computation is not supported. Interestingly when I reported it for CHM while Java 8 was in development, the HashMap developers decided it was safe to allow. They too found out it was not as the hash table resizing would corrupt the map and lose entries, so they disallow it in Java 9 too.

The FAQ example shows how you can work around this by decoupling the computation from the establishing the mapping.

**Comment by vernalces** [comment]
Thanks for your quick response! I will have a try.
