### ISSUE TITLE
Wiki section describing the population of manual cache suggests put and get(key, value) work interchangeably

### ISSUE THREAD

**Issue by krzysztof-owczarek** [ben-manes/caffeine#984]
Link: https://github.com/ben-manes/caffeine/wiki/Population#manual

Section:
```
Entries may be inserted into the cache directly with cache.put(key, value). This overwrites any previous entry in the cache for the specified key. **Prefer instead** to use cache.get(key, k -> value) to atomically compute and insert the value into the cache to avoid racing with other writes.
```
suggests that `cache.put(key, value)` and `cache.get(key, k -> value)` work interchangeably, while they obviously not, which corresponds to behaviour of `Map.computeIfAbsent` and is mentioned in the code comment:

```
// Lookup and compute an entry if absent, or null if not computable
graph = cache.get(key, k -> createExpensiveGraph(key));
```

.. but easily evades attention. Small rewrite could save someone from introducing a bug.

**Comment by ben-manes** [comment]
Thanks. I struggled with that wording originally. I reordered to emphasize `cache.get`,

> Prefer using `cache.get(key, k -> value)` to atomically compute and insert the value if absent into the cache, or else return the existing value. A `cache.put(key, value)` may be used to directly insert or update an entry, overwriting any previous value in the cache for the specified key. Note that a `cache.get` may return `null` if the entry was not computable or throw an exception if the computation failed.

@tydhot can you please update the Chinese translation? Thanks!

**Comment by tydhot** [comment]
@ben-manes ok :)

**Comment by tydhot** [comment]
@ben-manes  done :)

**Comment by krzysztof-owczarek** [comment]
Thanks!
