### ISSUE TITLE
Threads are getting blocked in case of expensive remapping function

### ISSUE THREAD

**Issue by iamshahjahan** [ben-manes/caffeine#997]
I am using caffeine to cache data from different APIs which are communicating to some external systems. Sometimes, these external systems take more that 20-30 seconds to respond. Since these fallback APIs are very slow, some threads get blocked. 

I know the issue is [computeIfAbsent](https://github.com/frohoff/jdk8u-jdk/blob/da0da73ab82ed714dc5be94acd2f0d00fbdfe2e9/src/share/classes/java/util/concurrent/ConcurrentHashMap.java#L1643) method of ConcurrentHashMap, since it is mentioned there:

>  The entire method invocation is performed atomically, so the function is applied at most once per key.  Some attempted update operations on this map by other threads may be blocked while computation is in progress, so the computation should be short and simple, and must not attempt to update any other mappings of this map.

 
I have no control over external systems, so what optimization I can do in our system to make sure no blocking happens? 

Will using AsyncCache help here?

![image](https://github.com/ben-manes/caffeine/assets/92710745/3aaaeca2-c5e1-4dda-9824-96abd5c79e95)

**Comment by ben-manes** [comment]
yes, using an async cache would make sense since it will block in the future and not within the map. That also would let you timeout the future if it exceeds a threshold.
